export const AUDIT_THEMES=[{id:"crawlability",label:"Crawlability",pattern:/http_error|client_error|is_[45]xx|broken|index|canonical|redirect|javascript/},{id:"https",label:"HTTPS",pattern:/https|is_http|mixed_content|certificate/},{id:"international",label:"International SEO",pattern:/hreflang/},{id:"performance",label:"Site Performance",pattern:/loading|load_time|slow/},{id:"linking",label:"Internal Linking",pattern:/link|orphan/},{id:"markups",label:"Markups",pattern:/schema|json_ld/},{id:"ai_answers",label:"AI answer eligibility",pattern:/^ai_|javascript_dependent|not_indexable/},{id:"metadata",label:"Titles & Content",pattern:/title|description|h1|duplicate.*content/}] as const;
export type AuditPage={url:string;statusCode:number|null;title:string|null;canonical:string|null;depth:number|null;loadTimeMs:number|null;checks:Record<string,boolean>;internalLinks:number|null;externalLinks:number|null;hreflang:Record<string,string>;schemaTypes:string[];source:"dataforseo"|"browser"};
export type AuditPageRun={id:string;date:string;source:AuditPage["source"];total:number;pages:AuditPage[];truncated:boolean};
export const auditIssueLabel=(key:string)=>key.replace(/_/g," ").replace(/^\w/,letter=>letter.toUpperCase());
export function auditPageDiff(before:AuditPageRun,after:AuditPageRun){
 const left=new Map(before.pages.map(page=>[page.url,page])),right=new Map(after.pages.map(page=>[page.url,page]));
 const rows:{key:string;url:string;issue:string;state:"new"|"fixed"|"recurring"|"unverified";before:boolean|null;after:boolean|null;detail:string}[]=[];
 for(const url of new Set([...left.keys(),...right.keys()])){const a=left.get(url),b=right.get(url);for(const issue of new Set([...Object.keys(a?.checks??{}),...Object.keys(b?.checks??{})])){const prev=a?.checks[issue]??null,next=b?.checks[issue]??null;if(prev!==true&&next!==true)continue;const compatible=before.source===after.source;const state=!compatible||prev==null||next==null?"unverified":prev&&next?"recurring":next?"new":"fixed";rows.push({key:`${url}:${issue}`,url,issue,state,before:prev,after:next,detail:!compatible?"Different crawl sources":!a?"URL not checked in the earlier crawl":!b?"URL not checked in the later crawl":prev==null||next==null?"This check was not recorded in both crawls":"Explicit page check in both crawls"});}}
 return rows;
}
export function themeSummary(pages:AuditPage[],pattern:RegExp){const relevant=pages.map(page=>({page,checks:Object.entries(page.checks).filter(([key])=>pattern.test(key))}));return {checked:relevant.filter(row=>row.checks.length).length,affected:relevant.filter(row=>row.checks.some(([,failed])=>failed)).length,occurrences:relevant.reduce((sum,row)=>sum+row.checks.filter(([,failed])=>failed).length,0),unknown:relevant.filter(row=>!row.checks.length).length};}
