import { describe, expect, it, vi } from "vitest";
import { normalizeResearch } from "@/providers/dataforseo/research-normalizers";
import { buildResearchPlan, researchInputSchema } from "@/platform/research-plan";
import { combineTrafficChannels, trafficInputSchema, trafficRequestPlan } from "./traffic-research";
import { TOOLKIT_FEATURES } from "./toolkits";
import type { ManagedSite } from "@/platform/types";
const site={id:"test",name:"Test",host:"example.com",dataForSeoLocationCode:2784,dataForSeoLanguageCode:"en",primaryMarket:"UAE"} as ManagedSite;
describe("prepared research connections",()=>{
 it("previews autocomplete without a paid call and retains query market",async()=>{const fetch=vi.spyOn(globalThis,"fetch");const input=researchInputSchema.parse({feature:"autocomplete",keywords:["bus hire","bus hire"]});const plan=await buildResearchPlan(site,input);expect(fetch).not.toHaveBeenCalled();fetch.mockRestore();expect(plan.units).toHaveLength(1);expect(plan.units[0]).toMatchObject({path:"/v3/serp/google/autocomplete/live/advanced",body:{keyword:"bus hire",location_code:2784,language_code:"en"}});const report=normalizeResearch(plan.units[0],[{items:[{type:"autocomplete",suggestion:"bus hire near me",rank_absolute:1},{type:"organic",title:"Not a suggestion"}]}]);expect(report.tables[0].rows).toHaveLength(1);expect(report.tables[0].rows[0].values).not.toHaveProperty("Volume");expect(report.tables[0].rows[0].keywords).toEqual(["bus hire near me"]);});
 it("collects countries without locking the result to the website's default country",async()=>{const plan=await buildResearchPlan(site,researchInputSchema.parse({feature:"countries",domains:["example.com"]}));expect(plan.units[0].body).toEqual({target:"example.com",limit:1000});const report=normalizeResearch(plan.units[0],[{items:[{location_code:2784,language_code:"en",metrics:{organic:{etv:0,count:10}}},{location_code:2784,language_code:"ar",metrics:{organic:{etv:12}}}]}]);expect(report.tables[0].rows).toHaveLength(2);expect(report.tables[0].rows[0].values["Organic traffic"]).toBe(0);expect(report.tables[0].rows[1].values["Organic keywords"]).toBeNull();});
 it("rejects non-domain traffic targets and invalid months",()=>{expect(trafficInputSchema.safeParse({domain:"https://example.com/path",month:"2026-09"}).success).toBe(false);expect(trafficInputSchema.safeParse({domain:"example.com",month:"2026-13"}).success).toBe(false);});
 it("prepares bounded credential-free requests for total and both device channel sets",()=>{const plan=trafficRequestPlan({domain:"example.com",month:"2026-08",country:"world"});expect(plan.credits).toBe(15);expect(plan.requests).toHaveLength(3);for(const r of plan.requests){const url=new URL(r.url);expect(url.hostname).toBe("api.similarweb.com");expect(url.searchParams.has("api_key")).toBe(false);expect(url.searchParams.get("start_date")).toBe("2026-08");expect(url.searchParams.get("end_date")).toBe("2026-08");}});
 it("does not disguise desktop-only channels as total traffic",()=>{const r=combineTrafficChannels({domain:"example.com",month:"2026-08",country:"world"},100,{Direct:30,"Organic Search":0},{Direct:20},"2026-09-15");expect(r.channels.find(c=>c.name==="Direct")).toMatchObject({visits:50,share:50});expect(r.channels.find(c=>c.name==="Organic Search")).toMatchObject({desktop:0,mobile:null,visits:null,share:null});});
 it("routes backlink gap to the existing gap tool and restores collection shortcuts",()=>{expect(TOOLKIT_FEATURES.find(t=>t.label==="Backlink Gap")?.href).toBe("/link-building?view=gap#link-gap");expect(TOOLKIT_FEATURES.some(t=>t.href==="/keyword-research?view=tracking")).toBe(true);expect(TOOLKIT_FEATURES.some(t=>t.href.includes("feature=links"))).toBe(true);});
});
