export type ComparisonDomain={id:string;sourceValue:string;locationCode:number;languageCode:string;locationLabel:string;capturedAt:string;summary:Record<string,number|null>;evidence:{keywords:{keyword:string;position:number|null;volume:number|null;difficulty:number|null;intent:string|null;url:string|null;traffic:number|null}[];pages:{url:string;keywords:number|null;traffic:number|null;trafficCost:number|null}[];backlinks:Record<string,number|null>}};
export type GapPosition={position:number|null;url:string|null;known:boolean;observed?:boolean};
export type GapKeyword={keyword:string;volume:number|null;difficulty:number|null;intent:string|null;positions:Record<string,GapPosition>};
export type GapKind="all"|"shared"|"missing"|"weak"|"strong"|"unique"|"untapped";
export function domainKeywordMatrix(domains:ComparisonDomain[],verified:GapKeyword[]=[]):GapKeyword[]{
 if(domains.some(domain=>domain.locationCode!==domains[0]?.locationCode||domain.languageCode!==domains[0]?.languageCode))throw new Error("Compare the same country and language database.");
 const map=new Map<string,GapKeyword>();
 for(const domain of domains)for(const item of domain.evidence.keywords){const key=item.keyword.toLowerCase();const row=map.get(key)??{keyword:item.keyword,volume:item.volume,difficulty:item.difficulty,intent:item.intent,positions:{}};row.positions[domain.sourceValue]={position:item.position,url:item.url,known:item.position!=null};map.set(key,row);}
 for(const verifiedRow of verified){const key=verifiedRow.keyword.toLowerCase(),previous=map.get(key);map.set(key,{...previous,...verifiedRow,positions:{...previous?.positions,...verifiedRow.positions}});}
 return [...map.values()].map(row=>({...row,positions:Object.fromEntries(domains.map(domain=>[domain.sourceValue,row.positions[domain.sourceValue]??{position:null,url:null,known:false}]))}));
}
export function matchesGap(row:GapKeyword,domains:string[],kind:GapKind){const own=row.positions[domains[0]!],others=domains.slice(1).map(domain=>row.positions[domain]);if(kind==="all")return true;if(!own)return false;const rank=(item:GapPosition|undefined)=>item?.known&&(item.position!=null||item.observed===true);const absent=(item:GapPosition|undefined)=>item?.known&&item.position===null&&!item.observed;if(kind==="shared")return rank(own)&&others.every(rank);if(kind==="missing")return absent(own)&&others.every(rank);if(kind==="untapped")return absent(own)&&others.some(rank);if(kind==="unique")return rank(own)&&others.every(absent);if(kind==="weak")return rank(own)&&own.position!=null&&others.some(item=>rank(item)&&item!.position!=null&&item!.position!<own.position!);return rank(own)&&own.position!=null&&others.every(item=>rank(item)&&item!.position!=null&&item!.position!>own.position!);}
