import {describe,it,expect} from "vitest";
import {belongsToHost,rankReportRows,rankSummary,type TrackedKeyword,type RankObservation} from "./rank-reports";
import {auditPageDiff,themeSummary,type AuditPage,type AuditPageRun} from "./audit-pages";
import {normalizeResearchTarget,targetMatches,targetRequest} from "./comparison-targets";
import {scopedMatrix,overlapGroups,type ComparisonReport} from "./scoped-comparison";
import {buildSerpStrategy,validClusterParents} from "./serp-strategy";
import {urlSwitchEvidence,cannibalisationAssessment} from "./cannibalisation";
import {compareAdvertising,normalizeHistoricalAds,type AdvertisingSnapshot} from "./ad-history";
import type {SerpEvidence} from "./serp-evidence";
const tracked:TrackedKeyword={id:"one",keyword:"bus rental",campaignId:null,locationCode:2840,languageCode:"en",device:"desktop",searchEngine:"google",tags:[],targetUrl:null,active:true,cadence:"daily"};
const point=(date:string,position:number|null,url:string|null,id="one"):RankObservation=>({trackedKeywordId:id,capturedOn:date,position,url,serpFeatures:[],ownedFeatures:[],competitors:[]});
const page=(url:string,checks:Record<string,boolean>):AuditPage=>({url,checks,statusCode:200,title:"Title",canonical:null,depth:1,loadTimeMs:500,internalLinks:3,externalLinks:0,hreflang:{},schemaTypes:[],source:"browser"});
const run=(pages:AuditPage[],source:"browser"|"dataforseo"="browser"):AuditPageRun=>({id:"run",date:"2026-09-15",source,total:pages.length,pages,truncated:false});
const serp=(keyword:string,ids:number[],patch:Partial<SerpEvidence>={}):SerpEvidence=>({keyword,locationCode:2840,languageCode:"en",device:"desktop",depth:10,collectedAt:"2026-09-15T00:00:00Z",checkUrl:null,items:ids.map((id,i)=>({type:"organic",position:i+1,groupPosition:i+1,url:`https://domain${id}.com/page`,domain:`domain${id}.com`,title:null,description:null})),...patch});
describe("position tracking evidence",()=>{
 it("matches host boundaries, not domains embedded in another host or path",()=>{expect(belongsToHost("https://notexample.com","example.com")).toBe(false);expect(belongsToHost("https://other.com/example.com","example.com")).toBe(false);expect(belongsToHost("https://shop.example.com/path","example.com")).toBe(true);});
 it("preserves unmeasured targets and does not invent endpoint movement",()=>{const rows=rankReportRows([tracked,{...tracked,id:"two",device:"mobile"}],[point("2026-09-10",4,"https://example.com"),point("2026-09-12",null,null)],"2026-09-10","2026-09-15");expect(rows[0]).toMatchObject({change:null,observed:true,position:null});expect(rows[1]).toMatchObject({observed:false,change:null});expect(rankSummary(rows)).toMatchObject({tracked:2,observed:1,average:null,top10:0});});
 it("compares first and last observations only inside the selected dates",()=>{const row=rankReportRows([tracked],[point("2026-09-01",1,"a"),point("2026-09-11",12,"b"),point("2026-09-14",5,"b")],"2026-09-10","2026-09-15")[0];expect(row?.change).toBe(7);});
});
describe("URL-level audit comparisons",()=>{
 it("distinguishes explicitly fixed, new, recurring and unverified checks",()=>{const before=run([page("https://a.com",{missing_title:true,http_error:false,missing_h1:true}),page("https://a.com/old",{missing_title:true})]),after=run([page("https://a.com",{missing_title:false,http_error:true,missing_h1:true}),page("https://a.com/new",{missing_title:true})]);const rows=auditPageDiff(before,after);expect(rows.find(row=>row.issue==="missing_title"&&row.url==="https://a.com")?.state).toBe("fixed");expect(rows.find(row=>row.issue==="http_error")?.state).toBe("new");expect(rows.find(row=>row.issue==="missing_h1")?.state).toBe("recurring");expect(rows.filter(row=>row.state==="unverified")).toHaveLength(2);});
 it("does not call an absent check or a different crawler a fix",()=>{expect(auditPageDiff(run([page("a",{missing_title:true})]),run([page("a",{})]))[0]?.state).toBe("unverified");expect(auditPageDiff(run([page("a",{missing_title:true})]),run([page("a",{missing_title:false})],"dataforseo"))[0]?.state).toBe("unverified");});
 it("separates unknown coverage from checked clean pages",()=>{expect(themeSummary([page("a",{}),page("b",{missing_title:false}),page("c",{missing_title:true})],/title/)).toEqual({checked:2,affected:1,occurrences:1,unknown:1});});
});
describe("scoped comparisons",()=>{
 it("respects root, subdomain, folder boundaries and exact query strings",()=>{const domain=normalizeResearchTarget({value:"example.com",scope:"domain",kind:"organic"}),sub=normalizeResearchTarget({value:"shop.example.com",scope:"subdomain",kind:"paid"}),folder=normalizeResearchTarget({value:"https://example.com/Shop",scope:"folder",kind:"organic"}),url=normalizeResearchTarget({value:"https://example.com/page?x=1",scope:"url",kind:"organic"});expect(targetMatches(domain,"https://a.example.com")).toBe(true);expect(targetMatches(sub,"https://child.shop.example.com")).toBe(false);expect(targetMatches(folder,"https://example.com/Shop/item")).toBe(true);expect(targetMatches(folder,"https://example.com/Shopper")).toBe(false);expect(targetMatches(folder,"https://example.com/shop/item")).toBe(false);expect(targetMatches(url,"https://example.com/page?x=2")).toBe(false);expect(targetRequest(folder).filters).toEqual([[["ranked_serp_element.serp_item.relative_url","=","/Shop"],"or",["ranked_serp_element.serp_item.relative_url","like","/Shop/%"]]]);});
 it("rejects credentials and non-web targets",()=>{expect(()=>normalizeResearchTarget({value:"https://user:pass@example.com",scope:"url",kind:"organic"})).toThrow();expect(()=>normalizeResearchTarget({value:"ftp://example.com",scope:"url",kind:"organic"})).toThrow();});
 it("keeps missing keywords unknown until target coverage or verification is sufficient",()=>{const a=normalizeResearchTarget({value:"a.com",scope:"domain",kind:"organic"}),b=normalizeResearchTarget({value:"b.com",scope:"domain",kind:"organic"});const report:ComparisonReport={input:{targets:[a,b],locationCode:2840,languageCode:"en"},collectedAt:"2026-09-15",costUsd:0,collections:[{target:a,keywords:[{keyword:"term",position:3,url:"https://a.com",volume:100,difficulty:20,intent:null}],offset:1,total:1,complete:true,collectedAt:"2026-09-15"}]};expect(scopedMatrix(report)[0]?.positions[b.id]?.known).toBe(false);report.collections.push({target:b,keywords:[],total:0,offset:0,complete:true,collectedAt:"2026-09-15"});expect(scopedMatrix(report)[0]?.positions[b.id]?.known).toBe(true);expect(overlapGroups(scopedMatrix(report),[a.id,b.id])).toEqual([{ids:[a.id],count:1}]);});
});
describe("SERP strategy",()=>{
 const input={keywords:["a","b","c"],locationCode:2840,languageCode:"en",device:"desktop"},now=new Date("2026-09-15T12:00:00Z");
 it("prevents a transitive chain from producing a weak cluster",()=>{const result=buildSerpStrategy(input,[serp("a",[1,2,3]),serp("b",[1,2,3,4,5,6]),serp("c",[4,5,6])],[],now);expect(result.clusters.map(row=>row.keywords)).toEqual([["a","b"],["c"]]);});
 it("excludes stale, different-device and insufficient evidence",()=>{const result=buildSerpStrategy(input,[serp("a",[1,2,3],{collectedAt:"2026-08-01"}),serp("b",[1,2,3],{device:"mobile"}),serp("c",[1,2])],[],now);expect(result.clusters).toHaveLength(0);expect(result.missing).toEqual(["a","b","c"]);});
 it("does not merge incompatible measured intent or invent volume",()=>{const result=buildSerpStrategy({...input,keywords:["a","b"]},[serp("a",[1,2,3]),serp("b",[1,2,3])],[{keyword:"a",volume:10,intent:"informational"},{keyword:"b",volume:null,intent:"transactional"}],now);expect(result.clusters).toHaveLength(2);expect(result.clusters[1]?.totalVolume).toBeNull();});
 it("rejects cycles or missing pillars",()=>{const groups=buildSerpStrategy(input,[serp("a",[1,2,3]),serp("b",[4,5,6])],[],now).clusters;groups[0]!.parentId=groups[1]!.id;groups[1]!.parentId=groups[0]!.id;expect(validClusterParents(groups)).toBe(false);groups[1]!.parentId=null;expect(validClusterParents(groups)).toBe(true);groups[0]!.parentId="missing";expect(validClusterParents(groups)).toBe(false);});
});
describe("cannibalisation confidence",()=>{
 it("does not equate multiple pages with harm",()=>{expect(cannibalisationAssessment([])).toMatchObject({priority:"low",label:"Potential page overlap"});});
 it("does not compare URL changes across devices or through unobserved results",()=>{const results=urlSwitchEvidence([tracked,{...tracked,id:"two",device:"mobile"}],[point("2026-09-11",4,"a"),point("2026-09-12",null,null),point("2026-09-13",7,"b"),point("2026-09-11",3,"c","two")]);expect(results).toHaveLength(0);});
 it("requires repeated switches and same-target decline for high review priority",()=>{const results=urlSwitchEvidence([tracked],[point("2026-09-11",4,"a"),point("2026-09-12",7,"b"),point("2026-09-13",12,"a")]);expect(cannibalisationAssessment(results.map(row=>row.evidence))).toMatchObject({priority:"high",label:"URL switching with decline"});});
});
describe("advertising history",()=>{
 const row={label:"bus rental",url:"https://example.com/a",position:1,volume:100,cpc:1,traffic:null,keywords:null,common:null,title:"Book now",description:"A bus"};const snap=(date:string,rows=[row],total:number|null=1):AdvertisingSnapshot=>({input:{domain:"example.com",locationCode:2840,languageCode:"en",kind:"keywords"},rows,total,collectedAt:date});
 it("compares copy, landing page and position without implying campaign dates",()=>{const changes=compareAdvertising(snap("2026-09-01"),snap("2026-09-15",[{...row,title:"Rent now",url:"https://example.com/b",position:3}]));expect(changes[0]).toMatchObject({status:"Changed",changes:["Landing page","Ad copy","Position"]});});
 it("does not infer lost ads from incomplete samples",()=>{expect(compareAdvertising(snap("2026-09-01"),snap("2026-09-15",[],100))[0]?.status).toBe("Not observed");expect(compareAdvertising(snap("2026-09-01"),snap("2026-09-15",[],0))[0]?.status).toBe("No longer in index");});
 it("rejects incomparable markets and reversed dates",()=>{expect(()=>compareAdvertising(snap("2026-09-15"),snap("2026-09-01"))).toThrow();expect(()=>compareAdvertising(snap("2026-09-01"),{...snap("2026-09-15"),input:{...snap("").input,locationCode:2826}})).toThrow();});
 it("keeps provider observation dates and ignores other advertisers",()=>{const result=normalizeHistoricalAds([{items:[{datetime:"2026-09-01 08:00:00 +00:00",items:[{type:"paid",url:"https://example.com/a",rank_group:1},{type:"paid",url:"https://notexample.com",rank_group:2},{type:"organic",url:"https://example.com/b",rank_group:1}]}]}],"example.com");expect(result[0]?.observedAt).toBe("2026-09-01T08:00:00.000Z");expect(result[0]?.ads).toHaveLength(1);});
});
