import {targetMatches,type NormalTarget} from "./comparison-targets";
import type {GapKeyword} from "./domain-comparison";
import type {SerpEvidence} from "./serp-evidence";
export type TargetCollection={target:NormalTarget;keywords:{keyword:string;position:number|null;url:string|null;volume:number|null;difficulty:number|null;intent:string|null}[];total:number|null;offset:number;complete:boolean;collectedAt:string};
export type ComparisonReport={input:{targets:NormalTarget[];locationCode:number;languageCode:string};collections:TargetCollection[];collectedAt:string;costUsd:number;verification?:SerpEvidence[]};
export function scopedMatrix(report:ComparisonReport,evidence:SerpEvidence[]=report.verification??[]):GapKeyword[]{
 const rows=new Map<string,GapKeyword>();for(const collection of report.collections)for(const item of collection.keywords){const key=item.keyword.toLowerCase(),row=rows.get(key)??{keyword:item.keyword,volume:item.volume,difficulty:item.difficulty,intent:item.intent,positions:{}};const previous=row.positions[collection.target.id];if(!previous||item.position!=null&&(previous.position==null||item.position<previous.position))row.positions[collection.target.id]={position:item.position,url:item.url,known:item.position!=null};rows.set(key,row);}
 for(const raw of evidence){if(raw.locationCode!==report.input.locationCode||raw.languageCode!==report.input.languageCode||raw.device!=="desktop")continue;const row=rows.get(raw.keyword.toLowerCase())??{keyword:raw.keyword,volume:null,difficulty:null,intent:null,positions:{}};
 for(const target of report.input.targets){const matches=raw.items.filter(item=>item.type===target.kind&&item.url&&targetMatches(target,item.url)).sort((a,b)=>(a.groupPosition??a.position??999)-(b.groupPosition??b.position??999));const first=matches[0];row.positions[target.id]={position:first?.groupPosition??first?.position??null,url:first?.url??null,known:!!first||raw.depth>=100,observed:!!first};}rows.set(raw.keyword.toLowerCase(),row);}
 return [...rows.values()].map(row=>({...row,positions:Object.fromEntries(report.input.targets.map(target=>[target.id,row.positions[target.id]??{position:null,url:null,known:report.collections.find(collection=>collection.target.id===target.id)?.complete??false}]))}));
}
export function overlapGroups(rows:GapKeyword[],ids:string[]){const groups=new Map<string,number>();for(const row of rows){const present=ids.filter(id=>row.positions[id]?.position!=null||row.positions[id]?.observed===true),key=JSON.stringify(present);if(present.length)groups.set(key,(groups.get(key)??0)+1);}return [...groups].map(([key,count])=>({ids:JSON.parse(key) as string[],count})).sort((a,b)=>b.count-a.count);}
