import type {SerpEvidence} from "./serp-evidence";
export type SerpCluster={id:string;label:string;keywords:string[];intent:string|null;totalVolume:number|null;targetUrl:string|null;parentId:string|null;minimumOverlap:number;collectedFrom:string;collectedTo:string};
export type SerpStrategy={clusters:SerpCluster[];missing:string[];input:{keywords:string[];locationCode:number;languageCode:string;device:string};builtAt:string};
export function organicUrls(report:SerpEvidence){return new Set(report.items.filter(item=>item.type==="organic"&&item.url).sort((a,b)=>(a.groupPosition??a.position??999)-(b.groupPosition??b.position??999)).slice(0,10).flatMap(item=>{try{const url=new URL(item.url!);url.hash="";return [url.toString().replace(/\/$/,"")];}catch{return [];}}));}
export function sharedResults(a:SerpEvidence,b:SerpEvidence){if(a.locationCode!==b.locationCode||a.languageCode!==b.languageCode||a.device!==b.device||Math.abs(Date.parse(a.collectedAt)-Date.parse(b.collectedAt))>7*86400000)return 0;const urls=organicUrls(a);return [...organicUrls(b)].filter(url=>urls.has(url)).length;}
/** Complete linkage prevents a chain of weakly related SERPs becoming one large cluster. */
export function buildSerpStrategy(input:SerpStrategy["input"],reports:SerpEvidence[],metrics:{keyword:string;volume:number|null;intent:string|null}[]=[],now=new Date()):SerpStrategy{
 const keys=[...new Set(input.keywords.map(key=>key.trim().toLowerCase()).filter(Boolean))],eligible=reports.filter(row=>row.locationCode===input.locationCode&&row.languageCode===input.languageCode&&row.device===input.device&&Date.parse(row.collectedAt)<=now.getTime()&&now.getTime()-Date.parse(row.collectedAt)<=7*86400000).sort((a,b)=>Date.parse(a.collectedAt)-Date.parse(b.collectedAt)),latest=new Map(eligible.map(row=>[row.keyword.toLowerCase(),row])),stats=new Map(metrics.map(row=>[row.keyword.toLowerCase(),row]));
 const evidence=keys.flatMap(key=>{const row=latest.get(key);return row&&organicUrls(row).size>=3?[row]:[];}).sort((a,b)=>(stats.get(b.keyword.toLowerCase())?.volume??0)-(stats.get(a.keyword.toLowerCase())?.volume??0)||a.keyword.localeCompare(b.keyword));
 const groups:SerpEvidence[][]=[];
 for(const row of evidence){const intent=stats.get(row.keyword.toLowerCase())?.intent;const group=groups.find(group=>group.every(other=>{const otherIntent=stats.get(other.keyword.toLowerCase())?.intent;return (!intent||!otherIntent||intent===otherIntent)&&sharedResults(row,other)>=3;}));if(group)group.push(row);else groups.push([row]);}
 const clusters=groups.map((group,index)=>{const volumes=group.flatMap(row=>{const volume=stats.get(row.keyword.toLowerCase())?.volume;return volume==null?[]:[volume];}),dates=group.map(row=>row.collectedAt).sort(),overlaps=group.flatMap((a,i)=>group.slice(i+1).map(b=>sharedResults(a,b)));return {id:`cluster-${index+1}`,label:group[0]!.keyword,keywords:group.map(row=>row.keyword),intent:stats.get(group[0]!.keyword.toLowerCase())?.intent??null,totalVolume:volumes.length===group.length?volumes.reduce((a,b)=>a+b,0):null,targetUrl:null,parentId:null,minimumOverlap:overlaps.length?Math.min(...overlaps):0,collectedFrom:dates[0]!,collectedTo:dates.at(-1)!};});
 return {input:{...input,keywords:keys},clusters,missing:keys.filter(key=>!evidence.some(row=>row.keyword.toLowerCase()===key)),builtAt:now.toISOString()};
}
export function validClusterParents(clusters:SerpCluster[]){const byId=new Map(clusters.map(row=>[row.id,row]));return clusters.every(row=>{const visited=new Set([row.id]);let parent=row.parentId;while(parent){if(visited.has(parent)||!byId.has(parent))return false;visited.add(parent);parent=byId.get(parent)!.parentId;}return true;});}
