export const TRAFFIC_REPORTS = {
  journey: { title: "Traffic Journey", metrics: ["Visits", "Upstream domains", "Downstream domains", "Traffic share"], sections: ["Traffic journey", "Traffic sources", "Traffic destinations"], columns: ["Domain", "Visits", "Traffic share", "Change"], requirement: "Upstream and downstream clickstream reports" },
  subfolders: { title: "Subfolders", metrics: ["Subfolders", "Visits", "Unique visitors", "Traffic share"], sections: ["Subfolder traffic trend", "Top subfolders"], columns: ["Subfolder", "Visits", "Share", "Change", "Top page"], requirement: "Subfolder-level traffic data" },
  "page-groups": { title: "Page Groups", metrics: ["Page groups", "Visits", "Unique visitors", "Pages per visit"], sections: ["Page group performance", "Page group comparison"], columns: ["Group", "Pages", "Visits", "Share", "Change"], requirement: "URL-level traffic and saved page-group rules" },
  funnels: { title: "Funnels", metrics: ["Visitors", "Conversions", "Conversion rate", "Drop-off"], sections: ["Conversion funnel", "Funnel stages"], columns: ["Stage", "Page / event", "Visitors", "Conversion rate", "Drop-off"], requirement: "Journey-level or owned event analytics; aggregate visit counts cannot reconstruct funnels" },
  audience: { title: "Audience Overview", metrics: ["Unique visitors", "Visits per visitor", "Audience overlap", "Cross-visitation"], sections: ["Audience trend", "Audience interests", "Audience distribution"], columns: ["Segment", "Visitors", "Share", "Change"], requirement: "Audience panel and cross-visitation data" },
  overlap: { title: "Audience Overlap", metrics: ["Shared audience", "Unique audience", "Overlap rate", "Potential audience"], sections: ["Audience overlap", "Compared domains"], columns: ["Domain", "Unique visitors", "Shared visitors", "Overlap"], requirement: "Cross-domain audience overlap data" },
  demographics: { title: "Demographics", metrics: ["Audience size", "Age coverage", "Gender coverage", "Countries"], sections: ["Age distribution", "Gender distribution", "Audience segments"], columns: ["Segment", "Audience share", "Coverage", "Period"], requirement: "Aggregated demographic panel data" },
  behavior: { title: "Audience Behaviour", metrics: ["Unique visitors", "Pages per visit", "Visit duration", "Bounce rate"], sections: ["Engagement trend", "Audience interests", "Visited domains"], columns: ["Category / domain", "Audience share", "Affinity", "Change"], requirement: "Engagement and browsing-interest panel data" },
  socioeconomics: { title: "Socioeconomics", metrics: ["Audience coverage", "Income coverage", "Education coverage", "Employment coverage"], sections: ["Household income", "Education", "Employment"], columns: ["Segment", "Share", "Market", "Coverage"], requirement: "Aggregated socioeconomic audience data" },
  market: { title: "Market Overview", metrics: ["Market traffic", "Market audience", "Growth", "Concentration"], sections: ["Market growth", "Growth quadrant", "Market players"], columns: ["Domain", "Traffic", "Market share", "Growth"], requirement: "A defined competitor set with comparable total-traffic coverage" },
  monitoring: { title: "Competitor Monitoring", metrics: ["Tracked domains", "Changes", "New pages", "Traffic change"], sections: ["Competitive changes", "Traffic trends", "Change history"], columns: ["Domain", "Change", "Detected", "Evidence"], requirement: "Comparable repeated competitor traffic/page observations" },
  daily: { title: "Daily Trends", metrics: ["Daily visits", "Change", "Peak day", "Coverage"], sections: ["Daily traffic", "Daily channel comparison"], columns: ["Date", "Visits", "Channel", "Change"], requirement: "Daily traffic entitlement; monthly totals are not interpolated into daily visits" },
  regions: { title: "Regional Trends", metrics: ["Regions", "Visits", "Traffic share", "Change"], sections: ["Geographical regions", "Business regions", "United States regions"], columns: ["Region", "Visits", "Traffic share", "Change"], requirement: "Regional traffic entitlement; country samples do not establish state-level traffic" },
  industry: { title: "Industry Trends", metrics: ["Industry traffic", "Growth", "Audience", "Leading domains"], sections: ["Industry trend", "Industry channels", "Leading websites"], columns: ["Industry / domain", "Visits", "Share", "Growth"], requirement: "Industry-level traffic coverage and a documented industry taxonomy" },
} as const;
export type ExtendedTrafficView = keyof typeof TRAFFIC_REPORTS;
export const trafficViewNames = ["overview", "channels", "countries", "pages", ...Object.keys(TRAFFIC_REPORTS)] as const;
export function trafficSource(params: URLSearchParams): "search" | "all" { return params.get("source") === "search" ? "search" : "all"; }
