import {NextResponse} from "next/server";
import {z} from "zod";
import {canAccessSite,hasPermission} from "@/platform/access";
import {getManagedSite} from "@/platform/site-store";
import {saveWorkspace,workspaceRecords,updateWorkspace} from "@/platform/workspace-store";
import {localSeoDashboard} from "@/platform/local-seo";
import {qaLocalSeo} from "@/data/qa-fixtures";
import {PublicUrlSchema} from "@/lib/content-workspace";
export async function GET(request:Request){const site=new URL(request.url).searchParams.get("site")??"";if(!await getManagedSite(site)||!await canAccessSite(request,site))return NextResponse.json({error:"Website access required."},{status:403});return NextResponse.json({records:await workspaceRecords(site,"listing_inventory"),distribution:{connected:false,reason:"Directory distribution requires a separate listing-provider contract. Inventory and review decisions are available now."}});}
const Input=z.object({site:z.string(),id:z.string().uuid().optional(),updatedAt:z.string().datetime().optional(),locationId:z.string().min(1).max(160),directory:z.string().trim().min(1).max(100),url:PublicUrlSchema.nullable(),businessName:z.string().trim().min(1).max(300),address:z.string().trim().max(1000),phone:z.string().trim().max(100),status:z.enum(["unverified","correct","needs_update","duplicate","missing"]),note:z.string().trim().max(4000),reviewed:z.boolean()});
export async function POST(request:Request){const parsed=Input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Complete the location, directory and business details."},{status:400});const input=parsed.data;if(!await getManagedSite(input.site)||!await canAccessSite(request,input.site)||!await hasPermission(request,"manage_content",input.site))return NextResponse.json({error:"Content permission required."},{status:403});const {site,id,updatedAt,...payload}=input;const locations=process.env.QA_SYNTHETIC==="true"?qaLocalSeo(site,[site]).locations:(await localSeoDashboard([site])).locations;if(!locations.some(row=>row.id===input.locationId))return NextResponse.json({error:"Choose a location belonging to this website."},{status:400});const existing=id?(await workspaceRecords(site,"listing_inventory")).find(row=>row.recordKey===id):null;if(id&&!existing)return NextResponse.json({error:"Listing not found."},{status:404});if(existing&&updatedAt!==existing.updatedAt)return NextResponse.json({error:"This listing changed. Reload before saving your review."},{status:409});const data={...payload,source:"manual_review",reviewedAt:input.reviewed?new Date().toISOString():existing?.payload.reviewedAt??null};const record=existing?await updateWorkspace(existing,data):await saveWorkspace(site,"listing_inventory",crypto.randomUUID(),data);if(!record)return NextResponse.json({error:"This listing changed during saving. Reload before retrying."},{status:409});return NextResponse.json({record});}
