"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {useDomain} from "@/components/shell/domain-context";
import {useJson} from "@/lib/use-live";
import {Card,Button} from "@/components/ui/primitives";
import {DataTable} from "@/components/ui/data-table";
import {Drawer} from "@/components/ui/drawer";
import {ReportMetric,ReportTabs} from "@/components/reports/report-layout";
import {ResearchEvidencePanel} from "@/components/research/evidence-panel";
import {ResearchHandoff} from "@/components/research/research-handoff";
import type {AiVisibilityDashboard} from "@/platform/ai-read-model";
import {competitorCitationGaps} from "@/lib/ai-research";
import {exportRows} from "@/lib/report-download";
const platformName=(value:string)=>({chatgpt:"ChatGPT",claude:"Claude",gemini:"Gemini",perplexity:"Perplexity",google_ai_overview:"Google AI Overview",google_ai_mode:"Google AI Mode",copilot:"Copilot"}[value]??value);
const field="h-9 rounded border border-border bg-card px-3 text-xs";
export default function PromptResearch(){
 const {activeDomain,range}=useDomain(),site=activeDomain?.id;
 const data=useJson<AiVisibilityDashboard>(site?`/api/ai-visibility?scope=${encodeURIComponent(site)}&days=${parseInt(range)||28}`:"/api/ai-visibility?scope=portfolio");
 const [view,setView]=useState("prompts"),[query,setQuery]=useState(""),[platform,setPlatform]=useState(""),[topic,setTopic]=useState(""),[absent,setAbsent]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[detail,setDetail]=useState<AiVisibilityDashboard["observations"][number]|null>(null),[collect,setCollect]=useState(false);
 const rows=useMemo(()=>{const topics=new Map((data.data?.trackedPrompts??[]).map(row=>[row.prompt,row.topic]));return (data.data?.observations??[]).map(row=>({...row,topic:topics.get(row.prompt)??"Unassigned"})).filter(row=>(!query||row.prompt.toLowerCase().includes(query.toLowerCase()))&&(!platform||row.platform===platform)&&(!topic||row.topic===topic)&&(!absent||!row.mentioned));},[data.data,query,platform,topic,absent]);
 const gaps=useMemo(()=>competitorCitationGaps(rows),[rows]);
 const clusters=[...new Set(rows.map(row=>row.topic))].map(label=>({label,rows:rows.filter(row=>row.topic===label)}));
 if(!site)return <Card className="p-8 text-sm text-muted">Choose a website for prompt research.</Card>;
 return <div className="space-y-4 pb-8"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-4"><div><p className="mb-2 text-xs text-muted">AI › AI Analysis</p><h1 className="text-xl font-bold">Prompt Research: <span className="font-medium">{activeDomain.host}</span></h1></div><div className="flex gap-2"><Button size="sm" onClick={()=>setCollect(true)}>Discover prompts</Button><Link className={`${field} flex items-center text-purple`} href={`/ai-visibility?view=prompts&site=${site}&range=${range}`}>Set up tracking</Link><Button size="sm" disabled={!rows.length} onClick={()=>exportRows("prompt-research.csv",["Prompt","Topic","Platform","Brand mentioned","Cited sources","Measured"],rows.filter(row=>!selected.size||selected.has(row.prompt)).map(row=>[row.prompt,row.topic,row.platform,row.mentioned?"Yes":"No",row.citations.map(item=>item.url).join("; "),String(row.capturedAt)]))}>Export</Button></div></div>
 <ReportTabs items={[{id:"prompts",label:"Prompts"},{id:"topics",label:"Topics"},{id:"sources",label:"Citation gaps"},{id:"demand",label:"Demand & discovery"}]} value={view} onChange={setView}/>
 {data.error&&<p role="alert" className="text-sm text-critical">Prompt evidence could not load. <button className="underline" onClick={data.refresh}>Retry</button></p>}
 <div className="flex flex-wrap items-center gap-2"><input aria-label="Filter prompts" className={field} value={query} placeholder="Filter by prompt" onChange={e=>setQuery(e.target.value)}/><select className={field} aria-label="Prompt platform" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">All AI platforms</option>{[...new Set(data.data?.observations.map(row=>row.platform)??[])].map(value=><option key={value} value={value}>{platformName(value)}</option>)}</select><select className={field} aria-label="Prompt topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{[...new Set((data.data?.trackedPrompts??[]).map(row=>row.topic)),"Unassigned"].map(value=><option key={value}>{value}</option>)}</select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={absent} onChange={e=>setAbsent(e.target.checked)}/>Brand absent</label><span className="ml-auto text-xs text-muted">Latest saved response per prompt and platform</span></div>
 <Card className="grid grid-cols-2 divide-x divide-border lg:grid-cols-4"><ReportMetric label="Prompts" value={data.data?new Set(rows.map(row=>row.prompt)).size:null}/><ReportMetric label="Responses" value={data.data?rows.length:null}/><ReportMetric label="Brand absent" value={data.data?rows.filter(row=>!row.mentioned).length:null}/><ReportMetric label="Citation gaps" value={data.data?gaps.length:null}/></Card>
 {view==="prompts"&&<Card className="p-4"><div className="mb-3 flex flex-wrap items-center gap-2"><Button size="sm" onClick={()=>setSelected(new Set(rows.map(row=>row.prompt)))}>Select filtered</Button><Button size="sm" disabled={!selected.size} onClick={()=>setSelected(new Set())}>Clear selection</Button><ResearchHandoff keywords={[...selected]} evidence={{observations:rows.filter(row=>selected.has(row.prompt)).map(row=>({prompt:row.prompt,platform:row.platform,mentioned:row.mentioned,citations:row.citations,capturedAt:row.capturedAt}))}} sourceUrl={`/ai-research?site=${site}`}/></div><DataTable rows={rows} rowKey={row=>row.id} columns={[{key:"select",header:"",render:row=><input type="checkbox" aria-label={`Select prompt ${row.prompt} — ${platformName(row.platform)}`} checked={selected.has(row.prompt)} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(row.prompt))next.delete(row.prompt);else next.add(row.prompt);return next;})}/>},{key:"prompt",header:"Prompt",render:row=><button className="text-left text-purple" onClick={()=>setDetail(row)}>{row.prompt}</button>},{key:"topic",header:"Topic",render:row=>row.topic},{key:"platform",header:"AI platform",render:row=>platformName(row.platform)},{key:"mentioned",header:"Brand presence",render:row=>row.mentioned?"Mentioned":"Absent"},{key:"citations",header:"Sources",render:row=>row.citations.length},{key:"date",header:"Updated",render:row=>new Date(row.capturedAt).toLocaleString()}]} pageSize={30} emptyLabel="No saved prompt responses match these filters. Discover prompts or set up tracking."/></Card>}
 {view==="topics"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{clusters.map(cluster=><Card key={cluster.label} className="p-4"><h2 className="text-base font-semibold">{cluster.label}</h2><p className="my-3 text-xs text-muted">{new Set(cluster.rows.map(row=>row.prompt)).size} prompts · {cluster.rows.filter(row=>!row.mentioned).length} responses without your brand</p>{cluster.rows.slice(0,5).map(row=><button key={row.id} className="mb-3 block text-left text-xs text-purple" onClick={()=>setDetail(row)}>{row.prompt}</button>)}<Button size="sm" onClick={()=>{setTopic(cluster.label);setView("prompts");}}>View all prompts</Button></Card>)}</div>}
 {view==="sources"&&<Card className="p-4"><h2 className="text-base font-semibold">Sources cited when competitors appear and your brand is absent</h2><p className="my-3 text-xs leading-5 text-muted">These are observed opportunities for review. A citation does not prove endorsement, and an external source alone is not a competitor gap.</p><DataTable rows={gaps} rowKey={row=>row.domain} columns={[{key:"source",header:"Source domain",render:row=><a href={row.urls[0]} target="_blank" rel="noreferrer" className="text-purple">{row.domain}</a>},{key:"competitors",header:"Competitors in responses",render:row=>row.competitors.join(", ")},{key:"responses",header:"Responses",render:row=>row.checks},{key:"prompts",header:"Prompts",render:row=>row.prompts.length},{key:"platforms",header:"Platforms",render:row=>row.platforms.join(", ")},{key:"evidence",header:"Evidence",render:row=><button className="text-purple" onClick={()=>setDetail(rows.find(item=>row.observationIds.includes(item.id))??null)}>Read response</button>}]} emptyLabel="No competitor citation gaps were verified in these saved responses."/></Card>}
 {view==="demand"&&<ResearchEvidencePanel features={["demand","mentions"]}/>}
 <Drawer open={collect} onClose={()=>setCollect(false)} title="Discover AI prompts" width="max-w-5xl"><ResearchEvidencePanel features={["demand","questions","mentions"]}/></Drawer>
 <Drawer open={!!detail} onClose={()=>setDetail(null)} title="Prompt evidence" width="max-w-3xl">{detail&&<div className="space-y-4"><h2 className="text-base font-semibold">{detail.prompt}</h2><p className="text-xs text-muted">{platformName(detail.platform)} · {new Date(detail.capturedAt).toLocaleString()}</p><p className="whitespace-pre-wrap text-sm leading-7">{detail.responseText||"No response text returned."}</p><h3 className="text-sm font-semibold">Cited sources</h3>{detail.citations.map(row=><a key={row.id} href={row.url} target="_blank" rel="noreferrer" className="block break-all text-xs text-purple">{row.title||row.url}</a>)}<ResearchHandoff keywords={[detail.prompt]} evidence={detail} sourceUrl={`/ai-research?site=${site}`}/></div>}</Drawer>
 </div>;
}
