"use client";
import { useState } from "react";
import Link from "next/link";
import { useDomain } from "@/components/shell/domain-context";
import { Card } from "@/components/ui/primitives";
import { DataTable, type Column } from "@/components/ui/data-table";
import { ReportMetric, ReportTabs, MissingChart } from "./report-layout";
import { MultiLine } from "@/components/charts/charts";
import type { AiVisibilityDashboard } from "@/platform/ai-read-model";
import { navigationHref } from "@/lib/nav";
import { competitorCitationGaps } from "@/lib/ai-research";
import { formatDate } from "@/lib/dates";

type Observation = AiVisibilityDashboard["observations"][number];
const label = (v: string) => ({ chatgpt: "ChatGPT", google_ai_overview: "Google AI Overview", google_ai_mode: "Google AI Mode" }[v] ?? v[0].toUpperCase() + v.slice(1));
export function AiOverview({ data, onSelect }: { data: AiVisibilityDashboard; onSelect: (row: Observation) => void }) {
  const { scope, range } = useDomain();
  const [metric, setMetric] = useState("counts"), [distribution, setDistribution] = useState("mentions");
  const [topicView, setTopicView] = useState("topics");
  const measured = data.summary.checks > 0;
  const link = (href: string) => navigationHref({ href, group: "site" }, scope, range);
  const platforms = ["chatgpt", "google_ai_overview", "google_ai_mode", "gemini", ...data.platforms.map((row) => row.platform)].filter((v, i, a) => a.indexOf(v) === i);
  const max = Math.max(1, ...data.platforms.map((r) => distribution === "mentions" ? r.mentions : r.citedPages));
  const columns: Column<Observation>[] = [
    {key:"prompt",header:"Topic / prompt",sortValue:r=>r.prompt,render:r=><div className="max-w-xl"><span className="font-medium text-purple">{r.prompt}</span><div className="mt-1 text-xs text-muted">{r.topic} · {r.siteName}</div></div>},
    {key:"platform",header:"AI platform",sortValue:r=>r.platform,render:r=>label(r.platform)},
    {key:"mentioned",header:"Your mention",sortValue:r=>Number(r.mentioned),render:r=>r.mentioned ? "Mentioned" : "Absent"},
    {key:"cited",header:"Citation",sortValue:r=>Number(r.cited),render:r=>r.cited ? "Cited" : "Not cited"},
    {key:"position",header:"Position",sortValue:r=>r.recommendationPosition??999,render:r=>r.recommendationPosition??"—"},
    {key:"date",header:"Checked",sortValue:r=>r.capturedOn,render:r=>formatDate(r.capturedOn)},
  ];
  const topics = topicView === "gaps" ? data.observations.filter(r=>!r.mentioned) : data.observations;
  const sources = topicView === "source-gaps" ? competitorCitationGaps(data.observations).map(row=>({domain:row.domain,citations:row.checks,platforms:row.platforms,urls:row.urls.slice(0,5)})) : data.sources.filter(row=>topicView !== "owned" || row.owned);
  return <div className="space-y-5">
    <div className="grid gap-5 xl:grid-cols-[minmax(250px,.9fr)_minmax(0,3fr)]">
      <Card className="min-h-[330px] p-5"><h2 className="text-base font-bold">AI mention rate</h2><p className="mt-1 text-xs text-muted">Measured brand presence</p><div className="relative mx-auto mt-8 h-36 max-w-60"><svg viewBox="0 0 220 125" className="w-full" aria-hidden="true"><path d="M 15 110 A 95 95 0 0 1 205 110" stroke="rgb(var(--border))" fill="none" strokeWidth="16" strokeLinecap="round"/><path d="M 15 110 A 95 95 0 0 1 205 110" stroke="var(--chart-orange)" fill="none" strokeWidth="16" strokeLinecap="round" pathLength="100" strokeDasharray={`${measured ? data.summary.mentionRate : 0} 100`}/></svg><div className="absolute inset-x-0 bottom-3 text-center"><strong className="text-4xl font-semibold">{measured ? `${data.summary.mentionRate}%` : "—"}</strong><p className="mt-1 text-xs text-muted">of checked responses</p></div></div><p className="text-center text-xs leading-5 text-muted">{data.summary.checks.toLocaleString()} checks · {data.scope.days} days</p><Link href={link("/ai-visibility?view=prompts")} className="mt-5 block text-center text-sm text-purple">Manage prompt tracking →</Link></Card>
      <Card className="min-w-0 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 pt-2"><ReportTabs items={[{id:"counts",label:"Main metrics"},{id:"audience",label:"Monthly audience"},{id:"rates",label:"AI visibility"}]} value={metric} onChange={setMetric}/><span className="pb-2 text-xs text-muted">Last {data.scope.days} days</span></div><div className="grid grid-cols-3 divide-x divide-border"><ReportMetric label="Mentions" value={measured ? data.summary.mentions : null} note="Responses mentioning your brand"/><ReportMetric label="Citations" value={measured ? data.summary.citedResponses : null} note="Responses citing your website"/><ReportMetric label="Cited pages" value={measured ? data.summary.citedPages : null} note="Distinct owned URLs"/></div>{metric === "audience" ? <MissingChart height="h-40" message="Monthly AI audience is not measured by response tracking. No audience estimate has been collected."/> : data.trend.length > 1 ? <div className="px-3 pb-4"><MultiLine data={data.trend} height={175} series={metric === "rates" ? [{key:"mentionRate",name:"Mention rate %",color:"var(--chart-orange)"},{key:"citationRate",name:"Citation rate %",color:"var(--chart-blue)"}] : [{key:"mentions",name:"Mentions",color:"var(--chart-orange)"},{key:"citedResponses",name:"Cited responses",color:"var(--chart-blue)"},{key:"citedPages",name:"Cited pages",color:"var(--chart-lilac)"}]}/></div> : <MissingChart height="h-40" message="At least two measurement dates are needed to show a trend."/>}</Card>
    </div>
    <div className="grid gap-5 xl:grid-cols-2"><Card className="min-h-[264px] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-base font-bold">Distribution by LLM</h2><select aria-label="Platform distribution metric" value={distribution} onChange={e=>setDistribution(e.target.value)} className="rounded border border-border bg-card px-2 py-1 text-xs"><option value="mentions">Mentions</option><option value="pages">Cited pages</option></select></div><div className="mt-5 space-y-4">{platforms.slice(0,4).map(name=>{const row=data.platforms.find(r=>r.platform===name), value=row ? distribution === "mentions" ? row.mentions : row.citedPages : null;return <div className="grid grid-cols-[140px_1fr_45px] items-center gap-3 text-xs" key={name}><span>{label(name)}</span><div className="h-3 rounded-sm bg-workspace"><div className="h-3 rounded-sm bg-purple" style={{width:`${value == null ? 0 : value/max*100}%`}}/></div><span className="text-right">{value??"—"}</span></div>;})}</div><details className="mt-4 text-xs"><summary className="cursor-pointer text-purple">Citation rates and recommendation positions</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Platform</th><th>Checks</th><th>Citation rate</th><th>Avg. position</th></tr></thead><tbody>{data.platforms.map(r=><tr key={r.platform} className="border-t border-border"><td className="py-2">{label(r.platform)}</td><td>{r.checks}</td><td>{r.citationRate}%</td><td>{r.avgPosition??"—"}</td></tr>)}</tbody></table></div></details></Card><Card className="min-h-[264px] p-5"><h2 className="text-base font-bold">Mentions by country / market</h2><p className="mt-1 text-xs text-muted">Collection location · unknown locations remain separate</p>{data.countries?.some(r=>r.locationCode) ? <table className="mt-5 w-full text-left text-sm"><thead className="text-xs text-muted"><tr><th>Market</th><th>Mentions</th><th>Checks</th></tr></thead><tbody>{data.countries.map(r=><tr key={r.locationCode??"unknown"} className="border-b border-border"><td className="py-3">{r.locationCode ? ({"2784":"United Arab Emirates","2840":"United States","2826":"United Kingdom"}[r.locationCode]??`Location ${r.locationCode}`) : "Unknown location"}</td><td>{r.mentions}</td><td>{r.checks}</td></tr>)}</tbody></table> : <MissingChart height="h-36" message="No country was recorded with these saved responses. Future location-targeted checks retain their collection market."/>}</Card></div>
    <div><h2 className="mb-3 text-lg font-bold">What’s next?</h2><div className="grid gap-4 md:grid-cols-3">{[{title:"Explore unanswered questions",text:"Review prompts where your website was absent.",href:"/ai-visibility?view=prompts"},{title:"Investigate cited sources",text:"Inspect the sources AI systems choose to cite.",href:"/ai-visibility?view=sources"},{title:"Check crawler access",text:"Review your website’s saved crawler audit.",href:"/ai-visibility?view=crawlers"}].map(r=><Link key={r.title} href={link(r.href)} className="rounded-md border border-border bg-card p-4 hover:border-purple"><h3 className="text-sm font-bold">{r.title} →</h3><p className="mt-2 text-xs text-muted">{r.text}</p></Link>)}</div></div>
    <section><h2 className="mb-3 text-lg font-bold">Topics & Sources</h2><Card className="p-4"><ReportTabs items={[{id:"topics",label:"Your performing topics"},{id:"gaps",label:"Topic opportunities"},{id:"sources",label:"Cited sources"},{id:"source-gaps",label:"Source opportunities"},{id:"owned",label:"Cited pages"}]} value={topicView} onChange={setTopicView}/><p className="my-3 text-xs text-muted">{["topics","gaps"].includes(topicView) ? "Latest saved response per prompt and platform. Open a row to inspect the answer." : topicView === "source-gaps" ? "Sources cited in responses that mention a verified competitor while your brand is absent. Review the original response in Prompt Research." : "Saved citation evidence. Source URLs are limited to five examples per domain."}</p>{["topics","gaps"].includes(topicView) ? <DataTable rows={topics} columns={columns} onRowClick={onSelect} searchKeys={r=>`${r.prompt} ${r.topic} ${r.platform}`} searchPlaceholder="Filter by topic or prompt" exportName="ai-topics"/> : <DataTable rows={sources} columns={[{key:"domain",header:"Source",sortValue:r=>r.domain,render:r=><span className="text-purple">{r.domain}</span>},{key:"citations",header:"Citations",sortValue:r=>r.citations,render:r=>r.citations},{key:"platforms",header:"AI platforms",render:r=>r.platforms.map(label).join(", ")},{key:"urls",header:"Example cited pages",render:r=><div>{r.urls.map(url=><a className="block max-w-md truncate text-purple" key={url} href={url} target="_blank" rel="noreferrer">{url}</a>)}</div>}]} searchKeys={r=>r.domain} exportName="ai-sources"/>}</Card></section>
  </div>;
}
