"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {Card,CardHeader,Button} from "@/components/ui/primitives";
import {DataTable,type Column} from "@/components/ui/data-table";
import {ReportMetric,ReportTabs,MissingChart} from "./report-layout";
import {MultiLine} from "@/components/charts/charts";
import {ResearchHandoff} from "@/components/research/research-handoff";
import {ResearchEvidencePanel} from "@/components/research/evidence-panel";
import {aiCompetitorMatrix,aiSourceRows,aiBrandRows,narrativeRows,type AiObservation,type GapKind} from "@/lib/ai-report-model";
import {competitorCitationGaps} from "@/lib/ai-research";
import type {AiVisibilityDashboard} from "@/platform/ai-read-model";
const field="h-9 rounded border border-border bg-card px-3 text-xs";
export function AiResearchReports({view,data,onSelect}:{view:string;data:AiVisibilityDashboard;onSelect:(row:AiObservation)=>void}) {
  const params=useSearchParams(),router=useRouter(),site=params.get("site")??data.scope.siteSlugs[0]??"";
  const defaults=data.competitors.filter(row=>!row.owned).map(row=>row.host||row.name).slice(0,4);
  const chosen=params.has("compare")?(params.get("compare")??"").split(",").filter(Boolean).slice(0,4):defaults;
  const [input,setInput]=useState(chosen.join(", ")),[group,setGroup]=useState<"topic"|"prompt">("topic"),[gap,setGap]=useState<GapKind>("all"),[sentiment,setSentiment]=useState("all"),[query,setQuery]=useState(""),[sourceKind,setSourceKind]=useState("all");
  const rows=useMemo(()=>data.observations.filter(row=>(!query||`${row.prompt} ${row.topic} ${row.responseText}`.toLowerCase().includes(query.toLowerCase()))&&(sentiment==="all"||row.mentioned&&row.sentiment===sentiment)),[data.observations,query,sentiment]);
  const matrix=aiCompetitorMatrix(rows,chosen,group),sources=aiSourceRows(rows,view==="cited-pages"),brands=aiBrandRows(rows),narratives=narrativeRows(rows),gaps=competitorCitationGaps(rows);
  const coverage=<p className="text-xs leading-5 text-muted">Based on {rows.length} latest saved responses, one per prompt/platform, within the selected period. Report totals may cover more historical responses. These are observed samples; audience and market-wide AI visibility are not inferred.</p>;
  const open=(ids:string[])=>{const row=rows.find(r=>ids.includes(r.id));if(row)onSelect(row);};
  const promptLink=(prompt:string)=>`/ai-visibility?site=${encodeURIComponent(site)}&view=prompts&prompt=${encodeURIComponent(prompt)}&range=${params.get("range")??"28d"}`;
  const rowActions=(items:AiObservation[])=>items.length?<div className="flex gap-2"><Button size="sm" onClick={()=>onSelect(items[0]!)}>Read response</Button><Link className="text-xs text-purple" href={promptLink(items[0]!.prompt)}>Track prompt →</Link></div>:"—";
  const matrixColumns:Column<typeof matrix[number]>[]=[{key:"topic",header:group==="topic"?"Topic":"Prompt",render:row=><button className="text-left text-purple" onClick={()=>{if(group==="topic"){setQuery(row.label);setGroup("prompt");}else onSelect(row.observations[0]!);}}>{row.label}</button>},{key:"prompts",header:"Prompts",sortValue:row=>row.prompts.length,render:row=>row.prompts.length},{key:"own",header:"Your mentions",sortValue:row=>row.own,render:row=>`${row.own} / ${row.checks}`},...chosen.map((name,i)=>({key:`competitor-${i}`,header:name,sortValue:(row:typeof matrix[number])=>row.rivals[i]??0,render:(row:typeof matrix[number])=>`${row.rivals[i]??0} / ${row.checks}`})),{key:"gap",header:"Opportunity",render:row=>row.kind},{key:"actions",header:"Actions",render:row=>rowActions(row.observations)}];
  return <div className="space-y-4">
    <div className="flex flex-wrap gap-2"><input aria-label="Search AI report" className={`${field} min-w-64 flex-1`} placeholder="Filter topics, prompts or answers" value={query} onChange={e=>setQuery(e.target.value)}/><select className={field} aria-label="AI answer sentiment" value={sentiment} onChange={e=>setSentiment(e.target.value)}>{["all","positive","neutral","mixed","negative"].map(value=><option key={value} value={value}>{value==="all"?"All sentiment":value}</option>)}</select><Link href={`/ai-research?site=${encodeURIComponent(site)}&view=demand&range=${params.get("range")??"28d"}`} className={`${field} flex items-center text-purple`}>Discover prompts</Link></div>
    {coverage}
    {view==="competitors"&&<><Card className="p-4"><label className="text-sm font-semibold">Compare up to four competitors</label><div className="mt-2 flex gap-2"><input aria-label="AI competitor domains or brands" className={`${field} flex-1`} value={input} onChange={e=>setInput(e.target.value)} placeholder="competitor.com, another brand"/><Button onClick={()=>{const next=new URLSearchParams(params);next.set("compare",input.split(",").map(v=>v.trim()).filter(Boolean).slice(0,4).join(","));router.push(`?${next}`,{scroll:false});}}>Compare saved evidence</Button></div><p className="mt-2 text-xs text-muted">Matches recorded competitor domains or names. Adding a competitor here does not trigger paid collection.</p></Card><Card className="grid grid-cols-2 lg:grid-cols-4"><ReportMetric label="Sampled prompts" value={new Set(rows.map(r=>r.prompt)).size}/><ReportMetric label="Your mentioned responses" value={rows.length?rows.filter(r=>r.mentioned).length:null}/><ReportMetric label="Competitors compared" value={chosen.length}/><ReportMetric label="Monthly audience" note="Audience dataset not connected"/></Card><ReportTabs items={[{id:"topic",label:"Topics"},{id:"prompt",label:"Prompts"}]} value={group} onChange={setGroup}/><div className="flex flex-wrap gap-2">{(["all","missing","weak","shared","strong","unique"] as GapKind[]).map(id=><Button size="sm" key={id} variant={gap===id?"primary":"secondary"} onClick={()=>setGap(id)}>{id[0]!.toUpperCase()+id.slice(1)}</Button>)}</div><Card className="p-4"><DataTable rows={matrix.filter(row=>gap==="all"||gap==="shared"?gap==="all"||row.shared:row.kind===gap)} columns={matrixColumns} rowKey={row=>row.label} exportName="ai-competitor-research" emptyLabel="No comparable saved responses. Discover prompts and collect matching brand/competitor evidence."/></Card></>}
    {["brand","perception","narrative","questions"].includes(view)&&<><Card className="grid grid-cols-2 divide-x divide-border lg:grid-cols-4"><ReportMetric label="Mentioned responses" value={rows.length?rows.filter(r=>r.mentioned).length:null}/><ReportMetric label="Positive mentions" value={rows.some(r=>r.mentioned)?rows.filter(r=>r.mentioned&&r.sentiment==="positive").length:null}/><ReportMetric label="Cited sources" value={rows.length?aiSourceRows(rows).length:null}/><ReportMetric label="Question topics" value={rows.length?narratives.length:null}/></Card>{view==="brand"&&<><Card><CardHeader title="Brand visibility trend" subtitle="All saved responses in the selected period"/>{data.trend.length>1?<div className="p-4"><MultiLine data={data.trend} height={210} series={[{key:"mentionRate",name:"Mention rate (%)",color:"var(--chart-orange)"},{key:"citationRate",name:"Citation rate (%)",color:"var(--chart-purple)"}]}/></div>:<MissingChart height="h-40" message="At least two dates of saved responses are needed."/>}</Card><Card className="p-4"><CardHeader title="Brand performance"/><DataTable rows={brands} rowKey={row=>row.host||row.name} exportName="ai-brands" columns={[{key:"brand",header:"Brand",render:row=>`${row.name}${row.owned?" (your brand)":""}`},{key:"mentions",header:"Mentioned responses",sortValue:row=>row.mentions,render:row=>row.mentions},{key:"sources",header:"Source domains",sortValue:row=>row.sources,render:row=>row.sources},{key:"positive",header:"Positive",render:row=>row.positive},{key:"negative",header:"Negative",render:row=>row.negative},{key:"response",header:"Evidence",render:row=><Button size="sm" onClick={()=>open(row.observationIds)}>Read response</Button>}]}/></Card><ResearchEvidencePanel features={["mentions"]}/></>}
    {view==="perception"&&<><Card><CardHeader title="Sentiment over time" subtitle="All saved mentioned responses, grouped by collection date"/><div className="p-4"><MultiLine data={data.trend} height={210} series={[{key:"positiveMentions",name:"Positive",color:"var(--chart-purple)"},{key:"negativeMentions",name:"Negative",color:"var(--chart-orange)"},{key:"neutralMentions",name:"Neutral / mixed",color:"var(--chart-blue)"}]}/></div></Card><div className="grid gap-4 lg:grid-cols-2">{[...new Set(rows.map(r=>r.platform))].map(platform=><Card key={platform} className="p-4"><CardHeader title={platform.replace(/_/g," ")}/>{["positive","neutral","mixed","negative"].map(value=>{const set=rows.filter(r=>r.platform===platform&&r.mentioned),count=set.filter(r=>r.sentiment===value).length;return <button key={value} className="my-2 flex w-full items-center gap-3 text-left text-sm" onClick={()=>setSentiment(value)}><span className="w-20 capitalize">{value}</span><span className="h-3 flex-1 bg-workspace"><span className="block h-3 bg-purple" style={{width:`${set.length?count/set.length*100:0}%`}}/></span><span>{count}/{set.length}</span></button>;})}</Card>)}</div><Card className="p-4"><CardHeader title="Sentiment evidence" subtitle="Automated classifications of saved answers; review the text and platform comparison before acting."/><DataTable rows={rows.filter(r=>r.mentioned)} rowKey={r=>r.id} onRowClick={onSelect} columns={[{key:"prompt",header:"Question",render:r=>r.prompt},{key:"platform",header:"Platform",render:r=>r.platform},{key:"sentiment",header:"Sentiment",render:r=>r.sentiment},{key:"date",header:"Checked",render:r=>new Date(r.capturedAt).toLocaleDateString()}]}/><Link href={`/ai-visibility?site=${site}&view=comparison`} className="mt-3 inline-block text-sm text-purple">Review matched answers and human assessments →</Link></Card></>}
    {view==="narrative"&&<Card className="p-4"><CardHeader title="Narrative drivers by topic" subtitle="Topics attached to saved prompts, grouped by observed sentiment. These associations do not establish what caused an opinion."/><DataTable rows={narratives} rowKey={r=>r.label} exportName="ai-narratives" columns={[{key:"topic",header:"Topic / driver",render:r=>r.label},{key:"frequency",header:"Responses",sortValue:r=>r.checks,render:r=>r.checks},{key:"mentions",header:"Brand mentions",render:r=>r.own},{key:"positive",header:"Positive",render:r=>r.positive},{key:"negative",header:"Negative",render:r=>r.negative},{key:"neutral",header:"Neutral / mixed",render:r=>r.neutral},{key:"evidence",header:"Evidence",render:r=>rowActions(r.observations)}]}/></Card>}
    {view==="questions"&&<Card className="p-4"><CardHeader title="Questions about your category and brand" subtitle="Question-level evidence from saved AI responses. Search PAA questions remain available in Keyword Research."/><DataTable rows={aiCompetitorMatrix(rows,[],"prompt")} rowKey={r=>r.label} exportName="ai-questions" columns={[{key:"question",header:"Question",render:r=>r.label},{key:"mentions",header:"Brand mentions",render:r=>`${r.own}/${r.checks}`},{key:"sources",header:"Cited sources",render:r=>aiSourceRows(r.observations).length},{key:"platforms",header:"AI platforms",render:r=>[...new Set(r.observations.map(o=>o.platform))].join(", ")},{key:"actions",header:"Actions",render:r=><><ResearchHandoff keywords={[r.label]} evidence={{observationIds:r.observations.map(o=>o.id)}} sourceUrl={`/ai-visibility?site=${site}&view=questions`}/>{rowActions(r.observations)}</>}]} /></Card>}</>}
    {["sources","cited-pages"].includes(view)&&<Card className="p-4"><CardHeader title={view==="cited-pages"?"Cited Pages":"Cited Sources"} subtitle="Counts are distinct saved responses; repeat citations inside one answer are deduplicated."/><select aria-label="Cited source ownership" className={`${field} mb-4`} value={sourceKind} onChange={e=>setSourceKind(e.target.value)}><option value="all">All sources</option><option value="owned">Your website</option><option value="external">External sources</option></select><DataTable rows={sources.filter(r=>sourceKind==="all"||(sourceKind==="owned"?r.owned:!r.owned))} rowKey={r=>r.key} searchKeys={r=>`${r.key} ${r.prompts.join(" ")}`} exportName={`ai-${view}`} columns={[{key:"source",header:view==="cited-pages"?"Source URL":"Source domain",render:r=><a href={r.url} target="_blank" rel="noreferrer" className="block max-w-96 truncate text-purple">{r.key}</a>},{key:"responses",header:"Citing responses",sortValue:r=>r.checks,render:r=>r.checks},{key:"urls",header:"Source pages",render:r=>r.urls.length},{key:"prompts",header:"Prompts",render:r=>r.prompts.length},{key:"platforms",header:"Platforms",render:r=>r.platforms.join(", ")},{key:"date",header:"Last observed",render:r=>r.latest.slice(0,10)},{key:"actions",header:"Evidence",render:r=><Button size="sm" onClick={()=>open(r.observationIds)}>Read response</Button>}]}/></Card>}
    {view==="source-opportunities"&&<Card className="p-4"><CardHeader title="Source Opportunities" subtitle="Sources cited in answers with verified competitors and no mention of your brand."/><DataTable rows={gaps} rowKey={r=>r.domain} exportName="ai-source-opportunities" columns={[{key:"domain",header:"Source",render:r=>r.domain},{key:"competitors",header:"Competitors mentioned",render:r=>r.competitors.join(", ")},{key:"responses",header:"Responses",sortValue:r=>r.checks,render:r=>r.checks},{key:"prompts",header:"Prompts",render:r=>r.prompts.length},{key:"action",header:"Evidence",render:r=><Button size="sm" onClick={()=>open(r.observationIds)}>Read response</Button>}]}/></Card>}
    {!rows.length&&<Card className="p-5"><CardHeader title="Build this report with saved AI evidence" subtitle="Add tracking prompts for this website, choose platforms and run an approved collection. Existing evidence is preserved."/><Link className="text-sm font-semibold text-purple" href={promptLink("")}>Set up prompt tracking →</Link></Card>}
  </div>;
}
