"use client";
import {useState} from "react";
import Link from "next/link";
import {useJson} from "@/lib/use-live";
import {Card,Button} from "@/components/ui/primitives";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Drawer} from "@/components/ui/drawer";
import {ReportMetric,ReportTabs} from "./report-layout";
import {AUDIT_THEMES,auditIssueLabel,auditPageDiff,themeSummary,type AuditPage,type AuditPageRun} from "@/lib/audit-pages";
import {SiteFindingWorkDrawer,type SiteFinding} from "@/components/workflow/site-finding-work-drawer";
type RunInfo=Omit<AuditPageRun,"pages"|"truncated">;
const field="h-9 rounded border border-border bg-card px-3 text-xs";
export function AuditPageWorkspace({site,compare=false,initialTheme="crawlability"}:{site:string;compare?:boolean;initialTheme?:string}){
 const inventory=useJson<{runs:RunInfo[]}>(`/api/site-audit/pages?site=${encodeURIComponent(site)}`),[chosen,setChosen]=useState(""),[previous,setPrevious]=useState(""),[theme,setTheme]=useState(initialTheme),[filter,setFilter]=useState("all"),[issue,setIssue]=useState(""),[page,setPage]=useState<AuditPage|null>(null),[finding,setFinding]=useState<SiteFinding|null>(null);
 const runs=inventory.data?.runs??[],current=runs.find(run=>run.id===chosen)??runs.at(-1),prior=runs.find(run=>run.id===previous&&run.date<(current?.date??""))??runs.filter(run=>run.source===current?.source&&run.date<(current?.date??"")).at(-1);
 const afterState=useJson<{run:AuditPageRun}>(current?`/api/site-audit/pages?site=${encodeURIComponent(site)}&run=${current.id}`:null),beforeState=useJson<{run:AuditPageRun}>(compare&&prior?`/api/site-audit/pages?site=${encodeURIComponent(site)}&run=${prior.id}`:null);
 const after=afterState.data?.run,before=beforeState.data?.run,selectedTheme=AUDIT_THEMES.find(row=>row.id===theme)??AUDIT_THEMES[0],pages=after?.pages??[],summary=themeSummary(pages,selectedTheme.pattern),changes=before&&after?auditPageDiff(before,after):[];
 const checks=[...new Set(pages.flatMap(page=>Object.keys(page.checks).filter(key=>selectedTheme.pattern.test(key))))];
 const counts=checks.map(key=>({key,title:auditIssueLabel(key),affected:pages.filter(page=>page.checks[key]===true).length,checked:pages.filter(page=>key in page.checks).length}));
 const filtered=pages.filter(page=>{const entries=Object.entries(page.checks).filter(([key])=>selectedTheme.pattern.test(key));return (!issue||page.checks[issue]===true)&&(filter==="all"||filter==="affected"&&entries.some(([,value])=>value)||filter==="clear"&&entries.length>0&&!entries.some(([,value])=>value)||filter==="unchecked"&&!entries.length);});
 const columns:Column<AuditPage>[]=[{key:"url",header:"Page URL",sortValue:row=>row.url,render:row=><button className="max-w-96 break-all text-left text-purple" onClick={()=>setPage(row)}>{row.url}</button>},{key:"status",header:"HTTP status",sortValue:row=>row.statusCode??0,render:row=>row.statusCode??"Unknown"},{key:"checks",header:"Findings",render:row=>Object.entries(row.checks).filter(([key,value])=>selectedTheme.pattern.test(key)&&value).map(([key])=>auditIssueLabel(key)).join(" · ")||(!Object.keys(row.checks).some(key=>selectedTheme.pattern.test(key))?"Not checked":"No recorded failure")},...(theme==="performance"?[{key:"time",header:"Load time",sortValue:(row:AuditPage)=>row.loadTimeMs??0,render:(row:AuditPage)=>row.loadTimeMs==null?"Unknown":`${row.loadTimeMs} ms`}]:theme==="linking"?[{key:"links",header:"Internal / external links",render:(row:AuditPage)=>`${row.internalLinks??"—"} / ${row.externalLinks??"—"}`}]:theme==="international"?[{key:"languages",header:"Hreflang targets",render:(row:AuditPage)=>Object.keys(row.hreflang).join(", ")||"Not recorded"}]:theme==="markups"?[{key:"schema",header:"Schema types",render:(row:AuditPage)=>row.schemaTypes.join(", ")||"Not recorded"}]:[{key:"depth",header:"Depth",render:(row:AuditPage)=>row.depth??"Unknown"}])];
 const select=(label:string,value:string,options:RunInfo[],change:(id:string)=>void)=><label className="text-xs">{label}<select aria-label={label} value={value} onChange={e=>change(e.target.value)} className={`${field} ml-2 max-w-full`}><option value="">Choose completed crawl</option>{options.map(run=><option key={run.id} value={run.id}>{new Date(run.date).toLocaleString()} · {run.source} · {run.total} pages</option>)}</select></label>;
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{compare?"Page-level crawl changes":selectedTheme.label}</h2><Link className="text-xs font-semibold text-purple" href={`/scan-centre?site=${site}`}>Run updated checks →</Link></div><div className="flex flex-wrap gap-3">{compare&&select("Earlier crawl",prior?.id??"",runs.filter(run=>run.date<(current?.date??"")),setPrevious)}{select(compare?"Later crawl":"Crawl date",current?.id??"",runs,setChosen)}</div>{[inventory.error,afterState.error,beforeState.error].filter(Boolean).map((error,i)=><p key={i} role="alert" className="text-sm text-critical">{error}</p>)}{(after?.truncated||before?.truncated)&&<p className="text-sm text-warning">This report shows up to 10,000 pages per crawl. Pages outside the loaded set are not treated as fixed.</p>}
 {compare?<><Card className="grid grid-cols-2 divide-x divide-border lg:grid-cols-4">{["new","fixed","recurring","unverified"].map(state=><button className="text-left" key={state} onClick={()=>setFilter(state)}><ReportMetric label={state[0]!.toUpperCase()+state.slice(1)} value={before&&after?changes.filter(row=>row.state===state).length:null}/></button>)}</Card><Card className="p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h3 className="text-base font-semibold">Issue changes by URL</h3><select aria-label="Crawl change status" className={field} value={filter} onChange={e=>setFilter(e.target.value)}>{["all","new","fixed","recurring","unverified"].map(value=><option key={value}>{value}</option>)}</select></div><p className="mb-4 text-xs text-muted">New and fixed require explicit results for the same URL and check from both crawls. Missing pages or checks remain unverified.</p><DataTable rows={changes.filter(row=>filter==="all"||row.state===filter)} columns={[{key:"url",header:"URL",render:row=><span className="break-all">{row.url}</span>},{key:"issue",header:"Issue",render:row=>auditIssueLabel(row.issue)},{key:"state",header:"Status",render:row=><span className={row.state==="fixed"?"text-success":row.state==="new"?"text-critical":"text-muted"}>{row.state}</span>},{key:"evidence",header:"Evidence",render:row=>row.detail}]} rowKey={row=>row.key} searchKeys={row=>`${row.url} ${row.issue}`} exportName="page-level-crawl-changes" emptyLabel={before&&after?"No matching issue changes.":"Select two completed crawls to compare page evidence."}/></Card></>:<>
 <ReportTabs items={AUDIT_THEMES} value={theme as typeof AUDIT_THEMES[number]["id"]} onChange={value=>{setTheme(value);setFilter("all");setIssue("");}} label="Thematic audit reports"/>
 <Card className="grid grid-cols-2 divide-x divide-border lg:grid-cols-4"><ReportMetric label="Pages checked" value={after?summary.checked:null}/><ReportMetric label="Affected pages" value={summary.checked?summary.affected:null}/><ReportMetric label="Issue occurrences" value={summary.checked?summary.occurrences:null}/><ReportMetric label="Checks unavailable" value={after?summary.unknown:null}/></Card>
 <div className="grid gap-4 lg:grid-cols-[1fr_2fr]"><Card className="p-4"><h3 className="mb-4 text-base font-semibold">{selectedTheme.label} checks</h3>{counts.length?counts.map(row=><button className="flex w-full items-start justify-between gap-3 border-b border-border py-3 text-left text-xs" key={row.key} onClick={()=>{setIssue(row.key);setFilter("all");}}><span className="text-purple">{row.title}<span className="mt-1 block text-[11px] text-muted">{row.checked} pages checked</span></span><strong>{row.affected}</strong></button>):<p className="text-sm text-muted">This crawl did not record these checks. Run a rendered crawl for international SEO and markup evidence.</p>}{theme==="performance"&&<p className="mt-4 text-xs leading-5 text-muted">These are crawler load timings. <Link className="text-purple" href={`/health?site=${site}&view=speed`}>Open measured mobile/desktop speed tests and Core Web Vitals.</Link></p>}</Card><Card className="p-4"><h3 className="mb-4 text-base font-semibold">Pages</h3><div className="mb-3 flex flex-wrap gap-2"><select aria-label="Thematic page status" className={field} value={filter} onChange={e=>setFilter(e.target.value)}>{["all","affected","clear","unchecked"].map(value=><option key={value}>{value}</option>)}</select>{issue&&<Button size="sm" onClick={()=>setIssue("")}>Clear: {auditIssueLabel(issue)}</Button>}</div><DataTable rows={filtered} columns={columns} searchKeys={row=>`${row.url} ${row.title??""}`} rowKey={row=>row.url} pageSize={25} exportName={`audit-${theme}`} emptyLabel="No pages match this report and filter."/></Card></div></>}
 <Drawer open={!!page} onClose={()=>setPage(null)} title={page?.title??"Page evidence"} subtitle={page?.url}>{page&&<div className="space-y-4"><a className="break-all text-sm text-purple" href={page.url} target="_blank" rel="noreferrer">{page.url}</a><p className="text-xs text-muted">{current?.source} · {current?.date}</p><DataTable rows={Object.entries(page.checks).map(([key,failed])=>({key,failed}))} columns={[{key:"check",header:"Check",render:row=>auditIssueLabel(row.key)},{key:"status",header:"Finding",render:row=>row.failed?"Review required":"Clear"}]} rowKey={row=>row.key}/><Button onClick={()=>{setFinding({key:`audit-page:${theme}:${page.url}`,title:`Review ${selectedTheme.label.toLowerCase()} on ${page.title??page.url}`,module:"Technical",executionType:"technical_task",priorityScore:75,pageMode:"existing_page",targetUrl:page.url,sourceUrl:`/site-audit?site=${site}&view=thematic`,evidenceLabel:`Page evidence from ${current?.date}`,sourceEvidence:{run:current,page}});setPage(null);}}>Create task from this page</Button></div>}</Drawer><SiteFindingWorkDrawer finding={finding} siteSlug={site} siteName={site} onClose={()=>setFinding(null)}/>
 </div>;
}
