"use client";
import {useState} from "react";
import {useJson} from "@/lib/use-live";
import {Card} from "@/components/ui/primitives";
import {DataTable} from "@/components/ui/data-table";
import {MissingChart} from "./report-layout";
import {MultiLine} from "@/components/charts/charts";
import {compareAudits,type AuditSnapshot} from "@/lib/audit-reports";
export function AuditHistory({site,view}:{site:string;view:"compare"|"progress"}){
 const state=useJson<{reports:AuditSnapshot[]}>(`/api/site-audit/history?site=${site}`),[from,setFrom]=useState(""),[to,setTo]=useState(""),[metric,setMetric]=useState("issues");
 const reports=state.data?.reports??[],before=reports.find(row=>row.date===from)??reports.at(-2),after=reports.find(row=>row.date===to)??reports.at(-1),rows=before&&after?compareAudits(before,after):[];
 const choice=(label:string,value:string,onChange:(value:string)=>void)=><label className="text-xs">{label}<select aria-label={label} className="ml-2 h-9 rounded border border-border bg-card px-2" value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose crawl</option>{reports.map(row=><option key={row.date} value={row.date}>{row.date}</option>)}</select></label>;
 const series=reports.filter(row=>(!from||row.date>=from)&&(!to||row.date<=to)).map(row=>({date:row.date,score:row.healthScore,issues:row.issues.length,errors:row.issues.filter(issue=>issue.severity==="critical"||issue.severity==="high").length,warnings:row.issues.filter(issue=>issue.severity==="medium").length,notices:row.issues.filter(issue=>issue.severity==="low").length}));
 return <Card className="p-4"><h2 className="mb-4 text-base font-semibold">{view==="compare"?"Compare Crawls":"Audit Progress"}</h2>{state.error&&<p className="text-sm text-critical">Saved history could not load. <button onClick={state.refresh}>Retry</button></p>}<div className="mb-4 flex flex-wrap gap-4">{choice("From crawl",view==="compare"?before?.date??"":from,setFrom)}{choice("To crawl",view==="compare"?after?.date??"":to,setTo)}{view==="progress"&&<select aria-label="Audit progress metric" className="h-9 rounded border border-border bg-card px-2 text-xs" value={metric} onChange={e=>setMetric(e.target.value)}>{[["issues","Issue types"],["score","Provider health score"],["errors","Errors"],["warnings","Warnings"],["notices","Notices"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>}</div>{view==="compare"?before&&after?<><p className="mb-4 text-xs text-muted">{rows[0]?.comparable?"Same reported crawl size and methodology. Changes describe issue occurrences; verify URLs before treating an issue as fixed.":"Crawl size or methodology differs, so changes are not interpreted as fixes. The original counts remain visible."}</p><DataTable rows={rows} columns={[{key:"title",header:"Issue",sortValue:row=>row.title,render:row=>row.title},{key:"severity",header:"Severity",render:row=>row.severity},{key:"before",header:before.date,sortValue:row=>row.before,render:row=>row.before},{key:"after",header:after.date,sortValue:row=>row.after,render:row=>row.after},{key:"change",header:"Occurrence change",sortValue:row=>row.change??0,render:row=>row.change==null?"Not comparable":`${row.change>0?"+":""}${row.change}`}]} rowKey={row=>row.key} exportName="crawl-comparison"/></>:<MissingChart message="Two completed crawl snapshots are needed to compare audit results."/>:series.length>1?<MultiLine data={series} series={[{key:metric,name:metric,color:"var(--chart-orange)"}]} height={280}/>:<MissingChart message="At least two completed crawl dates are needed to display progress."/>}<p className="mt-4 text-xs text-muted">{reports.length} completed crawl snapshots. Opening history makes no provider request.</p></Card>;
}
