"use client";
import {useState} from "react";
import {Card,EmptyState} from "@/components/ui/primitives";
import {DataTable} from "@/components/ui/data-table";
import {ResearchEvidencePanel} from "@/components/research/evidence-panel";
import {useJson} from "@/lib/use-live";
import type {Backlink} from "@/lib/types";
import type {BacklinkHistoryPoint} from "@/platform/types";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from "recharts";
export function BacklinkDetails({view,links,history,host,site,onSelect}:{view:string;links:Backlink[]|null;history:BacklinkHistoryPoint[]|null;host:string;site:string;onSelect:(link:Backlink)=>void}){
 const [source,setSource]=useState("");
 const groups=[...new Set((links??[]).map(row=>row.sourceDomain))].map(domain=>({domain,rows:(links??[]).filter(row=>row.sourceDomain===domain)})).sort((a,b)=>b.rows.length-a.rows.length);
 const nodes=groups.slice(0,16);
 return <div className="space-y-4">
 {view==="overview"&&<><div className="grid gap-4 lg:grid-cols-2"><Card className="p-4"><h2 className="mb-3 font-semibold">Backlinks & referring domains</h2>{history?.length?<div className="h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Line dataKey="backlinks" stroke="var(--chart-orange)" dot={false}/><Line dataKey="referringDomains" stroke="var(--chart-purple)" dot={false}/></LineChart></ResponsiveContainer></div>:<EmptyState title="History not yet collected" description="Collect backlink history from Scan Centre to chart the full provider totals."/>}</Card><Card className="p-4"><h2 className="mb-3 font-semibold">New & lost backlinks</h2>{history?.length?<div className="h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Line dataKey="newBacklinks" stroke="#24845b" dot={false}/><Line dataKey="lostBacklinks" stroke="#cf4960" dot={false}/></LineChart></ResponsiveContainer></div>:<p className="py-12 text-sm text-muted">Historical movement requires at least one provider history collection.</p>}</Card></div><ResearchEvidencePanel features={["link_bulk"]} title="Backlink profile" targetDomain={host}/></>}
 {view==="network"&&<Card className="p-4"><h2 className="font-semibold">Network Graph</h2><p className="mt-1 text-xs text-muted">Direct links in your saved sample. Select a referring domain to inspect its pages. Second-tier relationships are not inferred.</p>{!nodes.length?<EmptyState title="No network evidence yet" description="Collect backlink evidence from Scan Centre to build this graph."/>:<div className="grid gap-4 lg:grid-cols-[1fr_320px]"><svg viewBox="0 0 600 400" className="w-full" aria-label="Observed referring-domain network"><circle cx="300" cy="200" r="38" fill="var(--chart-orange)"/><text x="300" y="204" textAnchor="middle" fontSize="10" fill="white">{host}</text>{nodes.map((node,i)=>{const angle=i/nodes.length*Math.PI*2,x=300+230*Math.cos(angle),y=200+150*Math.sin(angle);return <g key={node.domain}><line x1="300" y1="200" x2={x} y2={y} stroke="#b9afd8" strokeWidth={Math.min(5,1+node.rows.length/5)}/><g role="button" tabIndex={0} aria-label={`Inspect ${node.domain}`} onClick={()=>setSource(node.domain)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSource(node.domain);}}} className="cursor-pointer"><circle cx={x} cy={y} r={source===node.domain?14:10} fill="var(--chart-purple)"/><text x={x} y={y+24} textAnchor="middle" fontSize="10" fill="currentColor">{node.domain.length>26?`${node.domain.slice(0,23)}…`:node.domain}</text></g></g>;})}</svg><div className="py-4"><label className="text-xs font-semibold">Referring domain<select className="mt-2 w-full rounded border border-border bg-card p-2" value={source} onChange={e=>setSource(e.target.value)}><option value="">All {groups.length} domains</option>{groups.map(row=><option key={row.domain}>{row.domain}</option>)}</select></label><DataTable rows={(links??[]).filter(row=>!source||row.sourceDomain===source)} columns={[{key:"source",header:"Source page",render:row=><button className="max-w-52 truncate text-purple" onClick={()=>onSelect(row)}>{row.sourceUrl}</button>},{key:"status",header:"Status",render:row=>row.status}]} pageSize={8} exportName="backlink-network"/><p className="mt-3 text-xs text-muted">Graph shows the 16 largest sampled referring domains. The table includes the complete saved sample.</p></div></div>}</Card>}
 {view==="pages"&&<ResearchEvidencePanel features={["link_pages"]} title="Indexed Pages" targetDomain={host}/>}
 {view==="bulk"&&<ResearchEvidencePanel features={["link_bulk"]} title="Bulk Analysis"/>}
 {view==="recovery"&&<ResearchEvidencePanel features={["recovery"]} title="Broken Backlink Recovery"/>}
 {view==="research"&&<ResearchEvidencePanel features={["links","link_pages","link_bulk"]}/>}
 {view==="outbound"&&<OutboundDomains site={site}/>}
 </div>;
}
function OutboundDomains({site}:{site:string}){
 const {data,error}=useJson<{rows:{domain:string;sourceUrl:string;targetUrl:string;anchor:string|null;nofollow:boolean;capturedAt:string}[];capturedAt:string|null;pages:number;coverageLimited:boolean}>(`/api/backlinks/outbound?site=${encodeURIComponent(site)}`);
 const [domain,setDomain]=useState("");const rows=data?.rows??[],hosts=[...new Set(rows.map(row=>row.domain))];
 return <Card className="p-4"><h2 className="font-semibold">Outbound Domains</h2><p className="my-3 text-xs text-muted">External links observed by the browser crawl{data?.capturedAt?` · ${new Date(data.capturedAt).toLocaleString()}`:""}. Counts cover {data?.pages??0} crawled pages only.{data?.coverageLimited&&" Collection limits apply; this is a partial saved sample."}</p>{error?<p role="alert" className="text-critical">Could not load saved outbound links.</p>:!data?<p>Loading outbound links…</p>:<><select aria-label="Outbound domain" value={domain} onChange={e=>setDomain(e.target.value)} className="mb-3 rounded border border-border bg-card p-2 text-sm"><option value="">All {hosts.length} domains</option>{hosts.map(host=><option key={host}>{host}</option>)}</select><DataTable rows={rows.filter(row=>!domain||row.domain===domain)} columns={[{key:"domain",header:"Domain",render:row=>row.domain},{key:"source",header:"Source page",render:row=><a href={row.sourceUrl} className="block max-w-64 truncate text-purple" target="_blank" rel="noreferrer">{row.sourceUrl}</a>},{key:"target",header:"Destination",render:row=><a href={row.targetUrl} className="block max-w-64 truncate text-purple" target="_blank" rel="noreferrer">{row.targetUrl}</a>},{key:"anchor",header:"Anchor",render:row=>row.anchor??"—"},{key:"follow",header:"Attribute",render:row=>row.nofollow?"Nofollow":"Follow"}]} searchKeys={row=>`${row.domain} ${row.sourceUrl} ${row.anchor}`} exportName="outbound-links"/>{!rows.length&&<p className="mt-3 text-sm text-muted">No outbound destinations saved. <a className="text-purple underline" href={`/technical-crawler?site=${site}`}>Run a browser crawl</a> to collect them. Older crawls recorded counts only.</p>}</>}</Card>;
}
