"use client";
import {useMemo,useState} from "react";
import {useJson} from "@/lib/use-live";
import {urlSwitchEvidence,cannibalisationAssessment,type UrlSwitchEvidence} from "@/lib/cannibalisation";
import type {RankObservation,TrackedKeyword} from "@/lib/rank-reports";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Drawer} from "@/components/ui/drawer";
import {ResearchHandoff} from "@/components/research/research-handoff";
type Candidate={query:string;pages:{page:string;clicks:number;impressions:number;position:number}[];totalImpressions:number};
type Row=Candidate&{evidence:UrlSwitchEvidence[];assessment:ReturnType<typeof cannibalisationAssessment>};
export function CannibalisationWorkspace({site,candidates}:{site:string;candidates:Candidate[]}){
 const [from,setFrom]=useState(()=>new Date(Date.now()-90*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10)),[detail,setDetail]=useState<Row|null>(null);
 const ranks=useJson<{keywords:TrackedKeyword[];history:RankObservation[];truncated:boolean}>(`/api/rank-tracking/report?site=${site}&from=${from}&to=${to}`);
 const rows=useMemo(()=>{const switches=urlSwitchEvidence(ranks.data?.keywords??[],ranks.data?.history??[]),queries=new Set([...candidates.map(row=>row.query.toLowerCase()),...switches.map(row=>row.keyword.toLowerCase())]);return [...queries].map(query=>{const candidate=candidates.find(row=>row.query.toLowerCase()===query),evidence=switches.filter(row=>row.keyword.toLowerCase()===query).map(row=>row.evidence);return {query:candidate?.query??query,pages:candidate?.pages??[],totalImpressions:candidate?.totalImpressions??0,evidence,assessment:cannibalisationAssessment(evidence)};}).sort((a,b)=>({high:0,medium:1,low:2}[a.assessment.priority]-{high:0,medium:1,low:2}[b.assessment.priority])||b.totalImpressions-a.totalImpressions);},[candidates,ranks.data]);
 const columns:Column<Row>[]=[{key:"query",header:"Keyword",render:row=><button className="text-left text-purple" onClick={()=>setDetail(row)}>{row.query}</button>},{key:"signal",header:"Evidence",render:row=>row.assessment.label},{key:"priority",header:"Review priority",render:row=>row.assessment.priority},{key:"pages",header:"Observed pages",render:row=>new Set([...row.pages.map(page=>page.page),...row.evidence.flatMap(target=>target.pages)]).size},{key:"switches",header:"URL switches",render:row=>row.evidence.length?row.evidence.reduce((sum,target)=>sum+target.switches,0):"Not observed"},{key:"impressions",header:"GSC impressions",render:row=>row.pages.length?row.totalImpressions.toLocaleString():"—"}];
 return <div className="space-y-3 p-4"><p className="text-xs text-muted">Separate potential page overlap from dated URL changes. High review priority requires repeated switches and a decline of at least five positions in the same search target.</p><div className="flex flex-wrap gap-3 text-xs"><label>Ranking evidence from <input aria-label="Cannibalisation from" type="date" className="rounded border border-border bg-card p-2" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>to <input aria-label="Cannibalisation to" type="date" className="rounded border border-border bg-card p-2" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{ranks.error&&<p role="alert" className="text-xs text-critical">{ranks.error}</p>}{ranks.data?.truncated&&<p className="text-xs text-warning">Ranking history is capped. Narrow the dates for complete coverage.</p>}<DataTable rows={rows} columns={columns} rowKey={row=>row.query} exportName="cannibalisation-evidence" emptyLabel="No overlapping pages or URL switches in the available evidence."/><Drawer open={!!detail} onClose={()=>setDetail(null)} title={detail?.query??"Cannibalisation evidence"}>{detail&&<div className="space-y-4"><h3 className="text-base font-semibold">{detail.assessment.label}</h3><p className="text-sm">{detail.assessment.explanation}</p>{detail.pages.length>0&&<><h3 className="text-sm font-semibold">Search Console page overlap</h3><p className="text-xs text-muted">Latest saved Search Console reporting period; independent of the ranking dates selected above.</p><DataTable rows={detail.pages} columns={[{key:"page",header:"Page",render:row=><span className="break-all">{row.page}</span>},{key:"impressions",header:"Impressions",render:row=>row.impressions},{key:"position",header:"Avg. position",render:row=>row.position.toFixed(1)}]} rowKey={row=>row.page}/></>}{detail.evidence.map(target=><div key={target.targetId}><h3 className="text-sm font-semibold">Database {target.locationCode} · {target.languageCode} · {target.device}</h3><p className="my-2 text-xs">{target.switches} URL changes · {target.decline==null?"Insufficient endpoint positions":`${target.decline>0?"Decline":"Improvement"} of ${Math.abs(target.decline)} positions`}</p><DataTable rows={target.sequence} columns={[{key:"date",header:"Date",render:row=>row.date},{key:"position",header:"Position",render:row=>row.position??"Not observed"},{key:"url",header:"Ranking URL",render:row=><span className="break-all">{row.url??"—"}</span>}]} rowKey={row=>row.date}/></div>)}<ResearchHandoff keywords={[detail.query]} evidence={{assessment:detail.assessment,targets:detail.evidence,pages:detail.pages}} sourceUrl={`/keyword-strategy?site=${site}&view=cannibalisation`}/></div>}</Drawer></div>;
}
