"use client";

import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {Card, Button} from "@/components/ui/primitives";
import {ReportMetric, MissingChart} from "./report-layout";
import {useJson} from "@/lib/use-live";
import type {CommandRecord} from "@/lib/command-model";
import {AdvertisingResearch} from "@/components/research/advertising-research";
import {ResearchEvidencePanel} from "@/components/research/evidence-panel";
import {Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis} from "recharts";

type Keyword = {keyword:string;position:number|null;volume:number|null;traffic:number|null;intent:string|null;url:string|null};
type Page = {url:string;keywords:number|null;traffic:number|null};
type Competitor = {domain:string;commonKeywords:number|null;keywords:number|null;traffic:number|null};
const number = (value:number|null|undefined) => value == null ? "—" : value.toLocaleString(undefined,{maximumFractionDigits:1});
const heading = "border-b border-border px-4 py-3 text-[15px] font-semibold";
const cell = "border-b border-border/60 px-4 py-2.5 text-xs last:border-0";

export function DomainOverviewPanels({site,host,market,language,keywords,pages,backlinks,onView}:{site?:string;host:string;market:number;language:string;keywords:Keyword[];pages:Page[];backlinks?:{backlinks:number|null;referringDomains:number|null;rank:number|null;spamScore:number|null};onView:(view:"keywords"|"pages")=>void}) {
 const params=useSearchParams();
 function href(path:string,view?:string){const query=new URLSearchParams(params);query.delete("evidence");query.delete("view");if(view)query.set("view",view);query.set("domain",host);return `${path}?${query}`;}
 const distribution=[{name:"1–3",min:1,max:3},{name:"4–10",min:4,max:10},{name:"11–20",min:11,max:20},{name:"21–50",min:21,max:50},{name:"51–100",min:51,max:100}].map(bucket=>({...bucket,count:keywords.filter(row=>row.position!=null&&row.position>=bucket.min&&row.position<=bucket.max).length}));
 const intents=["informational","navigational","commercial","transactional","unknown"].map(intent=>({intent,rows:keywords.filter(row=>(row.intent??"unknown")===intent)})).filter(row=>row.rows.length);
 const topKeywords=[...keywords].sort((a,b)=>(b.traffic??-1)-(a.traffic??-1)).slice(0,5);
 const topPages=[...pages].sort((a,b)=>(b.traffic??-1)-(a.traffic??-1)).slice(0,5);
 return <>
  <h2 className="pt-2 text-xl font-semibold">Organic Research</h2>
  <div className="grid gap-4 xl:grid-cols-2">
   <Card className="min-w-0 overflow-hidden"><h3 className={heading}>Top Organic Keywords</h3><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-workspace text-xs text-muted"><tr>{["Keyword","Position","Volume","Traffic est."].map(label=><th key={label} className="px-4 py-2 font-medium">{label}</th>)}</tr></thead><tbody>{topKeywords.map(row=><tr key={row.keyword}><td className={cell}><Link className="text-purple" href={`${href('/keyword-research')}&q=${encodeURIComponent(row.keyword)}`}>{row.keyword}</Link></td><td className={cell}>{number(row.position)}</td><td className={cell}>{number(row.volume)}</td><td className={cell}>{number(row.traffic)}</td></tr>)}</tbody></table></div>{!topKeywords.length&&<p className="p-6 text-xs text-muted">No ranking keyword evidence was returned.</p>}<div className="flex items-center justify-between p-4"><Button size="sm" onClick={()=>onView("keywords")}>View details</Button><span className="text-[11px] text-muted">{keywords.length} collected keywords</span></div></Card>
   <Card className="min-w-0"><h3 className={heading}>Organic Position Distribution</h3>{keywords.length?<div className="h-56 p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={distribution}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="count" name="Collected keywords" fill="var(--chart-orange)"/></BarChart></ResponsiveContainer></div>:<MissingChart height="h-40" message="Ranking positions have not been collected for this market."/>}<p className="px-4 pb-4 text-[11px] text-muted">Position groups in the collected sample. Historical index totals appear in the traffic summary.</p></Card>
   <Card className="min-w-0 overflow-hidden"><h3 className={heading}>Keywords by Intent</h3><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-workspace text-muted"><tr>{["Intent","Keywords","Share of sample","Traffic est."].map(label=><th key={label} className="px-4 py-2 font-medium">{label}</th>)}</tr></thead><tbody>{intents.map(({intent,rows})=><tr key={intent}><td className={`${cell} capitalize`}>{intent}</td><td className={cell}>{rows.length}</td><td className={cell}>{(rows.length/keywords.length*100).toFixed(1)}%</td><td className={cell}>{rows.every(row=>row.traffic!=null)?number(rows.reduce((sum,row)=>sum+row.traffic!,0)):"—"}</td></tr>)}</tbody></table></div>{!intents.length&&<p className="p-6 text-xs text-muted">No keyword intent evidence collected.</p>}<p className="p-4 text-[11px] text-muted">Shares describe collected keywords, not the full search index.</p></Card>
   {site?<DomainCompetitors site={site} host={host} market={market} language={language} href={href('/competitors','competitors')}/>:<Card><h3 className={heading}>Main Organic Competitors</h3><p className="p-6 text-xs text-muted">Select a website workspace to save competitor discovery.</p></Card>}
   <Card className="min-w-0 overflow-hidden"><h3 className={heading}>Top Organic Pages</h3><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-workspace text-muted"><tr>{["URL","Traffic est.","Keywords"].map(label=><th key={label} className="px-4 py-2 font-medium">{label}</th>)}</tr></thead><tbody>{topPages.map(row=><tr key={row.url}><td className={cell}><a href={row.url} target="_blank" rel="noreferrer" className="block max-w-64 truncate text-purple">{row.url}</a></td><td className={cell}>{number(row.traffic)}</td><td className={cell}>{number(row.keywords)}</td></tr>)}</tbody></table></div>{!topPages.length&&<p className="p-6 text-xs text-muted">No ranking page evidence was returned.</p>}<div className="p-4"><Button size="sm" onClick={()=>onView("pages")}>View details</Button></div></Card>
   <Card><h3 className={heading}>Competitive Positioning Map</h3><DomainPositioning site={site} host={host} market={market} language={language}/></Card>
  </div>
  <h2 className="pt-2 text-xl font-semibold">Advertising Research</h2>
  {site?<AdvertisingResearch site={site} domain={host} location={market} language={language}/>:<Card className="p-4 text-sm text-muted">Choose a website workspace to collect advertising research.</Card>}
  <h2 className="pt-2 text-xl font-semibold">Backlinks</h2>
  <Card><div className="grid grid-cols-2 divide-x divide-border lg:grid-cols-4"><ReportMetric label="Backlinks" value={backlinks?.backlinks}/><ReportMetric label="Referring domains" value={backlinks?.referringDomains}/><ReportMetric label="Domain rank" value={backlinks?.rank} note="DataForSEO rank; not Semrush Authority Score"/><ReportMetric label="Spam score" value={backlinks?.spamScore} note="Provider risk estimate; review individual links"/></div>{site&&<details className="border-t border-border p-4"><summary className="cursor-pointer text-sm font-semibold">Backlink records, anchors and referring domains</summary><div className="mt-4"><ResearchEvidencePanel features={["links"]} targetDomain={host}/></div></details>}</Card>
 </>;
}
function DomainCompetitors({site,host,market,language,href}:{site:string;host:string;market:number;language:string;href:string}){const state=useJson<{records:CommandRecord[]}>(`/api/organic-competitors?site=${site}`);const report=state.data?.records.find(row=>{const input=row.payload.input as {domain:string;locationCode:number;languageCode:string};return input.domain===host&&input.locationCode===market&&input.languageCode===language;});const rows=(report?.payload.rows??[]) as Competitor[];return <Card className="min-w-0 overflow-hidden"><h3 className={heading}>Main Organic Competitors</h3><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-workspace text-muted"><tr>{["Competitor","Common keywords","Organic keywords"].map(label=><th key={label} className="px-4 py-2 font-medium">{label}</th>)}</tr></thead><tbody>{rows.slice(0,5).map(row=><tr key={row.domain}><td className={cell}>{row.domain}</td><td className={cell}>{number(row.commonKeywords)}</td><td className={cell}>{number(row.keywords)}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="p-6 text-xs text-muted">{state.error?"Competitor evidence could not load.":"No competitor discovery saved for this domain and database."}</p>}<div className="flex items-center justify-between p-4"><Link className="rounded border border-border px-3 py-1.5 text-xs font-semibold text-purple" href={href}>View details</Link>{report&&<span className="text-[11px] text-muted">{new Date(report.updatedAt).toLocaleDateString()}</span>}</div></Card>;}
function DomainPositioning({site,host,market,language}:{site?:string;host:string;market:number;language:string}){return site?<PositioningData site={site} host={host} market={market} language={language}/>:<MissingChart height="h-40" message="Select a website workspace to compare discovered competitors."/>;}
function PositioningData({site,host,market,language}:{site:string;host:string;market:number;language:string}){const state=useJson<{records:CommandRecord[]}>(`/api/organic-competitors?site=${site}`);const report=state.data?.records.find(row=>{const input=row.payload.input as {domain:string;locationCode:number;languageCode:string};return input.domain===host&&input.locationCode===market&&input.languageCode===language;});const rows=((report?.payload.rows??[]) as Competitor[]).filter(row=>row.keywords!=null&&row.traffic!=null).slice(0,10);return rows.length?<PositioningChart rows={rows}/>:<MissingChart height="h-40" message="Discover organic competitors to compare their indexed keywords and estimated organic traffic."/>;}
import {Scatter,ScatterChart,ZAxis} from "recharts";
function PositioningChart({rows}:{rows:Competitor[]}){return <div className="h-64 p-4"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{bottom:18,left:12,right:12}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="keywords" type="number" name="Organic keywords" tick={{fontSize:10}} label={{value:"Organic keywords",position:"insideBottom",offset:-12,fontSize:10}}/><YAxis dataKey="traffic" type="number" name="Organic traffic est." tick={{fontSize:10}}/><ZAxis dataKey="commonKeywords" range={[40,240]} name="Common keywords"/><Tooltip cursor={{strokeDasharray:"3 3"}} content={({active,payload})=>active&&payload?.length?<div className="rounded border border-border bg-card p-3 text-xs"><strong>{payload[0]?.payload.domain}</strong><p>{number(payload[0]?.payload.keywords)} keywords</p><p>{number(payload[0]?.payload.traffic)} estimated traffic</p></div>:null}/><Scatter data={rows} fill="var(--chart-orange)"/></ScatterChart></ResponsiveContainer></div>;}
