"use client";
import { useDomain } from "@/components/shell/domain-context";
import { useJson } from "@/lib/use-live";
import type { AiVisibilityDashboard } from "@/platform/ai-read-model";
import { Card } from "@/components/ui/primitives";
import { ReportMetric } from "./report-layout";
import Link from "next/link";
export function DomainAiSummary({host}:{host:string}){const {sites,range}=useDomain();const site=sites.find(r=>r.host.replace(/^www\./,"")===host.replace(/^www\./,""));return site?<MeasuredDomainAi site={site.id} days={parseInt(range)}/>:<Card><div className="border-b border-border px-4 py-3 font-bold">AI Search</div><div className="grid grid-cols-3"><ReportMetric label="AI mention rate"/><ReportMetric label="Mentions"/><ReportMetric label="Cited pages"/></div><p className="px-4 py-3 text-xs text-muted">No tracked website matches this research domain. Indexed AI research is available from AI Visibility.</p></Card>;}
function MeasuredDomainAi({site,days}:{site:string;days:number}){const state=useJson<AiVisibilityDashboard>(`/api/ai-visibility?scope=${encodeURIComponent(site)}&days=${days}`);const measured=Boolean(state.data?.summary.checks);return <Card><div className="border-b border-border px-4 py-2 font-bold">AI Search</div><div className="grid grid-cols-3"><ReportMetric label="Mention rate" value={measured?`${state.data!.summary.mentionRate}%`:null}/><ReportMetric label="Mentions" value={measured?state.data!.summary.mentions:null}/><ReportMetric label="Cited pages" value={measured?state.data!.summary.citedPages:null}/></div><div className="px-4 pb-2"><div className="grid grid-cols-[1.5fr_1fr_1fr] text-[11px] text-muted"><span>Platform</span><span>Mentions</span><span>Cited pages</span></div>{[["chatgpt","ChatGPT"],["google_ai_overview","AI Overview"],["google_ai_mode","AI Mode"],["gemini","Gemini"]].map(([id,label])=>{const row=state.data?.platforms.find(p=>p.platform===id);return <Link key={id} href={`/ai-visibility?site=${site}&platform=${id}&range=${days}d`} className="grid grid-cols-[1.5fr_1fr_1fr] border-t border-border/50 py-1 text-xs hover:text-purple"><span>{label}</span><span>{row?.mentions??"—"}</span><span>{row?.citedPages??"—"}</span></Link>;})}</div><p className="px-4 pb-2 text-[11px] text-muted">Tracked responses · {days} days · {state.data?.summary.checks??0} checks. Independent of the SEO snapshot.</p>{state.error&&<button className="p-4 text-xs text-critical" onClick={state.refresh}>AI evidence could not load. Retry</button>}</Card>;}
