"use client";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { useState } from "react";
import { useJson } from "@/lib/use-live";
import type { ResearchRun } from "@/lib/research-evidence";
import { Card } from "@/components/ui/primitives";
import { MultiLine } from "@/components/charts/charts";
import { MissingChart } from "./report-layout";
import { ResearchEvidencePanel } from "@/components/research/evidence-panel";
export function DomainGrowth({site,target,market,language="en",marketLabel}:{site:string;target:string;market:number;language?:string;marketLabel?:string}) {
  const state=useJson<{runs:ResearchRun[]}>(`/api/research?site=${encodeURIComponent(site)}&feature=history`);
  const params=useSearchParams(); const countriesQuery=new URLSearchParams(params); countriesQuery.set("view","countries");
  const countries=useJson<{runs:ResearchRun[]}>(`/api/research?site=${encodeURIComponent(site)}&feature=countries`);
  const [months,setMonths]=useState(12);
  const host=target.replace(/^www\./,"").toLowerCase();
  const run=state.data?.runs.find(r=>r.status==="completed" && r.payload.market.locationCode===market && r.payload.market.languageCode===language && r.payload.input.domains.some(d=>d.replace(/^www\./,"").toLowerCase()===host));
  const countryRun=countries.data?.runs.find(r=>r.status==="completed"&&r.payload.input.domains.some(d=>d.replace(/^www\./,"")===host));
  const countryTable=countryRun?.payload.report?.tables.find(t=>t.title===`${host}: countries`);
  const table=run?.payload.report?.tables.find(t=>t.title===`${host}: monthly history`);
  const rows=(table?.rows??[]).map(r=>({date:r.id,traffic:r.values["Estimated traffic"],keywords:r.values["Ranking keywords"],top3:r.values["Top 3"],top10:r.values["Top 10"]})).slice(-months);
  return <><Card className="grid overflow-hidden lg:grid-cols-[25%_minmax(0,1fr)]"><div className="border-b border-border p-4 lg:border-b-0 lg:border-r"><h2 className="text-base font-bold">Distribution by country</h2><p className="mt-2 text-xs leading-5 text-muted">Historical series: {marketLabel ?? `Location ${market}`} · {language}. Country and language indices are compared separately.</p><Link href={`/domain-research?${countriesQuery}`} className="mt-4 block text-sm text-purple">Compare by countries →</Link>{countryTable&&<div className="mt-4 space-y-3 text-xs">{[...countryTable.rows].sort((a,b)=>Number(b.values["Organic traffic"]??-1)-Number(a.values["Organic traffic"]??-1)).slice(0,6).map(r=><div key={r.id} className="flex justify-between gap-2 border-b border-border pb-2"><span>{r.label} · {r.values.Language}</span><span>{typeof r.values["Organic traffic"] === "number" ? r.values["Organic traffic"].toLocaleString(undefined,{maximumFractionDigits:2}) : "—"}</span></div>)}<p className="text-muted">Estimated search traffic · separate language indices</p></div>}<h3 className="mt-8 text-sm font-bold">Collection date</h3><p className="mt-2 text-xs text-muted">{run ? new Date(run.updatedAt).toLocaleString() : "No matching saved history"}</p>{state.error&&<button className="mt-3 text-xs text-critical" onClick={state.refresh}>History could not load. Retry</button>}</div><div className="min-w-0 p-4"><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-bold">Traffic</h2><div className="flex gap-1">{[1,6,12].map(n=><button key={n} aria-pressed={months===n} onClick={()=>setMonths(n)} className={`rounded px-3 py-1 text-xs ${months===n?"bg-purple/10 text-purple":"text-muted"}`}>{n===12?"1Y":`${n}M`}</button>)}</div></div>{rows.length>0 ? <MultiLine data={rows} height={180} series={[{key:"traffic",name:"Estimated organic traffic",color:"var(--chart-orange)"}]}/> : <MissingChart height="h-40" message="Collect performance history for this domain and market to display the monthly trend."/>}<h2 className="mb-3 mt-5 text-base font-bold">Keywords</h2>{rows.length>0 ? <MultiLine data={rows} height={160} series={[{key:"keywords",name:"Ranking keywords",color:"var(--chart-blue)"},{key:"top10",name:"Top 10",color:"var(--chart-lilac)"},{key:"top3",name:"Top 3",color:"var(--chart-orange)"}]}/> : <MissingChart height="h-32" message="Ranking distribution is included in the same historical collection."/>}</div></Card><details className="rounded border border-border bg-card p-4"><summary className="cursor-pointer text-sm font-semibold">Manage historical evidence and review collection cost</summary><div className="mt-4"><ResearchEvidencePanel features={["history"]} targetDomain={target} targetMarket={{locationCode:market,languageCode:language,label:marketLabel??`Location ${market}`}}/></div></details></>;
}
