"use client";
import { rankingIntelligence, volumeKey } from "@/lib/rank-intelligence";
import {marketLabel} from "@/lib/markets";
import {useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import Link from "next/link";
import {useJson} from "@/lib/use-live";
import {Button,Card} from "@/components/ui/primitives";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Drawer} from "@/components/ui/drawer";
import {MultiLine} from "@/components/charts/charts";
import {MarketSelector} from "@/components/research/market-selector";
import {ReportMetric,ReportTabs,MissingChart,useReportView} from "./report-layout";
import {rankReportRows,rankSummary,rankGroups,rankCompetitors,type RankCampaign,type RankObservation,type TrackedKeyword,type RankReportRow} from "@/lib/rank-reports";
const field="h-9 rounded border border-border bg-card px-3 text-xs";
const tabs=[{id:"overview",label:"Landscape"},{id:"positions",label:"Overview"},{id:"distribution",label:"Rankings Distribution"},{id:"tags",label:"Tags"},{id:"pages",label:"Pages"},{id:"cannibalisation",label:"Cannibalisation"},{id:"competitors",label:"Competitors Discovery"},{id:"targets",label:"Devices & Locations"},{id:"snippets",label:"Featured Snippets"},{id:"settings",label:"Campaign Settings"}] as const;
type Tab=typeof tabs[number]["id"];
export function PositionTracking({site,host}:{site:string;host:string}){
 const params=useSearchParams(),days=Number((params.get("range")??"28d").replace("d",""))||28;
 const [from,setFrom]=useState(()=>new Date(Date.now()-(days-1)*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
 const state=useJson<{campaigns:RankCampaign[];keywords:TrackedKeyword[];history:RankObservation[];volumes?:Record<string,number|null>;volumeCollectedAt?:string|null;truncated?:boolean}>(`/api/rank-tracking/report?site=${encodeURIComponent(site)}&from=${from}&to=${to}`);
 const [view,setView]=useReportView<Tab>(tabs.map(tab=>tab.id),"overview"),[campaign,setCampaign]=useState(""),[device,setDevice]=useState(""),[location,setLocation]=useState(""),[positionRange,setPositionRange]=useState<[number,number]|null>(null),[tag,setTag]=useState(""),[query,setQuery]=useState(""),[active,setActive]=useState("active"),[selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<RankReportRow|null>(null),[edit,setEdit]=useState<RankCampaign|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [adding,setAdding]=useState(false),[newKeywords,setNewKeywords]=useState(""),[name,setName]=useState(""),[newDevice,setNewDevice]=useState("desktop"),[newLocation,setNewLocation]=useState(2840),[newLanguage,setNewLanguage]=useState("en"),[cadence,setCadence]=useState("weekly"),[bulkTags,setBulkTags]=useState("");
 const all=useMemo(()=>rankReportRows(state.data?.keywords??[],state.data?.history??[],from,to),[state.data,from,to]);
 const rows=all.filter(row=>(!positionRange||row.position!=null&&row.position>=positionRange[0]&&row.position<=positionRange[1])&&(!campaign||row.campaignId===campaign)&&(!device||row.device===device)&&(!location||String(row.locationCode)===location)&&(!tag||row.tags.includes(tag))&&(!query||`${row.keyword} ${row.url??""}`.toLowerCase().includes(query.toLowerCase()))&&(active==="all"||row.active===(active==="active")));
 const visibleSelected=selected.filter(id=>rows.some(row=>row.id===id)).slice(0,500);
 const summary=rankSummary(rows),current=state.data?.campaigns.find(row=>row.id===campaign),competitors=rankCompetitors(rows,current?.competitors),dates=[...new Set(rows.flatMap(row=>row.history.map(point=>point.capturedOn)))].sort();
 const trend=dates.map(date=>{const points=rows.flatMap(row=>row.history.filter(point=>point.capturedOn===date)),ranked=points.filter(row=>row.position!=null);return {date,average:ranked.length?Math.round(ranked.reduce((sum,row)=>sum+row.position!,0)/ranked.length*10)/10:null,top10:ranked.filter(row=>row.position!<=10).length,observed:points.length};});
 const intelligence = rankingIntelligence(rows, state.data?.volumes ?? {}, current?.competitors ?? []), latestIntelligence = intelligence.at(-1);
 const [metric, setMetric] = useState("visibility");
 async function mutate(body:Record<string,unknown>,method="PATCH") {setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/rank-tracking",{method,headers:{"content-type":"application/json"},body:JSON.stringify({siteSlug:site,...body})});const result=await response.json();if(!response.ok)throw new Error(result.error);setNotice(method==="POST"?`Keywords saved. ${result.skipped??0} existing targets retained. Collection follows the website schedule and limits.`:"Changes saved. Ranking history retained.");setSelected([]);setAdding(false);setEdit(null);state.refresh();return true;}catch(e){setError(e instanceof Error?e.message:"Could not save tracking changes.");return false;}finally{setBusy(false);}}
 const columns:Column<RankReportRow>[]=[{key:"volume",header:"Monthly volume",render:row=>state.data?.volumes?.[volumeKey(row)]?.toLocaleString()??"—"},{key:"select",header:"",render:row=><input type="checkbox" aria-label={`Select ${row.keyword} ${row.device} ${row.locationCode}`} checked={selected.includes(row.id)} onChange={()=>setSelected(current=>current.includes(row.id)?current.filter(id=>id!==row.id):[...current,row.id])}/>},{key:"keyword",header:"Keyword",sortValue:row=>row.keyword,render:row=><button className="text-left font-semibold text-purple" onClick={()=>setDetail(row)}>{row.keyword}<span className="mt-1 block text-[11px] font-normal text-muted">{row.tags.join(" · ")}</span></button>},{key:"position",header:"Position",sortValue:row=>row.position??1000,render:row=>row.observed?row.position??"Outside observed results":"Not checked"},{key:"change",header:"Change",sortValue:row=>row.change??0,render:row=><span className={row.change!=null&&row.change>0?"text-success":row.change!=null&&row.change<0?"text-critical":"text-muted"}>{row.change==null?"—":`${row.change>0?"+":""}${row.change}`}</span>},{key:"url",header:"Ranking URL",render:row=>row.url?<a className="block max-w-72 truncate text-purple" href={row.url} target="_blank" rel="noreferrer">{row.url}</a>:"—"},{key:"device",header:"Device / location",render:row=>`${row.device} · ${marketLabel(row.locationCode)}`},{key:"features",header:"SERP features",render:row=><span className="text-xs">{row.features.filter(value=>value!=="organic").join(", ")||"—"}</span>},{key:"date",header:"Last checked",sortValue:row=>row.lastChecked??"",render:row=>row.lastChecked??"Never"}];
 const groups=rankGroups(rows,view==="pages"?"pages":view==="targets"?"targets":"tags");
 const groupColumns:Column<typeof groups[number]>[]=[{key:"label",header:view==="pages"?"Page":view==="targets"?"Location · language · device · engine":"Tag",render:row=><button className="text-left text-purple" onClick={()=>{if(view==="targets"){const parts=row.label.split(" · ");setLocation(parts[0]!);setDevice(parts[2]!);}if(view==="tags"&&row.label!=="Untagged")setTag(row.label);else if(view==="pages"&&row.label.startsWith("http"))setQuery(row.label);setView("positions");}}>{row.label}</button>},...(["tracked","observed","top3","top10","average","improved","declined"] as const).map(key=>({key,header:({tracked:"Keywords",observed:"Checked",top3:"Top 3",top10:"Top 10",average:"Average position",improved:"Improved",declined:"Declined"})[key],sortValue:(row:typeof groups[number])=>row[key]??-1,render:(row:typeof groups[number])=>row[key]??"—"}))];
 return <div className="space-y-4 pb-8"><header className="border-b border-border pb-4"><p className="mb-2 text-xs text-muted">SEO › Rank Tracking</p><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold">Position Tracking: {host}</h1><p className="mt-1 text-xs text-muted">Google · observed SERP positions · {summary.observed} of {summary.tracked} targets measured in this interval</p></div><div className="flex gap-2"><Button onClick={()=>{setName("");setNewKeywords("");setCadence(current?.defaultCadence??"weekly");setAdding(true);}}>Add keywords</Button><Link className={`${field} inline-flex items-center text-purple`} href={`/scan-centre?site=${encodeURIComponent(site)}&range=${days}d`}>Update rankings</Link></div></div></header>
 <div className="flex flex-wrap gap-2"><select aria-label="Tracking campaign" className={field} value={campaign} onChange={e=>{setCampaign(e.target.value);setSelected([]);}}><option value="">All campaigns</option>{state.data?.campaigns.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><select aria-label="Tracking device" className={field} value={device} onChange={e=>setDevice(e.target.value)}><option value="">All devices</option><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select><select aria-label="Tracking location" className={field} value={location} onChange={e=>setLocation(e.target.value)}><option value="">All locations</option>{[...new Set(all.map(row=>row.locationCode))].map(code=><option key={code} value={code}>{marketLabel(code)}</option>)}</select><label className="text-xs">From <input type="date" className={field} value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs">To <input type="date" className={field} value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></div>
 <ReportTabs items={tabs} value={view} onChange={setView}/>{(error||state.error)&&<p role="alert" className="rounded border border-critical/20 p-3 text-sm text-critical">{error||state.error} <button onClick={state.refresh}>Retry loading</button></p>}{notice&&<p role="status" className="text-sm text-success">{notice}</p>}{state.data?.truncated&&<p className="text-xs text-warning">This interval exceeds the report limit. Shorten the dates to review complete history.</p>}
 <Card className="grid grid-cols-2 divide-x divide-border lg:grid-cols-5"><ReportMetric label="Tracked targets" value={state.data?summary.tracked:null}/><ReportMetric label="Average position" value={summary.average} note="Among observed ranking results"/><ReportMetric label="Top 3" value={summary.observed?summary.top3:null}/><ReportMetric label="Top 10" value={summary.observed?summary.top10:null}/><ReportMetric label="Improved / declined" value={summary.observed?`${summary.improved} / ${summary.declined}`:null}/></Card>
 {view === "overview" && <Card className="p-4"><div className="grid gap-3 sm:grid-cols-3"><ReportMetric label="Visibility %" value={latestIntelligence?.visibility == null ? null : Number(latestIntelligence.visibility.toFixed(2))}/><ReportMetric label="Estimated monthly search traffic" value={latestIntelligence?.estimatedTraffic == null ? null : Number(latestIntelligence.estimatedTraffic.toFixed(1))}/><ReportMetric label="Share of voice % · selected competitors" value={latestIntelligence?.shareOfVoice == null ? null : Number(latestIntelligence.shareOfVoice.toFixed(2))}/></div><select aria-label="Ranking intelligence metric" className={field} value={metric} onChange={e=>setMetric(e.target.value)}><option value="visibility">Visibility</option><option value="estimatedTraffic">Estimated traffic</option><option value="shareOfVoice">Share of voice</option></select>{intelligence.length>1?<MultiLine data={intelligence} series={[{key:metric,name:metric === "visibility" ? "Visibility %" : metric === "shareOfVoice" ? "Share of voice %" : "Estimated monthly traffic",color:"var(--chart-orange)"}]} height={200}/>:<MissingChart message="More dates with complete target coverage are needed."/>}<details className="mt-3 text-xs text-muted"><summary className="cursor-pointer">Calculation and coverage</summary><p className="mt-2">Latest date: {latestIntelligence?.date ?? "none"}. Checked {latestIntelligence?.observed ?? 0}/{rows.length} targets; exact-market volume {latestIntelligence?.volumeCoverage ?? 0}/{rows.length}. Missing observations or volume keep the corresponding metric unavailable.</p><p>SEO Command CTR v1: positions 1–10 use 28%, 15%, 10%, 7.5%, 5.5%, 4%, 3%, 2.5%, 2%, 1.5%; 11–100 use an exponential tail. Visibility normalises the average to a #1 ranking. Estimated traffic multiplies this curve by saved monthly volume. Share of voice divides own estimated clicks by own plus selected competitors’ estimated clicks. These are planning estimates, not measured Google clicks or Semrush scores.</p><p>Uses recorded absolute SERP positions. Historical dates use the same current volume weights, so the chart isolates ranking changes. Volume collected {state.data?.volumeCollectedAt ?? "not available"}. Select one device for a traffic estimate without duplicate device demand.</p></details></Card>}
 {(view==="overview"||view==="distribution")&&<div className="grid gap-4 lg:grid-cols-2"><Card className="p-4"><h2 className="text-base font-semibold">Ranking trend</h2>{trend.length>1?<MultiLine data={trend} series={[{key:"average",name:"Average position",color:"var(--chart-orange)"}]} height={240}/>:<MissingChart message="Two observation dates are needed for a ranking trend."/>}<p className="text-[11px] text-muted">Each date includes only targets checked that day. Lower positions are better.</p></Card><Card className="p-4"><h2 className="mb-5 text-base font-semibold">Rankings distribution</h2>{[[1,3],[4,10],[11,20],[21,50],[51,100]].map(([min,max])=>{const count=rows.filter(row=>row.position!=null&&row.position>=min!&&row.position<=max!).length;return <button key={min} className="mb-3 block w-full text-left" onClick={()=>{setPositionRange([min!,max!]);setView("positions");}}><span className="flex justify-between text-xs"><span>{min}–{max}</span><strong>{count}</strong></span><span className="mt-1 block h-2 bg-workspace"><span className="block h-2 bg-purple" style={{width:`${summary.observed?count/summary.observed*100:0}%`}}/></span></button>;})}<p className="text-xs text-muted">{summary.tracked-summary.observed} targets not checked in this interval.</p></Card></div>}
 {(view==="tags"||view==="pages"||view==="targets")&&<Card className="p-4"><h2 className="mb-4 text-base font-semibold">{tabs.find(tab=>tab.id===view)?.label}</h2><DataTable rows={groups} columns={groupColumns} rowKey={row=>row.label} exportName={`tracking-${view}`}/></Card>}
 {(view==="overview"||view==="competitors")&&<Card className="p-4"><h2 className="mb-4 text-base font-semibold">Competitor landscape</h2><DataTable rows={competitors} columns={[{key:"host",header:"Domain",render:row=>row.host},{key:"keywords",header:"Observed keywords",render:row=>row.keywords},{key:"top3",header:"Top 3",render:row=>row.top3},{key:"average",header:"Average observed position",render:row=>row.average??"—"}]} rowKey={row=>row.host} exportName="tracking-competitors"/><p className="mt-3 text-[11px] text-muted">Coverage reflects competitors captured in your tracked search results. An unobserved competitor is not assigned a ranking.</p></Card>}
 {view==="cannibalisation"&&<Card className="p-5"><h2 className="text-base font-semibold">Competing pages and URL changes</h2><p className="my-3 text-sm text-muted">Review Search Console page overlap alongside tracked URL changes and ranking movement.</p><Link className="text-sm font-semibold text-purple" href={`/keyword-strategy?site=${encodeURIComponent(site)}&view=cannibalisation&range=${days}d`}>Open cannibalisation evidence →</Link><DataTable rows={rows.filter(row=>new Set(row.history.map(point=>point.url).filter(Boolean)).size>1)} columns={columns.filter(column=>column.key!=="select")} rowKey={row=>row.id} emptyLabel="No ranking URL switches in the selected tracking history."/></Card>}
 {view==="settings"&&<Card className="p-4"><h2 className="mb-4 text-base font-semibold">Campaign settings</h2><DataTable rows={state.data?.campaigns??[]} columns={[{key:"name",header:"Campaign",render:row=>row.name},{key:"competitors",header:"Competitors",render:row=>row.competitors.join(", ")||"None selected"},{key:"cadence",header:"Default frequency",render:row=>row.defaultCadence},{key:"alert",header:"Drop alert threshold",render:row=>row.alertThreshold},{key:"edit",header:"",render:row=><Button size="sm" onClick={()=>setEdit({...row})}>Edit campaign</Button>}]} rowKey={row=>row.id}/><p className="mt-3 text-xs text-muted">Default frequency applies to new targets. Change existing target frequency using bulk actions in Overview.</p></Card>}
 {(view==="positions"||view==="snippets")&&<Card className="p-4"><h2 className="mb-3 text-base font-semibold">{view==="snippets"?"Featured snippet opportunities":"Rankings overview"}</h2>{view==="snippets"&&<p className="mb-3 text-xs text-muted">Keywords with observed featured snippets. Owned snippets are recorded separately from organic positions.</p>}<div className="mb-3 flex flex-wrap gap-2">{positionRange&&<span className="p-2 text-xs text-purple">Positions {positionRange[0]}–{positionRange[1]}</span>}<input aria-label="Filter tracked keywords" className={field} placeholder="Filter keyword or URL" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Keyword tag" className={field} value={tag} onChange={e=>setTag(e.target.value)}><option value="">All tags</option>{[...new Set(all.flatMap(row=>row.tags))].sort().map(value=><option key={value}>{value}</option>)}</select><select aria-label="Keyword status" className={field} value={active} onChange={e=>setActive(e.target.value)}><option value="active">Active</option><option value="paused">Paused</option><option value="all">All statuses</option></select><Button size="sm" onClick={()=>{setQuery("");setTag("");setDevice("");setLocation("");setActive("active");setPositionRange(null);}}>Clear filters</Button></div><div className="mb-3 flex flex-wrap items-center gap-2 rounded bg-workspace p-2"><span className="text-xs">{visibleSelected.length} selected</span><Button size="sm" onClick={()=>setSelected(rows.slice(0,500).map(row=>row.id))}>Select up to 500</Button><Button size="sm" disabled={busy||!visibleSelected.length} onClick={()=>void mutate({kind:"keywords",ids:visibleSelected,active:false})}>Pause</Button><Button size="sm" disabled={busy||!visibleSelected.length} onClick={()=>void mutate({kind:"keywords",ids:visibleSelected,active:true})}>Resume</Button><select aria-label="Bulk tracking frequency" className={field} defaultValue="" disabled={busy||!visibleSelected.length} onChange={e=>{if(e.target.value)void mutate({kind:"keywords",ids:visibleSelected,cadence:e.target.value});e.target.value="";}}><option value="">Change frequency</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select><input aria-label="Replace selected keyword tags" className={field} value={bulkTags} onChange={e=>setBulkTags(e.target.value)} placeholder="Tags, comma separated"/><Button size="sm" disabled={busy||!visibleSelected.length} onClick={()=>void mutate({kind:"keywords",ids:visibleSelected,tags:bulkTags.split(",").map(value=>value.trim()).filter(Boolean)})}>Set tags</Button></div><DataTable rows={view==="snippets"?rows.filter(row=>row.features.includes("featured_snippet")):rows} columns={view==="snippets"?[...columns,{key:"owned",header:"Snippet owned",render:row=>row.ownedFeatures.includes("featured_snippet")?"Yes":"No"}]:columns} rowKey={row=>row.id} pageSize={50} exportName="position-tracking"/></Card>}
 <Drawer open={!!detail} onClose={()=>setDetail(null)} title={detail?.keyword??"Keyword history"}>{detail&&<><p className="mb-3 text-xs text-muted">{detail.device} · {detail.locationCode} · {detail.languageCode}</p><DataTable rows={detail.history} columns={[{key:"date",header:"Date",render:row=>row.capturedOn},{key:"position",header:"Position",render:row=>row.position??"Outside observed results"},{key:"url",header:"URL",render:row=>row.url??"—"},{key:"features",header:"Owned features",render:row=>row.ownedFeatures.join(", ")||"None"}]} exportName="keyword-ranking-history"/><label className="mt-4 block text-sm">Target page<input className={`${field} mt-2 w-full`} value={detail.targetUrl??""} onChange={e=>setDetail({...detail,targetUrl:e.target.value})}/></label><Button disabled={busy} onClick={()=>void mutate({kind:"keywords",ids:[detail.id],targetUrl:detail.targetUrl||null}).then(ok=>{if(ok)setDetail(null);})}>Save target page</Button></>}</Drawer>
 <Drawer open={adding} onClose={()=>setAdding(false)} title="Add tracking targets" footer={<Button variant="primary" disabled={busy||!newKeywords.trim()} onClick={()=>void mutate({campaignId:campaign||undefined,campaignName:name||`${host} tracking`,cadence,device:newDevice,locationCode:newLocation,languageCode:newLanguage,searchEngine:"google",keywords:[...new Set(newKeywords.split("\n").map(value=>value.trim()).filter(Boolean))].map(keyword=>({keyword}))},"POST")}>Save tracking targets</Button>}><div className="space-y-4"><p className="text-xs text-muted">{current?`Add to ${current.name}`:"Create a named campaign"}. Up to 500 keywords per save.</p>{!campaign&&<label className="block text-sm">Campaign name<input className={`${field} mt-2 w-full`} value={name} onChange={e=>setName(e.target.value)}/></label>}<MarketSelector location={newLocation} language={newLanguage} onChange={(code,language)=>{setNewLocation(code);setNewLanguage(language);}}/><select aria-label="New tracking device" className={field} value={newDevice} onChange={e=>setNewDevice(e.target.value)}><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select><select aria-label="New tracking frequency" className={field} value={cadence} onChange={e=>setCadence(e.target.value)}><option value="weekly">Weekly</option><option value="daily">Daily</option></select><label className="block text-sm">Keywords, one per line<textarea className="mt-2 min-h-48 w-full rounded border border-border bg-card p-3" value={newKeywords} onChange={e=>setNewKeywords(e.target.value)}/></label>{error&&<p role="alert" className="text-xs text-critical">{error}</p>}</div></Drawer>
 <Drawer open={!!edit} onClose={()=>setEdit(null)} title="Edit tracking campaign" footer={<Button disabled={busy||!edit} onClick={()=>edit&&void mutate({kind:"campaign",...edit})}>Save campaign</Button>}>{edit&&<div className="space-y-4"><label className="block text-sm">Name<input className={`${field} mt-2 w-full`} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label className="block text-sm">Competitors, one per line<textarea className="mt-2 min-h-32 w-full rounded border border-border bg-card p-3" value={edit.competitors.join("\n")} onChange={e=>setEdit({...edit,competitors:e.target.value.split("\n")})}/></label><label className="block text-sm">Drop alert threshold<input type="number" min="1" max="100" className={`${field} ml-2 w-20`} value={edit.alertThreshold} onChange={e=>setEdit({...edit,alertThreshold:Number(e.target.value)})}/></label><label className="block text-sm">Default frequency<select className={`${field} ml-2`} value={edit.defaultCadence} onChange={e=>setEdit({...edit,defaultCadence:e.target.value})}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label>{error&&<p className="text-xs text-critical">{error}</p>}</div>}</Drawer>
 </div>;
}
