"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {Download} from "lucide-react";
import {useDomain} from "@/components/shell/domain-context";
import {useScopedLive} from "@/lib/use-live";
import {Button,Card} from "@/components/ui/primitives";
import {ReportTabs,ReportMetric} from "@/components/reports/report-layout";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Drawer} from "@/components/ui/drawer";
import {decisionFor,disavowText,type BacklinkDecision} from "@/lib/backlink-audit";
import {downloadReport,exportRows} from "@/lib/report-download";
import type {Backlink} from "@/lib/types";
const field="h-9 rounded border border-border bg-card px-3 text-xs";
export default function BacklinkAudit(){const {activeDomain}=useDomain(),{data:bundle,error:loadError}=useScopedLive();const [decisions,setDecisions]=useState<BacklinkDecision[]>([]),[tab,setTab]=useState("overview"),[selected,setSelected]=useState<Set<string>>(new Set()),[detail,setDetail]=useState<Backlink|null>(null),[note,setNote]=useState(""),[scope,setScope]=useState<"url"|"domain">("url"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[risk,setRisk]=useState("all"),[follow,setFollow]=useState("all");const ds=bundle?.datasets.backlinks,links=ds?.data??[];const site=activeDomain?.id;
 const load=useCallback(async()=>{if(!site)return;try{const response=await fetch(`/api/backlink-audit?site=${encodeURIComponent(site)}`);const body=await response.json();if(!response.ok)throw new Error(body.error);setDecisions(body.decisions??[]);}catch(e){setError(e instanceof Error?e.message:"Could not load audit decisions.");}},[site]);useEffect(()=>{setSelected(new Set());setDetail(null);void load();},[load]);
 const decision=(row:Backlink)=>decisionFor(row.sourceUrl,row.targetUrl,decisions)?.decision??"audit";
 const visible=links.filter(row=>(tab==="overview"||tab==="lostfound"?tab!=="lostfound"||row.status!=="active":decision(row)===tab)&&(risk==="all"||risk==="high"&&row.toxicity>50||risk==="lower"&&row.toxicity<=50)&&(follow==="all"||row.follow===(follow==="follow")));
 async function move(next:BacklinkDecision["decision"],rows=links.filter(row=>selected.has(row.id))){if(!site||!rows.length)return;setBusy(true);setError("");try{const response=await fetch("/api/backlink-audit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,rows:rows.map(row=>({sourceUrl:row.sourceUrl,targetUrl:row.targetUrl})),decision:next,scope,...(rows.length===1&&detail?{note}:{})})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();setSelected(new Set());}catch(e){setError(e instanceof Error?e.message:"Could not save review decision.");}finally{setBusy(false);}}
 const columns:Column<Backlink>[]=[{key:"select",header:"",render:row=><input type="checkbox" aria-label={`Select link from ${row.sourceUrl}`} checked={selected.has(row.id)} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(row.id))next.delete(row.id);else next.add(row.id);return next;})}/>},{key:"source",header:"Source page",exportValue:row=>row.sourceUrl,render:row=><button className="max-w-72 truncate text-left text-purple" title={row.sourceUrl} onClick={()=>{setDetail(row);const saved=decisionFor(row.sourceUrl,row.targetUrl,decisions);setNote(saved?.note??"");setScope(saved?.scope??"url");}}>{row.sourceUrl.replace(/^https?:\/\//,"")}</button>},{key:"target",header:"Target URL",exportValue:row=>row.targetUrl,render:row=><a href={row.targetUrl} target="_blank" rel="noreferrer" className="block max-w-52 truncate text-xs text-muted">{row.targetUrl}</a>},{key:"anchor",header:"Anchor",render:row=>row.anchor},{key:"score",header:"Spam score",sortValue:row=>row.toxicity,render:row=><span className={row.toxicity>50?"text-critical":"text-muted"}>{row.toxicity}</span>},{key:"follow",header:"Attribute",render:row=>row.follow?"Follow":"Nofollow"},{key:"status",header:"Link status",render:row=>row.status},{key:"review",header:"Review",render:row=>decision(row)},{key:"date",header:"Last seen",render:row=>row.lastSeen}];
 if(!activeDomain)return <Card className="p-8 text-sm text-muted">Select a website to review its backlinks.</Card>;
 return <div className="space-y-4 pb-8"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-4"><div><p className="mb-2 text-xs text-muted">SEO › Link Building</p><h1 className="text-xl font-bold">Backlink Audit: <span className="font-medium">{activeDomain.host}</span></h1></div><Link href={`/scan-centre?site=${site}`} className="rounded border border-border px-3 py-2 text-xs text-purple">Update backlink data</Link></div><ReportTabs items={[{id:"overview",label:"Overview"},{id:"audit",label:"Audit"},{id:"remove",label:"Remove"},{id:"disavow",label:"Disavow"},{id:"whitelist",label:"Whitelist"},{id:"lostfound",label:"Lost & Found"}]} value={tab} onChange={value=>{setTab(value);setSelected(new Set());}}/>{(error||loadError)&&<p role="alert" className="text-sm text-critical">{error||loadError}</p>}{tab==="overview"&&<div className="grid gap-4 lg:grid-cols-3"><Card><ReportMetric label="Links for review" value={ds?links.filter(row=>decision(row)==="audit").length:null} note="Saved backlink sample"/></Card><Card><ReportMetric label="Higher spam scores" value={ds?links.filter(row=>row.toxicity>50).length:null} note="Provider score above 50; review before deciding"/></Card><Card className="grid grid-cols-2 divide-x divide-border"><ReportMetric label="Referring domains" value={ds?new Set(links.map(row=>row.sourceDomain)).size:null}/><ReportMetric label="Whitelisted" value={ds?links.filter(row=>decision(row)==="whitelist").length:null}/></Card></div>}
 {tab==="remove"&&<Card className="flex flex-wrap items-center justify-between gap-3 p-4"><p className="max-w-2xl text-xs leading-5 text-muted">These are saved removal candidates. Review the source and reason, then use the outreach workspace to prepare contact. Moving a link here does not send a message or remove the link.</p><Link className="text-sm text-purple" href={`/link-building?site=${site}`}>Open outreach →</Link></Card>}
 {tab==="disavow"&&<Card className="flex flex-wrap items-center justify-between gap-3 p-4"><p className="max-w-2xl text-xs leading-5 text-muted">Export only candidates you have deliberately reviewed. The file uses URL or domain entries according to your choices. It is not submitted to Google automatically.</p><Button size="sm" disabled={!decisions.some(row=>row.decision==="disavow")} onClick={()=>downloadReport(`${activeDomain.host}-disavow.txt`,disavowText(decisions),"text/plain;charset=utf-8")}><Download className="h-4 w-4"/>Export disavow file</Button></Card>}
 <Card className="p-4"><div className="mb-4 flex flex-wrap items-center gap-2"><select aria-label="Backlink spam score filter" className={field} value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">All spam scores</option><option value="high">Above 50</option><option value="lower">50 and below</option></select><select aria-label="Backlink follow filter" className={field} value={follow} onChange={e=>setFollow(e.target.value)}><option value="all">All link attributes</option><option value="follow">Follow</option><option value="nofollow">Nofollow</option></select><Button size="sm" onClick={()=>setSelected(new Set(visible.slice(0,200).map(row=>row.id)))}>Select up to 200</Button><span className="text-xs text-muted">{selected.size} selected</span><select aria-label="Review scope" className={field} value={scope} onChange={e=>setScope(e.target.value as "url"|"domain")}><option value="url">This link</option><option value="domain">Entire source domain</option></select>{(["audit","whitelist","remove","disavow"] as const).map(value=><Button size="sm" key={value} disabled={busy||!selected.size} className="capitalize" onClick={()=>void move(value)}>{value==="audit"?"Return to audit":value}</Button>)}<Button size="sm" disabled={!visible.length} onClick={()=>exportRows("backlink-audit.csv",["Source","Target","Anchor","Spam score","Review","Note"],visible.map(row=>[row.sourceUrl,row.targetUrl,row.anchor,row.toxicity,decision(row),decisionFor(row.sourceUrl,row.targetUrl,decisions)?.note]))}><Download className="h-3.5 w-3.5"/>Export</Button></div><DataTable rows={visible} columns={columns} rowKey={row=>row.id} searchKeys={row=>`${row.sourceDomain} ${row.sourceUrl} ${row.anchor}`} pageSize={50} emptyLabel="No saved links match this report. Review your filters or update backlink data."/><p className="mt-3 text-xs leading-5 text-muted">{ds?`Collected ${new Date(ds.provenance.collectedAt).toLocaleString()}. `:""}Scores are provider spam indicators, not a confirmed Google penalty or Semrush Toxicity Score. Lists are editorial decisions and preserve original evidence.</p></Card>
 <Drawer open={!!detail} onClose={()=>setDetail(null)} title="Review backlink" footer={detail?<div className="flex flex-wrap gap-2">{(["audit","whitelist","remove","disavow"] as const).map(value=><Button size="sm" key={value} disabled={busy} onClick={()=>void move(value,[detail])} className="capitalize">{value}</Button>)}</div>:undefined}>{detail&&<div className="space-y-4"><a className="break-all text-sm text-purple" href={detail.sourceUrl} target="_blank" rel="noreferrer">{detail.sourceUrl}</a><p className="break-all text-xs text-muted">Target: {detail.targetUrl}</p><p className="text-sm">Anchor: {detail.anchor||"None"} · Spam score: {detail.toxicity}</p><label className="block text-sm">Decision scope<select className={`${field} mt-2 w-full`} value={scope} onChange={e=>setScope(e.target.value as "url"|"domain")}><option value="url">This source URL and target</option><option value="domain">All links from this domain</option></select></label><label className="block text-sm">Review notes<textarea rows={5} className="mt-2 w-full rounded border border-border bg-card p-3 text-sm" value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/></label><p className="text-xs text-muted">Saving a decision records these notes. Existing link data is retained.</p></div>}</Drawer></div>;
}
