"use client";
import {ExtendedTrafficReport} from "@/components/reports/traffic-extended";
import {TRAFFIC_REPORTS,trafficViewNames,trafficSource,type ExtendedTrafficView} from "@/lib/traffic-report-catalog";
import { ResearchEvidencePanel } from "@/components/research/evidence-panel";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import { useEffect, useState } from "react";
import { useJson } from "@/lib/use-live";
import type { TrafficEvidence,TrafficDetail } from "@/lib/traffic-research";
import type { prepareTrafficConnection } from "@/providers/similarweb/connection";
import { useDomain } from "@/components/shell/domain-context";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { Card, CardHeader, Button } from "@/components/ui/primitives";
import { ReportMetric, ReportTabs, UnavailableReport, useReportView } from "@/components/reports/report-layout";
import { MultiLine } from "@/components/charts/charts";
import { exportRows } from "@/lib/report-download";
import { navigationHref } from "@/lib/nav";

type ConnectionPayload = {connection:ReturnType<typeof prepareTrafficConnection>;evidence:TrafficEvidence|null;history:TrafficEvidence[];countries:TrafficEvidence[];canManage:boolean;detailConnections:{pages:ReturnType<typeof prepareTrafficConnection>;countries:ReturnType<typeof prepareTrafficConnection>};pageReport:TrafficDetail|null;countryReport:TrafficDetail|null};
const channels = ["Organic search", "Paid search", "Direct", "Social", "Referral", "Email", "Display ads"];
export default function TrafficAnalyticsPage() {
  const { activeDomain, scope, range } = useDomain();
  const params=useSearchParams(),router=useRouter();
  const source=trafficSource(new URLSearchParams(params));
  const setSource=(next:string)=>{const query=new URLSearchParams(params);query.set("source",next);router.push(`/traffic-analytics?${query}`,{scroll:false});};
  const [target,setTarget]=useState(""),[month,setMonth]=useState(()=>{const date=new Date();date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()-1);return date.toISOString().slice(0,7);}),[country,setCountry]=useState("world"),[device,setDevice]=useState("all"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>setTarget(""),[activeDomain?.id]);
  const traffic=useJson<ConnectionPayload>(activeDomain ? `/api/traffic-analytics?site=${activeDomain.id}&month=${month}&country=${country}${target?`&domain=${encodeURIComponent(target)}`:""}` : "/api/traffic-analytics?site=");
  const [view, setView] = useReportView(trafficViewNames, "overview");
  const extended=view in TRAFFIC_REPORTS;
  const detailView=view==="pages"||view==="countries",connection=detailView?traffic.data?.detailConnections[view]:traffic.data?.connection;
  const detail=view==="pages"?traffic.data?.pageReport:traffic.data?.countryReport;
  const evidence=traffic.data?.evidence,history=traffic.data?.history??[];
  const visits=(row:TrafficEvidence)=>device==="all"?row.visits:row.channels.every(channel=>channel[device as "desktop"|"mobile"]!=null)?row.channels.reduce((sum,channel)=>sum+channel[device as "desktop"|"mobile"]!,0):null;
  const previousMonth=new Date(`${month}-01T12:00:00Z`);previousMonth.setUTCMonth(previousMonth.getUTCMonth()-1);const previous=history.find(row=>row.input.month===previousMonth.toISOString().slice(0,7));
  async function collect(){if(!activeDomain)return;setBusy(true);setError("");try{const response=await fetch("/api/traffic-analytics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site:activeDomain.id,domain:target||activeDomain.host,month,country,report:detailView?view:"overview"})});const body=await response.json();if(!response.ok)throw new Error(body.error);traffic.refresh();}catch(e){setError(e instanceof Error?e.message:"Traffic collection failed.");}finally{setBusy(false);}}
  if (source === "search" && !extended) return <div className="space-y-4"><PageHeader title={`Traffic Analytics: ${activeDomain?.host ?? "Select a website"}`} description="Search traffic estimates powered by DataForSEO. Collection uses the selected website’s existing limits." /><ReportTabs items={[{ id: "search", label: "Search traffic · DataForSEO" }, { id: "all", label: "All traffic · provider required" }]} value={source} onChange={setSource} /><ResearchEvidencePanel features={view==="countries"?["countries"]:["traffic"]} title={view==="countries"?"Search traffic by country":view==="pages"?"Top pages from search":view==="channels"?"Organic and paid search traffic":"Search traffic overview and history"} targetDomain={activeDomain?.host} /><Card className="p-4"><CardHeader title="Measured website traffic" subtitle="Google Analytics reports actual sessions for connected websites. Search estimates remain separate."/><Link href={navigationHref({ href: "/performance?view=business", group: "site" }, scope, range)} className="text-sm text-purple">Open website analytics →</Link></Card></div>;
  return <div id="analytics-report" className="space-y-4"><PageHeader title={`${extended?TRAFFIC_REPORTS[view as ExtendedTrafficView].title:view==="countries"?"Geographical Distribution":view==="pages"?"Top Pages by Traffic":view==="channels"?"Traffic Channels":"Traffic Overview"}: ${target||activeDomain?.host||"Selected website"}`} description="Estimated competitor visits and acquisition channels. Review saved traffic evidence and prepare a provider connection." />
    <ReportTabs items={[{ id: "search", label: "Search traffic · DataForSEO" }, { id: "all", label: "All traffic · provider required" }]} value={source} onChange={setSource} /><Card className="p-4"><div className="flex flex-wrap items-center gap-3"><label className="text-sm">Research domain <input key={activeDomain?.id} aria-label="Traffic research domain" defaultValue={activeDomain?.host ?? ""} placeholder="competitor.com" className="ml-2 h-9 rounded border border-border bg-card px-3" onBlur={e=>setTarget(e.target.value)}/></label><Button size="sm" disabled={extended||busy||!connection?.collectionEnabled||!traffic.data?.canManage} onClick={()=>void collect()}>{busy?"Collecting…":detailView?`Collect ${view}`:"Collect traffic data"}</Button><Button size="sm" disabled={extended||!evidence||detailView} onClick={()=>evidence&&exportRows("traffic-channels.csv",["Domain","Month","Country","Channel","Desktop visits","Mobile visits","Total visits","Share %"],evidence.channels.map(row=>[evidence.input.domain,evidence.input.month,evidence.input.country,row.name,row.desktop,row.mobile,row.visits,row.share]))}>Export</Button><span className="text-xs text-muted">{connection?.collectionEnabled?"Approved traffic connection":traffic.data?.connection.configured ? "API key present · subscription approval needed" : "Similarweb API subscription and key needed"}</span></div><p className="mt-3 text-xs text-muted">Opening this report makes no paid provider request. {connection?.credits ?? 15} estimated credits for this report; approved subscription entitlements and monthly limits apply.</p>{traffic.error&&<button className="mt-2 text-xs text-critical" onClick={traffic.refresh}>Connection details could not load. Retry</button>}<details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold text-purple">Review connection requirements</summary><ul className="mt-2 list-disc space-y-2 pl-4">{connection?.requirements.map(r=><li key={r}>{r}</li>)}</ul><p className="mt-2 text-muted">Country distribution and total-traffic top pages need additional entitlements and pricing. They remain unavailable until approved.</p></details></Card>
    <ReportTabs items={[{id:"overview",label:"Overview"},{id:"channels",label:"Traffic channels"},{id:"countries",label:"Geographical distribution"},{id:"pages",label:"Top pages"}]} value={view} onChange={setView} />
    {error&&<p role="alert" className="text-sm text-critical">{error}</p>}
    <div className="flex flex-wrap items-center gap-2 text-xs text-muted"><select aria-label="Traffic country" className="h-9 rounded border border-border bg-card px-3" value={view==="countries"?"world":country} disabled={view==="countries"} onChange={e=>setCountry(e.target.value)}>{[["world","Worldwide"],["ae","United Arab Emirates"],["gb","United Kingdom"],["us","United States"],["ca","Canada"],["au","Australia"],["in","India"],["de","Germany"],["fr","France"]].map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><select aria-label="Traffic device" className="h-9 rounded border border-border bg-card px-3" value={detailView?"all":device} disabled={detailView} onChange={e=>setDevice(e.target.value)}><option value="all">All devices</option><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select><input aria-label="Traffic month" type="month" className="h-9 rounded border border-border bg-card px-3" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/><span>{(detailView?detail:evidence)?`Collected ${new Date((detailView?detail:evidence)!.collectedAt).toLocaleString()}`:"No collection for this selection"}</span><Link href={navigationHref({href:"/domain-research",group:"site"},scope,range)} className="ml-auto text-purple">Open saved organic research →</Link></div>
    {extended&&activeDomain&&<ExtendedTrafficReport view={view as ExtendedTrafficView} site={activeDomain.id}/>}
    {view === "overview" && traffic.data?.evidence && <Card><div className="grid grid-cols-3"><ReportMetric label="Visits" value={visits(traffic.data.evidence)}/><ReportMetric label="Month" value={traffic.data.evidence.input.month}/><ReportMetric label="Collected" value={new Date(traffic.data.evidence.collectedAt).toLocaleDateString()}/></div></Card>}
    {view === "overview" && !traffic.data?.evidence && <UnavailableReport title="Traffic overview" description="Estimated total visits require a traffic data source. Organic search estimates are available separately in Domain Overview." metrics={["Visits", "Unique visitors", "Pages / visit", "Bounce rate"]} />}
    {view==="overview"&&history.length>1&&<Card className="p-4"><CardHeader title="Traffic trend" subtitle={`${country} · ${device} devices`}/><MultiLine data={history.map(row=>({date:row.input.month,visits:visits(row)}))} series={[{key:"visits",name:"Estimated visits",color:"var(--chart-orange)"}]} height={220}/></Card>}
    {(view === "overview" || view === "channels") && <Card><CardHeader title="Traffic channels" subtitle="Estimated visits and share of total traffic" /><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border bg-workspace text-xs text-muted"><tr><th className="px-4 py-3">Channel</th><th>Visits</th><th>Traffic share</th><th>Change</th></tr></thead><tbody>{channels.map((channel) => { const alias:Record<string,string>={"Organic search":"Organic Search","Paid search":"Paid Search","Referral":"Referrals","Email":"Mail","Display ads":"Display Ads"}; const row=traffic.data?.evidence?.channels.find(r=>r.name===(alias[channel]??channel)); const metric=device==="all"?"visits":device as "desktop"|"mobile",value=row?.[metric]??null,old=previous?.channels.find(r=>r.name===(alias[channel]??channel))?.[metric]??null,total=evidence?visits(evidence):null; return <tr key={channel} className="border-b border-border last:border-0"><td className="px-4 py-3 font-medium">{channel}</td><td>{value?.toLocaleString()??"—"}</td><td>{value!=null&&total!=null&&total>0?`${(value/total*100).toFixed(1)}%`:"—"}</td><td className="text-xs text-muted">{value!=null&&old!=null&&old>0?`${((value-old)/old*100).toFixed(1)}%`:"—"}</td></tr>;})}</tbody></table></div></Card>}
    {view==="countries"&&!traffic.data?.countryReport&&Boolean(traffic.data?.countries?.length)&&<Card><CardHeader title="Collected countries" subtitle="Saved country reports for this month; not a complete worldwide distribution"/><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Country</th><th>Visits</th><th>Collected</th></tr></thead><tbody>{traffic.data?.countries.map(row=><tr key={row.input.country} className="border-t border-border"><td className="p-3 uppercase">{row.input.country}</td><td>{visits(row)?.toLocaleString()??"—"}</td><td>{new Date(row.collectedAt).toLocaleDateString()}</td></tr>)}</tbody></table></Card>}
    {view === "countries" && !traffic.data?.countryReport && !traffic.data?.countries?.length && <UnavailableReport title="Geographical distribution" description="Competitor traffic by country is unavailable until a traffic data source is connected." metrics={["Countries", "Visits", "Traffic share", "Change"]} />}
    {view==="countries"&&traffic.data?.countryReport&&<Card className="p-4"><CardHeader title="Geographical distribution" subtitle="Worldwide · desktop and mobile · up to 10 returned countries"/><DataTable rows={traffic.data.countryReport.countries??[]} rowKey={row=>String(row.code)} columns={[{key:"country",header:"Country",render:row=>row.name},{key:"share",header:"Traffic share",sortValue:row=>row.share??-1,render:row=>row.share==null?"—":`${row.share.toFixed(2)}%`},{key:"visits",header:"Visits",sortValue:row=>row.visits??-1,render:row=>row.visits?.toLocaleString(undefined,{maximumFractionDigits:0})??"—"},{key:"pages",header:"Pages / visit",render:row=>row.pagesPerVisit?.toFixed(2)??"—"},{key:"duration",header:"Avg. duration (seconds)",render:row=>row.duration?.toFixed(0)??"—"},{key:"bounce",header:"Bounce rate",render:row=>row.bounceRate==null?"—":`${row.bounceRate.toFixed(1)}%`}]} searchKeys={row=>row.name} exportName="traffic-countries"/></Card>}
    {view==="pages"&&traffic.data?.pageReport&&<Card className="p-4"><CardHeader title="Top pages by traffic share" subtitle="Desktop and mobile · saved Popular Pages sample"/><DataTable rows={traffic.data.pageReport.pages??[]} rowKey={row=>row.url} columns={[{key:"page",header:"Page",render:row=><a className="break-all text-purple" href={row.url} target="_blank" rel="noreferrer">{row.url}</a>},{key:"share",header:"Traffic share",sortValue:row=>row.share??-1,render:row=>row.share==null?"—":`${row.share.toFixed(2)}%`},{key:"change",header:"Share change (pp)",sortValue:row=>row.change??-1000,render:row=>row.change?.toFixed(2)??"—"},{key:"visits",header:"Visits",render:()=>"Unavailable"},{key:"entrances",header:"Entrances",render:()=>"Unavailable"},{key:"exits",header:"Exits",render:()=>"Unavailable"}]} searchKeys={row=>row.url} exportName="traffic-top-pages"/><p className="mt-3 text-xs text-muted">The provider returns page traffic share. Visits, entrances and exits are not inferred from that share.</p></Card>}
    {view === "pages" && !traffic.data?.pageReport && <UnavailableReport title="Top pages by total traffic" description="Competitor page-level total traffic has not been collected. The Popular Pages integration is prepared; its subscription add-on requires separate approval. Saved organic page estimates remain in Domain Overview." metrics={["Pages", "Visits", "Entrances", "Exits"]} />}
  </div>;
}
