"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {ArrowLeft,Download,Plus,RefreshCw} from "lucide-react";
import {useDomain} from "@/components/shell/domain-context";
import {ReportTabs,ReportMetric} from "@/components/reports/report-layout";
import {Button,Card} from "@/components/ui/primitives";
import {DataTable,type Column} from "@/components/ui/data-table";
import {SiteFindingWorkDrawer,type SiteFinding} from "@/components/workflow/site-finding-work-drawer";
import {Drawer} from "@/components/ui/drawer";
import {IDEA_CATEGORIES,type OnPageReport,type IdeaCategory,type OnPageIdea} from "@/lib/on-page-analysis";
import type {CommandRecord} from "@/lib/command-model";
import {MarketSelector} from "@/components/research/market-selector";
import {emptyBrief} from "@/lib/content-workspace";
import {exportRows,downloadReport} from "@/lib/report-download";
import {useRouter} from "next/navigation";
const field="h-9 rounded border border-border bg-card px-3 text-sm";
const count=(report:OnPageReport)=>report.ideas.filter(idea=>!report.decisions[idea.id]||report.decisions[idea.id]==="open").length;
export function OnPageWorkspace({template=false}:{template?:boolean}){
 const {activeDomain}=useDomain(),router=useRouter();const site=activeDomain?.id;
 const [records,setRecords]=useState<CommandRecord[]>([]),[finding,setFinding]=useState<SiteFinding|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[view,setView]=useState(template?"template":"overview"),[category,setCategory]=useState(""),[status,setStatus]=useState("open"),[query,setQuery]=useState(""),[setup,setSetup]=useState(false),[keyword,setKeyword]=useState(""),[url,setUrl]=useState(""),[location,setLocation]=useState(2840),[language,setLanguage]=useState("en"),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!site)return;setLoading(true);try{const response=await fetch(`/api/on-page?site=${encodeURIComponent(site)}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setRecords(body.records??[]);}catch(e){setError(e instanceof Error?e.message:"Could not load analyses.");}finally{setLoading(false);}},[site]);
 useEffect(()=>{setSelectedId(null);void load();},[load]);
 useEffect(()=>{if(activeDomain){setUrl(`https://${activeDomain.host}/`);setLocation(activeDomain.dataForSeoLocationCode??2840);setLanguage(activeDomain.dataForSeoLanguageCode??"en");}},[activeDomain]);
 const reports=records.flatMap(row=>row.payload.report?[row.payload.report as OnPageReport]:[]).filter(report=>template?report.kind==="template":report.kind!=="template"),selected=reports.find(report=>report.id===selectedId),visible=reports.filter(report=>`${report.url} ${report.keyword}`.toLowerCase().includes(query.toLowerCase()));
 const ideas=useMemo(()=>selected?.ideas.filter(idea=>(!category||idea.category===category)&&(!status||(selected.decisions[idea.id]??"open")===status))??[],[selected,category,status]);
 async function run(resume?:CommandRecord){if(!site)return;setBusy(true);setError("");let completed=0;try{const keywords=resume?[String((resume.payload.input as {keyword:string}).keyword)]:template?[...new Set(keyword.split(/[\n,]/).map(value=>value.trim()).filter(Boolean))].slice(0,30):[keyword];for(const targetKeyword of keywords){const response=await fetch("/api/on-page",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(resume?{...resume.payload.input as object,site,resumeId:resume.recordKey}:{site,keyword:targetKeyword,url,locationCode:location,languageCode:language,template})});const body=await response.json();if(!response.ok)throw new Error(body.error);completed++;setRecords(current=>[body.record,...current.filter(row=>row.id!==body.record.id)]);setSelectedId(body.record.recordKey);}setView(template?"template":"ideas");setSetup(false);}catch(e){setError(`${e instanceof Error?e.message:"Analysis failed."}${completed?` ${completed} completed templates were saved.`:""}`);void load();}finally{setBusy(false);}}
 async function verify(){if(!selected||!site)return;setBusy(true);setError("");try{const response=await fetch("/api/on-page/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,id:selected.id,updatedAt:records.find(row=>row.recordKey===selected.id)?.updatedAt})});const body=await response.json();if(!response.ok)throw new Error(body.error);setRecords(current=>current.map(row=>row.id===body.record.id?body.record:row));}catch(e){setError(e instanceof Error?e.message:"Could not verify page changes.");}finally{setBusy(false);}}
 async function decision(idea:OnPageIdea,next:string){if(!selected||!site)return;setBusy(true);setError("");try{const response=await fetch("/api/on-page",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({site,id:selected.id,idea:idea.id,decision:next,updatedAt:records.find(row=>row.recordKey===selected.id)?.updatedAt})});const body=await response.json();if(!response.ok)throw new Error(body.error);setRecords(current=>current.map(row=>row.id===body.record.id?body.record:row));}catch(e){setError(e instanceof Error?e.message:"Could not save idea status.");}finally{setBusy(false);}}
 function briefFor(report:OnPageReport){const terms=new Map<string,number>();for(const page of report.benchmarks)for(const term of page.topTerms?.slice(0,30)??[])terms.set(term.term,(terms.get(term.term)??0)+1);return {...emptyBrief,primaryKeyword:report.keyword,titleRecommendation:report.keyword,secondaryKeywords:[...terms].filter(([term,n])=>n>=2&&!report.keyword.includes(term)).sort((a,b)=>b[1]-a[1]).slice(0,15).map(([term])=>term),coverageNotes:[`Research database: ${report.locationCode} / ${report.languageCode}. Collected ${report.collectedAt}.`,...report.ideas.filter(idea=>["content","semantics","serp"].includes(idea.category)).map(idea=>idea.detail)],headingPlan:[...new Set(report.benchmarks.flatMap(page=>page.headings))].slice(0,12),internalLinks:report.own?.url?[report.own.url]:[]};}
 async function createBrief(){if(!selected||!site)return;setBusy(true);setError("");try{const response=await fetch("/api/content-workflow",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,title:`${selected.keyword} — content brief`,ownerEmail:null,dueDate:null,brief:briefFor(selected),targetUrl:template?null:selected.url,analysisId:selected.id})});const body=await response.json();if(!response.ok)throw new Error(body.error);router.push(`/content?view=briefs&site=${encodeURIComponent(site)}&item=${body.item.id}`);}catch(e){setError(e instanceof Error?e.message:"Could not create brief.");}finally{setBusy(false);}}
 const columns:Column<OnPageReport>[]=[{key:"url",header:"Landing page",render:report=><button className="text-left text-purple hover:underline" onClick={()=>{setSelectedId(report.id);setView(template?"template":"ideas");}}>{report.url}</button>},{key:"keyword",header:"Keyword",render:report=>report.keyword},{key:"ideas",header:"Ideas",sortValue:count,render:report=><button className="rounded bg-purple/10 px-3 py-1 font-semibold text-purple" onClick={()=>{setSelectedId(report.id);setView("ideas");}}>{count(report)} ideas</button>},{key:"coverage",header:"Top 10 analysed",render:report=>`${report.benchmarks.length} / ${report.serp.length}`},{key:"date",header:"Last update",render:report=>new Date(report.collectedAt).toLocaleString(),sortValue:report=>report.collectedAt}];
 if(!activeDomain)return <Card className="p-8 text-sm text-muted">Choose a website to view page optimisation and content templates.</Card>;
 return <div className="space-y-4 pb-8"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-4"><div><p className="mb-2 text-xs text-muted">SEO › {template?"Content Ideas":"Other"}</p><h1 className="text-xl font-bold">{template?"SEO Content Template":"On Page SEO Checker"}: <span className="font-medium">{activeDomain.host}</span></h1></div><div className="flex gap-2"><Button size="sm" disabled={loading} onClick={()=>void load()}><RefreshCw className="h-3.5 w-3.5"/>Refresh</Button><Button size="sm" variant="primary" onClick={()=>setSetup(true)}><Plus className="h-3.5 w-3.5"/>{template?"Create template":"Add page"}</Button><Button size="sm" disabled={!reports.length} onClick={()=>exportRows("page-ideas.csv",["Page","Keyword","Category","Idea","Priority","Status","Evidence"],reports.flatMap(report=>report.ideas.map(idea=>[report.url,report.keyword,idea.category,idea.title,idea.priority,report.decisions[idea.id]??"open",idea.evidence.join("; ")])))}><Download className="h-3.5 w-3.5"/>Export</Button></div></div>
 <ReportTabs items={[{id:"overview",label:"Overview"},{id:"ideas",label:"Optimization Ideas"},{id:"benchmark",label:"Top 10 Benchmarking"},{id:"template",label:"Content Template"}]} value={view} onChange={setView}/>
 {error&&<p role="alert" className="rounded border border-critical/20 bg-critical/5 p-3 text-sm text-critical">{error}</p>}
 {records.filter(row=>row.status==="failed"||row.status==="reading_pages").map(row=><Card key={row.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><p className="text-xs text-muted">{String((row.payload.input as {keyword?:string})?.keyword??"Page analysis")}: {String(row.payload.error??"Page reading was interrupted")}</p>{Array.isArray(row.payload.serp)&&<Button size="sm" disabled={busy} onClick={()=>void run(row)}>Resume saved results · no search charge</Button>}</Card>)}
 {selected&&<div className="flex flex-wrap items-center gap-3"><Button size="sm" onClick={()=>setSelectedId(null)}><ArrowLeft className="h-3.5 w-3.5"/>All pages</Button><select aria-label="Selected page analysis" className={`${field} min-w-0 flex-1`} value={selectedId??""} onChange={e=>setSelectedId(e.target.value)}>{reports.map(report=><option key={report.id} value={report.id}>{report.keyword} · {report.url} · {report.collectedAt.slice(0,10)}</option>)}</select><span className="text-xs text-muted">Database {selected.locationCode} · {selected.languageCode} · Desktop</span></div>}
 {view==="overview"&&<><div className="grid gap-4 lg:grid-cols-[1fr_2fr]"><Card><div className="grid grid-cols-2 divide-x divide-border"><ReportMetric label="Total ideas" value={reports.reduce((sum,report)=>sum+count(report),0)}/><ReportMetric label="Analysed pages" value={new Set(reports.map(report=>report.url)).size}/></div><p className="border-t border-border p-4 text-xs text-muted">Recommendations based on saved search results and readable page HTML.</p></Card><Card className="grid grid-cols-2 sm:grid-cols-4">{Object.entries(IDEA_CATEGORIES).map(([key,label])=><button key={key} className="border-b border-border text-left hover:bg-workspace" onClick={()=>{setCategory(key);setView("ideas");if(!selectedId)setSelectedId(reports.find(report=>report.ideas.some(idea=>idea.category===key))?.id??null);}}><ReportMetric label={`${label} ideas`} value={reports.reduce((sum,report)=>sum+report.ideas.filter(idea=>idea.category===key&&(report.decisions[idea.id]??"open")==="open").length,0)}/></button>)}</Card></div><Card className="p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-base font-semibold">Top pages to optimise</h2><input aria-label="Filter analysed pages" className={field} placeholder="Filter by URL or keyword" value={query} onChange={e=>setQuery(e.target.value)}/></div><DataTable rows={visible} columns={columns} rowKey={row=>row.id} emptyLabel="Add a page and target keyword to get recommendations."/></Card></>}
 {view!=="overview"&&!selected&&<Card className="p-4"><h2 className="mb-4 text-base font-semibold">Choose a saved analysis</h2><DataTable rows={visible} columns={columns} rowKey={row=>row.id} emptyLabel="Create your first analysis to inspect the ranking pages and generate a content template."/></Card>}
 {view==="ideas"&&selected&&<><div className="flex flex-wrap gap-2"><select aria-label="Idea category" className={field} value={category} onChange={e=>setCategory(e.target.value)}><option value="">All ideas</option>{Object.entries(IDEA_CATEGORIES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="Idea status" className={field} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="done">Done</option><option value="dismissed">Dismissed</option></select><Button size="sm" disabled={busy} onClick={()=>void createBrief()}>Send to content brief</Button><Button size="sm" disabled={busy} onClick={()=>void verify()}>Recheck page HTML · no search charge</Button></div><div className="space-y-3">{ideas.map(idea=><Card key={idea.id} className="grid gap-4 p-4 md:grid-cols-[150px_minmax(0,1fr)_120px]"><div><p className="text-xs font-semibold text-purple">{IDEA_CATEGORIES[idea.category]}</p><p className="mt-2 text-xs capitalize text-muted">{idea.priority} priority</p></div><div><h3 className="text-sm font-semibold">{idea.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{idea.detail}</p><button className="mt-2 text-xs font-semibold text-purple" onClick={()=>setFinding({key:`onpage:${selected.id}:${idea.id}`,title:idea.title,module:IDEA_CATEGORIES[idea.category],executionType:["content","semantics","serp"].includes(idea.category)?"refresh_brief":"technical_task",priorityScore:idea.priority==="high"?85:idea.priority==="medium"?65:40,pageMode:"existing_page",targetUrl:selected.url,targetKeywords:[selected.keyword],evidenceLabel:`${selected.keyword} · ${selected.collectedAt.slice(0,10)}`,sourceUrl:`/on-page?site=${site}`,sourceEvidence:{analysisId:selected.id,idea}})}>Create task →</button><details className="mt-2"><summary className="cursor-pointer text-xs text-purple">See supporting evidence</summary><ul className="mt-2 space-y-1 text-xs text-muted">{idea.evidence.map((value,i)=><li key={i} className="break-words">{value.startsWith("https://")||value.startsWith("http://")?<a href={value} target="_blank" rel="noreferrer" className="text-purple">{value}</a>:value}</li>)}</ul></details></div><select aria-label={`Status: ${idea.title}`} className={field} value={selected.decisions[idea.id]??"open"} disabled={busy} onChange={e=>void decision(idea,e.target.value)}><option value="open">Open</option><option value="done">Done</option><option value="dismissed">Dismissed</option></select></Card>)}{!ideas.length&&<Card className="p-6 text-sm text-muted">{selected.own?"No ideas match this filter in the collected evidence.":"The target page could not be read. Review the collection details below before retrying."}</Card>}</div></>}
 {view==="benchmark"&&selected&&<Card className="p-4"><h2 className="mb-4 text-base font-semibold">Google’s top 10 ranking pages</h2><DataTable rows={selected.serp} rowKey={row=>row.url} columns={[{key:"position",header:"Position",render:row=>row.position},{key:"page",header:"Page",render:row=><a href={row.url} target="_blank" rel="noreferrer" className="text-purple">{row.title||row.url}</a>},{key:"words",header:"Word count",render:row=>selected.benchmarks.find(page=>page.url===row.url)?.wordCount??(selected.own?.url===row.url?selected.own.wordCount:"Unavailable")},{key:"h1",header:"H1 headings",render:row=>selected.benchmarks.find(page=>page.url===row.url)?.h1?.length??"—"},{key:"status",header:"Collection",render:row=>selected.failures.find(f=>f.url===row.url)?.reason??"Read"}]} exportName="top-10-benchmark"/><p className="mt-3 text-xs text-muted">Word counts use returned HTML. Navigation is excluded where recognisable; JavaScript content may be missing.</p></Card>}
 {view==="template"&&selected&&<><div className="flex gap-2"><Button variant="primary" disabled={busy} onClick={()=>void createBrief()}>Use template in Writing Assistant</Button><Button onClick={()=>downloadReport(`${selected.keyword}-brief.txt`,[`# SEO Content Template: ${selected.keyword}`,`Database: ${selected.locationCode} / ${selected.languageCode}`,`Collected: ${selected.collectedAt}`,"## Recommended terms",briefFor(selected).secondaryKeywords.join(", "),"## Heading ideas",...briefFor(selected).headingPlan.map(line=>`- ${line}`),"## Coverage guidance",...briefFor(selected).coverageNotes.map(line=>`- ${line}`),"## Ranking-page sources",...selected.serp.map(page=>`${page.position}. ${page.title}: ${page.url}`)].join("\n\n"),"text/plain")}><Download className="h-4 w-4"/>Export template</Button></div><div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="text-base font-semibold">Key recommendations</h2><h3 className="mt-5 text-sm font-semibold">Semantically relevant terms from competitors</h3><div className="mt-2 flex flex-wrap gap-2">{briefFor(selected).secondaryKeywords.map(term=><span key={term} className="rounded bg-purple/10 px-2 py-1 text-xs text-purple">{term}</span>)}</div><p className="mt-2 text-xs text-muted">Terms appearing across at least two readable pages. Review relevance before adding them to the brief.</p><h3 className="mt-5 text-sm font-semibold">Text length</h3><p className="mt-2 text-sm">{selected.benchmarks.length?`${Math.min(...selected.benchmarks.map(page=>page.wordCount))}–${Math.max(...selected.benchmarks.map(page=>page.wordCount))} words across readable top results`:"No readable competitor pages."}</p><h3 className="mt-5 text-sm font-semibold">Readability</h3><p className="mt-2 text-sm text-muted">{selected.benchmarks.some(page=>page.readability!=null)?`${(selected.benchmarks.filter(page=>page.readability!=null).reduce((sum,page)=>sum+page.readability!,0)/selected.benchmarks.filter(page=>page.readability!=null).length).toFixed(1)} average Flesch reading ease across readable English competitor pages`:"English readability benchmarks are unavailable for these pages."}</p><h3 className="mt-5 text-sm font-semibold">Page title, description & headings</h3><p className="mt-2 text-sm text-muted">Explain the target topic in the title and main heading. Write an original description of the page’s value. Use the evidence below to plan relevant sections.</p></Card><Card className="p-5"><h2 className="text-base font-semibold">Top-ranking competitors</h2><ol className="mt-4 space-y-3">{selected.serp.map(page=><li key={page.url} className="text-sm"><span className="mr-2 text-muted">{page.position}.</span><a href={page.url} target="_blank" rel="noreferrer" className="text-purple">{page.title||new URL(page.url).hostname}</a></li>)}</ol><button className="mt-4 text-sm text-purple" onClick={()=>setView("benchmark")}>See detailed benchmarking →</button></Card></div></>}
 {selected&&<Card className="p-4 text-xs text-muted"><p>Collected {new Date(selected.collectedAt).toLocaleString()} · DataForSEO cost ${selected.costUsd.toFixed(4)} · {selected.benchmarks.length} competitor pages read.</p>{selected.failures.length>0&&<details className="mt-2"><summary className="cursor-pointer">{selected.failures.length} pages could not be read</summary>{selected.failures.map(f=><p key={f.url} className="mt-2 break-words">{f.url}: {f.reason}</p>)}</details>}<p className="mt-2">Backlink sample: {selected.supplemental?.links??"not collected"} · Landing-page Analytics: {selected.supplemental?.analytics??"not collected"}. An empty category means no supported recommendation was generated.</p>{selected.verification&&<p className="mt-2 text-success">HTML rechecked {new Date(selected.verification.checkedAt).toLocaleString()}: {selected.verification.resolved.length} original findings no longer observed; {selected.verification.remaining.length} remain. Competitor benchmarks and supplemental reports retain their original collection dates.</p>}</Card>}
 <SiteFindingWorkDrawer finding={finding} siteSlug={activeDomain.id} siteName={activeDomain.name} onClose={()=>setFinding(null)}/>
 <Drawer open={setup} onClose={()=>setSetup(false)} title={template?"Create SEO content template":"Collect page optimisation ideas"} footer={<Button variant="primary" disabled={busy||!keyword.trim()||!url.trim()} onClick={()=>void run()}>{busy?"Analysing ranking pages…":template?`Create templates · est. $${(Math.min(30,keyword.split(/[\n,]/).filter(value=>value.trim()).length)*.003).toFixed(3)}`:"Get ideas · estimated $0.003"}</Button>}><div className="space-y-4"><label className="block text-sm">{template?"Target keywords (up to 30, one per line)":"Target keyword"}{template?<textarea className={`${field} mt-1 h-28 w-full py-2`} value={keyword} onChange={e=>setKeyword(e.target.value)}/>:<input className={`${field} mt-1 w-full`} value={keyword} onChange={e=>setKeyword(e.target.value)}/>}</label>{!template&&<label className="block text-sm">Page on {activeDomain.host}<input type="url" className={`${field} mt-1 w-full`} value={url} onChange={e=>setUrl(e.target.value)}/></label>}<MarketSelector location={location} language={language} disabled={busy} onChange={(code,lang)=>{setLocation(code);setLanguage(lang);}}/><p className="text-xs leading-5 text-muted">Uses a live Google top-results check and reads up to 10 competing pages per keyword. Each keyword produces a saved template; a completed template can be reused without collecting again. Results and actual cost are saved under this website. Existing spend limits apply.</p>{error&&<p role="alert" className="text-sm text-critical">{error}</p>}</div></Drawer>
 </div>;
}
