import {NextResponse} from "next/server";
import {z} from "zod";
import {canAccessSite,hasPermission} from "@/platform/access";
import {getManagedSite} from "@/platform/site-store";
import {saveWorkspace,workspaceRecords} from "@/platform/workspace-store";
import {getDataForSeoClient} from "@/providers/dataforseo";
import {ENDPOINTS} from "@/providers/dataforseo/config";
import {cleanCompetitorHost} from "@/platform/competitive-intelligence";
import type {GapKeyword} from "@/lib/domain-comparison";
const Input=z.object({site:z.string(),domains:z.array(z.string().max(253)).min(2).max(5),locationCode:z.number().int().positive(),languageCode:z.string().min(2).max(12),limit:z.number().int().min(1).max(1000).default(250)});
export const runtime="nodejs";export const maxDuration=120;
export async function GET(request:Request){const site=new URL(request.url).searchParams.get("site")??"";if(!await canAccessSite(request,site))return NextResponse.json({error:"Website access required."},{status:403});return NextResponse.json({records:await workspaceRecords(site,"keyword_gap")});}
export async function POST(request:Request){const parsed=Input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Choose 2–5 distinct domains and the same database."},{status:400});const input=parsed.data;if(!await getManagedSite(input.site)||!await canAccessSite(request,input.site)||!await hasPermission(request,"research",input.site))return NextResponse.json({error:"Research permission required."},{status:403});let domains:string[];try{domains=input.domains.map(cleanCompetitorHost);if(new Set(domains).size!==domains.length)throw new Error("Choose distinct domains.");}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid domain."},{status:400});}if(process.env.QA_SYNTHETIC==="true")return NextResponse.json({error:"Paid gap collection is disabled in the synthetic preview. Saved report comparisons remain available."},{status:409});
 const id=crypto.randomUUID(),keywords=new Map<string,GapKeyword>();let costUsd=0,inFlight:string|null=null;const completed:string[]=[],totals:Record<string,number|null>={};
 const checkpoint=()=>({input:{...input,domains},rows:[...keywords.values()],completed,totals,costUsd,inFlight,collectedAt:new Date().toISOString()});
 try{await saveWorkspace(input.site,"keyword_gap",id,checkpoint(),"running");const client=getDataForSeoClient();for(const rival of domains.slice(1))for(const [target1,target2,intersections] of [[domains[0]!,rival,true],[rival,domains[0]!,false],[domains[0]!,rival,false]] as const){const key=`${target1}:${target2}:${intersections}`;inFlight=key;await saveWorkspace(input.site,"keyword_gap",id,{...checkpoint(),inFlight:key},"running");const call=await client.post<Record<string,unknown>>("labsDomainIntersection",ENDPOINTS.labsDomainIntersection,[{target1,target2,intersections,item_types:["organic"],location_code:input.locationCode,language_code:input.languageCode,limit:input.limit,include_serp_info:true}],{domainSlug:input.site});costUsd+=call.costUsd;const result=call.result[0]??{};totals[key]=typeof result.total_count==="number"?result.total_count:null;
 for(const raw of (result.items??[]) as Record<string,unknown>[]){const data=raw.keyword_data as Record<string,unknown>|undefined,info=data?.keyword_info as Record<string,unknown>|undefined,props=data?.keyword_properties as Record<string,unknown>|undefined,intent=data?.search_intent_info as Record<string,unknown>|undefined;const keyword=String(data?.keyword??"");if(!keyword)continue;const first=raw.first_domain_serp_element as Record<string,unknown>|undefined,second=raw.second_domain_serp_element as Record<string,unknown>|undefined;const number=(value:unknown)=>typeof value==="number"?value:null;const row=keywords.get(keyword.toLowerCase())??{keyword,volume:number(info?.search_volume),difficulty:number(props?.keyword_difficulty),intent:typeof intent?.main_intent==="string"?intent.main_intent:null,positions:{}};row.positions[target1]={position:number(first?.rank_absolute),url:typeof first?.url==="string"?first.url:null,known:number(first?.rank_absolute)!=null};row.positions[target2]={position:intersections?number(second?.rank_absolute):null,url:typeof second?.url==="string"?second.url:null,known:!intersections||number(second?.rank_absolute)!=null};keywords.set(keyword.toLowerCase(),row);}
 completed.push(key);inFlight=null;await saveWorkspace(input.site,"keyword_gap",id,checkpoint(),"running");}
 const record=await saveWorkspace(input.site,"keyword_gap",id,checkpoint(),"completed");return NextResponse.json({record});}catch(e){const error=e instanceof Error?e.message:"Gap comparison failed.";const record=await saveWorkspace(input.site,"keyword_gap",id,{...checkpoint(),error},"partial").catch(()=>null);return NextResponse.json({error,record},{status:502});}}
