import { beforeAll,afterAll,it,expect,vi } from "vitest";
import {GET as ai} from "./ai-visibility/route";
import {GET as traffic} from "./traffic-analytics/route";
import {POST as saveTopic,GET as topics} from "./topic-plans/route";
import {createSessionToken,SESSION_COOKIE,type AppRole} from "@/lib/auth";
vi.mock("server-only",()=>({}));
beforeAll(()=>{vi.stubEnv("QA_SYNTHETIC","true");vi.stubEnv("AUTH_SECRET","test-redesign-long-secret");});afterAll(()=>vi.unstubAllEnvs());
async function req(path:string,role:AppRole="admin",body?:unknown){const token=await createSessionToken({email:"test@example.com",name:"Test",role,groupIds:[],siteIds:[],allAccess:false,grants:[]},process.env.AUTH_SECRET!);return new Request(`https://test.local${path}`,{method:body?"POST":"GET",headers:{cookie:`${SESSION_COOKIE}=${token}`,"content-type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});}
it("AI report honors the requested period and platform and rejects invalid platforms",async()=>{const r=await ai(await req("/api/ai-visibility?scope=mortgagecompare&days=7&platform=gemini"));expect(r.status).toBe(200);const data=await r.json();expect(data.scope.days).toBe(7);expect(data.platforms.every((r:{platform:string})=>r.platform==="gemini")).toBe(true);expect((await ai(await req("/api/ai-visibility?scope=mortgagecompare&platform=made-up"))).status).toBe(400);});
it("traffic connection previews never call a paid provider or reveal credentials",async()=>{const fetch=vi.spyOn(globalThis,"fetch");vi.stubEnv("SIMILARWEB_API_KEY","secret-test-value");const response=await traffic(await req("/api/traffic-analytics?site=mortgagecompare&domain=competitor.example&month=2026-08"));expect(response.status).toBe(200);const text=await response.text();expect(text).not.toContain("secret-test-value");expect(JSON.parse(text).connection).toMatchObject({collectionEnabled:false,credits:15,priceUsd:null});expect(fetch).not.toHaveBeenCalled();fetch.mockRestore();});
it("traffic reports reject inaccessible sites",async()=>{expect((await traffic(await req("/api/traffic-analytics?site=mortgagecompare","viewer"))).status).toBe(403);});
it("topic handoff preserves research evidence through edits and rejects stale edits",async()=>{const base={site:"mortgagecompare",label:"Mortgage guide",keywords:["mortgage guide"],targetUrl:"/guides/mortgages",sourceEvidence:{scanId:"saved-scan",market:2784}};const response=await saveTopic(await req("/api/topic-plans","admin",base));expect(response.status).toBe(200);const saved=await response.json();const list=await (await topics(await req("/api/topic-plans?site=mortgagecompare"))).json();const plan=list.plans.find((r:{id:string})=>r.id===saved.id);expect(plan.sourceEvidence.scanId).toBe("saved-scan");const edit=await saveTopic(await req("/api/topic-plans","admin",{...base,id:plan.id,updatedAt:plan.updatedAt,label:"Updated guide",sourceEvidence:undefined}));expect(edit.status).toBe(200);const result=await (await topics(await req("/api/topic-plans?site=mortgagecompare"))).json();expect(result.plans.find((r:{id:string})=>r.id===saved.id).sourceEvidence.scanId).toBe("saved-scan");expect((await saveTopic(await req("/api/topic-plans","admin",{...base,id:plan.id,updatedAt:"2020-01-01T00:00:00.000Z"}))).status).toBe(409);});
