import { reportDefinition, reportWidgetSites } from "@/reports/definition";
import {NextResponse} from "next/server";
import {z} from "zod";
import {canAccessSite,hasPermission} from "@/platform/access";
import {saveWorkspace,updateWorkspace,workspaceRecords} from "@/platform/workspace-store";
import {REPORT_TEMPLATES,REPORT_WIDGET_SECTIONS} from "@/data/report-templates";
export const runtime="nodejs";
export async function GET(request:Request){const site=new URL(request.url).searchParams.get("site")??"";if(!await canAccessSite(request,site))return NextResponse.json({error:"Website access required."},{status:403});return NextResponse.json({layouts:await workspaceRecords(site,"report_layouts")});}
const Input=z.object({site:z.string().min(1).max(120),key:z.string().uuid().optional(),updatedAt:z.string().optional(),name:z.string().trim().min(1).max(120),templateId:z.string(),days:z.union([z.literal(7),z.literal(28),z.literal(90)]),widgets:z.record(z.string(),z.object({site:z.string().optional(),days:z.number().optional()})).optional(),sections:z.array(z.string()).min(1).max(30)});
export async function POST(request:Request){const parsed=Input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Choose a report name, template and at least one section."},{status:400});const input=parsed.data;if(!await canAccessSite(request,input.site)||!await hasPermission(request,"manage_reports",input.site))return NextResponse.json({error:"Report management access required."},{status:403});const template=REPORT_TEMPLATES.find(row=>row.id===input.templateId);if(!template||input.sections.some(section=>!REPORT_WIDGET_SECTIONS.includes(section))||new Set(input.sections).size!==input.sections.length)return NextResponse.json({error:"Choose distinct sections supported by this report template."},{status:400});const payload={name:input.name,templateId:input.templateId,days:input.days,sections:input.sections,widgets:input.widgets};let definition;try{definition=reportDefinition(input.templateId,payload);}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Invalid widget settings."},{status:400});}try{if(!(await Promise.all(reportWidgetSites(definition).map(async site=>await canAccessSite(request,site)&&await hasPermission(request,"manage_reports",site)))).every(Boolean))return NextResponse.json({error:"Report widget website access required."},{status:403});if(input.key){const current=(await workspaceRecords(input.site,"report_layouts")).find(row=>row.recordKey===input.key);if(!current)return NextResponse.json({error:"Report layout not found."},{status:404});if(current.updatedAt!==input.updatedAt)return NextResponse.json({error:"This layout changed in another session. Reopen it before saving."},{status:409});const layout=await updateWorkspace(current,payload);if(!layout)return NextResponse.json({error:"This layout changed in another session. Reopen it before saving."},{status:409});return NextResponse.json({layout});}return NextResponse.json({layout:await saveWorkspace(input.site,"report_layouts",crypto.randomUUID(),payload)});}catch{return NextResponse.json({error:"Could not save this report layout."},{status:503});}}
