"use client";
import Link from "next/link";
import {marketForIsoCountry} from "@/lib/markets";
import {useState} from "react";
import {Button, Card} from "@/components/ui/primitives";

import {SerpInspector} from "@/components/research/serp-inspector";
import {DEFAULT_KEYWORD_QUERY, type KeywordQuery} from "@/lib/keyword-query";
import type {KeywordResearchResult, KeywordResearchRow} from "@/lib/types";

const format=(value:number|null|undefined)=>value==null?"—":value.toLocaleString(undefined,{maximumFractionDigits:2});
const countryName=(code:string)=>{try{return new Intl.DisplayNames(["en"],{type:"region"}).of(code)??code;}catch{return code;}};
function ReportMetric({label,value,note}:{label:string;value?:number|string|null;note?:string}){return <div><p className="text-xs text-muted">{label}</p><p className="mt-1 text-2xl font-semibold leading-8 tracking-tight">{typeof value==="number"?format(value):value??"—"}</p>{note&&<p className="mt-1 text-[11px] leading-4 text-muted">{note}</p>}</div>;}
export function KeywordOverview({result,site,busy,onOpenMagic,onKeyword,onGlobal,onRefresh,onCountry}:{result?:KeywordResearchResult;site?:string;busy:boolean;onOpenMagic:(query:KeywordQuery)=>void;onKeyword:(row:KeywordResearchRow)=>void;onGlobal:()=>void;onRefresh:()=>void;onCountry:(code:number,label:string)=>void}){
  const [allCountries,setAllCountries]=useState(false);
  const primary=result?.report?.primary??result?.rows.find(row=>row.keyword.toLowerCase()===result.seed.toLowerCase());
  const global=result?.report?.global,history=[...(primary?.monthlySearches??[])].sort((a,b)=>a.year-b.year||a.month-b.month).slice(-12);
  const max=Math.max(1,...history.map(row=>row.volume));
  const strategy=new URLSearchParams({site:site??"",keywords:result?.seed??"",location:String(result?.locationCode??2840),language:result?.languageCode??"en",locationLabel:result?.locationLabel??"",view:"clusters"});
  return <div className="space-y-3" data-keyword-overview>
    <h1 className="hidden text-xl font-semibold print:block">SEO Command · Keyword Overview: {result?.seed}</h1>
    {result?.report?.warnings?.map(warning=><p key={warning} role="alert" className="rounded border border-warning/30 bg-warning/5 p-3 text-xs">{warning}</p>)}
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs"><span className="text-muted">{result?.locationLabel??"Choose a database"} · {result?.languageCode??"en"} · Google · USD · {primary?.updatedAt?`Metrics updated ${new Date(primary.updatedAt).toLocaleDateString()}`:"Metric date unavailable"}</span><div className="flex gap-2"><Button size="sm" disabled={busy||!result} onClick={onRefresh}>Update metrics</Button><Button size="sm" disabled={!result} onClick={()=>window.print()}>Export to PDF</Button></div></div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <Card className="p-4"><ReportMetric label="Volume" value={primary?.volume} note={result?.locationLabel}/><div className="my-3 border-t border-border"/><ReportMetric label="Keyword difficulty" value={primary?.difficulty==null?null:`${primary.difficulty}%`} note="DataForSEO KD"/><p className="mt-3 text-xs leading-5 text-muted">{primary?.difficulty==null?"Exact keyword metrics have not been collected.":primary.difficulty<30?"Lower difficulty. Check search intent and the leading pages before choosing a target.":primary.difficulty<60?"Moderate competition. Strong content and relevant authority may be needed.":"High competition. Review the leading results and your website’s strengths."}</p></Card>
      <Card className="p-4"><ReportMetric label="Global volume" value={global?.volume} note={global?"Clickstream estimate · all countries":"Global demand has not been collected"}/>{global?<><div className="mt-2 space-y-2">{global.countries.slice(0,allCountries?global.countries.length:6).map(country=><div key={country.code} className="grid grid-cols-[minmax(0,1fr)_60px_55px] items-center gap-2 text-xs"><button data-country-label disabled={busy||!marketForIsoCountry(country.code)} title={`Open ${countryName(country.code)} database`} className="truncate text-left text-purple disabled:text-muted" onClick={()=>{const market=marketForIsoCountry(country.code);if(market)onCountry(market.code,market.label);}}>{countryName(country.code)}</button><span className="h-2 overflow-hidden rounded bg-purple/10"><span className="block h-full bg-purple/60" style={{width:`${Math.min(100,country.percentage??0)}%`}}/></span><span className="text-right">{format(country.volume)}</span></div>)}</div><button className="mt-3 text-xs text-purple" onClick={()=>setAllCountries(!allCountries)}>{allCountries?"Show fewer":"Show all countries"}</button><p className="mt-2 text-[11px] leading-4 text-muted">Clickstream demand uses a different method from the Google Ads based country volume. Updated {new Date(global.fetchedAt).toLocaleDateString()}.</p></>:<Button size="sm" className="mt-3" disabled={busy||!result||result.seed.length<3} onClick={onGlobal}>Collect global demand · $0.18</Button>}</Card>
      <div className="grid gap-3"><Card className="p-4"><ReportMetric label="Intent" value={primary?.intent}/></Card><Card className="p-4"><h2 className="text-xs text-muted">Trend</h2>{history.length?<div className="mt-3 flex h-24 items-end gap-1" role="img" aria-label={history.map(row=>`${row.year}-${row.month}: ${row.volume}`).join(", ")}>{history.map(row=><div key={`${row.year}-${row.month}`} title={`${row.year}-${row.month}: ${format(row.volume)} searches`} className="min-w-0 flex-1 rounded-t bg-purple/50" style={{height:`${Math.max(1,row.volume/max*100)}%`}}/>)}</div>:<p className="py-6 text-xs text-muted">Monthly history unavailable</p>}<p className="mt-2 text-[11px] text-muted">Monthly searches{history.length?` · through ${history.at(-1)!.year}-${String(history.at(-1)!.month).padStart(2,"0")}`:""}</p></Card></div>
      <Card className="p-4"><ReportMetric label="CPC (USD)" value={primary?.cpc}/><div className="my-3 border-t border-border"/><ReportMetric label="Competitive density" value={primary?.competition} note="Google Ads competition · 0–1"/><div className="mt-4 grid grid-cols-2 gap-3 border-t border-border pt-3 text-xs"><span>PLA<br/><span className="text-muted">Unavailable</span></span><span>Ads history<br/><span className="text-muted">Unavailable</span></span></div></Card>
    </div>
    <Card className="overflow-hidden"><h2 className="border-b border-border px-4 py-3 text-base font-semibold">Keyword ideas</h2><div className="grid divide-border lg:grid-cols-3 lg:divide-x">{([{key:"variations",label:"Keyword variations",query:{...DEFAULT_KEYWORD_QUERY,match:"broad"}},{key:"questions",label:"Questions",query:{...DEFAULT_KEYWORD_QUERY,questions:true}}] as const).map(block=>{const data=result?.report?.[block.key];return <div key={block.key} className="min-w-0"><div className="p-4"><h3 className="text-sm">{block.label}</h3><p className="mt-1 text-xl font-semibold text-purple">{format(data?.total)} <span className="text-xs font-normal text-muted">matching keywords</span></p></div><table className="w-full text-left text-xs"><thead className="border-y border-border text-muted"><tr><th className="px-4 py-2">Keyword</th><th className="pr-3 text-right">Volume</th><th className="pr-4 text-right">KD %</th></tr></thead><tbody>{data?.rows.map(row=><tr key={row.keyword} className="border-b border-border/50"><td className="px-4 py-2"><button className="text-left text-purple hover:underline" disabled={busy} onClick={()=>onKeyword(row)}>{row.keyword}</button></td><td className="pr-3 text-right">{format(row.volume)}</td><td className="pr-4 text-right">{format(row.difficulty)}</td></tr>)}</tbody></table>{!data?.rows.length&&<p className="px-4 py-6 text-xs text-muted">{data?.total===0?"No matching results in this provider database.":"Analyze this keyword to collect the full report."}</p>}<Button size="sm" className="m-4" disabled={busy||!result} onClick={()=>onOpenMagic(block.query)}>View all {block.label.toLowerCase()}</Button></div>;})}<div className="p-4"><h3 className="text-sm">Keyword Strategy</h3><p className="mt-3 text-xs leading-5 text-muted">Group keywords into topics, choose pillar pages and build a content plan from your selected research.</p><div className="my-5 rounded border border-border bg-workspace p-4 text-sm"><strong>{result?.seed||"Your topic"}</strong><div className="ml-2 mt-3 space-y-3 border-l-2 border-purple/30 pl-4 text-xs text-muted"><p>Topic clusters</p><p>Pillar and supporting pages</p><p>Content brief and tracking</p></div></div>{result&&<Link className="inline-block rounded border border-border px-3 py-2 text-xs text-purple" href={`/keyword-strategy?${strategy}`}>Build a keyword strategy →</Link>}</div></div></Card>
    <div className="grid gap-3 lg:grid-cols-[2fr_1fr]"><Card className="p-4"><div className="mb-3 flex justify-between"><h2 className="text-base font-semibold">Related keywords</h2><Button size="sm" disabled={busy||!result} onClick={()=>onOpenMagic({...DEFAULT_KEYWORD_QUERY,match:"related"})}>View related keywords</Button></div><p className="mb-3 text-xs text-muted">{format(result?.report?.related?.total)} matches in DataForSEO’s related-keyword graph</p><div className="divide-y divide-border">{result?.report?.related?.rows.map(row=><button key={row.keyword} disabled={busy} className="flex w-full justify-between py-2 text-left text-sm text-purple" onClick={()=>onKeyword(row)}><span>{row.keyword}</span><span className="text-xs text-muted">Volume {format(row.volume)} · KD {format(row.difficulty)}</span></button>)}</div></Card><Card className="p-4"><h2 className="text-sm font-semibold">Personalized difficulty</h2><p className="mt-3 text-xs leading-5 text-muted">Unavailable. Semrush’s domain-specific PKD and traffic-potential models are proprietary. The KD shown here is DataForSEO’s general keyword difficulty.</p></Card></div>
    {result&&<SerpInspector key={`${result.seed}:${result.locationCode}:${result.languageCode}`} site={site} keyword={result.seed} locationCode={result.locationCode} languageCode={result.languageCode}/>}
    <p className="text-[11px] text-muted">DataForSEO · {result?`Collected ${new Date(result.fetchedAt).toLocaleString()}`:"No collection selected"}. Keyword coverage, estimates and scoring differ from Semrush.</p>
  </div>;
}
