"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {ChevronDown,ChevronRight,Download,ListPlus,Settings2,Target,RefreshCw} from "lucide-react";
import {Button,Card} from "@/components/ui/primitives";
import {Drawer} from "@/components/ui/drawer";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Sparkline} from "@/components/charts/sparkline";
import {ResearchHandoff} from "@/components/research/research-handoff";
import {keywordGroups,keywordTopics,keywordWords,keywordKey,keywordSummary,type WorkbenchKeyword} from "@/lib/keyword-workbench";
import {DEFAULT_KEYWORD_QUERY,KeywordQuerySchema,type KeywordQuery} from "@/lib/keyword-query";
import {useJson} from "@/lib/use-live";
import type {CommandRecord} from "@/lib/command-model";
import type {KeywordResearchResult} from "@/lib/types";
import {exportRows} from "@/lib/report-download";

const field="h-8 rounded border border-border bg-card px-2 text-xs text-ink";
const format=(value:number|null|undefined)=>value==null?"—":value.toLocaleString(undefined,{maximumFractionDigits:2});
const intents:Record<string,string>={informational:"I",navigational:"N",commercial:"C",transactional:"T"};
function RangeFilter({label,min,max,onChange}:{label:string;min:string;max:string;onChange:(min:string,max:string)=>void}){
  return <details className="relative"><summary className={`${field} flex cursor-pointer list-none items-center gap-3 ${min||max?"border-purple text-purple":""}`}>{label}{(min||max)&&` ${min||"0"}–${max||"∞"}`}<ChevronDown className="h-3 w-3"/></summary><div className="absolute left-0 top-full z-30 mt-1 flex w-56 gap-2 rounded border border-border bg-card p-3 shadow-pop"><input aria-label={`Minimum ${label}`} type="number" min="0" className={`${field} w-24`} placeholder="From" value={min} onChange={e=>onChange(e.target.value,max)}/><input aria-label={`Maximum ${label}`} type="number" min="0" className={`${field} w-24`} placeholder="To" value={max} onChange={e=>onChange(min,e.target.value)}/></div></details>;
}
function TextFilter({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){
  return <details className="relative"><summary className={`${field} flex cursor-pointer list-none items-center gap-3 ${value?"border-purple text-purple":""}`}>{label}{value&&" •"}<ChevronDown className="h-3 w-3"/></summary><div className="absolute left-0 top-full z-30 mt-1 w-64 rounded border border-border bg-card p-3 shadow-pop"><label className="text-xs">{label}<input aria-label={label} className={`${field} mt-2 w-full`} value={value} onChange={e=>onChange(e.target.value)} placeholder="Separate terms with commas"/></label></div></details>;
}

type Props={bulk?:boolean;rows:WorkbenchKeyword[];seed:string;site?:string;scanId:string|null;collectedAt?:string;selected:Set<string>;onSelect:(next:Set<string>)=>void;onTrack:()=>void;onSaveList:(rows:WorkbenchKeyword[],name:string)=>Promise<void>;onVisibleRows:(rows:WorkbenchKeyword[])=>void;appliedQuery?:KeywordQuery;initialQuery?:KeywordQuery;pagination?:KeywordResearchResult["pagination"];busy:boolean;onQuery:(next:KeywordQuery)=>void;onKeyword:(row:WorkbenchKeyword)=>void;onRefresh:(rows:WorkbenchKeyword[])=>void;onExcel:(grouped?:boolean)=>void;};
export function KeywordWorkbench({bulk=false,rows,seed,site,scanId,collectedAt,selected,onSelect,onTrack,onSaveList,onVisibleRows,appliedQuery,initialQuery,pagination,busy,onQuery,onKeyword,onRefresh,onExcel}:Props){
  const filterPanel=useRef<HTMLElement>(null);
  const [draft,setDraft]=useState<KeywordQuery>(initialQuery??appliedQuery??DEFAULT_KEYWORD_QUERY),[groupSort,setGroupSort]=useState("count"),[groupType,setGroupType]=useState("groups"),[hidden,setHidden]=useState<string[]>(["trend","competition","results","market"]),[listOpen,setListOpen]=useState(false),[listName,setListName]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState(""),[presetName,setPresetName]=useState(""),[copied,setCopied]=useState(false);
  useEffect(()=>{setDraft(appliedQuery??initialQuery??DEFAULT_KEYWORD_QUERY);},[appliedQuery,initialQuery]);
  const presets=useJson<{records:CommandRecord[]}>(site?`/api/keyword-research/filters?site=${encodeURIComponent(site)}`:null);
  const dirty=JSON.stringify(draft)!==JSON.stringify(appliedQuery??DEFAULT_KEYWORD_QUERY);
  const update=(next:Partial<KeywordQuery>)=>setDraft(current=>({...current,...next}));
  function apply(next=draft){setError("");const parsed=KeywordQuerySchema.safeParse(next);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Check your filters.");return;}setDraft(parsed.data);filterPanel.current?.querySelectorAll("details[open]").forEach(item=>item.removeAttribute("open"));onQuery(parsed.data);}
  useEffect(()=>onVisibleRows(rows),[rows,onVisibleRows]);
  const groups=useMemo(()=>(groupType==="topics"?keywordTopics:keywordGroups)(rows,seed,appliedQuery?.group??[]).sort((a,b)=>groupSort==="volume"?(b.volume??-1)-(a.volume??-1):b.count-a.count),[rows,seed,appliedQuery,groupSort,groupType]);
  const summary=keywordSummary(rows),chosen=rows.filter(row=>selected.has(keywordKey(row)));
  const markets=[...new Map(rows.map(row=>[`${row.marketCode}:${row.languageCode}`,row])).entries()];
  async function savePreset(){if(!site||!presetName.trim())return;setSaving(true);setError("");try{const response=await fetch("/api/keyword-research/filters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,name:presetName,filters:draft,query:"",hidden})});const body=await response.json();if(!response.ok)throw new Error(body.error);setPresetName("");presets.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save filters.");}finally{setSaving(false);}}
  async function saveList(){setSaving(true);setError("");try{await onSaveList(chosen.length?chosen:rows,listName);setListOpen(false);}catch(e){setError(e instanceof Error?e.message:"Could not save this list.");}finally{setSaving(false);}}
  const columns:Column<WorkbenchKeyword>[]=[
    {key:"select",header:"",width:"36px",render:row=><input type="checkbox" aria-label={`Select ${row.keyword} ${row.marketLabel}`} checked={selected.has(keywordKey(row))} onChange={()=>{const next=new Set(selected),key=keywordKey(row);if(next.has(key))next.delete(key);else next.add(key);onSelect(next);}}/>},
    {key:"keyword",header:"Keyword",sortValue:row=>row.keyword,render:row=><button disabled={busy} className="text-left text-purple hover:underline" onClick={()=>onKeyword(row)}>{row.keyword}</button>},
    {key:"intent",header:"Intent",sortValue:row=>row.intent??"",render:row=>row.intent?<button title={`${row.intent} · filter by this intent`} disabled={busy} className="rounded bg-purple/10 px-1.5 py-0.5 text-xs font-semibold text-purple" onClick={()=>apply({...draft,intent:row.intent!})}>{intents[row.intent]}</button>:"—"},
    {key:"volume",header:"Volume",sortValue:row=>row.volume??-1,align:"right",render:row=>format(row.volume)},
    {key:"trend",header:"Trend",render:row=>row.trend.length>1?<Sparkline data={row.trend} className="h-6 w-20"/>:"—"},
    {key:"difficulty",header:"KD %",sortValue:row=>row.difficulty??-1,align:"right",render:row=><span className="inline-flex items-center gap-2">{format(row.difficulty)}{row.difficulty!=null&&<span className={`h-2 w-2 rounded-full ${row.difficulty<30?"bg-success":row.difficulty<60?"bg-warning":"bg-critical"}`}/>}</span>},
    {key:"cpc",header:"CPC (USD)",sortValue:row=>row.cpc??-1,align:"right",render:row=>format(row.cpc)},
    {key:"competition",header:"Competitive density",sortValue:row=>row.competition??-1,align:"right",render:row=>format(row.competition)},
    {key:"serpFeatures",header:"SERP features",render:row=><div className="flex max-w-52 flex-wrap gap-1">{row.serpFeatures?.length?row.serpFeatures.map(feature=><button key={feature} disabled={busy} title={`Filter: ${feature.replaceAll("_"," ")}`} className="rounded bg-workspace px-1.5 py-0.5 text-[11px] text-muted hover:text-purple" onClick={()=>apply({...draft,serpFeature:feature})}>{feature.replaceAll("_"," ")}</button>):"—"}</div>},
    {key:"results",header:"Results",sortValue:row=>row.resultCount??-1,align:"right",render:row=>format(row.resultCount)},
    {key:"market",header:"Database",render:row=><span className="whitespace-nowrap text-xs">{row.marketLabel} · {row.languageCode}</span>},
    {key:"updated",header:"Updated",sortValue:row=>row.updatedAt??"",render:row=><div className="flex items-center gap-2"><span className="whitespace-nowrap text-xs text-muted" title={row.updatedAt??"Provider date unavailable"}>{row.updatedAt?.slice(0,10)||"Unavailable"}</span><button disabled={busy} aria-label={`Update metrics for ${row.keyword}`} onClick={()=>onRefresh([row])}><RefreshCw className="h-3 w-3 text-muted"/></button></div>},
  ];
  function exportCsv(){const output=chosen.length?chosen:rows;exportRows(`${seed||"keywords"}.csv`,["Keyword","Intent","Volume","KD % (DataForSEO)","CPC (USD)","Competitive density","SERP features","Results","Country","Language","Metrics updated","Collected","Monthly searches"],output.map(row=>[row.keyword,row.intent,row.volume,row.difficulty,row.cpc,row.competition,row.serpFeatures?.join("; "),row.resultCount,row.marketLabel,row.languageCode,row.updatedAt,row.collectedAt??collectedAt,row.monthlySearches.map(month=>`${month.year}-${month.month}:${month.volume}`).join("; ")]));}
  return <div className="space-y-3" aria-busy={busy}>
    {!bulk&&<section ref={filterPanel} aria-label="Keyword filters" className="space-y-3">
      <div className="flex flex-wrap items-center gap-2"><div className="inline-flex overflow-hidden rounded border border-border" role="tablist" aria-label="Keyword type">{[false,true].map(questions=><button role="tab" key={String(questions)} disabled={busy} onClick={()=>apply({...draft,questions,group:[]})} aria-selected={draft.questions===questions} className={`px-3 py-1.5 text-xs ${draft.questions===questions?"bg-purple/10 text-purple":"bg-card"}`}>{questions?"Questions":"All"}</button>)}</div><div className="inline-flex flex-wrap overflow-hidden rounded border border-border" role="tablist" aria-label="Match modifiers">{[["all","All Keywords"],["broad","Broad Match"],["phrase","Phrase Match"],["exact","Exact Match"],["related","Related"]].map(([value,label])=><button role="tab" key={value} disabled={busy} onClick={()=>apply({...draft,match:value as KeywordQuery["match"],group:[]})} aria-selected={draft.match===value} className={`border-r border-border px-3 py-1.5 text-xs last:border-0 ${draft.match===value?"bg-purple/10 text-purple":"bg-card"}`}>{label}</button>)}</div><span className="text-xs text-muted">{markets.map(([,row])=>`${row.marketLabel} · ${row.languageCode}`).join(" / ")}</span></div>
      <div className="flex flex-wrap items-center gap-2"><RangeFilter label="Volume" min={draft.minVolume} max={draft.maxVolume} onChange={(minVolume,maxVolume)=>update({minVolume,maxVolume})}/><RangeFilter label="KD %" min={draft.minDifficulty} max={draft.maxDifficulty} onChange={(minDifficulty,maxDifficulty)=>update({minDifficulty,maxDifficulty})}/><select aria-label="Search intent" value={draft.intent} className={field} onChange={e=>update({intent:e.target.value as KeywordQuery["intent"]})}><option value="">Intent</option>{Object.keys(intents).map(intent=><option key={intent} value={intent}>{intent}</option>)}</select><RangeFilter label="CPC (USD)" min={draft.minCpc} max={draft.maxCpc} onChange={(minCpc,maxCpc)=>update({minCpc,maxCpc})}/><TextFilter label="Include keywords" value={draft.include} onChange={include=>update({include})}/><TextFilter label="Exclude keywords" value={draft.exclude} onChange={exclude=>update({exclude})}/><details className="relative"><summary className={`${field} flex cursor-pointer items-center`}>Advanced filters</summary><div className="absolute right-0 z-30 mt-1 flex w-64 flex-col gap-3 rounded border border-border bg-card p-3 shadow-pop"><RangeFilter label="Word count" min={draft.minWords} max={draft.maxWords} onChange={(minWords,maxWords)=>update({minWords,maxWords})}/><RangeFilter label="Competitive density" min={draft.minCompetition} max={draft.maxCompetition} onChange={(minCompetition,maxCompetition)=>update({minCompetition,maxCompetition})}/><label className="text-xs">SERP features<select aria-label="SERP feature filter" value={draft.serpFeature} className={`${field} mt-2 w-full`} onChange={e=>update({serpFeature:e.target.value})}><option value="">Any feature</option>{[...new Set(["featured_snippet","people_also_ask","local_pack","images","video","shopping","ai_overview",...rows.flatMap(row=>row.serpFeatures??[])])].map(feature=><option key={feature} value={feature}>{feature.replaceAll("_"," ")}</option>)}</select></label></div></details><Button size="sm" variant="primary" disabled={busy||!seed} onClick={()=>apply()}>Apply filters</Button><button className="text-xs text-purple" disabled={busy} onClick={()=>apply(DEFAULT_KEYWORD_QUERY)}>Clear filters</button></div>
      <p className="text-[11px] text-muted">{busy?"Searching the provider database…":dirty?"Filter changes are pending. Apply filters to search the database.":appliedQuery?"Match, filters and column sorting apply to the provider database before results are collected.":"Saved collection. Apply filters to search the provider database with these settings."} All/Broad use seed-word suggestions and provider synonyms; Related uses the related-keyword graph. New searches use your existing spending limits.</p>
    </section>}
    {!bulk&&site&&<details className="text-xs"><summary className="cursor-pointer text-muted">Saved filter presets</summary><div className="mt-2 flex flex-wrap items-center gap-2"><select aria-label="Saved keyword filters" className={field} defaultValue="" onChange={e=>{const payload=presets.data?.records.find(row=>row.id===e.target.value)?.payload;if(payload){const parsed=KeywordQuerySchema.safeParse({...DEFAULT_KEYWORD_QUERY,...payload.filters as object});if(parsed.success)setDraft(parsed.data);setHidden(Array.isArray(payload.hidden)?payload.hidden as string[]:[]);}}}><option value="">Choose a preset</option>{presets.data?.records.map(row=><option key={row.id} value={row.id}>{String(row.payload.name)}</option>)}</select><input aria-label="Filter preset name" className={field} placeholder="Name these filters" value={presetName} onChange={e=>setPresetName(e.target.value)}/><Button size="sm" disabled={saving||!presetName.trim()} onClick={()=>void savePreset()}>Save filters</Button></div></details>}
    {error&&<p role="alert" className="text-sm text-critical">{error}</p>}
    <Card className={`grid overflow-hidden ${bulk?"":"lg:grid-cols-[220px_minmax(0,1fr)]"} ${busy?"opacity-60":""}`}>
      {!bulk&&<aside aria-label="Keyword groups" className="border-b border-border lg:border-b-0 lg:border-r"><div className="flex border-b border-border">{["topics","groups"].map(value=><button key={value} className={`flex-1 px-3 py-3 text-xs capitalize ${groupType===value?"border-b-2 border-purple text-purple":"text-muted"}`} onClick={()=>setGroupType(value)}>{value}</button>)}</div><div className="flex justify-between px-3 py-2 text-[11px] text-muted"><span>Collected keywords</span><select aria-label="Sort keyword groups" className="bg-card" value={groupSort} onChange={e=>setGroupSort(e.target.value)}><option value="count">By number</option><option value="volume">By volume</option></select></div><button disabled={busy} className="flex w-full justify-between p-3 text-xs font-semibold text-purple" onClick={()=>apply({...draft,group:[]})}><span>All keywords</span><span>{format(pagination?.total??rows.length)}</span></button>{!!draft.group.length&&<div className="border-b border-border px-3 pb-2 text-xs text-muted">{draft.group.join(" › ")}<button disabled={busy} className="ml-2 text-purple" onClick={()=>apply({...draft,group:draft.group.slice(0,-1)})}>Back</button></div>}<div className="max-h-[600px] overflow-y-auto">{groups.map(group=><button key={group.term} disabled={busy||draft.group.length>=4} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs hover:bg-workspace" onClick={()=>apply({...draft,group:[...draft.group,...keywordWords(group.term)].slice(0,4)})}><ChevronRight className="h-3 w-3 text-muted"/><span className="min-w-0 flex-1 capitalize">{group.term}</span><span className="text-muted">{format(groupSort==="volume"?group.volume:group.count)}</span></button>)}</div><p className="p-3 text-[11px] leading-4 text-muted">Group counts cover collected rows. Selecting a group searches the full provider database. Topics use recurring phrases; these are not Semrush’s proprietary topic clusters.</p></aside>}
      <div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><div className="text-sm"><strong>{format(pagination?.total??summary.count)}</strong> {pagination?.total!=null?"matching keywords":"saved keywords"}<p className="mt-1 text-xs text-muted">{summary.count} collected · Collected volume: {format(summary.volume)} · Collected average KD: {format(summary.difficulty)}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy||!rows.length} onClick={()=>onRefresh(chosen.length?chosen:rows)}><RefreshCw className="h-3 w-3"/>Update metrics</Button><details className="relative"><summary className={`${field} flex cursor-pointer list-none items-center gap-2`}><Settings2 className="h-3.5 w-3.5"/>Columns</summary><div className="absolute right-0 top-full z-30 mt-1 w-52 rounded border border-border bg-card p-3 shadow-pop">{columns.filter(column=>!["select","keyword"].includes(column.key)).map(column=><label key={column.key} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={!hidden.includes(column.key)} onChange={()=>setHidden(current=>current.includes(column.key)?current.filter(key=>key!==column.key):[...current,column.key])}/>{column.header}</label>)}</div></details><details className="relative"><summary className={`${field} flex cursor-pointer items-center gap-2`}><Download className="h-3 w-3"/>Export</summary><div className="absolute right-0 z-30 mt-1 w-48 rounded border border-border bg-card p-2 shadow-pop">{[["CSV",exportCsv],["Excel",()=>onExcel(false)],["Excel with groups",()=>onExcel(true)]] .map(([label,action])=><button key={String(label)} disabled={!rows.length} className="block w-full p-2 text-left text-xs" onClick={event=>{event.currentTarget.closest("details")?.removeAttribute("open");(action as ()=>void)();}}>{String(label)}</button>)}</div></details></div></div>
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border bg-workspace/40 px-4 py-2"><div className="flex gap-2 text-xs"><label className="flex items-center gap-2"><input aria-label="Select all collected keywords" type="checkbox" checked={rows.length>0&&chosen.length===rows.length} onChange={e=>onSelect(new Set(e.target.checked?rows.map(keywordKey):[]))}/>{chosen.length} selected</label><button disabled={!chosen.length} className="text-purple" onClick={()=>{void navigator.clipboard.writeText(chosen.map(row=>row.keyword).join("\n")).then(()=>setCopied(true)).catch(()=>setError("Clipboard permission was denied. Use CSV export instead."));}}>{copied?"Copied":"Copy"}</button></div><div className="flex flex-wrap items-center gap-2"><Button size="sm" disabled={!rows.length} onClick={()=>{setListName(`${seed} keywords`);setListOpen(true);}}><ListPlus className="h-3.5 w-3.5"/>Save to list</Button><Button size="sm" disabled={!chosen.length||!site} onClick={onTrack}><Target className="h-3.5 w-3.5"/>Track keywords</Button></div></div>
      {chosen.length>0&&<div className="border-b border-border p-3">{markets.map(([key,marketRow])=>{const group=chosen.filter(row=>row.marketCode===marketRow.marketCode&&row.languageCode===marketRow.languageCode);return group.length?<ResearchHandoff key={`${key}:${group.map(row=>row.keyword).join("|")}`} keywords={group.map(row=>row.keyword)} evidence={{scanId,rows:group,collectedAt,market:{locationCode:marketRow.marketCode,languageCode:marketRow.languageCode,label:marketRow.marketLabel}}} sourceUrl={`/keyword-research?site=${site??""}&view=discover`}/>:null;})}</div>}
      <div className="p-3"><DataTable columnControls={false} rows={rows} columns={columns.filter(column=>!hidden.includes(column.key))} rowKey={keywordKey} pageSize={50} serverSort={appliedQuery?{key:appliedQuery.sort,direction:appliedQuery.direction,onChange:(key,direction)=>{if(!busy)apply({...draft,sort:key as KeywordQuery["sort"],direction});}}:undefined} emptyLabel={pagination?.total===0?"No matching keywords in this provider database. Adjust your filters.":"Enter a keyword and choose a database, or open a saved search."}/></div><p className="border-t border-border px-4 py-2 text-[11px] text-muted">DataForSEO · {collectedAt?`Collected ${new Date(collectedAt).toLocaleString()}`:"No saved collection selected"} · {summary.measuredVolumes}/{summary.count} keywords have reported volume. KD is DataForSEO’s estimate. Exports include selected rows, or all collected rows when none are selected.</p></div>
    </Card>
    <Drawer open={listOpen} onClose={()=>setListOpen(false)} title="Save keyword list" footer={<Button variant="primary" disabled={saving||!listName.trim()} onClick={()=>void saveList()}>{saving?"Saving…":"Save list"}</Button>}><label className="block text-sm">List name<input className={`${field} mt-2 w-full`} value={listName} onChange={e=>setListName(e.target.value)}/></label><p className="mt-3 text-xs text-muted">{chosen.length||rows.length} keyword rows. Country, language and original metrics are preserved.</p>{error&&<p role="alert" className="mt-3 text-sm text-critical">{error}</p>}</Drawer>
  </div>;
}
