"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronRight, Download, ListPlus, Search, Settings2, Target } from "lucide-react";
import { Button, Card } from "@/components/ui/primitives";
import { Drawer } from "@/components/ui/drawer";
import { DataTable, type Column } from "@/components/ui/data-table";
import { Sparkline } from "@/components/charts/sparkline";
import { ResearchHandoff } from "@/components/research/research-handoff";
import { ReportMetric } from "@/components/reports/report-layout";
import { EMPTY_KEYWORD_FILTERS, filterKeywords, keywordGroups, keywordTopics, keywordWords, keywordKey, keywordSummary, type KeywordFilters, type WorkbenchKeyword } from "@/lib/keyword-workbench";
import { SerpInspector } from "@/components/research/serp-inspector";
import { useJson } from "@/lib/use-live";
import type { CommandRecord } from "@/lib/command-model";
import { exportRows } from "@/lib/report-download";

const field = "h-8 rounded border border-border bg-card px-2 text-xs text-ink";
const format = (value: number | null | undefined) => value == null ? "—" : value.toLocaleString(undefined,{maximumFractionDigits:2});
const intentNames: Record<string,string> = { informational:"I",navigational:"N",commercial:"C",transactional:"T" };

function RangeFilter({label,min,max,onChange}:{label:string;min:string;max:string;onChange:(min:string,max:string)=>void}) {
  return <details className="relative"><summary className={`${field} flex cursor-pointer list-none items-center gap-3 ${min || max ? "border-purple text-purple" : ""}`}>{label}{(min||max)&&` ${min||"0"}–${max||"∞"}`}<ChevronDown className="h-3 w-3"/></summary><div className="absolute left-0 top-full z-30 mt-1 flex w-56 gap-2 rounded border border-border bg-card p-3 shadow-pop"><input aria-label={`Minimum ${label}`} type="number" min="0" className={`${field} w-24`} placeholder="From" value={min} onChange={e=>onChange(e.target.value,max)}/><input aria-label={`Maximum ${label}`} type="number" min="0" className={`${field} w-24`} placeholder="To" value={max} onChange={e=>onChange(min,e.target.value)}/></div></details>;
}
function TextFilter({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) {
  return <details className="relative"><summary className={`${field} flex cursor-pointer list-none items-center gap-3 ${value?"border-purple text-purple":""}`}>{label}{value&&" •"}<ChevronDown className="h-3 w-3"/></summary><div className="absolute left-0 top-full z-30 mt-1 w-64 rounded border border-border bg-card p-3 shadow-pop"><label className="text-xs">{label}<input aria-label={label} className={`${field} mt-2 w-full`} value={value} onChange={e=>onChange(e.target.value)} placeholder="Separate words with commas"/></label></div></details>;
}

export function KeywordWorkbench({rows,seed,site,scanId,collectedAt,selected,onSelect,onTrack,onSaveList,onVisibleRows,overview=false,onOpenMagic,onCollectRelated}:{rows:WorkbenchKeyword[];seed:string;site?:string;scanId:string|null;collectedAt?:string;selected:Set<string>;onSelect:(next:Set<string>)=>void;onTrack:()=>void;onSaveList:(rows:WorkbenchKeyword[],name:string)=>Promise<void>;onVisibleRows:(rows:WorkbenchKeyword[])=>void;overview?:boolean;onOpenMagic:()=>void;onCollectRelated?:()=>void}) {
  const [filters,setFilters]=useState<KeywordFilters>({...EMPTY_KEYWORD_FILTERS,match:rows.length>0&&rows.every(row=>row.relatedToSeed)?"related":"all"}),[query,setQuery]=useState(""),[groupSort,setGroupSort]=useState("count"),[groupType,setGroupType]=useState("groups"),[hidden,setHidden]=useState<string[]>([]),[detail,setDetail]=useState<WorkbenchKeyword|null>(null),[listOpen,setListOpen]=useState(false),[listName,setListName]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const presets=useJson<{records:CommandRecord[]}>(site?`/api/keyword-research/filters?site=${site}`:null),[presetName,setPresetName]=useState("");
  async function savePreset(){if(!site||!presetName.trim())return;setSaving(true);setError("");try{const response=await fetch("/api/keyword-research/filters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,name:presetName,filters,query,hidden})});const body=await response.json();if(!response.ok)throw new Error(body.error);setPresetName("");presets.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save preset.");}finally{setSaving(false);}}
  const filtered=useMemo(()=>filterKeywords(rows,seed,filters).filter(row=>!query||row.keyword.toLowerCase().includes(query.toLowerCase())),[rows,seed,filters,query]);
  useEffect(()=>onVisibleRows(filtered),[filtered,onVisibleRows]);
  const groups=useMemo(()=>(groupType==="topics"?keywordTopics:keywordGroups)(filterKeywords(rows,seed,{...filters,group:[]}),seed,filters.group).sort((a,b)=>groupSort==="volume"?(b.volume??-1)-(a.volume??-1):b.count-a.count),[rows,seed,filters,groupSort,groupType]);
  const summary=keywordSummary(filtered), chosen=rows.filter(row=>selected.has(keywordKey(row)));
  const markets=[...new Map(rows.map(row=>[`${row.marketCode}:${row.languageCode}`,row])).entries()];
  const update=(next:Partial<KeywordFilters>)=>setFilters(current=>({...current,...next}));
  const allColumns:Column<WorkbenchKeyword>[]=[
    {key:"select",header:"",width:"36px",render:row=><input type="checkbox" aria-label={`Select ${row.keyword} ${row.marketLabel}`} checked={selected.has(keywordKey(row))} onChange={()=>{const next=new Set(selected);const key=keywordKey(row);if(next.has(key))next.delete(key);else next.add(key);onSelect(next);}}/>},
    {key:"keyword",header:"Keyword",sortValue:row=>row.keyword,render:row=><button className="text-left text-purple hover:underline" onClick={()=>setDetail(row)}>{row.keyword}</button>},
    {key:"intent",header:"Intent",sortValue:row=>row.intent??"",render:row=>row.intent?<span title={row.intent} className="rounded bg-purple/10 px-1.5 py-0.5 text-xs font-semibold text-purple">{intentNames[row.intent]}</span>:"—"},
    {key:"volume",header:"Volume",sortValue:row=>row.volume??-1,align:"right",render:row=>format(row.volume)},
    {key:"trend",header:"Trend",render:row=>row.trend.length>1?<Sparkline data={row.trend} className="h-6 w-20"/>:"—"},
    {key:"difficulty",header:"KD %",sortValue:row=>row.difficulty??-1,align:"right",render:row=><span className="inline-flex items-center gap-2">{format(row.difficulty)}{row.difficulty!=null&&<span className={`h-2 w-2 rounded-full ${row.difficulty<30?"bg-success":row.difficulty<60?"bg-warning":"bg-critical"}`}/>}</span>},
    {key:"cpc",header:"CPC (USD)",sortValue:row=>row.cpc??-1,align:"right",render:row=>format(row.cpc)},
    {key:"competition",header:"Competitive density",sortValue:row=>row.competition??-1,align:"right",render:row=>format(row.competition)},
    {key:"serpFeatures",header:"SERP features",render:row=>row.serpFeatures?.join(", ")||"—"},
    {key:"results",header:"Results",sortValue:row=>row.resultCount??-1,align:"right",render:row=>format(row.resultCount)},
    {key:"market",header:"Database",render:row=><span className="whitespace-nowrap text-xs">{row.marketLabel} · {row.languageCode}</span>},
    {key:"updated",header:"Updated",render:row=><span className="whitespace-nowrap text-xs text-muted">{(row.updatedAt??collectedAt)?.slice(0,10)||"Unknown"}</span>},
  ];
  function exportKeywords() {const selectedFiltered=filtered.filter(row=>selected.has(keywordKey(row))), output=selectedFiltered.length?selectedFiltered:filtered;exportRows(`${seed||"keywords"}.csv`,["Keyword","Intent","Volume","KD %","CPC (USD)","Competitive density","Country / database","Language","Updated"],output.map(row=>[row.keyword,row.intent,row.volume,row.difficulty,row.cpc,row.competition,row.marketLabel,row.languageCode,row.updatedAt??collectedAt]));}
  async function saveList(){setSaving(true);setError("");try{await onSaveList(chosen.length?chosen:filtered,listName);setListOpen(false);}catch(e){setError(e instanceof Error?e.message:"Could not save this list.");}finally{setSaving(false);}}
  const primary=rows.find(row=>row.keyword.toLowerCase()===seed.toLowerCase());
  return <div className="space-y-4">
    {overview ? <>
      <div className="grid gap-4 xl:grid-cols-[1.1fr_1fr_1fr]"><Card className="overflow-hidden"><div className="grid grid-cols-2 divide-x divide-border"><ReportMetric label="Volume" value={primary?.volume} note={primary?.marketLabel??"Choose a saved keyword"}/><ReportMetric label="Keyword difficulty" value={primary?.difficulty==null?null:`${primary.difficulty}%`} note="DataForSEO difficulty"/></div><div className="border-t border-border px-4 py-3 text-xs text-muted">{primary?.difficulty==null?"Collect the exact keyword to see its metrics.":primary.difficulty<30?"Lower observed competition. Review search intent and top-ranking pages before planning content.":"Compare your page with the leading results to identify the content and authority required."}</div></Card><Card><ReportMetric label="Global volume" note="Requires the same keyword across all country databases"/><div className="border-t border-border px-4 py-3 text-xs">{markets.map(([key,row])=><div key={key} className="flex justify-between py-1"><span>{row.marketLabel}</span><span>{format(rows.find(r=>r.marketCode===row.marketCode&&r.languageCode===row.languageCode&&r.keyword.toLowerCase()===seed.toLowerCase())?.volume)}</span></div>)}</div></Card><Card><div className="grid grid-cols-2 divide-x divide-border"><ReportMetric label="Intent" value={primary?.intent}/><ReportMetric label="CPC (USD)" value={primary?.cpc}/></div><div className="border-t border-border p-4"><p className="mb-3 text-xs text-muted">Trend · monthly search volume</p>{primary&&primary.trend.length>1?<Sparkline data={primary.trend} className="h-16 w-full"/>:<p className="text-xs text-muted">Monthly history is not available for this keyword.</p>}</div></Card></div>
      <div className="grid gap-4 lg:grid-cols-3">{[{label:"Keyword variations",items:filterKeywords(rows,seed,{...EMPTY_KEYWORD_FILTERS,match:"broad"})},{label:"Questions",items:filterKeywords(rows,seed,{...EMPTY_KEYWORD_FILTERS,questions:true})},{label:"Related keywords",items:filterKeywords(rows,seed,{...EMPTY_KEYWORD_FILTERS,match:"related"})}].map(block=><Card key={block.label} className="overflow-hidden"><h2 className="border-b border-border p-4 text-base font-semibold">{block.label} <span className="text-xs font-normal text-muted">{block.items.length}</span></h2><table className="w-full text-left text-xs"><thead className="bg-workspace text-muted"><tr><th className="px-4 py-2">Keyword</th><th>Volume</th><th>KD %</th></tr></thead><tbody>{block.items.slice(0,5).map(row=><tr key={keywordKey(row)} className="border-t border-border"><td className="px-4 py-2"><button className="text-left text-purple" onClick={()=>setDetail(row)}>{row.keyword}</button></td><td>{format(row.volume)}</td><td>{format(row.difficulty)}</td></tr>)}</tbody></table>{!block.items.length&&<p className="p-4 text-xs text-muted">No matching keywords in this saved collection.</p>}<button className="m-4 text-xs font-semibold text-purple" onClick={onOpenMagic}>View all keywords →</button></Card>)}</div>
    </> : <>
      <div className="flex flex-wrap items-center gap-2"><div className="inline-flex overflow-hidden rounded border border-border">{[false,true].map(questions=><button key={String(questions)} onClick={()=>update({questions})} aria-pressed={filters.questions===questions} className={`px-3 py-1.5 text-xs ${filters.questions===questions?"bg-purple/10 text-purple":"bg-card"}`}>{questions?"Questions":"All"}</button>)}</div><div className="inline-flex flex-wrap overflow-hidden rounded border border-border">{[["all","All Keywords"],["broad","Broad Match"],["phrase","Phrase Match"],["exact","Exact Match"],["related","Related"]].map(([value,label])=><button key={value} onClick={()=>{update({match:value as KeywordFilters["match"]});if(value==="related"&&!rows.some(row=>row.relatedToSeed))onCollectRelated?.();}} aria-pressed={filters.match===value} className={`border-r border-border px-3 py-1.5 text-xs last:border-0 ${filters.match===value?"bg-purple/10 text-purple":"bg-card"}`}>{label}</button>)}</div><select aria-label="Keyword database" className={field} value={filters.market} onChange={e=>update({market:e.target.value})}><option value="">All saved databases</option>{markets.map(([key,row])=><option key={key} value={key}>{row.marketLabel} · {row.languageCode}</option>)}</select></div>
      <div className="flex flex-wrap items-center gap-2"><RangeFilter label="Volume" min={filters.minVolume} max={filters.maxVolume} onChange={(minVolume,maxVolume)=>update({minVolume,maxVolume})}/><RangeFilter label="KD %" min={filters.minDifficulty} max={filters.maxDifficulty} onChange={(minDifficulty,maxDifficulty)=>update({minDifficulty,maxDifficulty})}/><select aria-label="Search intent" value={filters.intent} className={field} onChange={e=>update({intent:e.target.value})}><option value="">Intent</option>{Object.keys(intentNames).map(intent=><option key={intent} value={intent}>{intent}</option>)}</select><RangeFilter label="CPC (USD)" min={filters.minCpc} max={filters.maxCpc} onChange={(minCpc,maxCpc)=>update({minCpc,maxCpc})}/><TextFilter label="Include keywords" value={filters.include} onChange={include=>update({include})}/><TextFilter label="Exclude keywords" value={filters.exclude} onChange={exclude=>update({exclude})}/><RangeFilter label="Word count" min={filters.minWords} max={filters.maxWords} onChange={(minWords,maxWords)=>update({minWords,maxWords})}/><button className="text-xs text-purple" onClick={()=>{setFilters(EMPTY_KEYWORD_FILTERS);setQuery("");}}>Clear filters</button></div>
    </>}
    {!overview&&site&&<div className="flex flex-wrap items-center gap-2"><select aria-label="Saved keyword filters" className={field} defaultValue="" onChange={e=>{const row=presets.data?.records.find(row=>row.id===e.target.value);if(row){setFilters({...EMPTY_KEYWORD_FILTERS,...row.payload.filters as KeywordFilters});setQuery(String(row.payload.query??""));setHidden(row.payload.hidden as string[]??[]);}}}><option value="">Apply saved filters</option>{presets.data?.records.map(row=><option key={row.id} value={row.id}>{String(row.payload.name)}</option>)}</select><input aria-label="Filter preset name" placeholder="Name this filter preset" className={field} value={presetName} onChange={e=>setPresetName(e.target.value)}/><Button size="sm" disabled={saving||!presetName.trim()} onClick={()=>void savePreset()}>Save filters</Button>{error&&<span role="alert" className="text-xs text-critical">{error}</span>}</div>}
    {overview&&primary&&<SerpInspector key={`${primary.keyword}:${primary.marketCode}`} site={site} keyword={primary.keyword} locationCode={primary.marketCode} languageCode={primary.languageCode}/>}
    {!overview&&filters.match==="related"&&!rows.some(row=>row.relatedToSeed)&&<p className="rounded border border-border bg-workspace p-3 text-xs text-muted">This collection has no related-keyword evidence. Related keywords is selected in the search controls above; choose Analyze to collect it at the displayed estimate.</p>}
    <Card className={`grid overflow-visible ${overview?"":"lg:grid-cols-[230px_minmax(0,1fr)]"}`}>
      {!overview&&<aside className="min-w-0 border-b border-border lg:border-b-0 lg:border-r"><div className="flex gap-1 border-b border-border p-3">{["topics","groups"].map(type=><button key={type} className={`rounded border border-border px-3 py-1 text-xs capitalize ${groupType===type?"bg-purple/10 text-purple":""}`} aria-pressed={groupType===type} onClick={()=>{setGroupType(type);update({group:[]});}}>{type}</button>)}</div><div className="flex items-center justify-between border-b border-border p-3 text-xs"><span>{groupType==="topics"?"Topic":"Group"}</span><select aria-label="Sort keyword groups" className="bg-card" value={groupSort} onChange={e=>setGroupSort(e.target.value)}><option value="count">By number</option><option value="volume">By volume</option></select></div><button className="flex w-full justify-between p-3 text-xs font-semibold text-purple" onClick={()=>update({group:[]})}><span>All keywords</span><span>{rows.length}</span></button>{filters.group.length>0&&<div className="border-b border-border px-3 pb-2 text-xs text-muted">{filters.group.join(" › ")}<button className="ml-2 text-purple" onClick={()=>update({group:filters.group.slice(0,-1)})}>Back</button></div>}<div className="max-h-[560px] overflow-y-auto">{groups.map(group=><button key={group.term} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs hover:bg-workspace" onClick={()=>update({group:[...filters.group,...keywordWords(group.term)].slice(-4)})}><ChevronRight className="h-3 w-3 text-muted"/><span className="min-w-0 flex-1 capitalize">{group.term}</span><span className="text-muted">{format(groupSort==="volume"?group.volume:group.count)}</span></button>)}{groupType==="topics"&&<p className="p-3 text-[11px] text-muted">Grouped by recurring phrases in this collection.</p>}{!groups.length&&<p className="p-4 text-xs text-muted">No further groups in the filtered keywords.</p>}</div></aside>}
      <div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><div className="text-sm"><strong>{format(summary.count)}</strong> keywords <span className="ml-3 text-xs text-muted">Total volume: {format(summary.volume)} · Average KD: {format(summary.difficulty)}</span></div><div className="flex flex-wrap gap-2"><Button size="sm" disabled={!rows.length} onClick={()=>onSelect(new Set(filtered.map(keywordKey)))}>Select filtered</Button><details className="relative"><summary className={`${field} flex cursor-pointer list-none items-center gap-2`}><Settings2 className="h-3.5 w-3.5"/>Columns</summary><div className="absolute right-0 top-full z-30 mt-1 w-52 rounded border border-border bg-card p-3 shadow-pop">{allColumns.filter(column=>!["select","keyword"].includes(column.key)).map(column=><label key={column.key} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={!hidden.includes(column.key)} onChange={()=>setHidden(current=>current.includes(column.key)?current.filter(key=>key!==column.key):[...current,column.key])}/>{column.header}</label>)}</div></details><Button size="sm" disabled={!filtered.length} onClick={exportKeywords}><Download className="h-3.5 w-3.5"/>Export</Button></div></div>
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border bg-workspace/40 px-4 py-2"><div className="flex items-center gap-2"><Search className="h-3.5 w-3.5 text-muted"/><input aria-label="Filter keyword table" className={`${field} w-52`} placeholder="Filter keywords" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-muted">{chosen.length} selected</span><Button size="sm" disabled={!filtered.length} onClick={()=>{setListName(`${seed} keywords`);setListOpen(true);}}><ListPlus className="h-3.5 w-3.5"/>Save to list</Button><Button size="sm" disabled={!chosen.length||!site} onClick={onTrack}><Target className="h-3.5 w-3.5"/>Track keywords</Button><ResearchHandoff keywords={chosen.map(row=>row.keyword)} evidence={{scanId,rows:chosen,collectedAt}} sourceUrl={`/keyword-research?site=${site??""}&view=discover`}/></div></div>
      <div className="p-3"><DataTable rows={filtered} columns={allColumns.filter(column=>!hidden.includes(column.key))} rowKey={keywordKey} pageSize={50} emptyLabel={rows.length?"No keywords match these filters. Clear filters to see the saved collection.":"Enter a keyword and choose a database, or open a saved search to begin."}/></div><p className="border-t border-border px-4 py-2 text-[11px] text-muted">DataForSEO · {collectedAt?`Collected ${new Date(collectedAt).toLocaleString()}`:"No saved collection selected"} · {summary.measuredVolumes}/{summary.count} keywords have reported volume. Filters apply to the collected keyword sample.</p></div>
    </Card>
    <Drawer open={!!detail} onClose={()=>setDetail(null)} title={detail?.keyword??"Keyword overview"} subtitle={detail?`${detail.marketLabel} · ${detail.languageCode}`:undefined}>{detail&&<div className="space-y-4"><div className="grid grid-cols-2 rounded border border-border"><ReportMetric label="Volume" value={detail.volume}/><ReportMetric label="Keyword difficulty" value={detail.difficulty}/><ReportMetric label="CPC (USD)" value={detail.cpc}/><ReportMetric label="Intent" value={detail.intent}/></div><SerpInspector key={`${detail.keyword}:${detail.marketCode}`} site={site} keyword={detail.keyword} locationCode={detail.marketCode} languageCode={detail.languageCode}/><h3 className="text-sm font-semibold">Monthly search volume</h3><DataTable rows={[...detail.monthlySearches].sort((a,b)=>a.year-b.year||a.month-b.month)} columns={[{key:"date",header:"Month",render:r=>`${r.year}-${String(r.month).padStart(2,"0")}`,sortValue:r=>r.year*100+r.month},{key:"volume",header:"Searches",render:r=>format(r.volume),sortValue:r=>r.volume}]} exportName={`${detail.keyword}-history`}/><ResearchHandoff keywords={[detail.keyword]} evidence={{scanId,keyword:detail,collectedAt}} sourceUrl={`/keyword-research?site=${site??""}`}/><button className="text-sm text-purple" onClick={()=>{onSelect(new Set([keywordKey(detail)]));setDetail(null);onTrack();}}>Add this keyword to tracking →</button></div>}</Drawer>
    <Drawer open={listOpen} onClose={()=>setListOpen(false)} title="Save keyword list" footer={<Button variant="primary" disabled={saving||!listName.trim()} onClick={()=>void saveList()}>{saving?"Saving…":"Save list"}</Button>}><label className="block text-sm">List name<input className={`${field} mt-2 w-full`} value={listName} onChange={e=>setListName(e.target.value)}/></label><p className="mt-3 text-xs text-muted">{chosen.length||filtered.length} keyword rows. Each country and language is saved separately with its original evidence.</p>{error&&<p role="alert" className="mt-3 text-sm text-critical">{error}</p>}</Drawer>
  </div>;
}
