"use client";
import {AdvertisingChanges,AdvertisingHistory} from "./advertising-history";
import {useState} from "react";
import {useJson} from "@/lib/use-live";
import {Card,Button} from "@/components/ui/primitives";
import {DataTable,type Column} from "@/components/ui/data-table";
import {ReportTabs} from "@/components/reports/report-layout";
import type {AdvertisingKind,AdvertisingRow} from "@/lib/advertising";
import type {CommandRecord} from "@/lib/command-model";
export function AdvertisingResearch({site,domain,location,language}:{site:string;domain:string;location:number;language:string}){
 const state=useJson<{records:CommandRecord[]}>(`/api/advertising?site=${site}`),[kind,setKind]=useState<AdvertisingKind|"copies"|"changes"|"history">("keywords"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const reportKind=kind==="copies"||kind==="changes"||kind==="history"?"keywords":kind,records=state.data?.records.filter(row=>{const input=row.payload.input as {domain:string;locationCode:number;languageCode:string;kind:AdvertisingKind};return input.domain===domain&&input.locationCode===location&&input.languageCode===language&&input.kind===reportKind;})??[],[selected,setSelected]=useState("");
 const report=records.find(row=>row.id===selected)??records[0],rows=(report?.payload.rows??[]) as AdvertisingRow[];
 const number=(value:number|null)=>value==null?"—":value.toLocaleString(undefined,{maximumFractionDigits:2});
 const cols:Column<AdvertisingRow>[]=[{key:"label",header:kind==="competitors"?"Domain":kind==="pages"?"Landing page":"Paid keyword",sortValue:row=>row.label,render:row=>row.url&&kind==="pages"?<a className="text-purple" href={row.url} target="_blank" rel="noreferrer">{row.label}</a>:row.label},...(reportKind==="keywords"?[{key:"position",header:"Ad position",sortValue:(row:AdvertisingRow)=>row.position??-1,render:(row:AdvertisingRow)=>number(row.position)},{key:"volume",header:"Volume",sortValue:(row:AdvertisingRow)=>row.volume??-1,render:(row:AdvertisingRow)=>number(row.volume)},{key:"cpc",header:"CPC (USD)",sortValue:(row:AdvertisingRow)=>row.cpc??-1,render:(row:AdvertisingRow)=>number(row.cpc)}]:[{key:"keywords",header:"Paid keywords",sortValue:(row:AdvertisingRow)=>row.keywords??-1,render:(row:AdvertisingRow)=>number(row.keywords)}]),{key:"traffic",header:"Paid traffic est.",sortValue:row=>row.traffic??-1,render:row=>number(row.traffic)},...(kind==="competitors"?[{key:"common",header:"Common keywords",sortValue:(row:AdvertisingRow)=>row.common??-1,render:(row:AdvertisingRow)=>number(row.common)}]:[])];
 async function collect(){setBusy(true);setError("");try{const response=await fetch("/api/advertising",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,domain,locationCode:location,languageCode:language,kind:reportKind})});const body=await response.json();if(!response.ok)throw new Error(body.error);setSelected(body.record.id);state.refresh();}catch(e){setError(e instanceof Error?e.message:"Advertising report failed.");}finally{setBusy(false);}}
 return <Card className="p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h3 className="text-base font-semibold">Advertising Research: {domain}</h3>{kind!=="history"&&<Button size="sm" disabled={busy||!domain} onClick={()=>void collect()}>{busy?"Collecting…":`Collect ${reportKind} · est. $${reportKind==="keywords"?"0.05":reportKind==="competitors"?"0.03":"0.04"}`}</Button>}</div><ReportTabs items={[{id:"keywords",label:"Positions"},{id:"competitors",label:"Competitors"},{id:"copies",label:"Ad Copies"},{id:"pages",label:"Pages"},{id:"changes",label:"Position Changes"},{id:"history",label:"Ads History"}]} value={kind} onChange={setKind} label="Advertising reports"/><div className="my-3 flex flex-wrap items-center justify-between gap-2 text-xs text-muted"><span>DataForSEO {kind==="history"?"historical SERPs":"paid search index"} · {location} / {language}</span>{kind!=="history"&&kind!=="changes"&&<select aria-label="Advertising report date" className="max-w-72 rounded border border-border bg-card px-2 py-1" value={report?.id??""} onChange={e=>setSelected(e.target.value)}><option value="">{records.length?"Latest saved report":"No saved collection"}</option>{records.map(row=><option key={row.id} value={row.id}>{new Date(row.updatedAt).toLocaleString()}</option>)}</select>}</div>{(error||state.error)&&<p role="alert" className="mb-3 text-sm text-critical">{error||state.error}</p>}{kind==="changes"?<AdvertisingChanges records={records}/>:kind==="history"?<AdvertisingHistory key={`${site}:${domain}:${location}:${language}`} site={site} domain={domain} location={location} language={language}/>:kind==="copies"?<div className="grid gap-3 md:grid-cols-2">{rows.filter(row=>row.title||row.description).map((row,index)=><div key={`${row.label}:${index}`} className="rounded border border-border p-4"><p className="text-[11px] text-muted">Sponsored · {row.label}</p><h4 className="mt-2 text-sm font-semibold">{row.title??"Title not provided"}</h4>{row.url&&<a className="mt-1 block truncate text-xs text-purple" href={row.url} target="_blank" rel="noreferrer">{row.url}</a>}<p className="mt-2 text-xs leading-5">{row.description??"Description not provided"}</p></div>)}{!rows.some(row=>row.title||row.description)&&<p className="py-6 text-sm text-muted">Collect paid keyword positions to inspect ad copies returned by the provider.</p>}</div>:<DataTable rows={rows} columns={cols} rowKey={row=>`${row.label}:${row.url}`} searchKeys={row=>row.label} exportName={`${domain}-paid-${kind}`} emptyLabel="No paid records saved for this domain, database and report."/>}<p className="mt-3 text-[11px] text-muted">Indexed ad observations and estimates; not the advertiser’s Google Ads account. The history report adds indexed historical SERPs where available.</p></Card>;
}
