"use client";
import {useState} from "react";
import {useJson} from "@/lib/use-live";
import {compareAdvertising,type AdvertisingSnapshot,type AdvertisingChange,type HistoricalAdSnapshot} from "@/lib/ad-history";
import type {CommandRecord} from "@/lib/command-model";
import {Button} from "@/components/ui/primitives";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Drawer} from "@/components/ui/drawer";
const field="h-9 rounded border border-border bg-card px-3 text-xs";
export function AdvertisingChanges({records}:{records:CommandRecord[]}){
 const [before,setBefore]=useState(""),[after,setAfter]=useState(""),[filter,setFilter]=useState(""),[detail,setDetail]=useState<AdvertisingChange|null>(null);
 const ordered=[...records].filter(row=>(row.payload.input as AdvertisingSnapshot["input"]).kind==="keywords").sort((a,b)=>Date.parse(String(b.payload.collectedAt))-Date.parse(String(a.payload.collectedAt))),baseline=ordered.find(row=>row.id===before)??ordered[1],current=ordered.find(row=>row.id===after)??ordered[0];let rows:AdvertisingChange[]=[],error="";if(baseline&&current){try{rows=compareAdvertising(baseline.payload as unknown as AdvertisingSnapshot,current.payload as unknown as AdvertisingSnapshot);}catch(e){error=e instanceof Error?e.message:"Choose comparable snapshots.";}}
 const columns:Column<AdvertisingChange>[]=[{key:"keyword",header:"Keyword",render:row=><button className="text-left text-purple" onClick={()=>setDetail(row)}>{row.keyword}</button>},{key:"status",header:"Change",render:row=>row.status},{key:"fields",header:"Changed details",render:row=>row.changes.join(", ")||"—"},{key:"before",header:"Previous position",render:row=>row.before?.position??"—"},{key:"after",header:"Current position",render:row=>row.after?.position??"—"},{key:"url",header:"Landing page",render:row=><span className="block max-w-64 truncate">{row.after?.url??row.before?.url??"—"}</span>}];
 return <div className="space-y-3"><div className="flex flex-wrap gap-2">{[{label:"Advertising baseline",value:baseline?.id??"",set:setBefore},{label:"Advertising comparison",value:current?.id??"",set:setAfter}].map(control=><label key={control.label} className="text-xs">{control.label}<select aria-label={control.label} className={`${field} ml-2 max-w-full`} value={control.value} onChange={e=>control.set(e.target.value)}><option value="">Choose a saved date</option>{ordered.map(row=><option key={row.id} value={row.id}>{new Date(String(row.payload.collectedAt)).toLocaleString()}</option>)}</select></label>)}<select aria-label="Advertising change type" className={field} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All changes</option>{[...new Set(rows.map(row=>row.status))].map(value=><option key={value}>{value}</option>)}</select></div>{error&&<p role="alert" className="text-xs text-critical">{error}</p>}<DataTable rows={rows.filter(row=>!filter?row.status!=="Unchanged":row.status===filter)} columns={columns} rowKey={row=>row.keyword} exportName="advertising-changes" emptyLabel={ordered.length<2?"Save paid keyword collections on two different dates to compare changes.":"No changes match these dates and filters."}/><p className="text-[11px] text-muted">Missing keywords in partial collections are marked “not observed”. Index changes do not prove when an advertiser started or stopped a campaign.</p><Drawer open={!!detail} onClose={()=>setDetail(null)} title={detail?.keyword??"Advertising changes"}>{detail&&<div className="grid gap-4">{[{label:"Before",data:detail.before},{label:"After",data:detail.after}].map(item=><div key={item.label} className="rounded border border-border p-4"><p className="text-xs text-muted">{item.label}</p><h3 className="my-2 font-semibold">{item.data?.title??"No observed ad copy"}</h3><p className="text-sm">{item.data?.description??""}</p><p className="mt-2 break-all text-xs text-purple">{item.data?.url??"No observed landing page"}</p><p className="mt-2 text-xs">Ad position: {item.data?.position??"—"}</p></div>)}</div>}</Drawer></div>;
}
export function AdvertisingHistory({site,domain,location,language}:{site:string;domain:string;location:number;language:string}){
 const state=useJson<{records:CommandRecord[]}>(`/api/advertising/history?site=${site}`),[keyword,setKeyword]=useState(""),[from,setFrom]=useState(()=>new Date(Date.now()-180*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10)),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const records=state.data?.records.filter(row=>{const input=row.payload.input as {domain:string;locationCode:number;languageCode:string};return input.domain===domain&&input.locationCode===location&&input.languageCode===language;})??[],report=records.find(row=>row.id===selected)??records[0],snapshots=(report?.payload.snapshots??[]) as HistoricalAdSnapshot[],rows=snapshots.flatMap(snapshot=>snapshot.ads.length?snapshot.ads.map(ad=>({observedAt:snapshot.observedAt,...ad})):[{observedAt:snapshot.observedAt,type:"unobserved",position:null,domain:null,title:null,url:null,description:"No matching paid ad observed in this indexed SERP.",groupPosition:null}]);
 async function collect(){setBusy(true);setError("");try{const response=await fetch("/api/advertising/history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,domain,keyword,locationCode:location,languageCode:language,from,to})});const body=await response.json();if(!response.ok)throw new Error(body.error);setSelected(body.record.id);state.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not collect advertising history.");}finally{setBusy(false);}}
 return <div className="space-y-3"><div className="flex flex-wrap gap-2"><input aria-label="Historical advertising keyword" placeholder="Keyword to inspect" className={field} value={keyword} onChange={e=>setKeyword(e.target.value)}/><input aria-label="Advertising history from" type="date" className={field} value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="Advertising history to" type="date" className={field} value={to} onChange={e=>setTo(e.target.value)}/><Button size="sm" disabled={busy||!keyword.trim()} onClick={()=>void collect()}>{busy?"Collecting…":"Collect history · est. up to $0.003"}</Button><select aria-label="Saved advertising history" className={`${field} max-w-full`} value={report?.id??""} onChange={e=>setSelected(e.target.value)}><option value="">Open saved history</option>{records.map(row=><option key={row.id} value={row.id}>{String((row.payload.input as {keyword:string}).keyword)} · {new Date(row.createdAt).toLocaleString()}</option>)}</select></div>{(error||state.error)&&<p role="alert" className="text-xs text-critical">{error||state.error}</p>}{report&&<p className="text-xs font-semibold">{String((report.payload.input as {keyword:string}).keyword)} · {snapshots.length} indexed dates</p>}<DataTable rows={rows} columns={[{key:"date",header:"Observed date",render:row=>new Date(row.observedAt).toLocaleDateString(),sortValue:row=>row.observedAt},{key:"position",header:"Ad position",render:row=>row.groupPosition??"—"},{key:"copy",header:"Ad copy",render:row=><div className="max-w-lg"><strong>{row.title}</strong><p className="mt-1 text-xs text-muted">{row.description}</p></div>},{key:"url",header:"Landing page",render:row=>row.url?<a className="block max-w-72 break-all text-xs text-purple" href={row.url} target="_blank" rel="noreferrer">{row.url}</a>:"—"}]} rowKey={row=>`${row.observedAt}:${row.url}:${row.groupPosition}`} exportName="historical-ads" emptyLabel="No historical SERPs saved for this domain and database."/><p className="text-[11px] text-muted">Monthly indexed SERPs available within the last 12 months. Coverage varies by keyword and country. Blank dates are not evidence that a campaign was inactive; spend and targeting are not available.</p></div>;
}
