"use client";
import { useState } from "react";
import { useDomain } from "@/components/shell/domain-context";
import { useJson } from "@/lib/use-live";
import { Panel, stamp } from "@/components/command/shared";
import { Button } from "@/components/ui/primitives";
import { safeEvidenceUrl } from "@/lib/research-evidence";
import type { CommandRecord } from "@/lib/command-model";
import styles from "@/components/command/command.module.css";
type Review = { reviewId: string; comment?: string; starRating: string; updateTime?: string; reviewReply?: { comment: string } };
export function BusinessManager({ reviewsOnly = false }: { reviewsOnly?: boolean }) { const { activeDomain } = useDomain(); return activeDomain ? <Manager key={activeDomain.id} site={activeDomain.id} reviewsOnly={reviewsOnly} /> : null; }
function Manager({ site, reviewsOnly }: { site: string; reviewsOnly: boolean }) {
  const state = useJson<{ businesses: { id: string; name: string }[]; records: CommandRecord[]; connected: boolean }>(`/api/business-management?site=${site}`), [businessId, setBusinessId] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState(""), [reviewId, setReviewId] = useState(""), [reply, setReply] = useState(""), [title, setTitle] = useState(""), [phone, setPhone] = useState(""), [website, setWebsite] = useState(""), [sourceUrl, setSourceUrl] = useState(""), [observed, setObserved] = useState({ name: "", address: "", phone: "" }), [confirmProfile, setConfirmProfile] = useState(false);
  const selected = businessId || state.data?.businesses[0]?.id || "", rows = state.data?.records ?? [], profile = rows.find((r) => r.kind === "workspace_business" && r.recordKey === selected), reviews = rows.find((r) => r.kind === "workspace_business_reviews" && r.recordKey === selected), draft = rows.find((r) => r.kind === "workspace_reply_draft" && r.payload.businessId === selected && r.payload.reviewId === reviewId);
  async function act(action: string) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/business-management", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ site, action, businessId: selected, ...(action === "profile" ? { title, phone, website } : action.startsWith("reply_") ? { reviewId, reply } : action === "listing" ? { sourceUrl, observed } : {}) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setMessage(body.message); setConfirmProfile(false); state.refresh(); } catch (error) { setError(error instanceof Error ? error.message : "Business request failed."); } finally { setBusy(false); } }
  function choose(id: string) { setBusinessId(id); setReviewId(""); setReply(""); setTitle(""); setPhone(""); setWebsite(""); setConfirmProfile(false); setMessage(""); setError(""); }
  return <Panel title={reviewsOnly ? "Review management" : "Business profiles, review replies and listing consistency"} description="Manage owned Google profiles and record directory checks alongside the same business."><div className="space-y-4 p-4"><div className="flex flex-wrap items-center gap-2"><select aria-label="Business to manage" className={`${styles.field} max-w-sm`} value={selected} onChange={(e) => choose(e.target.value)}><option value="">Choose a saved business</option>{state.data?.businesses.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select><Button size="sm" disabled={busy || !selected || !state.data?.connected} onClick={() => void act("connect")}>{profile ? "Refresh Google profile" : "Link matching Google profile"}</Button><Button size="sm" disabled={busy || !profile || !state.data?.connected} onClick={() => void act("refresh")}>Load owned reviews</Button></div>{!state.data?.connected && <p className="text-xs text-muted">Google Business Profile authorisation is required for profile changes and publishing replies. DataForSEO review analysis works separately.</p>}{profile && <p className="text-xs text-muted">Profile matched by Place ID · checked {stamp(profile.updatedAt)}. Public listing changes are submitted to Google and may require review.</p>}{state.error && <p role="alert" className="text-xs text-critical">Business evidence could not load. <button className="underline" onClick={state.refresh}>Retry</button></p>}{message && <p role="status" className="text-xs text-success">{message}</p>}{error && <p role="alert" className="text-xs text-critical">{error}</p>}
    <details open={reviewsOnly || undefined}><summary className="cursor-pointer text-sm font-bold">Review and reply</summary><div className="mt-3 space-y-3"><p className="text-xs text-muted">Reviews checked {stamp(reviews?.updatedAt)} · {reviews?.payload.moreAvailable ? "More than 200 reviews; newest 200 loaded." : "Most recently updated reviews."}</p><select aria-label="Review to reply to" className={styles.field} value={reviewId} onChange={(e) => { setReviewId(e.target.value); const d = rows.find((r) => r.kind === "workspace_reply_draft" && r.payload.reviewId === e.target.value && r.payload.businessId === selected); setReply(String(d?.payload.reply ?? "")); }}><option value="">Choose a review</option>{(reviews?.payload.reviews as Review[] ?? []).map((r) => <option key={r.reviewId} value={r.reviewId}>{r.starRating} · {(r.comment ?? "Rating without text").slice(0, 160)}</option>)}</select>{reviewId && <><p className="whitespace-pre-wrap text-sm">{(reviews?.payload.reviews as Review[] ?? []).find((r) => r.reviewId === reviewId)?.comment}</p><label className={styles.label}>Your reply<textarea rows={5} className={styles.field} value={reply} onChange={(e) => setReply(e.target.value)} /></label><div className="flex gap-2"><Button size="sm" disabled={busy || !reply.trim()} onClick={() => void act("reply_draft")}>Save reply draft</Button><Button size="sm" variant="primary" disabled={busy || draft?.payload.reply !== reply || !state.data?.connected} onClick={() => void act("reply_publish")}>Publish this reply to Google</Button></div><p className="text-xs text-muted">Publishing replaces the existing owner reply, if one is present.</p></>}</div></details>
    {!reviewsOnly && <><details><summary className="cursor-pointer text-sm font-bold">Update Google listing</summary><div className="mt-3 space-y-3"><p className="text-xs text-muted">Current saved Google name: {String((profile?.payload.profile as { title?: string } | undefined)?.title ?? "Not linked")}. Review the latest public profile before submitting changes.</p><label className={styles.label}>Business name<input className={styles.field} value={title} onChange={(e) => { setTitle(e.target.value); setConfirmProfile(false); }} /></label><label className={styles.label}>Phone<input className={styles.field} value={phone} onChange={(e) => { setPhone(e.target.value); setConfirmProfile(false); }} /></label><label className={styles.label}>Website<input className={styles.field} value={website} onChange={(e) => { setWebsite(e.target.value); setConfirmProfile(false); }} /></label>{confirmProfile && <p className="rounded border border-warning/30 p-3 text-sm">Submit these exact changes to Google: <strong>{title}</strong> · {phone} · {website}</p>}<Button size="sm" variant="primary" disabled={busy || !profile || !title || !phone || !website || !state.data?.connected} onClick={() => confirmProfile ? void act("profile") : setConfirmProfile(true)}>{confirmProfile ? "Publish these changes to Google" : "Review profile changes"}</Button></div></details>
    <details><summary className="cursor-pointer text-sm font-bold">Directory consistency checks</summary><div className="mt-3 space-y-3"><label className={styles.label}>Public listing URL<input className={styles.field} value={sourceUrl} onChange={(e) => setSourceUrl(e.target.value)} /></label>{(["name", "address", "phone"] as const).map((field) => <label key={field} className={styles.label}>Observed {field}<input className={styles.field} value={observed[field]} onChange={(e) => setObserved({ ...observed, [field]: e.target.value })} /></label>)}<p className="text-xs text-muted">Record details you verified on the linked directory. Comparisons normalise punctuation and spacing; differences need review, not automatic correction.</p><Button size="sm" disabled={busy || !selected || !sourceUrl} onClick={() => void act("listing")}>Save directory check</Button>{rows.filter((r) => r.kind === "workspace_listing" && r.payload.businessId === selected).map((r) => <div key={r.id} className="rounded border border-border p-3 text-xs"><a href={safeEvidenceUrl(r.payload.sourceUrl)} target="_blank" rel="noreferrer" className="break-all text-purple">{String(r.payload.sourceUrl)}</a><p className="text-muted">Manually checked {stamp(r.updatedAt)}</p>{(r.payload.comparison as { field: string; state: string }[]).map((c) => <span key={c.field} className="mr-3">{c.field}: {c.state}</span>)}</div>)}</div></details>
    </>}
  </div></Panel>;
}
