"use client";
import { ResearchHandoff } from "./research-handoff";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { ArrowUpRight, Download, RefreshCw, Search } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useDomain } from "@/components/shell/domain-context";
import { Button } from "@/components/ui/primitives";
import { Drawer } from "@/components/ui/drawer";
import { SiteFindingWorkDrawer, type SiteFinding } from "@/components/workflow/site-finding-work-drawer";
import { Panel, Empty, stamp } from "@/components/command/shared";
import { useJson } from "@/lib/use-live";
import { RESEARCH_FEATURES, compareEvidenceDates, money, researchFeature, safeEvidenceUrl, type EvidenceRow, type EvidenceTable, type ResearchFeature, type ResearchInput, type ResearchPayload, type ResearchRun } from "@/lib/research-evidence";
import styles from "@/components/command/command.module.css";

import { researchCanResume } from "@/lib/research-pagination";
type Payload = { runs: ResearchRun[]; defaults: { keywords: string[]; domains: string[]; businesses: { id: string; name: string; identified: boolean }[]; market: { label: string; location_code: number; language_code: string } }; canScan: boolean; canEdit: boolean; configured: boolean };
export function ResearchEvidencePanel({ features, title = "Research and opportunities", targetDomain, targetMarket, onExportReady }: { features: ResearchFeature[]; title?: string; targetDomain?: string; targetMarket?: ResearchInput["market"]; onExportReady?: (action: (() => void) | null) => void }) {
  const { activeDomain } = useDomain();
  const params = useSearchParams(), pathname = usePathname(), router = useRouter();
  const requested = params.get("feature") as ResearchFeature;
  const feature = features.includes(requested) ? requested : features[0]!;
  function setFeature(next: ResearchFeature) {
    const query = new URLSearchParams(params); query.set("feature", next);
    router.push(`${pathname}?${query}#research`, { scroll: false });
  }
  if (!activeDomain) return null;
  return <section id="research" className="min-w-0 scroll-mt-6">{features.length > 1 && <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="text-base font-bold text-ink">{title}</h2><nav aria-label={title} className="flex flex-wrap gap-1">{features.map((id) => <button key={id} onClick={() => setFeature(id)} aria-pressed={feature === id} className={`min-h-9 rounded-full border px-3 py-1 text-xs font-semibold ${feature === id ? "border-purple/30 bg-purple/10 text-purple" : "border-border bg-card text-muted"}`}>{researchFeature(id)?.title}</button>)}</nav></div>}<ResearchTool key={`${activeDomain.id}:${feature}`} site={activeDomain.id} siteName={activeDomain.name} siteHost={activeDomain.host} feature={feature} targetDomain={targetDomain} targetMarket={targetMarket} onExportReady={onExportReady} /></section>;
}

function ResearchTool({ site, siteName, siteHost, feature, targetDomain, targetMarket, onExportReady }: { site: string; siteName: string; siteHost: string; feature: ResearchFeature; targetDomain?: string; targetMarket?: ResearchInput["market"]; onExportReady?: (action: (() => void) | null) => void }) {
  const [historyOffset, setHistoryOffset] = useState(0), [maxRows, setMaxRows] = useState(1000);
  const state = useJson<Payload>(`/api/research?site=${encodeURIComponent(site)}&feature=${feature}&offset=${historyOffset}`, 0);
  const info = researchFeature(feature)!;
  const [open, setOpen] = useState(false), [keywords, setKeywords] = useState(""), [domains, setDomains] = useState(""), [businessId, setBusinessId] = useState(""), [platform, setPlatform] = useState<ResearchInput["platform"]>("google"), [device, setDevice] = useState<ResearchInput["device"]>("desktop");
  const [plan, setPlan] = useState<ResearchPayload | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""), [selected, setSelected] = useState("");
  const [path, setPath] = useState(""), [pathMode, setPathMode] = useState<"page" | "folder">("folder");
  const [finding, setFinding] = useState<SiteFinding | null>(null);
  const run = state.data?.runs.find((row) => row.id === selected) ?? state.data?.runs[0];
  const pending = state.data?.runs.some((row) => ["queued", "running", "waiting"].includes(row.status));
  const refresh = state.refresh;
  useEffect(() => { if (!pending) return; const timer = window.setInterval(() => { if (document.visibilityState === "visible") refresh(); }, 7000); return () => clearInterval(timer); }, [pending, refresh]);
  const input = (): ResearchInput => ({ feature, maxRows, market: targetMarket, keywords: keywords.split("\n").map((v) => v.trim()).filter(Boolean), domains: domains.split("\n").map((v) => v.trim()).filter(Boolean), businessId: businessId || undefined, platform, device, path: path || undefined, pathMode });
  async function action(action: string, extra: Record<string, unknown> = {}) {
    if (busy) return;
    setBusy(true); setError(""); setMessage("");
    try {
      const response = await fetch("/api/research", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ site, action, ...extra }) });
      const body = await response.json();
      if (!response.ok) throw new Error(body.error ?? "Research request failed.");
      if (action === "preview") setPlan(body.plan);
      else { setMessage(body.run ? "" : body.message); if (body.run) setSelected(body.run.id); setOpen(false); refresh(); }
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not complete this request."); }
    finally { setBusy(false); }
  }
  function configure() { const defaults = state.data?.defaults; setKeywords(feature === "keyword_bulk" ? defaults?.keywords[0] ?? "" : defaults?.keywords.join("\n") ?? ""); setDomains(targetDomain ?? defaults?.domains.join("\n") ?? siteHost); setBusinessId(defaults?.businesses.find((b) => b.identified)?.id ?? ""); setPlan(null); setError(""); setOpen(true); }
  function work(row: EvidenceRow, table: EvidenceTable) {
    if (!run) return;
    const ownUrl = safeEvidenceUrl(row.url), isOwn = ownUrl && (new URL(ownUrl).hostname.replace(/^www\./, "") === siteHost.replace(/^www\./, ""));
    setFinding({ key: `research:${feature}:${table.title}:${row.label}`.slice(0, 230), title: `${feature === "recovery" ? "Recover links to" : feature === "reviews" ? "Review customer feedback:" : "Plan improvement:"} ${row.label}`.slice(0, 200), module: info.title, executionType: feature === "recovery" ? "technical_task" : feature === "links" ? "link_prospect_list" : feature === "clusters" ? "keyword_page_map" : "content_brief", priorityScore: feature === "recovery" ? 80 : 65, pageMode: isOwn ? "existing_page" : "site_wide", targetUrl: isOwn ? ownUrl : null, targetKeywords: row.keywords, sourceUrl: `${info.home}${info.home.includes("?") ? "&" : "?"}site=${encodeURIComponent(site)}&feature=${feature}#research`, evidenceLabel: `DataForSEO · ${stamp(run.updatedAt)}`, sourceEvidence: { provider: "DataForSEO", runId: run.id, feature, collectedAt: run.updatedAt, market: run.payload.market, row, caveat: table.note } });
  }
  const report = run?.payload.report;
  useEffect(() => {
    onExportReady?.(report && run ? () => download(`${site}-${feature}.json`, JSON.stringify({ ...run, payload: { ...run.payload, lease: undefined } }, null, 2), "application/json") : null);
    return () => onExportReady?.(null);
  }, [onExportReady, report, run, site, feature]);
  return <><Panel title={info.title} description={info.description} actions={<div className="flex gap-2"><Button size="sm" aria-label="Reload saved research" disabled={state.loading} onClick={refresh}><RefreshCw className="h-3.5 w-3.5" /></Button><Button size="sm" variant="primary" disabled={!state.data?.canScan || !!pending} onClick={configure}>{pending ? "Collection active" : "Collect evidence"}</Button></div>}>
    {["keyword_bulk", "footprint"].includes(feature) && <label className="block px-4 py-3 text-xs font-semibold">Collection ceiling <select aria-label="Background collection ceiling" className="ml-2 rounded border border-border bg-card p-2" value={maxRows} onChange={e => { setMaxRows(Number(e.target.value)); setPlan(null); }}>{[1000,5000,10000,20000,50000].map(value => <option key={value} value={value}>{value.toLocaleString()} rows per target</option>)}</select></label>}
    {state.loading && !state.data && <Empty>Loading saved research…</Empty>}
    {state.error && <p role="alert" className={styles.empty}>Saved evidence could not load. <button className={styles.link} onClick={refresh}>Try again</button></p>}
    {error && !open && <p role="alert" className="p-4 text-sm text-critical">{error}</p>}{message && (!run || ["queued", "running", "waiting"].includes(run.status)) && <p role="status" className="px-4 py-2 text-sm text-success">{message}</p>}
    {(historyOffset > 0 || state.data?.runs.length === 12) && <div className="flex gap-2 px-4 py-2"><Button size="sm" disabled={!historyOffset} onClick={() => { setSelected(""); setHistoryOffset(Math.max(0, historyOffset - 12)); }}>Newer collections</Button><Button size="sm" disabled={state.data?.runs.length !== 12} onClick={() => { setSelected(""); setHistoryOffset(historyOffset + 12); }}>Older collections</Button></div>}
    {!run && state.data && <Empty>No collection yet. Review the selected inputs and estimated cost before collecting. <span className="block mt-1">Saved websites and earlier scans are retained.</span></Empty>}
    {run && <><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><div className="space-y-1"><label className="text-xs font-semibold">Saved collection <select aria-label="Saved collection" className="ml-2 max-w-full rounded border border-border bg-card p-1 text-xs" value={run.id} onChange={(event) => setSelected(event.target.value)}>{state.data?.runs.map((row) => <option key={row.id} value={row.id}>{stamp(row.createdAt)} · {row.status}</option>)}</select></label><p className="text-xs text-muted">{feature === "countries" ? "All returned countries and languages" : `${run.payload.market.label} · ${run.payload.market.languageCode}`} · {run.payload.units.filter((u) => u.status === "completed").length}/{run.payload.units.length} requests completed · {money(run.payload.units.reduce((sum, u) => sum + (u.costUsd ?? 0), 0))} recorded cost</p><p className="text-xs text-muted">Last activity {stamp(run.updatedAt)} · Evidence collected {stamp(run.payload.units.map((u) => u.collectedAt).filter((v): v is string => !!v).sort().at(-1))}</p></div><div className="flex flex-wrap gap-2">{["failed", "cancelled"].includes(run.status) && researchCanResume(run.payload.units) && <Button size="sm" disabled={busy || !state.data?.canScan} onClick={() => void action("resume", { id: run.id })}>Resume saved progress</Button>}{["queued", "waiting"].includes(run.status) && <Button size="sm" disabled={busy || !state.data?.canScan} onClick={() => void action("continue", { id: run.id, input: run.payload.input })}>Check / continue</Button>}{["queued", "running", "waiting"].includes(run.status) && <Button size="sm" disabled={busy || !state.data?.canScan} onClick={() => void action("cancel", { id: run.id })}>Stop collection</Button>}{report && <Button size="sm" onClick={() => download(`${site}-${feature}-${run.createdAt.slice(0, 10)}.json`, JSON.stringify({ ...run, payload: { ...run.payload, lease: undefined } }, null, 2), "application/json")}><Download className="h-3.5 w-3.5" />Export evidence</Button>}</div></div>
    {run.status === "completed" && <p role="status" className="px-4 py-2 text-sm text-success">Collection complete. Results saved.</p>}
    {run.status === "waiting" && <p role="status" className="p-4 text-sm text-muted">Reviews are processing at DataForSEO. The saved task will be checked by the worker; “Check / continue” uses the same task without purchasing it again.</p>}
    {run.status === "queued" && <p role="status" className="p-4 text-sm text-muted">Queued for collection. Completed requests are saved as the worker progresses.</p>}
    {run.payload.error && <p role="alert" className="p-4 text-sm text-critical">{run.payload.error} Completed evidence is retained. An uncertain request is not retried automatically.</p>}
    {report?.notes.map((note, i) => <p key={i} className="px-4 py-2 text-xs text-muted">{note}</p>)}
    {report && state.data?.canEdit && <div className="flex justify-end p-3"><ResearchHandoff keywords={[...new Set(report.tables.flatMap(t=>t.rows.flatMap(r=>r.keywords??[])))].slice(0,100)} evidence={{runId:run.id,feature,market:run.payload.market,collectedAt:run.updatedAt}} sourceUrl={`${info.home}${info.home.includes("?")?"&":"?"}site=${site}&feature=${feature}#research`}/></div>}
    {!!report?.series.length && <SeriesView series={report.series} />}
    {report?.tables.map((table, index) => <EvidenceTableView key={`${run.id}:${index}`} table={table} onWork={state.data?.canEdit ? (row) => work(row, table) : undefined} />)}
    {run.status === "completed" && !report?.tables.some((table) => table.rows.length) && <Empty>No matching records were returned for this collection. Try a different query or inspect coverage; missing evidence is not treated as zero performance.</Empty>}
    </>}
  </Panel>
  <Drawer open={open} onClose={() => setOpen(false)} title={`Collect ${info.title.toLowerCase()}`} subtitle={siteName} footer={<div className="flex justify-end gap-2"><Button onClick={() => setOpen(false)}>Cancel</Button>{plan ? <Button variant="primary" disabled={busy || !state.data?.configured} onClick={() => void action("collect", { input: plan.input, approvedEstimate: plan.estimateUsd })}>{busy ? "Queuing…" : `Collect · estimated ${money(plan.estimateUsd)}`}</Button> : <Button variant="primary" disabled={busy} onClick={() => void action("preview", { input: input() })}>{busy ? "Checking…" : "Review cost"}</Button>}</div>}>
    <div className="space-y-4"><p className="text-sm text-muted">{feature === "countries" ? "All available countries and languages" : `${targetMarket?.label ?? state.data?.defaults.market.label} · ${targetMarket?.languageCode ?? state.data?.defaults.market.language_code}`}. Website and $200 monthly portfolio limits apply.</p>
    {info.input === "keywords" && <label className={styles.label}>Keywords, one per line (maximum 100)<textarea className={styles.field} rows={8} value={keywords} onChange={(event) => { setKeywords(event.target.value); setPlan(null); }} /></label>}
    {info.input === "domains" && <label className={styles.label}>Domains, one per line (maximum 4)<textarea className={styles.field} rows={4} value={domains} onChange={(event) => { setDomains(event.target.value); setPlan(null); }} /></label>}
    {feature === "footprint" && <label className={styles.label}>Optional page or subfolder path<input className={styles.field} placeholder="/guides" value={path} onChange={(e) => { setPath(e.target.value); setPlan(null); }} /><select className={styles.field} value={pathMode} onChange={(e) => { setPathMode(e.target.value as "page" | "folder"); setPlan(null); }}><option value="folder">This folder and its pages</option><option value="page">This exact page</option></select><span className="text-xs text-muted">Path research collects ranking keywords for that path; leading-page totals are available for full-domain research.</span></label>}
    {feature === "mentions" && <label className={styles.label}>AI platform<select className={styles.field} value={platform} onChange={(event) => { setPlatform(event.target.value as ResearchInput["platform"]); setPlan(null); }}><option value="google">Google AI answers</option><option value="chat_gpt" disabled={state.data?.defaults.market.location_code !== 2840}>ChatGPT (US index only)</option></select></label>}
    {["clusters", "questions"].includes(feature) && <label className={styles.label}>Search device<select className={styles.field} value={device} onChange={(event) => { setDevice(event.target.value as ResearchInput["device"]); setPlan(null); }}><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select></label>}
    {info.input === "business" && <label className={styles.label}>Business<select className={styles.field} value={businessId} onChange={(event) => { setBusinessId(event.target.value); setPlan(null); }}><option value="">Choose a business</option>{state.data?.defaults.businesses.map((business) => <option key={business.id} value={business.id} disabled={!business.identified}>{business.name}{!business.identified ? " · Place ID needed" : ""}</option>)}</select><Link href={`/local-seo?site=${site}`} className={styles.link}>Manage local businesses</Link></label>}
    {plan && <div className="space-y-2 rounded-lg border border-purple/20 bg-purple/5 p-4"><h3 className="font-bold">Estimated {money(plan.estimateUsd)} per collection</h3><p className="text-sm">{plan.units.length} provider requests. Actual returned costs are recorded; larger results remain bounded by this plan.</p>{plan.notes.map((note, i) => <p key={i} className="text-xs text-muted">{note}</p>)}<p className="text-xs text-muted">No recurring spending is enabled by this action.</p></div>}
    {!state.data?.configured && <p className="text-sm text-warning">A live DataForSEO connection is needed to collect. Paid research is disabled in preview environments.</p>}
    {error && <p role="alert" className="text-sm text-critical">{error}</p>}
    </div>
  </Drawer><SiteFindingWorkDrawer finding={finding} siteSlug={site} siteName={siteName} onClose={() => setFinding(null)} /></>;
}

function SeriesView({ series }: { series: NonNullable<ResearchPayload["report"]>["series"] }) {
  const [chosen, setChosen] = useState(0), item = series[chosen] ?? series[0]!;
  const [from, setFrom] = useState(""), [to, setTo] = useState("");
  const first = item.points.some((p) => p.date === from) ? from : item.points[0]?.date ?? "";
  const last = item.points.some((p) => p.date === to) ? to : item.points.at(-1)?.date ?? "";
  const comparison = compareEvidenceDates(item, first, last);
  const format = (value: number | null) => value == null ? "Not reported" : value.toLocaleString(undefined, { maximumFractionDigits: 1 });
  return <div className="border-b border-border p-4"><label className="text-xs font-semibold">Trend <select className="ml-2 max-w-[70%] rounded border border-border bg-card p-1" value={chosen} onChange={(event) => setChosen(Number(event.target.value))}>{series.map((row, i) => <option value={i} key={i}>{row.label}</option>)}</select></label><p className="my-2 text-xs text-muted">{item.unit} · missing periods are left empty</p><div className="my-3 flex flex-wrap items-center gap-3 rounded-lg bg-purple/5 p-3 text-xs"><label>From <select aria-label="Compare from date" className="ml-1 rounded border border-border bg-card p-1" value={first} onChange={(e) => setFrom(e.target.value)}>{item.points.map((p) => <option key={p.date}>{p.date}</option>)}</select></label><label>To <select aria-label="Compare to date" className="ml-1 rounded border border-border bg-card p-1" value={last} onChange={(e) => setTo(e.target.value)}>{item.points.map((p) => <option key={p.date}>{p.date}</option>)}</select></label><span>{format(comparison.before)} → {format(comparison.after)} {item.unit}</span><strong>{comparison.change == null ? "Change unavailable" : `${comparison.change > 0 ? "+" : ""}${format(comparison.change)} change`}{comparison.percent == null ? "" : ` (${comparison.percent > 0 ? "+" : ""}${format(comparison.percent)}%)`}</strong></div><div className="h-44" role="img" aria-label={`${item.label}: ${item.unit}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={item.points} accessibilityLayer margin={{ left: -10, right: 8, top: 5, bottom: 5 }}><CartesianGrid stroke="rgb(var(--border))" vertical={false} /><XAxis dataKey="date" tick={{ fontSize: 10 }} minTickGap={60} /><YAxis tick={{ fontSize: 10 }} /><Tooltip contentStyle={{ background: "rgb(var(--card))", borderColor: "rgb(var(--border))" }} /><Line dataKey="value" name={item.unit} stroke="var(--chart-orange)" dot={false} connectNulls={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></div></div>;
}
function EvidenceTableView({ table, onWork }: { table: EvidenceTable; onWork?: (row: EvidenceRow) => void }) {
  const [query, setQuery] = useState(""), [column, setColumn] = useState(""), [min, setMin] = useState(""), [max, setMax] = useState(""), [page, setPage] = useState(0), [detail, setDetail] = useState<EvidenceRow | null>(null);
  const numeric = table.columns.filter((column) => table.rows.some((row) => typeof row.values[column] === "number"));
  const filtered = table.rows.filter((row) => `${row.label} ${row.url ?? ""} ${Object.values(row.values).join(" ")}`.toLowerCase().includes(query.toLowerCase()) && (!column || (!min && !max) || (typeof row.values[column] === "number" && (!min || Number(row.values[column]) >= Number(min)) && (!max || Number(row.values[column]) <= Number(max)))));
  const current = Math.min(page, Math.max(0, Math.ceil(filtered.length / 20) - 1));
  return <div className="border-t border-border"><div className="space-y-2 p-4"><h3 className="text-sm font-bold text-ink">{table.title}</h3>{table.note && <p className="text-xs leading-relaxed text-muted">{table.note}</p>}<div className="flex flex-wrap gap-2"><label className="flex min-w-40 flex-1 items-center gap-2 rounded border border-border px-2"><Search className="h-3.5 w-3.5 text-muted" /><input aria-label={`Filter ${table.title}`} placeholder="Filter rows, URLs or anchors" className="h-9 min-w-0 flex-1 bg-transparent text-xs outline-none" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} /></label>{numeric.length > 0 && <><select aria-label="Numeric filter" className="max-w-48 rounded border border-border bg-card px-2 text-xs" value={column} onChange={(event) => { setColumn(event.target.value); setPage(0); }}><option value="">Filter a metric</option>{numeric.map((item) => <option key={item}>{item}</option>)}</select>{column && <><input aria-label="Minimum value" type="number" placeholder="Min" className="w-20 rounded border border-border bg-card px-2 text-xs" value={min} onChange={(event) => { setMin(event.target.value); setPage(0); }} /><input aria-label="Maximum value" type="number" placeholder="Max" className="w-20 rounded border border-border bg-card px-2 text-xs" value={max} onChange={(event) => { setMax(event.target.value); setPage(0); }} /></>}</>}
    <Button size="sm" onClick={() => download("research-evidence.csv", toCsv([ ["Item", "URL", ...table.columns], ...filtered.map((row) => [row.label, row.url ?? "", ...table.columns.map((column) => row.values[column] ?? "")]) ]), "text/csv;charset=utf-8")}><Download className="h-3.5 w-3.5" />CSV</Button></div><p className="text-xs text-muted">{filtered.length} matching / {table.rows.length} saved{table.total != null ? ` / ${table.total.toLocaleString()} provider matches` : ""}</p></div>
    {filtered.length ? <div className="overflow-x-auto"><table className={styles.table}><thead><tr><th>Evidence</th>{table.columns.map((column) => <th key={column}>{column}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.slice(current * 20, (current + 1) * 20).map((row, i) => <tr key={`${row.id}:${i}`}><td className="min-w-48 max-w-96"><button className="line-clamp-3 text-left font-medium hover:text-purple" onClick={() => setDetail(row)}>{row.label || "Untitled evidence"}</button></td>{table.columns.map((column) => <td key={column} className="max-w-72 whitespace-normal break-words">{typeof row.values[column] === "number" ? row.values[column].toLocaleString(undefined, { maximumFractionDigits: 2 }) : row.values[column] ?? "—"}</td>)}<td><div className="flex gap-2"><Button size="sm" onClick={() => setDetail(row)}>Inspect</Button>{onWork && <Button size="sm" onClick={() => onWork(row)}>Create work</Button>}</div></td></tr>)}</tbody></table></div> : <Empty>No matching evidence in this collection.</Empty>}
    {filtered.length > 20 && <div className="flex items-center justify-end gap-3 p-3 text-xs"><Button size="sm" disabled={current === 0} onClick={() => setPage(current - 1)}>Previous</Button><span>Page {current + 1} of {Math.ceil(filtered.length / 20)}</span><Button size="sm" disabled={(current + 1) * 20 >= filtered.length} onClick={() => setPage(current + 1)}>Next</Button></div>}
    <Drawer open={!!detail} onClose={() => setDetail(null)} title="Saved evidence" subtitle={table.title}>{detail && <div className="space-y-4"><h3 className="break-words text-base font-bold">{detail.label}</h3>{detail.url && <a className="inline-flex break-all text-sm text-purple" href={safeEvidenceUrl(detail.url)} target="_blank" rel="noreferrer">Open source <ArrowUpRight className="h-4 w-4 shrink-0" /></a>}<dl className="space-y-2">{Object.entries(detail.values).map(([key, value]) => <div key={key}><dt className="text-xs font-bold text-muted">{key}</dt><dd className="break-words text-sm">{value ?? "Not reported"}</dd></div>)}</dl>{detail.detail && <p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{detail.detail}</p>}{Array.isArray(detail.evidence?.sources) && <div className="space-y-2">{(detail.evidence.sources as { title?: string; url?: string }[]).filter((source) => safeEvidenceUrl(source.url)).map((source, index) => <a key={index} href={safeEvidenceUrl(source.url)} target="_blank" rel="noreferrer" className="block break-all text-sm text-purple">{source.title || source.url}</a>)}</div>}<p className="text-xs text-muted">{table.note}</p>{onWork && <Button variant="primary" onClick={() => { onWork(detail); setDetail(null); }}>Create work from this evidence</Button>}</div>}</Drawer>
  </div>;
}
function download(name: string, data: string, type: string) { const url = URL.createObjectURL(new Blob([data], { type })), link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function toCsv(rows: (string | number)[][]) { return rows.map((row) => row.map((v) => { let text = String(v); if (/^[\s]*[=+@-]/.test(text)) text = `'${text}`; return `"${text.replace(/"/g, '""')}"`; }).join(",")).join("\r\n"); }
export function ResearchDirectory() { const { activeDomain } = useDomain(); if (!activeDomain) return null; return <Panel title="Additional research" description="Deeper tools live in their relevant website sections. Collection is optional and uses existing budgets."><div className="grid gap-2 p-4 sm:grid-cols-2 lg:grid-cols-3">{RESEARCH_FEATURES.map((item) => <Link key={item.id} href={`${item.home}${item.home.includes("?") ? "&" : "?"}site=${activeDomain.id}&feature=${item.id}#research`} className="rounded-lg border border-border p-3 text-xs font-semibold hover:border-purple/40 hover:bg-purple/5">{item.title}<ArrowUpRight className="ml-1 inline h-3 w-3" /></Link>)}</div></Panel>; }
