"use client";
import { useState } from "react";
import { useDomain } from "@/components/shell/domain-context";
import { useJson } from "@/lib/use-live";
import { Button, Card, StatusBadge } from "@/components/ui/primitives";
import { DataTable } from "@/components/ui/data-table";
import { UnsavedChanges, navigateSafely } from "@/components/ui/unsaved-changes";
import type { CommandRecord } from "@/lib/command-model";
import { downloadReport } from "@/lib/report-download";
const field="mt-1 w-full rounded border border-border bg-card p-2 text-sm";
type State={posts:CommandRecord[];campaigns:CommandRecord[];locations:{id:string;name:string;placeId:string|null}[];businessConnected:boolean;mailConnected:boolean};
export function LocalWorkflows({reviews=false}:{reviews?:boolean}) {const {activeDomain}=useDomain();return activeDomain?<Board key={`${activeDomain.id}:${reviews}`} site={activeDomain.id} reviews={reviews}/>:null;}
function Board({site,reviews}:{site:string;reviews:boolean}) {
 const state=useJson<State>(`/api/local-workflows?site=${site}`),kind=reviews?"review_campaigns":"local_posts";
 const [current,setCurrent]=useState<CommandRecord|null>(null),[editing,setEditing]=useState(false),[businessId,setBusinessId]=useState(""),[title,setTitle]=useState(""),[text,setText]=useState(""),[subject,setSubject]=useState("How was your experience?"),[recipients,setRecipients]=useState(""),[actionUrl,setActionUrl]=useState(""),[imageUrl,setImageUrl]=useState(""),[date,setDate]=useState(""),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[confirm,setConfirm]=useState(false);
 const records=reviews?state.data?.campaigns??[]:state.data?.posts??[],locked=!!current&&!['draft','paused'].includes(current.status);
 function open(row:CommandRecord|null){setCurrent(row);setBusinessId(String(row?.payload.businessId??state.data?.locations[0]?.id??""));setTitle(String(row?.payload.title??""));setText(String(row?.payload.summary??row?.payload.message??""));setSubject(String(row?.payload.subject??"How was your experience?"));setRecipients((row?.payload.recipients as string[]??[]).join("\n"));setActionUrl(String(row?.payload.actionUrl??""));setImageUrl(String(row?.payload.imageUrl??""));setDate("");setDirty(false);setConfirm(false);setEditing(true);setError("");}
 async function act(action:"save"|"schedule"|"pause"|"send") {setBusy(true);setError("");setMessage("");try{const payload=reviews?{businessId,title,subject,message:text,recipients:recipients.split(/[\n,;]/).map(value=>value.trim()).filter(Boolean)}:{businessId,title,summary:text,...(actionUrl?{actionUrl}:{}),...(imageUrl?{imageUrl}:{})};const response=await fetch("/api/local-workflows",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,kind,action,key:current?.recordKey,updatedAt:current?.updatedAt,...(action==="save"?{payload}:{}),...(action==="schedule"?{scheduledAt:new Date(date).toISOString()}:{})})});const body=await response.json();if(!response.ok)throw new Error(body.error);if(body.record)setCurrent(body.record);setDirty(false);setConfirm(false);setMessage(body.message);state.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save workflow.");}finally{setBusy(false);}}
 const change=()=>{setDirty(true);setConfirm(false);};
 return <Card className="space-y-4 p-4"><UnsavedChanges dirty={dirty} saving={busy} title="Unsaved local content" description="Save your draft before leaving, or discard your edits." onDiscard={()=>setDirty(false)}/><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{reviews?"Review request campaigns":"Google posts & publishing calendar"}</h2><p className="mt-1 text-xs text-muted">{reviews?"Prepare neutral requests for customer feedback, review every recipient, then send individual emails from your connected mailbox.":"Save updates for your verified business location. Schedule only the exact saved copy after reviewing it."}</p></div><Button size="sm" onClick={()=>navigateSafely(()=>open(null))}>{reviews?"Create campaign":"Create post"}</Button></div>
 {!state.loading&&!state.data?.locations.length&&<p className="rounded bg-purple/5 p-3 text-sm">Add a business location and its Google Place ID first. <a className="text-purple underline" href={`/local-seo?site=${site}&view=overview`}>Open location setup</a></p>}
 <p className="text-xs text-muted">{reviews?(state.data?.mailConnected?"Review-request mailbox configured.":"Mailbox connection required to send. Drafts can be prepared after adding a location."):(state.data?.businessConnected?"Google Business Profile account configured; link the matching location above.":"Connect Google Business Profile to publish. Saving a draft does not publish it.")} <a className="text-purple" href={`/sites/${site}/settings`}>Connection settings →</a></p>
 {(error||state.error)&&<p role="alert" className="text-sm text-critical">{error||state.error}</p>}{message&&<p role="status" className="text-sm text-success">{message}</p>}
 {editing&&<div className="grid gap-4 rounded border border-border bg-workspace/20 p-4 lg:grid-cols-2"><div className="space-y-3"><label className="block text-xs">Business location<select className={field} value={businessId} disabled={locked} onChange={e=>{setBusinessId(e.target.value);change();}}><option value="">Choose location</option>{state.data?.locations.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="block text-xs">{reviews?"Campaign name":"Internal post title"}<input className={field} value={title} disabled={locked} onChange={e=>{setTitle(e.target.value);change();}} maxLength={160}/></label>{reviews&&<label className="block text-xs">Email subject<input className={field} value={subject} disabled={locked} onChange={e=>{setSubject(e.target.value);change();}} maxLength={150}/></label>}<label className="block text-xs">{reviews?"Message":"Post copy"}<textarea className={`${field} min-h-44`} value={text} disabled={locked} maxLength={reviews?5000:1500} onChange={e=>{setText(e.target.value);change();}}/></label>{reviews?<label className="block text-xs">Recipients, one email per line (maximum 50)<textarea className={`${field} min-h-24`} value={recipients} disabled={locked} onChange={e=>{setRecipients(e.target.value);change();}}/></label>:<><label className="block text-xs">Learn more URL (optional)<input type="url" className={field} value={actionUrl} disabled={locked} onChange={e=>{setActionUrl(e.target.value);change();}}/></label><label className="block text-xs">Public image URL (optional)<input type="url" className={field} value={imageUrl} disabled={locked} onChange={e=>{setImageUrl(e.target.value);change();}}/></label></>}
 <div className="flex flex-wrap gap-2"><Button variant="primary" disabled={busy||locked||!businessId||!title.trim()||!text.trim()} onClick={()=>void act("save")}>Save draft</Button><Button disabled={busy} onClick={()=>navigateSafely(()=>{setEditing(false);setDirty(false);})}>Close</Button><Button disabled={!text} onClick={()=>downloadReport(reviews?"review-request.txt":"google-post.txt",`${title}\n\n${text}${current?.payload.reviewUrl?`\n\n${current.payload.reviewUrl}`:""}`,"text/plain")}>Export copy</Button></div></div>
 <div className="space-y-4"><h3 className="text-sm font-semibold">Preview & delivery</h3><div className="rounded border border-border bg-card p-4"><strong className="text-sm">{reviews?subject:state.data?.locations.find(row=>row.id===businessId)?.name??"Business name"}</strong><p className="mt-3 whitespace-pre-wrap text-sm">{text||"Your draft preview will appear here."}</p>{Boolean(current?.payload.reviewUrl)&&<a className="mt-3 block break-all text-sm text-purple" href={String(current?.payload.reviewUrl)} target="_blank" rel="noreferrer">Share your honest experience</a>}{!reviews&&actionUrl&&<span className="mt-3 inline-block rounded border border-border px-3 py-2 text-xs">Learn more · {actionUrl}</span>}</div>{current&&<><StatusBadge label={current.status}/><p className="text-xs text-muted">Saved {new Date(current.updatedAt).toLocaleString()}</p>{Boolean(current.payload.error)&&<p role="alert" className="text-xs text-critical">{String(current.payload.error)}</p>}{!reviews&&['draft','paused'].includes(current.status)&&<label className="block text-xs">Publish at (your local time)<input className={field} type="datetime-local" value={date} onChange={e=>{setDate(e.target.value);setConfirm(false);}}/></label>}{current.status==="scheduled"&&<><p className="text-sm">Scheduled: {new Date(String(current.payload.scheduledAt)).toLocaleString()}. The hourly worker submits at or after this time.</p><Button disabled={busy} onClick={()=>void act("pause")}>Pause scheduled post</Button></>}{['draft','paused'].includes(current.status)&&<>{confirm&&<p className="rounded border border-warning/30 p-3 text-sm">{reviews?`Send this exact saved message to ${[...new Set(recipients.split(/[\n,;]/).map(value=>value.trim()).filter(Boolean))].length} recipients? Each receives a separate email.`:`Publish this saved copy to Google at or after ${date.replace("T"," ")}?`}</p>}<Button variant="primary" disabled={busy||dirty||(reviews?!state.data?.mailConnected:!state.data?.businessConnected||!date)} onClick={()=>confirm?void act(reviews?"send":"schedule"):setConfirm(true)}>{confirm?(reviews?"Send these review requests":"Confirm scheduled publication"):(reviews?"Review recipients & send":"Review publication schedule")}</Button>{dirty&&<p className="text-xs text-muted">Save changes before submitting.</p>}</>}{Array.isArray(current.payload.deliveries)&&<p className="text-xs text-muted">{current.payload.deliveries.length} recipients accepted by the mailbox. Review changes cannot be attributed to an individual email without additional consented tracking.</p>}</>}</div></div>}
 <DataTable rows={records} columns={[{key:"title",header:reviews?"Campaign":"Post",render:row=><button className="text-left text-purple" onClick={()=>navigateSafely(()=>open(row))}>{String(row.payload.title)}</button>},{key:"business",header:"Location",render:row=>state.data?.locations.find(item=>item.id===row.payload.businessId)?.name??"Location unavailable"},{key:"status",header:"Status",render:row=><StatusBadge label={row.status}/>},{key:"date",header:reviews?"Last update":"Scheduled / submitted",render:row=>new Date(String(row.payload.submittedAt??row.payload.scheduledAt??row.updatedAt)).toLocaleString()}]} rowKey={row=>row.id} exportName={reviews?"review-campaigns":"google-posts"}/></Card>;
}
