"use client";
import {useState} from "react";
import {useJson} from "@/lib/use-live";
import {Card,Button} from "@/components/ui/primitives";
import {DataTable} from "@/components/ui/data-table";
import type {CommandRecord} from "@/lib/command-model";
type Competitor={domain:string;commonKeywords:number|null;relevance:number|null;keywords:number|null;traffic:number|null;trafficCost:number|null;averagePosition:number|null};
export function OrganicCompetitors({site,domain,location,language,onDomain}:{site:string;domain:string;location:number;language:string;onDomain:(domain:string)=>void}){
 const state=useJson<{records:CommandRecord[]}>(`/api/organic-competitors?site=${site}`),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const record=state.data?.records.find(row=>{const input=row.payload.input as {domain:string;locationCode:number;languageCode:string};return input.domain===domain&&input.locationCode===location&&input.languageCode===language;});
 const rows=(record?.payload.rows??[]) as Competitor[];
 async function collect(){setBusy(true);setError("");try{const response=await fetch("/api/organic-competitors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,domain,locationCode:location,languageCode:language})});const body=await response.json();if(!response.ok)throw new Error(body.error);state.refresh();}catch(e){setError(e instanceof Error?e.message:"Competitors unavailable.");}finally{setBusy(false);}}
 return <Card className="p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold">Organic competitors: {domain}</h2><p className="mt-1 text-xs text-muted">{record?`Collected ${new Date(record.updatedAt).toLocaleString()}`:"Discover domains competing in the same organic search database."}</p></div><Button size="sm" disabled={busy||!domain} onClick={()=>void collect()}>{busy?"Discovering…":"Discover competitors · est. $0.03"}</Button></div>{(error||state.error)&&<p role="alert" className="mb-3 text-sm text-critical">{error||state.error}</p>}<DataTable rows={rows} rowKey={row=>row.domain} columns={[{key:"domain",header:"Domain",render:row=><button className="text-purple" onClick={()=>onDomain(row.domain)}>{row.domain}</button>},{key:"relevance",header:"Competition relevance",sortValue:row=>row.relevance??-1,render:row=>row.relevance?.toFixed(2)??"—"},{key:"common",header:"Common keywords",sortValue:row=>row.commonKeywords??-1,render:row=>row.commonKeywords?.toLocaleString()??"—"},{key:"keywords",header:"Organic keywords",sortValue:row=>row.keywords??-1,render:row=>row.keywords?.toLocaleString()??"—"},{key:"traffic",header:"Organic traffic est.",sortValue:row=>row.traffic??-1,render:row=>row.traffic?.toLocaleString()??"—"},{key:"cost",header:"Traffic cost (USD)",sortValue:row=>row.trafficCost??-1,render:row=>row.trafficCost?.toFixed(2)??"—"}]} searchKeys={row=>row.domain} exportName="organic-competitors" pageSize={30} emptyLabel="No competitor discovery has been saved for this domain and database."/></Card>;
}
