"use client";
import {useCallback,useEffect,useState} from "react";
import {useSearchParams,useRouter} from "next/navigation";
import {useDomain} from "@/components/shell/domain-context";
import {Card,Button} from "@/components/ui/primitives";
import {ReportTabs,ReportMetric} from "@/components/reports/report-layout";
import {DataTable,type Column} from "@/components/ui/data-table";
import {ResearchEvidencePanel} from "./evidence-panel";
import {OrganicCompetitors} from "./organic-competitors";
import {MarketSelector} from "./market-selector";
import {ResearchHandoff} from "./research-handoff";
import {DOMAIN_RESEARCH_ESTIMATE_USD} from "@/lib/research";
import type {CompetitorExplorerResult} from "@/platform/competitive-intelligence";
import {BarChart,Bar,ResponsiveContainer,CartesianGrid,XAxis,YAxis,Tooltip} from "recharts";
type Evidence={id:string;sourceValue:string;capturedAt:string;locationCode:number|null;languageCode:string|null;summary:CompetitorExplorerResult["overview"];evidence:{keywords:CompetitorExplorerResult["keywords"];pages:CompetitorExplorerResult["pages"];backlinks:CompetitorExplorerResult["backlinks"]}};
type Keyword=CompetitorExplorerResult["keywords"][number];
const field="h-9 rounded border border-border bg-card px-3 text-sm";
export function OrganicRankings(){const {activeDomain}=useDomain(),params=useSearchParams(),router=useRouter();const requestedDomain=params.get("domain"),view=params.get("view")??"overview",[target,setTarget]=useState(""),[history,setHistory]=useState<Evidence[]>([]),[result,setResult]=useState<Evidence|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[change,setChange]=useState(params.get("change")??"all"),[position,setPosition]=useState("all"),[intent,setIntent]=useState(""),[selected,setSelected]=useState<Set<string>>(new Set()),[location,setLocation]=useState(2840),[language,setLanguage]=useState("en"),[locationLabel,setLocationLabel]=useState("United States"),[comparison,setComparison]=useState<Evidence|null>(null);
 const setView=(next:string)=>{const query=new URLSearchParams(params);query.set("view",next);query.delete("feature");router.push(`/competitors?${query}`,{scroll:false});};
 const load=useCallback(async()=>{if(!activeDomain)return;try{const [research,legacy]=await Promise.all([fetch("/api/domain-research"),fetch(`/api/competitor-explorer?site=${activeDomain.id}`)]);const [body,old]=await Promise.all([research.json(),legacy.json()]);if(!research.ok)throw new Error(body.error);const older:Evidence[]=(old.runs??[]).map((row:CompetitorExplorerResult&{id:string})=>({id:`legacy:${row.id}`,sourceValue:row.targetHost,capturedAt:row.capturedAt,locationCode:null,languageCode:null,summary:row.overview,evidence:{keywords:row.keywords,pages:row.pages,backlinks:row.backlinks}}));setHistory([...(body.evidence??[]),...older].sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt)));}catch(e){setError(e instanceof Error?e.message:"Could not load research.");}},[activeDomain]);
 useEffect(()=>{setTarget(requestedDomain??activeDomain?.host??"");setLocation(activeDomain?.dataForSeoLocationCode??2840);setLanguage(activeDomain?.dataForSeoLanguageCode??"en");setLocationLabel(activeDomain?.primaryMarket||"Saved market");setResult(null);setComparison(null);void load();},[activeDomain,load,requestedDomain]);
 async function open(row:Evidence,compare=false){setBusy(true);setError("");try{if(row.id.startsWith("legacy:")){if(compare)setComparison(row);else{setResult(row);setTarget(row.sourceValue);setComparison(null);setSelected(new Set());}return;}const response=await fetch(`/api/domain-research?id=${row.id}`);const body=await response.json();if(!response.ok||!body.evidence)throw new Error(body.error??"Saved report unavailable.");if(compare)setComparison(body.evidence);else{setResult(body.evidence);setTarget(body.evidence.sourceValue);setComparison(null);setSelected(new Set());}}catch(e){setError(e instanceof Error?e.message:"Saved report unavailable.");}finally{setBusy(false);}}
 async function analyse(refresh=false){if(!activeDomain||!target.trim())return;const host=target.replace(/^https?:\/\//,"").replace(/^www\./,"").split("/")[0]!.toLowerCase();const saved=!refresh?history.find(row=>row.sourceValue===host&&row.locationCode===location&&row.languageCode===language):undefined;if(saved){await open(saved);return;}setBusy(true);setError("");try{const response=await fetch("/api/domain-research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetHost:host,locationCode:location,languageCode:language,locationLabel})});const body=await response.json();if(!response.ok)throw new Error(body.error);setResult(body.evidence);await load();}catch(e){setError(e instanceof Error?e.message:"Could not collect rankings.");}finally{setBusy(false);}}
 useEffect(()=>{if(!result){const saved=history.find(row=>row.sourceValue===(target||activeDomain?.host)&&row.locationCode===location&&row.languageCode===language);if(saved)void open(saved);}},[history,activeDomain?.host,location,language,result,target]);
 const previousWords=new Map(comparison?.evidence.keywords.map(row=>[row.keyword.toLowerCase(),row])??[]);
 const words=(result?.evidence.keywords??[]).map(row=>comparison?{...row,previousPosition:previousWords.get(row.keyword.toLowerCase())?.position??null,isNew:null,isLost:row.isLost===true&&previousWords.has(row.keyword.toLowerCase())?true:null}:row),isNew=(row:Keyword)=>row.isNew===true,isLost=(row:Keyword)=>row.isLost===true,delta=(row:Keyword)=>row.position!=null&&row.previousPosition!=null?row.previousPosition-row.position:null;
 const changes=(row:Keyword)=>change==="all"||change==="new"&&isNew(row)||change==="lost"&&isLost(row)||change==="improved"&&(delta(row)??0)>0||change==="declined"&&(delta(row)??0)<0;
 const filtered=words.filter(row=>changes(row)&&(!intent||row.intent===intent)&&(position==="all"||row.position!=null&&row.position<=Number(position)));
 const cols:Column<Keyword>[]=[{key:"select",header:"",render:row=><input type="checkbox" aria-label={`Select ${row.keyword}`} checked={selected.has(row.keyword)} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(row.keyword))next.delete(row.keyword);else next.add(row.keyword);return next;})}/>},{key:"keyword",header:"Keyword",sortValue:row=>row.keyword,render:row=>row.keyword},{key:"intent",header:"Intent",render:row=>row.intent??"—"},{key:"position",header:"Position",sortValue:row=>row.position??1000,render:row=>row.isLost?"Lost":row.position??"—"},{key:"change",header:"Change",sortValue:row=>delta(row)??0,render:row=>isNew(row)?"New":delta(row)==null?"—":<span className={(delta(row)??0)>0?"text-success":(delta(row)??0)<0?"text-critical":"text-muted"}>{(delta(row)??0)>0?"+":""}{delta(row)}</span>},{key:"traffic",header:"Traffic est.",sortValue:row=>row.traffic??-1,render:row=>row.traffic?.toLocaleString(undefined,{maximumFractionDigits:1})??"—"},{key:"volume",header:"Volume",sortValue:row=>row.volume??-1,render:row=>row.volume?.toLocaleString()??"—"},{key:"difficulty",header:"KD %",sortValue:row=>row.difficulty??-1,render:row=>row.difficulty??"—"},{key:"url",header:"URL",exportValue:row=>row.url,render:row=>row.url?<a className="block max-w-56 truncate text-purple" href={row.url} target="_blank" rel="noreferrer">{row.url}</a>:"—"},{key:"updated",header:"Updated",render:row=>(row.updatedAt??result?.capturedAt)?.slice(0,10)??"—"}];
 const pages=result?.evidence.pages??[],pageCols:Column<typeof pages[number]>[]=[{key:"url",header:"Page",exportValue:row=>row.url,render:row=><a href={row.url} className="block max-w-xl truncate text-purple" target="_blank" rel="noreferrer">{row.url}</a>},{key:"traffic",header:"Traffic est.",sortValue:row=>row.traffic??-1,render:row=>row.traffic?.toLocaleString(undefined,{maximumFractionDigits:1})??"—"},{key:"keywords",header:"Keywords",sortValue:row=>row.keywords??-1,render:row=>row.keywords?.toLocaleString()??"—"},{key:"cost",header:"Traffic cost (USD)",render:row=>row.trafficCost?.toFixed(2)??"—"}];
 const distribution=[{name:"1–3",min:1,max:3},{name:"4–10",min:4,max:10},{name:"11–20",min:11,max:20},{name:"21–50",min:21,max:50},{name:"51–100",min:51,max:100}].map(bucket=>({...bucket,count:words.filter(row=>row.position!=null&&row.position>=bucket.min&&row.position<=bucket.max&&!row.isLost).length}));
 return <div className="space-y-4 pb-8"><div className="border-b border-border py-4"><p className="mb-2 text-xs text-muted">SEO › Competitive Analysis</p><h1 className="text-xl font-bold">Organic Rankings{result&&`: ${result.sourceValue}`}</h1></div><div className="flex flex-wrap items-center gap-2"><input aria-label="Organic rankings domain" className={`${field} min-w-60 flex-1`} value={target} onChange={e=>setTarget(e.target.value)} placeholder="Enter a domain"/><Button variant="primary" disabled={busy||!target.trim()} onClick={()=>void analyse()}>{busy?"Loading…":"Analyze"}</Button><Button disabled={busy||!target.trim()} onClick={()=>void analyse(true)}>Refresh · ${DOMAIN_RESEARCH_ESTIMATE_USD.toFixed(2)}</Button><select aria-label="Saved ranking report" className={`${field} max-w-80`} value={result?.id??""} onChange={e=>{const row=history.find(item=>item.id===e.target.value);if(row)void open(row);}}><option value="">Saved reports</option>{history.map(row=><option key={row.id} value={row.id}>{row.sourceValue} · {row.capturedAt.slice(0,10)}</option>)}</select></div><MarketSelector location={location} language={language} disabled={busy} onChange={(code,lang,label)=>{setLocation(code);setLanguage(lang);setLocationLabel(label);setResult(null);setComparison(null);}}/><ReportTabs items={[{id:"overview",label:"Overview"},{id:"keywords",label:"Positions"},{id:"changes",label:"Position Changes"},{id:"competitors",label:"Competitors"},{id:"pages",label:"Pages"},{id:"research",label:"Historical & deeper research"}]} value={view} onChange={setView}/>{error&&<p role="alert" className="text-sm text-critical">{error}</p>}
 {view==="competitors"&&activeDomain?<OrganicCompetitors site={activeDomain.id} domain={result?.sourceValue??target} location={location} language={language} onDomain={host=>{setTarget(host);setResult(null);setView("overview");}}/>:view==="research"||params.has("feature")?<ResearchEvidencePanel features={["footprint","history"]}/>:result?<><p className="text-xs text-muted">Root domain · Database {result.locationCode==null?"not recorded in this legacy report":`${result.locationCode} / ${result.languageCode}`} · Collected {new Date(result.capturedAt).toLocaleString()}</p><Card className="grid grid-cols-2 divide-x divide-border lg:grid-cols-4"><ReportMetric label="Keywords" value={result.summary.organicKeywords}/><ReportMetric label="Traffic" value={result.summary.organicTraffic} note="Estimated organic visits"/><ReportMetric label="Traffic cost" value={result.summary.estimatedTrafficCost==null?null:`$${result.summary.estimatedTrafficCost.toFixed(2)}`}/><ReportMetric label="Ranking pages in sample" value={pages.length}/></Card>
 {view==="overview"&&<><div className="grid gap-4 lg:grid-cols-2"><Card className="p-4"><h2 className="mb-4 text-base font-semibold">Organic keyword distribution</h2><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={distribution}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="count" fill="var(--chart-orange)"/></BarChart></ResponsiveContainer></div><p className="text-xs text-muted">Distribution across {words.length} collected keywords.</p></Card><Card className="p-4"><h2 className="mb-4 text-base font-semibold">Position changes</h2><div className="grid grid-cols-2">{[["new","New",words.filter(isNew).length],["improved","Improved",words.filter(row=>(delta(row)??0)>0).length],["declined","Declined",words.filter(row=>(delta(row)??0)<0).length],["lost","Lost",words.filter(isLost).length]].map(([key,label,count])=><button key={key} className="text-left hover:bg-workspace" onClick={()=>{setChange(String(key));setView("changes");}}><ReportMetric label={String(label)} value={words.some(row=>row.isNew!=null||row.previousPosition!=null||row.isLost!=null)?Number(count):null} note="Provider change flags in collected sample"/></button>)}</div></Card></div><Card className="p-4"><h2 className="mb-3 text-base font-semibold">Top organic pages</h2><DataTable rows={pages.slice(0,5)} columns={pageCols} rowKey={row=>row.url}/><Button size="sm" className="mt-3" onClick={()=>setView("pages")}>View all pages</Button></Card></>}
 {view==="changes"&&<div className="flex flex-wrap items-center gap-3"><label className="text-xs">Compare with <select aria-label="Compare ranking dates" className={`${field} ml-2 max-w-80`} value={comparison?.id??""} onChange={e=>{const previous=history.find(row=>row.id===e.target.value);if(previous)void open(previous,true);else setComparison(null);}}><option value="">Provider previous indexed positions</option>{history.filter(row=>row.locationCode!=null&&row.id!==result.id&&row.sourceValue===result.sourceValue&&row.locationCode===result.locationCode&&row.languageCode===result.languageCode&&row.capturedAt<result.capturedAt).map(row=><option key={row.id} value={row.id}>{new Date(row.capturedAt).toLocaleString()}</option>)}</select></label>{comparison&&<span className="text-xs text-muted">{comparison.capturedAt.slice(0,10)} → {result.capturedAt.slice(0,10)} · only keywords observed in both samples have a calculated position change</span>}</div>}
 {view==="pages"?<Card className="p-4"><DataTable rows={pages} columns={pageCols} searchKeys={row=>row.url} rowKey={row=>row.url} pageSize={50} exportName="organic-pages"/></Card>:<Card className="p-4"><div className="mb-4 flex flex-wrap gap-2"><select aria-label="Position change filter" className={field} value={change} onChange={e=>setChange(e.target.value)}>{["all","new","improved","declined","lost"].map(value=><option key={value} value={value}>{value==="all"?"All changes":value}</option>)}</select><select aria-label="Ranking position range" className={field} value={position} onChange={e=>setPosition(e.target.value)}><option value="all">All positions</option>{[3,10,20,50,100].map(value=><option key={value} value={value}>Top {value}</option>)}</select><select aria-label="Organic search intent" className={field} value={intent} onChange={e=>setIntent(e.target.value)}><option value="">All intents</option>{["informational","commercial","transactional","navigational"].map(value=><option key={value}>{value}</option>)}</select><ResearchHandoff keywords={[...selected]} evidence={{domain:result.sourceValue,date:result.capturedAt,rows:words.filter(row=>selected.has(row.keyword))}} sourceUrl={`/competitors?site=${activeDomain?.id??""}`}/></div><DataTable rows={view==="overview"?filtered.slice(0,10):filtered} columns={cols} rowKey={row=>`${row.keyword}:${row.url}`} pageSize={50} searchKeys={row=>`${row.keyword} ${row.url??""}`} exportName="organic-rankings"/><p className="mt-3 text-xs leading-5 text-muted">{comparison?"Changes compare the two selected saved reports.":"Changes come from the provider’s prior indexed ranking."} Missing change flags remain unavailable. A row absent from a small saved collection is not counted as lost.</p></Card>}</>:<Card className="p-12 text-center"><h2 className="text-lg font-semibold">Analyse organic search performance</h2><p className="mt-2 text-sm text-muted">Enter your own domain or a competitor. Existing saved evidence is reused; new collections use the approved budget.</p></Card>}</div>;
}
