"use client";
import {useJson} from "@/lib/use-live";
import {useState} from "react";
import {Card,Button} from "@/components/ui/primitives";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Drawer} from "@/components/ui/drawer";
import {ResearchHandoff} from "./research-handoff";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from "recharts";
import type {CompetitorExplorerResult as Result} from "@/platform/competitive-intelligence";
type Saved={capturedAt:string;summary:Result["overview"];evidence?:{pages:Result["pages"]}};
type Report=Saved&{locationCode?:number|null;languageCode?:string|null;sourceValue:string;evidence:{keywords:Result["keywords"];pages:Result["pages"]}};
function host(url:string){try{return new URL(url).hostname;}catch{return "Unknown";}}
export function OrganicReportDetails({view,result,history,site}:{view:string;result:Report;history:Saved[];site:string}){
 const [selected,setSelected]=useState<string|null>(null);
 const words=result.evidence.keywords,pages=result.evidence.pages;
 const market={locationCode:result.locationCode??undefined,languageCode:result.languageCode??undefined};
 const context=new URLSearchParams({site,...(result.locationCode?{location:String(result.locationCode)}:{}),...(result.languageCode?{language:result.languageCode}:{})});
 const pageTrend=useJson<{history:{date:string;traffic:number|null}[]}>(selected&&result.locationCode?`/api/domain-research?${context}&domain=${encodeURIComponent(result.sourceValue)}&historyPage=${encodeURIComponent(selected)}`:null);
 const pageHistory=pageTrend.data?.history??[];
 const intents=[...new Set(words.map(row=>row.intent??"Not recorded"))].map(intent=>({intent,keywords:words.filter(row=>(row.intent??"Not recorded")===intent).length,traffic:words.filter(row=>(row.intent??"Not recorded")===intent).some(row=>row.traffic!=null)?words.filter(row=>(row.intent??"Not recorded")===intent).reduce((sum,row)=>sum+(row.traffic??0),0):null}));
 const subdomains=[...new Set(pages.map(row=>host(row.url)))].map(domain=>({domain,pages:pages.filter(row=>host(row.url)===domain).length,keywords:words.filter(row=>row.url&&host(row.url)===domain).length,traffic:pages.filter(row=>host(row.url)===domain).some(row=>row.traffic!=null)?pages.filter(row=>host(row.url)===domain).reduce((sum,row)=>sum+(row.traffic??0),0):null}));
 const groups=new Map<string,typeof words>();for(const row of words){const theme=row.keyword.toLowerCase().split(/\s+/).slice(0,2).join(" ");groups.set(theme,[...(groups.get(theme)??[]),row]);}
 const topics=[...groups].map(([topic,rows])=>({topic,keywords:rows.length,volume:rows.some(row=>row.volume!=null)?rows.reduce((sum,row)=>sum+(row.volume??0),0):null,traffic:rows.some(row=>row.traffic!=null)?rows.reduce((sum,row)=>sum+(row.traffic??0),0):null,rows})).sort((a,b)=>b.keywords-a.keywords);
 const columns:Column<typeof pages[number]>[]=[{key:"url",header:"Page",render:row=><button className="max-w-80 truncate text-left text-purple" onClick={()=>setSelected(row.url)}>{row.url}</button>},{key:"share",header:"Traffic share",render:row=>row.traffic!=null&&result.summary.organicTraffic?`${(row.traffic/result.summary.organicTraffic*100).toFixed(1)}%`:"—"},{key:"keywords",header:"Keywords",sortValue:row=>row.keywords??-1,render:row=>row.keywords??"—"},{key:"top",header:"Top keyword in sample",render:row=>[...words].filter(word=>word.url===row.url).sort((a,b)=>(b.traffic??0)-(a.traffic??0))[0]?.keyword??"Not in sample"},{key:"intent",header:"Intent",render:row=>[...new Set(words.filter(word=>word.url===row.url).map(word=>word.intent).filter(Boolean))].join(", ")||"—"},{key:"traffic",header:"Traffic estimate",sortValue:row=>row.traffic??-1,render:row=>row.traffic?.toFixed(1)??"—"}];
 return <>{view==="overview"&&<div className="grid gap-4 lg:grid-cols-2"><Card className="p-4"><h2 className="mb-3 font-semibold">Organic traffic trend</h2>{history.length>1?<div className="h-48"><ResponsiveContainer width="100%" height="100%"><LineChart data={[...history].reverse().map(row=>({date:row.capturedAt.slice(0,10),traffic:row.summary.organicTraffic,keywords:row.summary.organicKeywords}))}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Line dataKey="traffic" stroke="var(--chart-orange)" connectNulls={false}/></LineChart></ResponsiveContainer></div>:<p className="py-12 text-sm text-muted">A second saved report for the same country and language is needed to show change over time.</p>}<p className="text-xs text-muted">Saved observations in the same database; gaps are not interpolated.</p></Card><Card className="p-4"><h2 className="mb-3 font-semibold">Keywords by intent</h2><DataTable rows={intents} columns={[{key:"intent",header:"Intent",render:row=>row.intent},{key:"keywords",header:"Keywords",render:row=>row.keywords},{key:"traffic",header:"Traffic in sample",render:row=>(row.traffic==null?"—":row.traffic.toFixed(1))}]} exportName="organic-intent"/></Card></div>}
 {view==="pages"&&<Card className="p-4"><h2 className="mb-3 font-semibold">Page performance & keyword drill-down</h2><DataTable rows={pages} columns={columns} searchKeys={row=>row.url} exportName="organic-page-performance"/><p className="mt-3 text-xs text-muted">Traffic share uses the full domain estimate. Keyword details cover the collected sample. Open a page to inspect its ranking terms and plan content.</p></Card>}
 {view==="subdomains"&&<Card className="p-4"><h2 className="mb-3 font-semibold">Subdomain performance</h2><DataTable rows={subdomains} columns={[{key:"domain",header:"Subdomain",render:row=>row.domain},{key:"pages",header:"Pages in sample",render:row=>row.pages},{key:"keywords",header:"Keywords in sample",render:row=>row.keywords},{key:"traffic",header:"Estimated traffic in sample",render:row=>(row.traffic==null?"—":row.traffic.toFixed(1))}]} exportName="organic-subdomains"/></Card>}
 {view==="topics"&&<Card className="p-4"><h2 className="mb-2 font-semibold">Keyword topics</h2><p className="mb-4 text-xs text-muted">Phrase groups from the first two words of saved keywords. Use Keyword Strategy Builder for SERP-based topic clustering.</p><DataTable rows={topics} columns={[{key:"topic",header:"Topic",render:row=>row.topic},{key:"keywords",header:"Keywords",render:row=>row.keywords},{key:"volume",header:"Combined volume",render:row=>row.volume??"—"},{key:"traffic",header:"Traffic estimate",render:row=>row.traffic?.toFixed(1)??"—"},{key:"plan",header:"Content plan",render:row=><ResearchHandoff keywords={row.rows.map(word=>word.keyword)} evidence={{domain:result.sourceValue,topic:row.topic,date:result.capturedAt,market}} sourceUrl={`/competitors?site=${site}&view=topics`}/>}]} searchKeys={row=>row.topic} exportName="organic-topics"/></Card>}
 <Drawer open={selected!=null} onClose={()=>setSelected(null)} title="Page rankings" subtitle={selected??undefined}>{selected&&<div className="space-y-4"><a href={selected} target="_blank" rel="noreferrer" className="break-all text-purple">Open page</a><Card className="p-3"><h3 className="mb-2 text-sm font-semibold">Saved page traffic trend</h3>{pageTrend.error&&<p role="alert" className="text-xs text-critical">Page history could not load. <button onClick={pageTrend.refresh}>Retry</button></p>}{pageHistory.filter(row=>row.traffic!=null).length>1?<div className="h-40"><ResponsiveContainer width="100%" height="100%"><LineChart data={pageHistory}><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Line dataKey="traffic" stroke="var(--chart-orange)" connectNulls={false}/></LineChart></ResponsiveContainer></div>:<p className="text-xs text-muted">Two saved observations of this page in the same database are needed. Missing pages in a sample do not mean zero traffic.</p>}</Card><DataTable rows={words.filter(row=>row.url===selected)} columns={[{key:"keyword",header:"Keyword",render:row=><a className="text-purple" href={`/keyword-research?${context}&q=${encodeURIComponent(row.keyword)}`}>{row.keyword}</a>},{key:"position",header:"Position",render:row=>row.position??"—"},{key:"volume",header:"Volume",render:row=>row.volume??"—"}]} exportName="page-keywords"/><ResearchHandoff keywords={words.filter(row=>row.url===selected).map(row=>row.keyword)} evidence={{url:selected,domain:result.sourceValue,date:result.capturedAt,market}} sourceUrl={`/competitors?site=${site}&view=pages`}/><Button onClick={()=>setSelected(null)}>Close</Button></div>}</Drawer></>;
}
