"use client";
import { unmeasuredKeyword } from "@/lib/keyword-lists";
import {useSearchParams} from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/primitives";
import { Drawer } from "@/components/ui/drawer";
import { SiteFindingWorkDrawer, type SiteFinding } from "@/components/workflow/site-finding-work-drawer";
import { useDomain } from "@/components/shell/domain-context";
export function ResearchHandoff({keywords,evidence,sourceUrl}:{keywords:string[];evidence:Record<string,unknown>;sourceUrl:string}) {
  const {activeDomain}=useDomain(),params=useSearchParams();
  const projectId=typeof evidence.projectId==="string"?evidence.projectId:params.get("project")??undefined;
  const market=(evidence.market??{}) as {locationCode?:number;location_code?:number;languageCode?:string;language_code?:string;label?:string};
  const location=Number(market.locationCode??market.location_code??evidence.locationCode??(Number(params.get("location"))||activeDomain?.dataForSeoLocationCode||2840)),language=String(market.languageCode??market.language_code??evidence.languageCode??params.get("language")??activeDomain?.dataForSeoLanguageCode??"en");
  const unique=[...new Set(keywords.map(value=>value.trim()).filter(Boolean))].slice(0,100);
  const query=new URLSearchParams({site:activeDomain?.id??"",keywords:unique.join("\n"),location:String(location),language,locationLabel:market.label??String(location),device:String(evidence.device??"desktop")});
  if(projectId)query.set("project",projectId);
  const origin=new URL(sourceUrl,"https://seo-command.invalid");if(activeDomain)origin.searchParams.set("site",activeDomain.id);if(projectId)origin.searchParams.set("project",projectId);if(typeof evidence.scanId==="string")origin.searchParams.set("scan",evidence.scanId);origin.searchParams.set("location",String(location));origin.searchParams.set("language",language);const sourceHref=`${origin.pathname}${origin.search}${origin.hash}`;
  const [savedList,setSavedList]=useState("");
  async function saveList(){if(!activeDomain||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/keyword-research/scans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,siteSlug:activeDomain.id,label:`Research: ${unique[0]}`.slice(0,160),sourceType:"list",sourceValue:sourceHref.slice(0,500),seed:unique[0]?.slice(0,200),locationCode:location,languageCode:language,locationLabel:market.label??String(location),rows:unique.map(keyword=>({...unmeasuredKeyword(keyword),researchEvidence:evidence,sourceUrl:sourceHref}))})});const body=await response.json();if(!response.ok)throw new Error(body.error);setSavedList(body.scan.id);}catch(e){setError(e instanceof Error?e.message:"Could not save keyword list.");}finally{setBusy(false);}}
  const [open,setOpen]=useState(false),[title,setTitle]=useState(""),[path,setPath]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[finding,setFinding]=useState<SiteFinding|null>(null);
  async function save(){if(!activeDomain||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/topic-plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,site:activeDomain.id,label:title,keywords:[...new Set(keywords)].slice(0,100),targetUrl:path,sourceEvidence:{...evidence,projectId}})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Could not save topic plan.");setFinding({key:`topic:${body.id}`,title:`Create content for ${title}`,module:"Keyword research",executionType:"content_brief",priorityScore:65,pageMode:"new_page",plannedUrl:body.targetUrl,targetKeywords:keywords.slice(0,50),sourceUrl:sourceHref,evidenceLabel:"Saved research → topic plan",sourceEvidence:{...evidence,projectId,topicPlanId:body.id}});setOpen(false);}catch(e){setError(e instanceof Error?e.message:"Could not save topic plan.");}finally{setBusy(false);}}
  return <><div className="flex flex-wrap items-center gap-2">{activeDomain&&unique.length>0&&<><a className="rounded border border-border px-3 py-2 text-xs text-purple" href={`/keyword-research?${query}&view=overview&q=${encodeURIComponent(unique[0]??"")}`}>Keyword overview</a><Button size="sm" disabled={busy||!!savedList} onClick={()=>void saveList()}>{savedList?"List saved":"Save to keyword list"}</Button><a className="rounded border border-border px-3 py-2 text-xs text-purple" href={`/keyword-strategy?${query}&view=clusters`}>Build strategy</a><a className="rounded border border-border px-3 py-2 text-xs text-purple" href={`/keyword-research?${query}&view=discover&action=track`}>Track selected</a>{savedList&&<a className="text-xs text-purple" href={`/keyword-research?site=${activeDomain.id}&view=discover&scan=${savedList}${projectId?`&project=${projectId}`:""}`}>Open saved list</a>}</>}<Button size="sm" disabled={!activeDomain||!keywords.length} onClick={()=>{setTitle(keywords[0]??"");setOpen(true);}}>Plan content ({keywords.length})</Button></div>{error&&!open&&<p role="alert" className="text-xs text-critical">{error}</p>}<Drawer open={open} onClose={()=>setOpen(false)} title="Research → page plan → content brief" subtitle={activeDomain?.name} footer={<Button variant="primary" disabled={busy||!title.trim()||!path.trim()} onClick={()=>void save()}>Save topic and prepare brief</Button>}><div className="space-y-4"><p className="text-sm text-muted">Save the selected evidence to a page plan, then review the content brief’s owner and deadline. Tracking remains available from Keyword Research.</p><label className="block text-sm">Topic name<input className="mt-2 h-10 w-full rounded border border-border bg-card px-3" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block text-sm">Planned page<input className="mt-2 h-10 w-full rounded border border-border bg-card px-3" placeholder="/guides/topic" value={path} onChange={e=>setPath(e.target.value)}/></label><p className="text-xs text-muted">{keywords.join(" · ")}</p>{error&&<p role="alert" className="text-sm text-critical">{error}</p>}</div></Drawer>{activeDomain&&<SiteFindingWorkDrawer finding={finding} siteSlug={activeDomain.id} siteName={activeDomain.name} onClose={()=>setFinding(null)}/>}</>;
}
