"use client";
import { useState } from "react";
import { Button } from "@/components/ui/primitives";
import { Drawer } from "@/components/ui/drawer";
import { SiteFindingWorkDrawer, type SiteFinding } from "@/components/workflow/site-finding-work-drawer";
import { useDomain } from "@/components/shell/domain-context";
export function ResearchHandoff({keywords,evidence,sourceUrl}:{keywords:string[];evidence:Record<string,unknown>;sourceUrl:string}) {
  const {activeDomain}=useDomain();
  const [open,setOpen]=useState(false),[title,setTitle]=useState(""),[path,setPath]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[finding,setFinding]=useState<SiteFinding|null>(null);
  async function save(){if(!activeDomain||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/topic-plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site:activeDomain.id,label:title,keywords:[...new Set(keywords)].slice(0,100),targetUrl:path,sourceEvidence:evidence})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Could not save topic plan.");setFinding({key:`topic:${body.id}`,title:`Create content for ${title}`,module:"Keyword research",executionType:"content_brief",priorityScore:65,pageMode:"new_page",plannedUrl:body.targetUrl,targetKeywords:keywords.slice(0,50),sourceUrl,evidenceLabel:"Saved research → topic plan",sourceEvidence:{...evidence,topicPlanId:body.id}});setOpen(false);}catch(e){setError(e instanceof Error?e.message:"Could not save topic plan.");}finally{setBusy(false);}}
  return <><Button size="sm" disabled={!activeDomain||!keywords.length} onClick={()=>{setTitle(keywords[0]??"");setOpen(true);}}>Plan content ({keywords.length})</Button><Drawer open={open} onClose={()=>setOpen(false)} title="Research → page plan → content brief" subtitle={activeDomain?.name} footer={<Button variant="primary" disabled={busy||!title.trim()||!path.trim()} onClick={()=>void save()}>Save topic and prepare brief</Button>}><div className="space-y-4"><p className="text-sm text-muted">Save the selected evidence to a page plan, then review the content brief’s owner and deadline. Tracking remains available from Keyword Research.</p><label className="block text-sm">Topic name<input className="mt-2 h-10 w-full rounded border border-border bg-card px-3" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block text-sm">Planned page<input className="mt-2 h-10 w-full rounded border border-border bg-card px-3" placeholder="/guides/topic" value={path} onChange={e=>setPath(e.target.value)}/></label><p className="text-xs text-muted">{keywords.join(" · ")}</p>{error&&<p role="alert" className="text-sm text-critical">{error}</p>}</div></Drawer>{activeDomain&&<SiteFindingWorkDrawer finding={finding} siteSlug={activeDomain.id} siteName={activeDomain.name} onClose={()=>setFinding(null)}/>}</>;
}
