"use client";
import {useMemo,useState} from "react";
import {useJson} from "@/lib/use-live";
import type {CommandRecord} from "@/lib/command-model";
import type {SerpEvidence,SerpItem} from "@/lib/serp-evidence";
import {DataTable,type Column} from "@/components/ui/data-table";
import {Button,Card} from "@/components/ui/primitives";
const field="h-8 rounded border border-border bg-card px-2 text-xs";
export function SerpInspector({site,keyword,locationCode,languageCode}:{site?:string;keyword:string;locationCode:number;languageCode:string}){
 const saved=useJson<{records:CommandRecord[]}>(site?`/api/serp-evidence?site=${encodeURIComponent(site)}`:null),[device,setDevice]=useState("desktop"),[chosen,setChosen]=useState(""),[filter,setFilter]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const reports=useMemo(()=>(saved.data?.records??[]).map(row=>({id:row.id,data:row.payload as unknown as SerpEvidence})).filter(row=>row.data.keyword.toLowerCase()===keyword.toLowerCase()&&row.data.locationCode===locationCode&&row.data.languageCode===languageCode&&row.data.device===device).sort((a,b)=>Date.parse(b.data.collectedAt)-Date.parse(a.data.collectedAt)),[saved.data,keyword,locationCode,languageCode,device]);
 const report=(reports.find(row=>row.id===chosen)??reports[0])?.data,rows=report?.items.filter(row=>!filter||row.type===filter)??[];
 async function collect(){if(!site)return;setBusy(true);setError("");try{const response=await fetch("/api/serp-evidence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,keywords:[keyword],locationCode,languageCode,device,depth:100,refresh:true})});const body=await response.json();saved.refresh();setChosen("");if(!response.ok)throw new Error(body.error);}catch(e){setError(e instanceof Error?e.message:"Search results could not be collected.");}finally{setBusy(false);}}
 const columns:Column<SerpItem>[]=[{key:"position",header:"Position",render:row=>row.position??"—",sortValue:row=>row.position??999},{key:"type",header:"Result type",render:row=>row.type.replaceAll("_"," ")},{key:"result",header:"Result",render:row=><div className="max-w-xl"><a href={row.url??undefined} target="_blank" rel="noreferrer" className="text-purple">{row.title||row.domain||row.url||"Search feature"}</a>{row.url&&<p className="mt-1 break-all text-[11px] text-muted">{row.url}</p>}{row.description&&<p className="mt-1 text-xs">{row.description}</p>}</div>}];
 return <Card className="min-w-0 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-base font-semibold">SERP Analysis</h2><Button size="sm" disabled={!site||busy} onClick={()=>void collect()}>{busy?"Collecting…":"Update SERP · est. $0.03"}</Button></div><div className="my-3 flex flex-wrap gap-2"><select aria-label="SERP device" value={device} onChange={e=>{setDevice(e.target.value);setChosen("");}} className={field}><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select><select aria-label="SERP snapshot" value={chosen||reports[0]?.id||""} onChange={e=>setChosen(e.target.value)} className={`${field} max-w-full`}><option value="">Latest collected result</option>{reports.map(row=><option key={row.id} value={row.id}>{new Date(row.data.collectedAt).toLocaleString()}</option>)}</select><select aria-label="SERP result type" value={filter} onChange={e=>setFilter(e.target.value)} className={field}><option value="">All result types</option>{[...new Set(report?.items.map(row=>row.type)??[])].map(type=><option key={type} value={type}>{type.replaceAll("_"," ")}</option>)}</select></div>{(error||saved.error)&&<p role="alert" className="my-3 text-xs text-critical">{error||saved.error}</p>}<DataTable rows={rows} columns={columns} rowKey={row=>`${row.type}:${row.position}:${row.url}:${row.title}`} pageSize={20} exportName={`${keyword}-serp`} emptyLabel={site?"No saved results for this keyword and device. Update SERP to collect them.":"Select a website to collect and save search results."}/><p className="mt-3 text-[11px] text-muted">{report?`DataForSEO · ${new Date(report.collectedAt).toLocaleString()} · Requested depth ${report.depth} · Database ${locationCode} · ${languageCode}`:"Saved results are free to reopen. Updating uses the website’s existing collection limits."}</p></Card>;
}
