"use client";
import {useCallback,useEffect,useState} from "react";
import {Star,Search,Download,ChevronRight} from "lucide-react";
import {useDomain} from "@/components/shell/domain-context";
import {Button,Card} from "@/components/ui/primitives";
import {Drawer} from "@/components/ui/drawer";
import {DataTable} from "@/components/ui/data-table";
import {ReportTabs} from "@/components/reports/report-layout";
import {ResearchHandoff} from "./research-handoff";
import {ResearchEvidencePanel} from "./evidence-panel";
import {trendSummary,type EvidenceSeries,type ResearchRun,type EvidenceRow} from "@/lib/research-evidence";
import {MultiLine} from "@/components/charts/charts";
import {exportRows} from "@/lib/report-download";
import type {CommandRecord} from "@/lib/command-model";
type Topic={key:string;label:string;questions:EvidenceRow[];headlines:EvidenceRow[];date:string;market:string;locationCode:number;languageCode:string};
const field="h-9 rounded border border-border bg-card px-3 text-sm";
export function TopicWorkspace(){
 const {activeDomain}=useDomain();const [runs,setRuns]=useState<ResearchRun[]>([]),[trendRuns,setTrendRuns]=useState<ResearchRun[]>([]),[favorites,setFavorites]=useState<CommandRecord[]>([]),[view,setView]=useState("cards"),[query,setQuery]=useState(""),[onlyFavorites,setOnlyFavorites]=useState(false),[selected,setSelected]=useState<Topic|null>(null),[setup,setSetup]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!activeDomain)return;try{const [r,f,t]=await Promise.all([fetch(`/api/research?site=${activeDomain.id}&feature=questions`),fetch(`/api/topic-favorites?site=${activeDomain.id}`),fetch(`/api/research?site=${activeDomain.id}&feature=trends`)]);const [research,saved]=await Promise.all([r.json(),f.json()]);if(!r.ok)throw new Error(research.error);if(!f.ok)throw new Error(saved.error);setRuns(research.runs??[]);if(t.ok)setTrendRuns((await t.json()).runs??[]);setFavorites(saved.favorites??[]);}catch(e){setError(e instanceof Error?e.message:"Could not load topics.");}},[activeDomain]);
 useEffect(()=>{setSelected(null);void load();},[load]);const onExportReady=useCallback(()=>{void load();},[load]);
 const topicMap=new Map<string,Topic>();for(const run of runs)for(const unit of run.payload.units){if(!unit.report)continue;const key=`${run.payload.market.locationCode}:${run.payload.market.languageCode}:${unit.label.toLowerCase()}`;if(topicMap.has(key))continue;topicMap.set(key,{key,label:unit.label,questions:unit.report.tables.filter(table=>table.title.endsWith(": customer questions")).flatMap(table=>table.rows),headlines:unit.report.tables.filter(table=>table.columns.includes("Organic position")).flatMap(table=>table.rows),date:unit.collectedAt??run.updatedAt,locationCode:run.payload.market.locationCode,languageCode:run.payload.market.languageCode,market:`${run.payload.market.label} · ${run.payload.market.languageCode}`});}
 function trendFor(topic:Topic):EvidenceSeries|undefined{return trendRuns.filter(run=>run.payload.market.locationCode===topic.locationCode&&run.payload.market.languageCode===topic.languageCode).flatMap(run=>run.payload.units.flatMap(unit=>unit.report?.series??[])).find(series=>series.label.toLowerCase()===topic.label.toLowerCase());}
 const topics=[...topicMap.values()].filter(topic=>(!query||topic.label.toLowerCase().includes(query.toLowerCase())||topic.questions.some(row=>row.label.toLowerCase().includes(query.toLowerCase())))&&(!onlyFavorites||favorites.some(row=>row.recordKey===topic.key)));
 async function favorite(topic:Topic){if(!activeDomain)return;setBusy(true);setError("");try{const response=await fetch("/api/topic-favorites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site:activeDomain.id,key:topic.key,label:topic.label,saved:!favorites.some(row=>row.recordKey===topic.key)})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();}catch(e){setError(e instanceof Error?e.message:"Could not save topic.");}finally{setBusy(false);}}
 if(!activeDomain)return <Card className="p-8 text-sm text-muted">Choose a website for topic research.</Card>;
 return <div className="space-y-4 pb-8"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-4"><div><p className="mb-2 text-xs text-muted">SEO › Content Ideas</p><h1 className="text-xl font-bold">Topic Research</h1></div><Button size="sm" disabled={!topics.length} onClick={()=>exportRows("topic-research.csv",["Topic","Question / headline","Type","Source","Database","Collected"],topics.flatMap(topic=>[...topic.questions.map(row=>[topic.label,row.label,"Question",row.url,topic.market,topic.date]),...topic.headlines.map(row=>[topic.label,row.label,"Headline",row.url,topic.market,topic.date])]))}><Download className="h-3.5 w-3.5"/>Export</Button></div><div className="flex flex-wrap gap-2"><input className={`${field} min-w-60 flex-1`} aria-label="Filter topics" placeholder="Filter topics or questions" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="primary" onClick={()=>setSetup(true)}><Search className="h-4 w-4"/>Get content ideas</Button><Button onClick={()=>void load()}>Refresh</Button></div><div className="flex flex-wrap items-center justify-between gap-3"><ReportTabs items={[{id:"cards",label:"Cards"},{id:"explorer",label:"Explorer"},{id:"overview",label:"Overview"},{id:"mindmap",label:"Mind Map"}]} value={view} onChange={setView}/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={onlyFavorites} onChange={e=>setOnlyFavorites(e.target.checked)}/>Favourite ideas ({favorites.length})</label></div>{error&&<p role="alert" className="text-sm text-critical">{error}</p>}
 {(view==="cards"||view==="overview")&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{topics.map(topic=><Card key={topic.key} className="overflow-hidden"><div className="flex items-center justify-between border-b border-border bg-purple/5 p-4"><button className="text-left text-base font-semibold" onClick={()=>setSelected(topic)}>{topic.label}</button><button aria-label={`${favorites.some(row=>row.recordKey===topic.key)?"Remove favourite":"Save favourite"} ${topic.label}`} disabled={busy} onClick={()=>void favorite(topic)}><Star className={`h-4 w-4 text-warning ${favorites.some(row=>row.recordKey===topic.key)?"fill-warning":""}`}/></button></div><div className="p-4"><p className="text-xs text-muted">{topic.market} · {new Date(topic.date).toLocaleDateString()}</p><div className="my-4 flex gap-6 text-sm"><span><strong>{topic.headlines.length}</strong> Headlines</span><span><strong>{topic.questions.length}</strong> Questions</span></div><p className="mb-3 text-xs text-muted">Recent interest change: {trendFor(topic)&&typeof trendSummary(trendFor(topic)!).values["Change %"]==="number"?`${Number(trendSummary(trendFor(topic)!).values["Change %"]).toFixed(1)}%`:"Not collected"}</p><h3 className="mb-2 text-xs font-semibold">{view==="overview"?"Top headlines":"Questions people ask"}</h3>{(view==="overview"?topic.headlines:topic.questions).slice(0,3).map(row=><button key={row.id} className="mb-2 block text-left text-xs leading-5 text-purple" onClick={()=>setSelected(topic)}>{row.label}</button>)}<Button size="sm" onClick={()=>setSelected(topic)}>Show more<ChevronRight className="h-3.5 w-3.5"/></Button></div></Card>)}</div>}
 {view==="explorer"&&<Card className="p-4"><DataTable rows={topics.flatMap(topic=>[...topic.headlines.map(row=>({...row,type:"Headline",topic})),...topic.questions.map(row=>({...row,type:"Question",topic}))])} columns={[{key:"topic",header:"Subtopic",render:row=><button className="text-purple" onClick={()=>setSelected(row.topic)}>{row.topic.label}</button>},{key:"idea",header:"Content idea",render:row=>row.label},{key:"type",header:"Type",render:row=>row.type},{key:"source",header:"Source",render:row=>row.url?<a href={row.url} target="_blank" rel="noreferrer" className="text-purple">{new URL(row.url).hostname}</a>:"—"},{key:"date",header:"Updated",render:row=>row.topic.date.slice(0,10)}]} pageSize={30} rowKey={row=>`${row.topic.key}:${row.type}:${row.id}`}/></Card>}
 {view==="mindmap"&&<Card className="overflow-auto p-6"><div className="min-w-[650px] space-y-4">{topics.map(topic=><div key={topic.key} className="grid grid-cols-[200px_40px_minmax(0,1fr)] items-center"><button className="rounded-lg border border-purple/40 bg-purple/10 p-4 text-left text-sm font-semibold text-purple" onClick={()=>setSelected(topic)}>{topic.label}</button><div className="border-t border-purple/30"/><div className="space-y-2 border-l border-purple/30 pl-5">{topic.questions.slice(0,6).map(row=><button key={row.id} className="block rounded border border-border bg-card px-3 py-2 text-left text-xs" onClick={()=>setSelected(topic)}>{row.label}</button>)}</div></div>)}</div></Card>}
 {!topics.length&&<Card className="p-12 text-center"><h2 className="text-lg font-semibold">Find topics your audience asks about</h2><p className="mx-auto mt-2 max-w-xl text-sm text-muted">Collect search results for your seed topics to explore questions, ranking headlines and answer sources. Save ideas and turn them into content briefs.</p><Button className="mt-5" variant="primary" onClick={()=>setSetup(true)}>Get content ideas</Button></Card>}
 <Drawer open={!!selected} onClose={()=>setSelected(null)} title={selected?.label??"Topic"} width="max-w-4xl" subtitle={selected?.market}>{selected&&<div className="space-y-5"><ResearchHandoff keywords={[selected.label,...selected.questions.map(row=>row.label)]} evidence={selected} sourceUrl={`/topic-research?site=${activeDomain.id}`}/>{trendFor(selected)&&<Card className="p-4"><h3 className="mb-3 text-sm font-semibold">Search interest & seasonality</h3><MultiLine data={trendFor(selected)!.points.map(point=>({date:point.date,interest:point.value}))} series={[{key:"interest",name:"Relative interest",color:"var(--chart-orange)"}]} height={180}/><p className="text-xs text-muted">Relative interest within this collection (0–100), through {trendFor(selected)!.points.at(-1)?.date}. This is not monthly search volume.</p></Card>}<div className="grid gap-5 md:grid-cols-2"><div><h3 className="mb-3 text-sm font-semibold">Headlines from ranking pages</h3>{selected.headlines.map(row=><div key={row.id} className="mb-3 border-b border-border pb-3 text-sm"><a className="text-purple" href={row.url} target="_blank" rel="noreferrer">{row.label}</a><p className="mt-1 text-xs text-muted">Organic position {row.values["Organic position"]}</p></div>)}</div><div><h3 className="mb-3 text-sm font-semibold">Questions</h3>{selected.questions.map(row=><details key={row.id} className="mb-3 border-b border-border pb-3"><summary className="cursor-pointer text-sm text-purple">{row.label}</summary><p className="mt-2 text-xs leading-5 text-muted">{row.detail}</p>{row.url&&<a className="mt-2 block text-xs text-purple" href={row.url} target="_blank" rel="noreferrer">Answer source →</a>}</details>)}</div></div><p className="text-xs text-muted">Observed Google results collected {new Date(selected.date).toLocaleString()}. Question presence does not measure search volume or topic difficulty.</p></div>}</Drawer><Drawer open={setup} onClose={()=>setSetup(false)} title="Collect topic ideas" width="max-w-4xl"><ResearchEvidencePanel features={["questions","trends","autocomplete"]} onExportReady={onExportReady}/></Drawer>
 </div>;
}
