"use client";

import { useEffect, useState } from "react";
import { CalendarCheck2, Check, CircleDashed, Loader2, PackageCheck } from "lucide-react";
import { Button, StatusBadge } from "@/components/ui/primitives";
import type { Metric, Outcome, VerificationState } from "@/platform/workflow-verification";

type Item = { id: string; status: "approved" | "in_progress" | "shipped" | "verifying" | "done" | null; verification?: VerificationState; targetUrl: string | null; plannedUrl: string | null; updatedAt: string };
const outcomes: Array<{ value: Outcome; label: string }> = [{ value: "won", label: "Won" }, { value: "lost", label: "Lost" }, { value: "inconclusive", label: "Inconclusive" }, { value: "awaiting_data", label: "Awaiting data" }];
const formatValue = (metric: Metric) => metric.unit === "ratio" ? `${(metric.value * 100).toFixed(1)}%` : metric.value.toLocaleString(undefined, { maximumFractionDigits: 2 });

export function VerificationPanel({ item, onUpdate }: { item: Item; onUpdate: (item: Partial<Item> & { id: string }) => void }) {
  const verification = item.verification ?? {};
  const [shipmentNote, setShipmentNote] = useState("");
  const [shipmentUrl, setShipmentUrl] = useState(item.targetUrl ?? item.plannedUrl ?? "");
  const [activeDay, setActiveDay] = useState<number | null>(null);
  const [metrics, setMetrics] = useState<Metric[]>([]);
  const [outcome, setOutcome] = useState<Outcome>("awaiting_data");
  const [note, setNote] = useState("");
  const [confidence, setConfidence] = useState<"low" | "medium" | "high">("medium");
  const [alternatives, setAlternatives] = useState("");
  const [valueAmount, setValueAmount] = useState("");
  const [valueCurrency, setValueCurrency] = useState("AED");
  const [valueMethod, setValueMethod] = useState<"recorded" | "estimated">("estimated");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { setShipmentUrl(item.targetUrl ?? item.plannedUrl ?? ""); }, [item.id, item.targetUrl, item.plannedUrl]);
  const act = async (payload: Record<string, unknown>) => { setBusy(true); setError(null); try { const response = await fetch(`/api/workflow/tasks/${item.id}/verification`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok || !body.item) throw new Error(body.error ?? "Verification could not be updated."); onUpdate(body.item); setActiveDay(null); setNote(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Verification could not be updated."); } finally { setBusy(false); } };
  const openCheckpoint = (day: number) => { const checkpoint = verification.checkpoints?.find((item) => item.day === day); setActiveDay(day); setMetrics(checkpoint?.metrics ?? verification.baseline?.metrics ?? []); setOutcome(verification.outcome ?? "awaiting_data"); setNote(checkpoint?.note ?? ""); setConfidence(verification.confidence ?? "medium"); setAlternatives((verification.alternativeExplanations ?? []).join("\n")); setValueAmount(verification.valueCreated?.amount ? String(verification.valueCreated.amount) : ""); setValueCurrency(verification.valueCreated?.currency ?? "AED"); setValueMethod(verification.valueCreated?.method ?? "estimated"); };

  return <section className="overflow-hidden rounded-lg border border-border bg-card">
    <div className="flex items-start justify-between gap-3 border-b border-border px-4 py-3"><div><div className="text-2xs font-bold uppercase tracking-[0.12em] text-muted">Evidence timeline</div><p className="mt-1 text-xs text-muted">Baseline → shipped → 7/14/28-day checks → measured outcome</p></div><StatusBadge label={(verification.outcome ?? "awaiting_data").replace(/_/g, " ")} tone={verification.outcome === "won" ? "success" : verification.outcome === "lost" ? "warning" : "neutral"} /></div>
    <div className="p-4"><div className="grid grid-cols-[1fr_26px_1fr_26px_1fr] items-center gap-2"><Milestone done={Boolean(verification.baseline)} label="Baseline" detail={verification.baseline ? new Date(verification.baseline.capturedAt).toLocaleDateString() : "Not captured"} /><Line done={Boolean(verification.shipment)} /><Milestone done={Boolean(verification.shipment)} label="Shipped" detail={verification.shipment ? new Date(verification.shipment.recordedAt).toLocaleDateString() : "Not recorded"} /><Line done={Boolean(verification.checkpoints?.some((entry) => entry.status === "recorded"))} /><Milestone done={verification.outcome !== undefined && verification.outcome !== "awaiting_data"} label="Outcome" detail={(verification.outcome ?? "Awaiting data").replace(/_/g, " ")} /></div>
      {verification.baseline ? <div className="mt-4 rounded-md bg-workspace/60 p-3"><div className="text-[10px] font-bold uppercase tracking-wide text-muted">Pre-action baseline</div>{verification.baseline.metrics.length ? <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{verification.baseline.metrics.map((metric) => <div key={metric.key}><div className="text-[10px] text-muted">{metric.label}</div><div className="text-sm font-bold text-ink tnum">{formatValue(metric)}</div><div className="text-[9px] text-muted">{metric.source.replace(/_/g, " ")}</div></div>)}</div> : <p className="mt-2 text-xs text-muted">Baseline timestamp saved. This finding did not contain numeric source metrics.</p>}</div> : <div className="mt-4 flex items-center justify-between gap-3 rounded-md border border-purple/20 bg-purple/5 p-3"><p className="text-xs text-muted">Capture the attached research evidence before work changes the result.</p><Button size="sm" variant="primary" onClick={() => void act({ action: "capture_baseline" })} disabled={busy}>Capture baseline</Button></div>}
      {verification.baseline && !verification.shipment && <div className="mt-4 rounded-md border border-border p-3"><div className="flex items-center gap-2 text-xs font-bold text-ink"><PackageCheck className="h-4 w-4 text-purple" />Record shipment</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><input value={shipmentUrl} onChange={(event) => setShipmentUrl(event.target.value)} placeholder="Published or deployed URL" className="h-9 rounded-md border border-border bg-card px-3 text-xs outline-none focus:border-purple" /><input value={shipmentNote} onChange={(event) => setShipmentNote(event.target.value)} placeholder="What changed?" className="h-9 rounded-md border border-border bg-card px-3 text-xs outline-none focus:border-purple" /></div><div className="mt-2 flex justify-end"><Button size="sm" variant="primary" onClick={() => void act({ action: "record_shipment", url: shipmentUrl || null, note: shipmentNote || null })} disabled={busy}>{busy && <Loader2 className="h-3.5 w-3.5 animate-spin" />}Mark shipped</Button></div></div>}
      {verification.checkpoints && <div className="mt-4 grid gap-2 sm:grid-cols-3">{verification.checkpoints.map((checkpoint) => <button key={checkpoint.day} onClick={() => openCheckpoint(checkpoint.day)} className="rounded-md border border-border p-3 text-left hover:border-purple/40"><div className="flex items-center justify-between"><span className="text-xs font-bold text-ink">Day {checkpoint.day}</span>{checkpoint.status === "recorded" ? <Check className="h-4 w-4 text-success" /> : <CalendarCheck2 className="h-4 w-4 text-muted" />}</div><div className="mt-1 text-[10px] text-muted">{checkpoint.status === "recorded" ? `Checked ${new Date(checkpoint.recordedAt!).toLocaleDateString()}` : `Due ${new Date(checkpoint.dueAt).toLocaleDateString()}`}</div></button>)}</div>}
      {activeDay && <div className="mt-4 rounded-md border border-purple/20 bg-purple/5 p-3"><div className="text-xs font-bold text-ink">Record day {activeDay} check</div><div className="mt-3 grid grid-cols-2 gap-2">{metrics.map((metric, index) => <label key={metric.key} className="text-[10px] font-semibold text-muted">{metric.label}<input type="number" step="any" value={metric.value} onChange={(event) => setMetrics((current) => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, value: Number(event.target.value) } : entry))} className="mt-1 h-8 w-full rounded border border-border bg-card px-2 text-xs text-ink" /></label>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select value={outcome} onChange={(event) => setOutcome(event.target.value as Outcome)} className="h-9 rounded-md border border-border bg-card px-2 text-xs text-ink">{outcomes.map((entry) => <option key={entry.value} value={entry.value}>{entry.label}</option>)}</select><select value={confidence} onChange={(event) => setConfidence(event.target.value as typeof confidence)} className="h-9 rounded-md border border-border bg-card px-2 text-xs text-ink"><option value="low">Low confidence</option><option value="medium">Medium confidence</option><option value="high">High confidence</option></select><input value={note} onChange={(event) => setNote(event.target.value)} placeholder="What changed and why?" className="h-9 rounded-md border border-border bg-card px-3 text-xs" /><textarea value={alternatives} onChange={(event) => setAlternatives(event.target.value)} placeholder="Alternative explanations, one per line" className="min-h-16 rounded-md border border-border bg-card px-3 py-2 text-xs" /></div><div className="mt-2 grid grid-cols-[1fr_72px_110px] gap-2"><input type="number" min="0" step="any" value={valueAmount} onChange={(event) => setValueAmount(event.target.value)} placeholder="Value created" className="h-9 rounded-md border border-border bg-card px-3 text-xs" /><input maxLength={3} value={valueCurrency} onChange={(event) => setValueCurrency(event.target.value.toUpperCase())} aria-label="Value currency" className="h-9 rounded-md border border-border bg-card px-2 text-xs uppercase" /><select value={valueMethod} onChange={(event) => setValueMethod(event.target.value as typeof valueMethod)} className="h-9 rounded-md border border-border bg-card px-2 text-xs"><option value="estimated">Estimated</option><option value="recorded">Recorded</option></select></div><div className="mt-2 flex justify-end"><Button size="sm" variant="primary" onClick={() => void act({ action: "record_checkpoint", day: activeDay, metrics, outcome, confidence, note: note || null, alternativeExplanations: alternatives.split("\n").map((value) => value.trim()).filter(Boolean), valueCreated: valueAmount ? { amount: Number(valueAmount), currency: valueCurrency, method: valueMethod, assumption: note || null } : null })} disabled={busy || valueCurrency.length !== 3}>Save check</Button></div></div>}
      {error && <div role="alert" className="mt-3 text-xs font-semibold text-critical">{error}</div>}
    </div>
  </section>;
}

function Milestone({ done, label, detail }: { done: boolean; label: string; detail: string }) { return <div className="min-w-0 text-center">{done ? <Check className="mx-auto h-5 w-5 rounded-full bg-success p-1 text-white" /> : <CircleDashed className="mx-auto h-5 w-5 text-muted" />}<div className="mt-1 text-[10px] font-bold text-ink">{label}</div><div className="truncate text-[9px] capitalize text-muted">{detail}</div></div>; }
function Line({ done }: { done: boolean }) { return <div className={`h-px ${done ? "bg-success" : "bg-border"}`} />; }
