"use client";
import Link from "next/link";
import { createContext, useContext, useEffect, useState } from "react";
import { useDomain } from "@/components/shell/domain-context";
import { MultiLine } from "@/components/charts/charts";
import { ArrowUpRight, X } from "lucide-react";
import { Card } from "@/components/ui/primitives";
import { ReportMetric, MissingChart } from "@/components/reports/report-layout";
import { useJson } from "@/lib/use-live";
import type { DomainLiveBundle } from "@/lib/live";
import type { AiVisibilityDashboard } from "@/platform/ai-read-model";
import { searchPeriod, analyticsPeriod } from "@/lib/reporting";
import { compactNumber } from "@/lib/format";
import type { CommandRecord } from "@/lib/command-model";
import type { CompetitorExplorerResult } from "@/platform/competitive-intelligence";
import type { OnPageReport } from "@/lib/on-page-analysis";
import type { TrafficEvidence } from "@/lib/traffic-research";
import { navigationHref } from "@/lib/nav";

type LocalSummary = { locations: { id: string; name: string; address: string | null }[]; snapshots: { locationId: string; capturedOn: string; rating: number | null; reviewCount: number | null }[] };
const num = (value: number | null | undefined) => value == null ? null : compactNumber(value);
const WidgetContext = createContext<{hidden:string[];hide:(title:string)=>void}>({hidden:[],hide:()=>{}});
function Widget({title,href,note,children,className=""}:{title:string;href:string;note?:string;children:React.ReactNode;className?:string}) {
  const widgets=useContext(WidgetContext);
  if(widgets.hidden.includes(title)) return null;
  return <Card className={`min-w-0 overflow-hidden rounded-md shadow-none [&_.report-metric]:py-2 [&_.report-metric]:px-3 [&_.report-metric>span:nth-child(2)]:text-xl [&_.report-metric>span:nth-child(2)]:leading-6 ${className}`}><div className="flex h-[42px] items-center gap-3 border-b border-border px-4"><Link href={href} className="flex-1 text-[15px] font-bold hover:text-purple">{title}</Link><Link aria-label={`Open ${title}`} href={href}><ArrowUpRight className="h-4 w-4 text-muted"/></Link><button aria-label={`Hide ${title}`} onClick={()=>widgets.hide(title)} className="text-muted hover:text-ink"><X className="h-3.5 w-3.5"/></button></div>{note&&<p className="px-4 pt-2 text-[11px] text-muted">{note}</p>}{children}</Card>;
}
export function SeoDashboardSummary({ site, bundle, days }: { site: string; bundle: DomainLiveBundle | null; days: number }) {
  const { activeDomain } = useDomain();
  const [hidden,setHidden]=useState<string[]>([]), [hiddenReady,setHiddenReady]=useState("");
  const [trafficSource,setTrafficSource]=useState("google");
  useEffect(()=>{try{const value=JSON.parse(localStorage.getItem(`dashboard-widgets:${site}`)??"[]");if(Array.isArray(value))setHidden(value.filter(v=>typeof v==="string"));}catch{}setHiddenReady(site);},[site]);
  useEffect(()=>{if(hiddenReady===site)localStorage.setItem(`dashboard-widgets:${site}`,JSON.stringify(hidden));},[hidden,hiddenReady,site]);
  const domainResearch=useJson<{evidence:{id:string;sourceValue:string;locationCode:number;languageCode:string;capturedAt:string;summary:{organicTraffic?:number;organicKeywords?:number;paidTraffic?:number;paidKeywords?:number}}[]}>("/api/domain-research");
  const domain=domainResearch.data?.evidence.find(r=>r.sourceValue.replace(/^www\./,"")===activeDomain?.host.replace(/^www\./,"")&&r.locationCode===activeDomain?.dataForSeoLocationCode&&r.languageCode===activeDomain?.dataForSeoLanguageCode);
  const [organic,setOrganic]=useState<CompetitorExplorerResult["keywords"]>([]);
  useEffect(()=>{let live=true;setOrganic([]);if(domain?.id)fetch(`/api/domain-research?id=${encodeURIComponent(domain.id)}`).then(response=>response.ok?response.json():null).then(body=>{if(live)setOrganic(body?.evidence?.evidence?.keywords??[]);}).catch(()=>undefined);return()=>{live=false;};},[domain?.id]);
  const organicHistory=(domainResearch.data?.evidence??[]).filter(row=>row.sourceValue===domain?.sourceValue&&row.locationCode===domain?.locationCode&&row.languageCode===domain?.languageCode).slice().reverse().map(row=>({date:row.capturedAt,keywords:row.summary.organicKeywords??null,traffic:row.summary.organicTraffic??null}));
  const organicChanges=[{label:"New",key:"new",count:organic.filter(row=>row.isNew===true).length},{label:"Improved",key:"improved",count:organic.filter(row=>row.previousPosition!=null&&row.position!=null&&row.previousPosition>row.position).length},{label:"Declined",key:"declined",count:organic.filter(row=>row.previousPosition!=null&&row.position!=null&&row.previousPosition<row.position).length},{label:"Lost",key:"lost",count:organic.filter(row=>row.isLost===true).length}];
  const changesAvailable=organic.some(row=>row.previousPosition!=null||row.isNew!=null||row.isLost!=null);
  const ai = useJson<AiVisibilityDashboard>(`/api/ai-visibility?scope=${encodeURIComponent(site)}&days=${days}`);
  const local = useJson<LocalSummary>(`/api/local-seo?scope=${encodeURIComponent(site)}`);
  const pageReports=useJson<{records:CommandRecord[]}>(`/api/on-page?site=${encodeURIComponent(site)}`);
  const latestPages=[...new Map((pageReports.data?.records??[]).filter(row=>row.payload.report&&(row.payload.report as OnPageReport).kind!=="template").slice().reverse().map(row=>{const report=row.payload.report as OnPageReport;return [`${report.url}:${report.keyword}:${report.locationCode}:${report.languageCode}`,report] as const;})).values()];
  const traffic=useJson<{evidence:TrafficEvidence|null;history?:TrafficEvidence[]}>(`/api/traffic-analytics?site=${encodeURIComponent(site)}`);
  const d = bundle?.datasets;
  const search = searchPeriod(bundle, days), analytics = analyticsPeriod(bundle, days);
  const link = (href: string) => navigationHref({ href, group: "site" }, site, `${days}d`);
  const ga4=d?.ga4_overview;
  const matchingAggregate=ga4?.provenance.rangeStart===analytics.start&&ga4?.provenance.rangeEnd===analytics.end?ga4?.data:null;
  const users=matchingAggregate?.totalUsers,duration=matchingAggregate?.averageSessionDuration;
  const backlinkHistory=d?.backlink_history?.data??[];
  const authorityBuckets=Array.from({length:5},(_,i)=>({label:`${i*20+1}–${(i+1)*20}`,count:(d?.referring_domains?.data??[]).filter(row=>row.authority>i*20&&row.authority<=(i+1)*20).length}));
  const measured = Boolean(ai.data?.summary.checks);
  const audit = d?.onpage?.data;
  const ranks = d?.rank_snapshots?.data;
  const positions = ranks?.filter((row) => row.position != null && row.position > 0);
  const latestProfiles = [...new Map((local.data?.snapshots ?? []).slice().sort((a, b) => a.capturedOn.localeCompare(b.capturedOn)).map((row) => [row.locationId, row])).values()];
  const source = (date?: string) => date ? `Saved ${date.slice(0, 10)}` : "Awaiting collection";
  return <WidgetContext.Provider value={{hidden,hide:(title)=>setHidden(v=>[...v,title])}}><div className="space-y-4">
    <div className="grid gap-4 lg:grid-cols-2">
      <Widget title="AI Search" href={link("/ai-visibility")} className="min-h-[200px]"><div className="grid grid-cols-3 divide-x divide-border"><ReportMetric label="AI mention rate" value={measured ? `${ai.data!.summary.mentionRate}%` : null}/><ReportMetric label="Mentions" value={measured ? num(ai.data!.summary.mentions) : null}/><ReportMetric label="Cited pages" value={measured ? num(ai.data!.summary.citedPages) : null}/></div><div className="px-4 pb-3">{["chatgpt","google_ai_overview","google_ai_mode","gemini"].map(name=>{const row=ai.data?.platforms.find(r=>r.platform===name);return <div key={name} className="grid grid-cols-3 py-1 text-xs"><span className="text-muted">{{chatgpt:"ChatGPT",google_ai_overview:"Google AI Overview",google_ai_mode:"Google AI Mode",gemini:"Gemini"}[name]}</span><span className="px-4">{row?.mentions??"—"}</span><span className="px-4">{row?.citedPages??"—"}</span></div>;})}{ai.error&&<button className="text-xs text-critical" onClick={ai.refresh}>AI data failed to load. Retry</button>}</div></Widget>
      <Widget title="SEO" href={link("/domain-research")} className="min-h-[200px]" note={domain ? `Provider estimates · saved ${domain.capturedAt.slice(0,10)}` : "Provider estimates · awaiting domain research"}><div className="grid grid-cols-3 divide-x divide-border"><ReportMetric label="Authority Score"/><ReportMetric label="Organic traffic" value={num(domain?.summary.organicTraffic)}/><ReportMetric label="Organic keywords" value={num(domain?.summary.organicKeywords)}/></div><div className="grid grid-cols-3 divide-x divide-border"><ReportMetric label="Paid traffic" value={num(domain?.summary.paidTraffic)}/><ReportMetric label="Paid keywords" value={num(domain?.summary.paidKeywords)}/><ReportMetric label="Referring domain sample" value={d?.referring_domains ? num(d.referring_domains.data.length) : null}/></div></Widget>
    </div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Widget title="Position Tracking" href={link("/rankings")} className="min-h-[190px]"><ReportMetric label="Average tracked position" value={positions?.length ? (positions.reduce((sum, row) => sum + row.position!, 0) / positions.length).toFixed(1) : null} note={source(d?.rank_snapshots?.capturedOn)} /><div className="flex justify-between border-t border-border px-4 py-3 text-xs"><span className="text-muted">Ranked keywords</span><span>{ranks ? positions?.length : "—"}</span></div></Widget>
      <Widget title="Site Audit" href={link("/site-audit")} className="min-h-[190px]"><ReportMetric label="Site health" value={audit ? `${audit.healthScore}%` : null} note={source(d?.onpage?.capturedOn)} /><div className="flex justify-between border-t border-border px-4 py-3 text-xs"><span className="text-muted">Critical issues</span><span>{audit?.issues.filter((issue) => issue.severity === "critical" && issue.status !== "resolved").length ?? "—"}</span></div></Widget>
      <Widget title="Listing Management" href={link("/local-seo?view=locations")} note="Saved Google Business Profile evidence" className="sm:col-span-2 min-h-[190px]"><div className="grid grid-cols-2 divide-x divide-border"><ReportMetric label="Business locations" value={local.data ? local.data.locations.length : null} /><ReportMetric label="Reviews in saved profiles" value={latestProfiles.some((row) => row.reviewCount != null) ? num(latestProfiles.reduce((sum, row) => sum + (row.reviewCount ?? 0), 0)) : null} note={`${latestProfiles.length} profiles with saved evidence`} /></div><div className="border-t border-border px-4 py-3 text-xs text-muted">{local.error ? <span role="alert">Local summary could not load. <button onClick={local.refresh} className="underline">Retry</button></span> : local.data?.locations.length ? local.data.locations.slice(0, 2).map((row) => row.name).join(" · ") : <Link href={link("/local-seo")}>{local.loading ? "Loading saved locations…" : "Add a location to start local monitoring →"}</Link>}</div></Widget>
    </div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      {title:"On Page SEO Checker",href:"/on-page",label:"Optimisation ideas",value:pageReports.data?latestPages.reduce((total,report)=>total+report.ideas.filter(idea=>(report.decisions[idea.id]??"open")==="open").length,0):null,note:`${latestPages.length} saved page analyses`},
      {title:"Backlink Audit",href:"/backlink-audit",label:"High-spam links",value:d?.backlinks ? d.backlinks.data.filter((row) => row.toxicity > 50).length : null,note:"Within the saved link sample"},
      {title:"Organic Traffic Insights",href:"/organic-traffic",label:"Organic sessions",value:num(analytics.total?.sessions),note:"Google Analytics · saved period"},
      {title:"Link Building Tool",href:"/link-building",label:"Referring domains",value:d?.referring_domains ? num(d.referring_domains.data.length) : null,note:"Within the saved domain sample"},
    ].map((item) => <Widget key={item.title} title={item.title} href={link(item.href)} className="min-h-[190px]"><ReportMetric label={item.label} value={item.value} note={item.note} /></Widget>)}</div>
    <Widget title="Traffic Analytics" href={link("/traffic-analytics")}><div className="flex gap-2 border-b border-border px-4 py-3 text-xs">{[["google","Google Analytics"],["provider","Competitor traffic"]].map(([id,label])=><button aria-pressed={trafficSource===id} onClick={()=>setTrafficSource(id)} key={id} className={`rounded border border-border px-3 py-1 ${trafficSource===id?"bg-purple/10 text-purple":"text-muted"}`}>{label}</button>)}</div><div className="grid grid-cols-2 divide-x divide-border lg:grid-cols-5"><ReportMetric label={trafficSource==="google"?"Organic sessions":"Estimated visits"} value={trafficSource==="google"?num(analytics.total?.sessions):num(traffic.data?.evidence?.visits)}/><ReportMetric label="Unique visitors" value={trafficSource==="google"?num(users):null}/><ReportMetric label="Views / session" value={trafficSource==="google"?analytics.total?.viewsPerSession?.toFixed(2):null}/><ReportMetric label="Visit duration" value={trafficSource==="google"&&duration!=null?`${Math.floor(duration/60)}m ${Math.round(duration%60)}s`:null} note="Average session duration for this saved period"/><ReportMetric label="Engagement rate" value={trafficSource==="google"&&analytics.total?`${analytics.total.engagementRate.toFixed(1)}%`:null}/></div>{trafficSource==="google"&&analytics.current.length>1 ? <div className="p-4"><MultiLine data={analytics.current.map(r=>({...r}))} height={190} series={[{key:"sessions",name:"Organic sessions",color:"var(--chart-orange)"}]}/></div>:trafficSource==="provider"&&traffic.data?.evidence?<div className="grid gap-2 p-4 sm:grid-cols-4">{traffic.data.evidence.channels.map(row=><div key={row.name} className="rounded border border-border p-3 text-xs"><p className="text-muted">{row.name}</p><p className="mt-2 font-semibold">{num(row.visits)??"—"}</p><p className="text-muted">{row.share==null?"Incomplete device coverage":`${row.share.toFixed(1)}%`}</p></div>)}<p className="text-[11px] text-muted">{traffic.data.evidence.input.month} · {traffic.data.evidence.input.country} · Similarweb estimates</p></div>:<MissingChart height="h-44" message={trafficSource==="provider"?"Review the traffic provider connection before collecting total visits and channels.":"Daily Analytics history is not available for this period."}/>}</Widget>
    <Widget title="Organic Rankings" href={link("/competitors")} note={domain?`Database ${domain.locationCode} / ${domain.languageCode} · ${organic.length} collected keywords · ${source(domain.capturedAt)}`:"Collect a domain report to see organic rankings and indexed changes."}><div className="grid grid-cols-2 divide-x divide-border sm:grid-cols-4">{organicChanges.map(row=><Link key={row.key} href={link(`/competitors?view=changes&change=${row.key}`)} className="hover:bg-workspace"><ReportMetric label={row.label} value={changesAvailable?row.count:null}/></Link>)}</div>{organicHistory.length>1?<div className="p-4"><MultiLine data={organicHistory} series={[{key:"keywords",name:"Organic keywords",color:"var(--chart-orange)"}]} height={180}/></div>:<MissingChart height="h-32" message="Two saved domain reports in the same database are needed for the historical trend."/>}</Widget>
    <Widget title="Google Search Performance" href={link("/organic-traffic")}><div className="grid grid-cols-3 divide-x divide-border"><ReportMetric label="Clicks" value={num(search.total?.clicks)}/><ReportMetric label="Impressions" value={num(search.total?.impressions)}/><ReportMetric label="Average position" value={search.total?.position?.toFixed(1)}/></div>{search.current.length>1?<div className="p-4"><MultiLine data={search.current.map(r=>({...r}))} height={190} series={[{key:"clicks",name:"Search clicks",color:"var(--chart-orange)"}]}/></div>:<MissingChart height="h-40" message="Saved Search Console history is not available."/>}</Widget>
    <Widget title="Backlinks" href={link("/backlinks")} note={source(d?.backlink_history?.capturedOn)}><div className="grid gap-4 lg:grid-cols-[2fr_1fr]"><div className="min-w-0 p-4"><h3 className="mb-3 text-xs font-semibold">Referring domains over time</h3>{backlinkHistory.length>1?<MultiLine data={backlinkHistory.map(row=>({date:row.date,referringDomains:row.referringDomains}))} height={180} series={[{key:"referringDomains",name:"Referring domains",color:"var(--chart-orange)"}]}/>:<MissingChart height="h-44" message="At least two saved backlink history dates are needed."/>}</div><div className="border-t border-border p-4 lg:border-l lg:border-t-0"><h3 className="mb-4 text-xs font-semibold">Referring domain rank distribution</h3>{authorityBuckets.map(row=><div key={row.label} className="mb-3 grid grid-cols-[44px_1fr_35px] items-center gap-2 text-xs"><span>{row.label}</span><div className="h-3 bg-workspace"><div className="h-3 bg-purple" style={{width:`${row.count/Math.max(1,...authorityBuckets.map(bucket=>bucket.count))*100}%`}}/></div><span>{d?.referring_domains?row.count:"—"}</span></div>)}<p className="text-[11px] text-muted">Saved sample · provider rank, not Semrush Authority Score</p></div></div></Widget>
    <Card className="grid gap-4 p-4 sm:grid-cols-2">{[{name:"Google Search Console",available:Boolean(d?.gsc_totals||d?.gsc_timeseries),date:d?.gsc_totals?.capturedOn??d?.gsc_timeseries?.capturedOn},{name:"Google Analytics",available:Boolean(d?.ga4_overview||d?.ga4_dashboard),date:d?.ga4_overview?.capturedOn??d?.ga4_dashboard?.capturedOn}].map(provider=><div key={provider.name} className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">{provider.name}</h3><p className="mt-1 text-xs text-muted">{provider.available?source(provider.date):"No saved data"}</p></div><Link className="text-xs text-purple" href={`/sites/${site}/settings`}>Manage connection →</Link></div>)}</Card>
    <details className="rounded border border-border bg-card p-4 text-sm"><summary className="cursor-pointer font-semibold">Hidden widgets ({hidden.length})</summary><div className="mt-3 flex flex-wrap gap-2">{hidden.map(title=><button key={title} onClick={()=>setHidden(v=>v.filter(t=>t!==title))} className="rounded border border-border px-3 py-2 text-xs text-purple">Restore {title}</button>)}{!hidden.length&&<span className="text-xs text-muted">Use × on a widget to move it here.</span>}</div></details>
  </div></WidgetContext.Provider>;
}
