"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, ExternalLink, Filter, FlaskConical, Route, Scale, Trophy } from "lucide-react";
import { useDomain } from "@/components/shell/domain-context";
import { Drawer } from "@/components/ui/drawer";
import { PageHeader } from "@/components/ui/page-header";
import { Card, EmptyState, Skeleton, StatusBadge } from "@/components/ui/primitives";

type Outcome = "won" | "lost" | "inconclusive" | "awaiting_data";
type Row = { id: string; domainSlug: string; title: string; module: string; executionType: string | null; ownerEmail: string | null; sourceUrl: string | null; sourceLabel: string; destination: string | null; priorityScore: number; status: string | null; shippedAt: string | null; latestCheckDay: number; nextCheck: string | null; proof: Record<"researched"|"approved"|"shipped"|"verified"|"valued", boolean>; metrics: Array<{ key: string; label: string; value: number; current: number | null; absoluteChange: number | null; percentChange: number | null; direction: string; unit: string; source: string }>; verification: { outcome?: Outcome; outcomeNote?: string | null; confidence?: string; alternativeExplanations?: string[]; valueCreated?: { amount: number; currency: string; method: string; assumption?: string | null } | null; checkpoints?: Array<{ day: number; dueAt: string; status: string }> } };
type Ledger = { rows: Row[]; summary: { total: number; shipped: number; verified: number; won: number; lost: number; inconclusive: number; awaitingData: number; valueByCurrency: Array<{ currency: string; amount: number }> }; learning: Array<{ domainSlug: string; executionType: string; samples: number; wins: number; losses: number; adjustment: number; explanation: string }> };
const inputClass = "h-9 rounded-md border border-border bg-card px-3 text-xs text-ink outline-none focus:border-purple";
const outcomeTone = (value?: Outcome) => value === "won" ? "success" : value === "lost" ? "warning" : value === "inconclusive" ? "info" : "neutral";
const money = (amount: number, currency: string) => new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 0 }).format(amount);

export default function OutcomesPage() {
  const { sites } = useDomain();
  const [data, setData] = useState<Ledger | null>(null);
  const [selected, setSelected] = useState<Row | null>(null);
  const [site, setSite] = useState("all"); const [type, setType] = useState("all"); const [owner, setOwner] = useState("all"); const [outcome, setOutcome] = useState("all");
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); setLoading(true); fetch("/api/outcomes", { signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Outcome ledger could not be loaded."); setData(body); setError(null); }).catch((reason) => { if (!(reason instanceof DOMException && reason.name === "AbortError")) setError(reason instanceof Error ? reason.message : "Outcome ledger could not be loaded."); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  const rows = useMemo(() => (data?.rows ?? []).filter((row) => (site === "all" || row.domainSlug === site) && (type === "all" || row.executionType === type) && (owner === "all" || row.ownerEmail === owner) && (outcome === "all" || (row.verification.outcome ?? "awaiting_data") === outcome)), [data, site, type, owner, outcome]);
  const types = [...new Set((data?.rows ?? []).map((row) => row.executionType).filter(Boolean))] as string[]; const owners = [...new Set((data?.rows ?? []).map((row) => row.ownerEmail).filter(Boolean))] as string[];
  return <div className="animate-in space-y-5"><PageHeader title="Outcome ledger" description="The proof of what moved—from original evidence and approved execution to measured SEO value." />
    {error && <div role="alert" className="rounded-md border border-critical/20 bg-critical/5 p-3 text-xs text-critical">{error}</div>}
    {loading ? <><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Skeleton className="h-24" /><Skeleton className="h-24" /><Skeleton className="h-24" /><Skeleton className="h-24" /></div><Skeleton className="h-96" /></> : data && <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><ProofStat label="Shipped" value={data.summary.shipped} detail={`${data.summary.total} approved actions`} /><ProofStat label="Verified" value={data.summary.verified} detail={`${data.summary.awaitingData} awaiting evidence`} /><ProofStat label="Won" value={data.summary.won} detail={`${data.summary.lost} lost · ${data.summary.inconclusive} inconclusive`} accent /><ProofStat label="Value created" value={data.summary.valueByCurrency.map((entry) => money(entry.amount, entry.currency)).join(" + ") || "—"} detail="Recorded and estimated, labelled" /></div>
      <Card><div className="flex flex-wrap items-center gap-2 border-b border-border p-3"><Filter className="h-4 w-4 text-muted" /><select value={site} onChange={(e) => setSite(e.target.value)} className={inputClass}><option value="all">All websites</option>{sites.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={type} onChange={(e) => setType(e.target.value)} className={inputClass}><option value="all">All action types</option>{types.map((item) => <option key={item} value={item}>{item.replace(/_/g," ")}</option>)}</select><select value={owner} onChange={(e) => setOwner(e.target.value)} className={inputClass}><option value="all">All owners</option>{owners.map((item) => <option key={item} value={item}>{item}</option>)}</select><select value={outcome} onChange={(e) => setOutcome(e.target.value)} className={inputClass}><option value="all">All outcomes</option><option value="won">Won</option><option value="lost">Lost</option><option value="inconclusive">Inconclusive</option><option value="awaiting_data">Awaiting data</option></select></div>
        {rows.length ? <div className="divide-y divide-border">{rows.map((row) => <button key={row.id} onClick={() => setSelected(row)} className="grid w-full gap-3 p-4 text-left transition hover:bg-workspace/50 lg:grid-cols-[minmax(240px,1.2fr)_minmax(250px,1fr)_130px_120px]"><div><div className="flex items-center gap-2"><StatusBadge label={(row.verification.outcome ?? "awaiting data").replace(/_/g," ")} tone={outcomeTone(row.verification.outcome)} /><span className="text-[10px] font-bold uppercase text-muted">{row.module}</span></div><div className="mt-2 text-sm font-bold text-ink">{row.title}</div><div className="mt-1 text-2xs text-muted">{sites.find((item) => item.id === row.domainSlug)?.name ?? row.domainSlug} · {row.ownerEmail ?? "Unassigned"}</div></div><ProofChain proof={row.proof} /><div><div className="text-[10px] font-bold uppercase text-muted">Latest movement</div>{row.metrics[0]?.current != null ? <div className={`mt-2 flex items-center gap-1 text-sm font-bold ${row.metrics[0].direction === "up" ? "text-success" : row.metrics[0].direction === "down" ? "text-critical" : "text-ink"}`}>{row.metrics[0].direction === "up" ? <ArrowUpRight className="h-4 w-4" /> : row.metrics[0].direction === "down" ? <ArrowDownRight className="h-4 w-4" /> : null}{row.metrics[0].percentChange?.toFixed(1)}%</div> : <div className="mt-2 text-xs text-muted">No check yet</div>}<div className="mt-1 text-[10px] text-muted">{row.metrics[0]?.label}</div></div><div><div className="text-[10px] font-bold uppercase text-muted">Value</div><div className="mt-2 text-sm font-bold text-ink">{row.verification.valueCreated ? money(row.verification.valueCreated.amount, row.verification.valueCreated.currency) : "—"}</div><div className="mt-1 text-[10px] capitalize text-muted">{row.verification.valueCreated?.method ?? "Not recorded"}</div></div></button>)}</div> : <div className="p-5"><EmptyState title="No outcomes match these filters" description="Adjust the filters or ship work to begin the evidence timeline." /></div>}
      </Card>
      <Card><div className="border-b border-border p-4"><div className="flex items-center gap-2 text-sm font-bold text-ink"><FlaskConical className="h-4 w-4 text-purple" />Learning signals</div><p className="mt-1 text-2xs text-muted">Transparent adjustments require at least two verified outcomes and are capped at ±10 points.</p></div><div className="divide-y divide-border">{data.learning.length ? data.learning.map((signal) => <div key={`${signal.domainSlug}:${signal.executionType}`} className="grid gap-2 px-4 py-3 sm:grid-cols-[1fr_120px_90px]"><div><div className="text-xs font-bold text-ink">{sites.find((item) => item.id === signal.domainSlug)?.name ?? signal.domainSlug} · {signal.executionType.replace(/_/g," ")}</div><div className="mt-1 text-[10px] text-muted">{signal.explanation}</div></div><div className="text-xs text-muted">{signal.samples} samples · {signal.wins} won</div><div className={`text-right text-sm font-black ${signal.adjustment > 0 ? "text-success" : signal.adjustment < 0 ? "text-critical" : "text-muted"}`}>{signal.adjustment > 0 ? "+" : ""}{signal.adjustment} priority</div></div>) : <div className="p-4 text-xs text-muted">Learning begins after two comparable actions have verified outcomes.</div>}</div></Card>
    </>}
    <Drawer open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.title ?? "Outcome"} subtitle={selected ? `${selected.sourceLabel} → ${selected.executionType?.replace(/_/g," ")}` : undefined} width="max-w-2xl">{selected && <div className="space-y-5"><ProofChain proof={selected.proof} /><section className="rounded-md border border-border p-3"><div className="text-2xs font-bold uppercase text-muted">Before and after</div><div className="mt-3 space-y-2">{selected.metrics.map((metric) => <div key={metric.key} className="grid grid-cols-[1fr_90px_20px_90px_80px] items-center gap-2 text-xs"><span className="font-semibold text-ink">{metric.label}</span><span className="text-right tnum">{metric.value.toLocaleString()}</span><span className="text-muted">→</span><span className="text-right font-bold tnum">{metric.current?.toLocaleString() ?? "—"}</span><span className={metric.direction === "up" ? "text-success" : metric.direction === "down" ? "text-critical" : "text-muted"}>{metric.percentChange == null ? "—" : `${metric.percentChange > 0 ? "+" : ""}${metric.percentChange.toFixed(1)}%`}</span></div>)}</div></section><section className="rounded-md bg-workspace/60 p-3"><div className="flex items-center justify-between"><span className="text-xs font-bold text-ink">Outcome reasoning</span><StatusBadge label={`${selected.verification.confidence ?? "no"} confidence`} tone="info" /></div><p className="mt-2 text-xs leading-5 text-muted">{selected.verification.outcomeNote || "No outcome note recorded."}</p>{selected.verification.alternativeExplanations?.length ? <div className="mt-3"><div className="text-[10px] font-bold uppercase text-muted">Alternative explanations</div><ul className="mt-1 list-disc space-y-1 pl-4 text-xs text-muted">{selected.verification.alternativeExplanations.map((item) => <li key={item}>{item}</li>)}</ul></div> : null}</section><div className="flex flex-wrap gap-2">{selected.sourceUrl && <Link href={selected.sourceUrl} className="inline-flex items-center gap-1 text-xs font-bold text-purple">Original evidence <ExternalLink className="h-3.5 w-3.5" /></Link>}<Link href={`/work?item=${selected.id}`} className="inline-flex items-center gap-1 text-xs font-bold text-purple">Execution record <Route className="h-3.5 w-3.5" /></Link></div></div>}</Drawer>
  </div>;
}

function ProofStat({ label, value, detail, accent }: { label: string; value: number|string; detail: string; accent?: boolean }) { return <div className={`rounded-lg border p-4 ${accent ? "border-success/30 bg-success/5" : "border-border bg-card"}`}><div className="text-2xs font-bold uppercase tracking-wide text-muted">{label}</div><div className="mt-2 text-2xl font-black text-ink tnum">{value}</div><div className="mt-1 text-[10px] text-muted">{detail}</div></div>; }
function ProofChain({ proof }: { proof: Row["proof"] }) { const steps = [["researched","Research"],["approved","Approved"],["shipped","Shipped"],["verified","Verified"],["valued","Value"]] as const; return <div className="flex items-start">{steps.map(([key,label], index) => <div key={key} className="flex min-w-0 flex-1 items-start"><div className="min-w-0 flex-1 text-center"><span className={`mx-auto flex h-5 w-5 items-center justify-center rounded-full ${proof[key] ? "bg-purple text-white" : "border border-border bg-card text-muted"}`}>{proof[key] ? <Trophy className="h-2.5 w-2.5" /> : <Scale className="h-2.5 w-2.5" />}</span><div className="mt-1 truncate text-[9px] font-semibold text-muted">{label}</div></div>{index < steps.length - 1 && <span className={`mt-2.5 h-px w-3 ${proof[steps[index + 1]![0]] ? "bg-purple" : "bg-border"}`} />}</div>)}</div>; }
