import {NextResponse} from "next/server";
import {z} from "zod";
import {canAccessSite,hasPermission} from "@/platform/access";
import {workspaceRecords,saveWorkspace} from "@/platform/workspace-store";
import {getDataForSeoClient} from "@/providers/dataforseo";
import {ENDPOINTS} from "@/providers/dataforseo/config";
import {normalizeSerpItems,type SerpEvidence} from "@/lib/serp-evidence";
const Input=z.object({site:z.string().min(1),keywords:z.array(z.string().trim().min(1).max(400)).min(1).max(50),locationCode:z.number().int().positive(),languageCode:z.string().min(2).max(12),device:z.enum(["desktop","mobile"]).default("desktop"),depth:z.union([z.literal(10),z.literal(100)]).default(10),refresh:z.boolean().default(false)});
export const maxDuration=120;
export async function GET(request:Request){const site=new URL(request.url).searchParams.get("site")??"";if(!site||!await canAccessSite(request,site))return NextResponse.json({error:"Website access required."},{status:403});return NextResponse.json({records:await workspaceRecords(site,"serp_evidence")});}
export async function POST(request:Request){const parsed=Input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Choose up to 50 keywords and a valid search target."},{status:400});const input=parsed.data;if(!await canAccessSite(request,input.site)||!await hasPermission(request,"research",input.site))return NextResponse.json({error:"Website research access required."},{status:403});const saved=await workspaceRecords(input.site,"serp_evidence"),reports:SerpEvidence[]=[];let costUsd=0;try{for(const keyword of new Set(input.keywords)){
 const existing=saved.find(row=>{const value=row.payload as unknown as SerpEvidence;return value.keyword.toLowerCase()===keyword.toLowerCase()&&value.locationCode===input.locationCode&&value.languageCode===input.languageCode&&value.device===input.device&&value.depth>=input.depth&&Date.now()-Date.parse(value.collectedAt)<7*86400000;});if(existing&&!input.refresh){reports.push(existing.payload as unknown as SerpEvidence);continue;}
 let items:SerpEvidence["items"],checkUrl:string|null=null;
 if(process.env.QA_SYNTHETIC==="true")items=Array.from({length:10},(_,i)=>({type:"organic",position:i+1,groupPosition:i+1,url:`https://competitor${i}.example/${keyword.includes("mortgage")?"mortgages":"transport"}`,domain:`competitor${i}.example`,title:`${keyword} result ${i+1}`,description:"Synthetic search evidence for isolated preview testing."}));
 else {const response=await getDataForSeoClient().post<Record<string,unknown>>("serpOrganicLive",ENDPOINTS.serpOrganicLive,[{keyword,location_code:input.locationCode,language_code:input.languageCode,device:input.device,depth:input.depth}],{domainSlug:input.site});costUsd+=response.costUsd;const root=response.result[0];if(!root||!Array.isArray(root.items)&&root.items_count!==0)throw new Error("The provider did not return a complete search result. Completed keywords remain saved.");items=normalizeSerpItems(root.items??[]);checkUrl=typeof root.check_url==="string"?root.check_url:null;}
 const report:SerpEvidence={keyword,locationCode:input.locationCode,languageCode:input.languageCode,device:input.device,depth:input.depth,collectedAt:new Date().toISOString(),items,checkUrl};await saveWorkspace(input.site,"serp_evidence",crypto.randomUUID(),report as unknown as Record<string,unknown>,"completed");reports.push(report);
 }return NextResponse.json({reports,costUsd});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Search collection failed.",reports,costUsd},{status:502});}}
