"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CloudLightning, Crown, Eye, Sparkles } from "lucide-react";
import { useResolvedDomain } from "@/components/shell/domain-context";
import { PageHeader } from "@/components/ui/page-header";
import { Card, EmptyState, Skeleton, StatusBadge, Button } from "@/components/ui/primitives";
import { Drawer } from "@/components/ui/drawer";
import { SiteFindingWorkDrawer, type SiteFinding } from "@/components/workflow/site-finding-work-drawer";

type Weather = { date: string; volatility: number; keywords: number; features: string[]; ownedFeatures: string[]; avgPosition: number | null };
type Keyword = { id: string; keyword: string; device: string; locationCode: number; position: number | null; change: number | null; intent: string | null; url: string | null; features: string[]; ownedFeatures: string[]; history: Array<{ date: string; position: number | null; intent: string | null; features: string[]; ownedFeatures: string[]; leader: string | null }> };
type Competitor = { host: string; keywordCoverage: number; top3: number; avgPosition: number | null; movement: number | null };
type Alert = { id: string; date: string; type: "volatility"|"intent_change"|"feature_change"|"competitor_takeover"; severity: "high"|"medium"; title: string; detail: string; keyword?: string };
type Data = { summary: { trackedKeywords: number; historyDays: number; volatility: number; intentChanges: number; ownedFeatures: number; activeCompetitors: number }; weather: Weather[]; keywords: Keyword[]; competitors: Competitor[]; alerts: Alert[] };

export default function SerpIntelligencePage() {
  const domain = useResolvedDomain(); const [data, setData] = useState<Data | null>(null); const [tab, setTab] = useState<"keywords"|"competitors"|"alerts">("keywords"); const [selected, setSelected] = useState<Keyword | null>(null); const [work, setWork] = useState<SiteFinding | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); setLoading(true); fetch(`/api/serp-intelligence?site=${encodeURIComponent(domain.id)}`, { signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "SERP intelligence could not be loaded."); setData(body); setError(null); }).catch((reason) => { if (!(reason instanceof DOMException && reason.name === "AbortError")) setError(reason instanceof Error ? reason.message : "SERP intelligence could not be loaded."); }).finally(() => setLoading(false)); return () => controller.abort(); }, [domain.id]);
  const featureOwnership = useMemo(() => { const all = new Map<string,{feature:string,present:number,owned:number}>(); for(const keyword of data?.keywords ?? []) for(const feature of keyword.features){ const entry=all.get(feature)??{feature,present:0,owned:0}; entry.present += 1; if(keyword.ownedFeatures.includes(feature)) entry.owned += 1; all.set(feature,entry); } return [...all.values()].sort((a,b)=>b.present-a.present); },[data]);
  const alertFinding = (alert: Alert): SiteFinding => ({ key:`serp-alert:${alert.id}`, title:alert.title, module:"Rankings", executionType:alert.type === "intent_change" ? "keyword_page_map" : "refresh_brief", priorityScore:alert.severity === "high" ? 88 : 70, pageMode:alert.keyword ? "existing_page" : "site_wide", targetUrl:alert.keyword ? data?.keywords.find((item)=>item.keyword===alert.keyword)?.url : null, targetKeywords:alert.keyword ? [alert.keyword] : [], evidenceLabel:`${alert.detail} · observed ${alert.date}`, sourceUrl:`/serp-intelligence?site=${encodeURIComponent(domain.id)}`, sourceEvidence:{kind:"serp_intelligence_alert",...alert} });
  return <div className="animate-in space-y-5"><PageHeader title="SERP intelligence" description={`Historical ranking weather, feature ownership, intent shifts and competitor takeovers for ${domain.name}.`} />{error && <div role="alert" className="rounded-md border border-critical/20 bg-critical/5 p-3 text-xs text-critical">{error}</div>}
    {loading ? <><div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{Array.from({length:6},(_,i)=><Skeleton key={i} className="h-20" />)}</div><Skeleton className="h-44" /><Skeleton className="h-80" /></> : !data ? <EmptyState title="No SERP history" description="Approved rank tracking builds history during scheduled DataForSEO syncs." /> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><Stat label="Tracked" value={data.summary.trackedKeywords} /><Stat label="History" value={`${data.summary.historyDays} days`} /><Stat label="Volatility" value={data.summary.volatility} tone={data.summary.volatility>=8?"critical":data.summary.volatility>=4?"warning":"normal"} /><Stat label="Intent changes" value={data.summary.intentChanges} /><Stat label="Features owned" value={data.summary.ownedFeatures} /><Stat label="Competitors" value={data.summary.activeCompetitors} /></div>
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div><div className="flex items-center gap-2 text-sm font-bold text-ink"><CloudLightning className="h-4 w-4 text-purple" />SERP weather</div><p className="mt-1 text-2xs text-muted">Ranking turbulence and search-layout changes aligned by observation date.</p></div><span className="text-[10px] text-muted">Stored observations · no live refresh</span></div><div className="overflow-x-auto p-4"><div className="flex min-w-[720px] items-end gap-2">{data.weather.map((day) => <div key={day.date} className="group min-w-16 flex-1"><div className="flex h-24 items-end rounded-md bg-workspace/60 p-1"><div title={`Volatility ${day.volatility}`} className={`w-full rounded-sm transition-all group-hover:opacity-80 ${day.volatility>=8?"bg-critical":day.volatility>=4?"bg-warning":"bg-purple"}`} style={{height:`${Math.max(8,Math.min(100,day.volatility*10))}%`}} /></div><div className="mt-1 text-center text-[9px] text-muted">{new Date(`${day.date}T00:00:00Z`).toLocaleDateString(undefined,{day:"numeric",month:"short"})}</div><div className="text-center text-[9px] font-bold text-ink">{day.volatility}</div>{day.ownedFeatures.length>0 && <Crown className="mx-auto mt-1 h-3 w-3 text-success" />}</div>)}</div></div></Card>
      <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_310px]"><Card><div className="flex gap-1 border-b border-border p-2">{([['keywords','Keyword history'],['competitors','Competitor movement'],['alerts','Change alerts']] as const).map(([value,label])=><button key={value} onClick={()=>setTab(value)} className={`rounded-md px-3 py-2 text-xs font-semibold ${tab===value?"bg-purple text-white":"text-muted hover:bg-workspace"}`}>{label}</button>)}</div>
        {tab==="keywords" && <div className="divide-y divide-border">{data.keywords.map((row)=><button key={row.id} onClick={()=>setSelected(row)} className="grid w-full grid-cols-[minmax(0,1fr)_75px_75px_110px] items-center gap-2 px-4 py-3 text-left hover:bg-workspace/50"><div><div className="text-xs font-bold text-ink">{row.keyword}</div><div className="mt-1 text-[10px] text-muted">{row.device} · {row.intent ?? "intent unknown"}</div></div><div className="text-right text-lg font-black text-ink tnum">{row.position??"—"}</div><Movement value={row.change}/><div className="flex flex-wrap justify-end gap-1">{row.ownedFeatures.map((feature)=><StatusBadge key={feature} label={feature.replace(/_/g," ")} tone="success" />)}</div></button>)}</div>}
        {tab==="competitors" && <div className="divide-y divide-border">{data.competitors.map((row,index)=><div key={row.host} className="grid grid-cols-[30px_minmax(0,1fr)_100px_80px_80px] items-center gap-2 px-4 py-3"><span className="text-xs font-black text-muted">{index+1}</span><div className="text-xs font-bold text-ink">{row.host}</div><div className="text-right text-xs text-muted">{row.keywordCoverage} keywords</div><div className="text-right text-xs font-bold">{row.top3} top 3</div><Movement value={row.movement}/></div>)}</div>}
        {tab==="alerts" && <div className="divide-y divide-border">{data.alerts.length?data.alerts.map((alert)=><div key={alert.id} className="flex items-start gap-3 px-4 py-3"><AlertTriangle className={`mt-0.5 h-4 w-4 shrink-0 ${alert.severity==="high"?"text-critical":"text-warning"}`}/><div className="min-w-0 flex-1"><div className="text-xs font-bold text-ink">{alert.title}</div><div className="mt-1 text-[10px] text-muted">{alert.detail} · {alert.date}</div></div><Button size="sm" onClick={()=>setWork(alertFinding(alert))}>Create work</Button></div>):<div className="p-4"><EmptyState title="No material SERP changes" description="Intent, features, competitors and volatility are stable in the stored history." /></div>}</div>}
      </Card><Card><div className="border-b border-border p-4"><div className="flex items-center gap-2 text-sm font-bold text-ink"><Sparkles className="h-4 w-4 text-purple"/>Feature ownership</div><p className="mt-1 text-2xs text-muted">Where each result format appears and whether your website owns it.</p></div><div className="divide-y divide-border">{featureOwnership.map((item)=><div key={item.feature} className="p-3"><div className="flex justify-between gap-2 text-xs"><span className="font-semibold text-ink">{item.feature.replace(/_/g," ")}</span><span className="text-muted">{item.owned}/{item.present}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-workspace"><div className="h-full bg-success" style={{width:`${item.present?item.owned/item.present*100:0}%`}}/></div></div>)}</div></Card></div>
    </>}
    <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.keyword??"Keyword history"} subtitle={selected?`${selected.device} · ${selected.intent??"intent unknown"}`:undefined} width="max-w-2xl">{selected&&<div className="space-y-5"><div className="flex items-end gap-2 overflow-x-auto rounded-md bg-workspace/60 p-4">{selected.history.map((point)=><div key={point.date} className="min-w-12 flex-1 text-center"><div className="flex h-36 items-end"><div className="w-full rounded-t bg-purple/80" style={{height:`${Math.max(8,100-(point.position??100))}%`}} /></div><div className="mt-1 text-[9px] text-muted">{new Date(`${point.date}T00:00:00Z`).toLocaleDateString(undefined,{day:"numeric",month:"short"})}</div><div className="text-xs font-black text-ink">{point.position??"—"}</div></div>)}</div><div className="space-y-2">{selected.history.map((point,index)=><div key={point.date} className="grid grid-cols-[80px_70px_1fr] gap-2 rounded-md border border-border p-2 text-xs"><span className="text-muted">{point.date}</span><span className="font-bold text-ink">#{point.position??"—"}</span><span className="text-muted">{point.intent} · leader {point.leader??"unknown"}{point.ownedFeatures.length?` · owns ${point.ownedFeatures.join(", ")}`:""}</span></div>)}</div></div>}</Drawer><SiteFindingWorkDrawer finding={work} siteSlug={domain.id} siteName={domain.name} onClose={()=>setWork(null)}/>
  </div>;
}
function Stat({label,value,tone="normal"}:{label:string;value:string|number;tone?:"normal"|"warning"|"critical"}){return <div className={`rounded-lg border p-3 ${tone==="critical"?"border-critical/25 bg-critical/5":tone==="warning"?"border-warning/25 bg-warning/5":"border-border bg-card"}`}><div className="text-[10px] font-bold uppercase text-muted">{label}</div><div className="mt-2 text-xl font-black text-ink tnum">{value}</div></div>}
function Movement({value}:{value:number|null}){if(value==null)return <div className="text-right text-xs text-muted">—</div>; const Icon=value>0?ArrowUpRight:value<0?ArrowDownRight:Eye; return <div className={`flex items-center justify-end gap-1 text-xs font-bold ${value>0?"text-success":value<0?"text-critical":"text-muted"}`}><Icon className="h-3.5 w-3.5"/>{value>0?"+":""}{value}</div>}
