"use client";
import {useState} from "react";
import {useDomain} from "@/components/shell/domain-context";
import {AdvertisingResearch} from "@/components/research/advertising-research";
import {MarketSelector} from "@/components/research/market-selector";
import {Button,Card} from "@/components/ui/primitives";
export default function AdvertisingPage(){const {activeDomain}=useDomain();return activeDomain?<AdvertisingWorkspace key={activeDomain.id} site={activeDomain.id} host={activeDomain.host} location={activeDomain.dataForSeoLocationCode??2840} language={activeDomain.dataForSeoLanguageCode??"en"}/>:<Card className="p-5">Select a website to open Advertising Research.</Card>;}
function AdvertisingWorkspace({site,host,location:initialLocation,language:initialLanguage}:{site:string;host:string;location:number;language:string}){const [domain,setDomain]=useState(host),[draft,setDraft]=useState(host),[location,setLocation]=useState(initialLocation),[language,setLanguage]=useState(initialLanguage),[error,setError]=useState("");function open(){try{const value=new URL(draft.includes("://")?draft:`https://${draft}`);if(!["http:","https:"].includes(value.protocol)||value.username||value.password||!value.hostname.includes("."))throw new Error();setDomain(value.hostname.replace(/^www\./,""));setError("");}catch{setError("Enter a valid domain.");}}
 return <div className="space-y-4 pb-8"><header className="border-b border-border pb-4"><p className="mb-2 text-xs text-muted">SEO › Competitive Analysis</p><h1 className="text-xl font-bold">Advertising Research</h1></header><form className="flex flex-wrap gap-2" onSubmit={event=>{event.preventDefault();open();}}><input aria-label="Advertising domain" className="h-9 min-w-48 rounded border border-border bg-card px-3 text-sm" value={draft} onChange={e=>setDraft(e.target.value)}/><MarketSelector location={location} language={language} onChange={(code,lang)=>{setLocation(code);setLanguage(lang);}}/><Button type="submit" size="sm">Open saved reports</Button></form>{error&&<p role="alert" className="text-sm text-critical">{error}</p>}<AdvertisingResearch key={`${domain}:${location}:${language}`} site={site} domain={domain} location={location} language={language}/></div>;
}
